### ISSUE TITLE
Slow memory leak

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#1011]
I've observed this in the past, I've started to worry more recently.

I've configured my tservers to use 24g (Xmx) of java memory, and 2g for the native map (tserver.memory.maps.max). With this, one would expect the resident memory size (RES) to maybe be around 28g-30g (including native thread memory/etc), but I don't think it should get above 30g.

My tservers on fresh restart sit at approximately 24g of RES and slowly grow well above 30g to as high as 40g at times. What's causing this slow leak? Java memory usage is low, 4g-12g.

After quite a bit of digging, I tentatively believe it's an issue with NativeMap creation/cleanup or something not closing it's NativeMap. Doing a grep | wc -l for 'Allocated native map' and 'Deallocated native map' in a server debug log, the count differential is about 100K. Looking at the code, I suspect the issue may be the tablet isn't closing it's in memory map when it gets unloaded. Dumping the servers memory and analyzing with MAT, I can confirm there are about 100K live NativeMap references.

**Comment by andrewglowacki** [comment]
I should note, this is accumulo 1.9.2.

**Comment by keith-turner** [comment]
I took a quick look at the tablet close code.  One possible path I see where the memory may not be freed is if an exception is thrown in the close method before the native map is deleted.

**Comment by andrewglowacki** [comment]
@keith-turner - thanjs for checking so quickly. now I see the section in tablet unload where he map is deleted. I don't think I have any unload errors other than ones stating the tablet is in the closing state - I'll double check. I also see multiple maps are allocated per tablet, so maybe 100k makes more sense. I'll continue looking.

**Comment by keith-turner** [comment]
@andrewglowacki the NativeMap code has a finalize method that logs a warning if it GCed but was not deleted.  Have you seen that in the logs? May not see these because you mentioned there were *100K live NativeMap references* in your memory dump, but its worth checking.  In your memory dump what Object holds a reference to some of the native maps?  

https://github.com/apache/accumulo/blob/rel/1.9.2/server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java#L486

**Comment by keith-turner** [comment]
@andrewglowacki  nevermind about looking for the finalize log message, I was just looking at the code a second time and noticed the logs message is commented out.  I missed that the first time.

**Comment by keith-turner** [comment]
@andrewglowacki  actually it does log a warning.  There are two finalize methods, my earlier link was for an inner class which is the wrong class.  The link below is for the top level class.  Sorry for the spam.

https://github.com/apache/accumulo/blob/rel/1.9.2/server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java#L505

**Comment by andrewglowacki** [comment]
@keith-turner no problem - I don't see any finalize dealloc warnings. 

Looking more closely today, they may be legitimate (although still seems high). In a sample dump I took this morning, I have 93k live references. Virtually all (except 17) of them have a modcount of 0 and an active (non-zero) native map pointer. Randomly sampling a bunch of them, they are all ultimately referenced by various Tablet's in memory map.

**Comment by keith-turner** [comment]
>  Randomly sampling a bunch of them, they are all ultimately referenced by various Tablet's in memory map.

Would it be possible to inspect that state of those tablets to see they are closed?

https://github.com/apache/accumulo/blob/rel/1.9.2/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L200

**Comment by andrewglowacki** [comment]
Sure - it looks like they are all open

**Comment by andrewglowacki** [comment]
Ok, this seems like a dead end - I probably should have mentioned this earlier... This server has a little more than 11k tablets, each tablet has (expectedly) 4 locality groups, so that's 4 sample and 4 normal native maps = 8 maps per tablet ~ 93k native maps. I can see this as room for improvement (especially for table structures with more locality groups), but not a leak.

**Comment by mjwall** [comment]
Are you saying one tserver is hosting 11k tablets?  That is a lot.

I try to stay around 1k, seems like things bad when it is higher than that.  Why so many?  Can you get more nodes or merge down the number of tablets.

For completeness, I was going to ask if you have short-circuit reads turned on, if you were using NUMA on either the tserver or the datanode, and what the datanode looked like memory wise on the server.

Feel free to close this ticket if you think you are done.

**Comment by andrewglowacki** [comment]
@mjwall - yes. 

Haha, yeah with infinite resources, I would have 10 times as many nodes as I do. A lot of data gets deleted/compacted away pretty quickly, so the large number of tablets could be merged into more optimally sized ones. Doing this efficiently periodically is on my to-do list.

Yes, short circuit reads are enabled. No I'm not using NUMA at the moment, but may try it in the future. The cluster performs pretty well as it is.

This can certainly be closed, however the fact remains that the all of my tservers are leaking significantly. I'm still investigating on my own. 

Using pmap, I can see the main 'heap' segment is the majority of the memory, usually capped at 7g. The rest is scattered among smaller 1-2gb segments. I've dumped some of these, but it's hard to tell whether or not what I'm see is short or long lived.

**Comment by mjwall** [comment]
Do you presplit?  Perhaps reduce the number and see if it helps.  Especially if you are just deleting and compacting away anyway.  

If you do not presplit, consider upping the split threshold, https://accumulo.apache.org/1.9/accumulo_user_manual.html#_table_split_threshold

Closing, feel free to continue the discussion.  Or put this out to the dev mailing list.

**Comment by andrewglowacki** [comment]
The issue was DirectByteBuffers (DBB) created by HDFS DFSInputStreams (for RFile reads) not getting cleaned up fast enough (or at all). Setting -XX:MaxDirectMemorySize=2g fixed it.

After quite a bit of looking (multiple weeks), I correlated some multi-hour old/unfreed native memory segments with DBBs in the java heap - sure enough, direct memory usage was very high (multiple GB). In my java heap dump, I found 36k live DBBs with 46 referenced by live DFSInputStreams in the FileManager's openFiles list, 20k cached in the HDFS PacketReceiver 'bufferPool' and the rest awaiting finialization of their parent PacketReceiver.

The sizes were not large, at most 1 MB each, but the number was the issue.

**Comment by mjwall** [comment]
Makes sense, thanks for following up @andrewglowacki

**Comment by keith-turner** [comment]
Interesting find @andrewglowacki .  Should any hadoop issues be opened for this?

**Comment by andrewglowacki** [comment]
@keith-turner yea, I was thinking I might. I'll look at the latest 2.x and 3.x versions to see if it could be a problem.
