### ISSUE TITLE
Monitor while ZK is down

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1045]
I noticed while doing some testing that the monitor will hang if ZK (no zookeepers available) is down.  Normally, if ZK is down this is really bad and Accumulo can't do anything but the monitor should still work and be able to inform users that ZK is down.

**Comment by ctubbsii** [comment]
The monitor is so different in 2.0, I don't think it's worth spending a lot of time enhancing the old monitor in 1.9. If we were to spend any time doing monitor stuff in 1.9, the time would probably be better spent backporting the 2.0 monitor rather than adding enhancements to the 1.9 monitor. So, I'm dropping the 1.9.3 label.

**Comment by milleruntime** [comment]
I was looking at it briefly for 1.9 because it seems more like a bug.  A lot of the monitor runs separate threads for ZK the prevent it from hanging.

**Comment by milleruntime** [comment]
The problem is in the ZooConfiguration:
https://github.com/apache/accumulo/blob/1.9/server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/BasicServlet.java#L60
The servlet tries to get 3 values form the configuration but the ZooConfiguration will keep trying.  Not sure how to fix easily for 1.9

**Comment by ctubbsii** [comment]
Bug or enhancement... either way, I'm not sure it's worth the effort in 1.9.

Regardless, a fix isn't currently ready for 1.9, and I don't think it's worth holding up 1.9.3.

**Comment by milleruntime** [comment]
I looked at this for 2.0 as well and it is just as difficult.  I don't think this is worth doing since all ZK being down is pretty catastrophic to Accumulo as a whole and making the Monitor work independently doesn't get us a whole lot.
