### ISSUE TITLE
Don't retry failed walog creation immediately 

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1054]
While looking at #1005 I noticed that when there is a failure to create a walog it retires immediately.  It should probably wait a bit using the Accumulo retry code.

**Comment by ctubbsii** [comment]
@keith-turner  Should this go in 1.9?

**Comment by keith-turner** [comment]
> @keith-turner Should this go in 1.9?

No

**Comment by keith-turner** [comment]
Well maybe 1.9.4.  Does not need to hold up 1.9.3

**Comment by keith-turner** [comment]
invalidated by #1057
