### ISSUE TITLE
Fate Metrics coupled with Replication

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1058]
The forward merge of #1046 from 1.9 to 2.0 went without conflicts but the code in 2.0 was moved into a method that is only called when replication is enabled.  This will result in fate metrics requiring replication to be enabled to be registered.

**Comment by milleruntime** [comment]
@EdColeman

**Comment by ctubbsii** [comment]
The merged occurred in f896c98c2356a52dfa2235d2cc02ae556ab17909 . It was a relatively easy merge, but it did have some conflicts to resolve :smiley_cat:

**Comment by EdColeman** [comment]
See https://github.com/apache/accumulo/pull/1063
