### ISSUE TITLE
[minicluster] Have mini collect/re-log logs generated by services it launches

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1062]
MiniAccumuloCluster should start up a log4j socket appender service to receive logs. When it launches tserver, master, etc. services, it should do so with a log4j configuration that sends certain logs (warning and higher?) back through to the socket listening in the mini process that launched them. This would enable MiniAccumuloCluster to be able to make these important logs available to the process using mini, instead of only available in the mini log directory.

The most common use case I can think of is being able to see that an IT is failing because native maps aren't available, which caused the tserver to fail. Currently, the IT will probably time out waiting for Accumulo to come online, but it never will, and the only way to troubleshoot is to scour the logs in the target/mini-tests/ directory corresponding to the failing IT. I'm sure there are other use cases, too.

**Comment by ctubbsii** [comment]
This won't be possible in log4j2 right now, since the SocketServer code is in a separate log4j-tools jar, which has not yet been released. It could be possible in future, but I'm closing this for now, since the effort is probably not worth it.

**Comment by keith-turner** [comment]
It would have been a cool feature, but I agree its probably not worth the effort.
