### ISSUE TITLE
Tests failing running against standalone instance

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1084]
Catch all ticket for Tests failing running against standalone instance of 2.0:

- org.apache.accumulo.test.YieldScannersIT
- org.apache.accumulo.test.mapreduce.AccumuloFileOutputFormatIT
- org.apache.accumulo.test.mapreduce.TokenFileIT
- org.apache.accumulo.test.BadDeleteMarkersCreatedIT
- org.apache.accumulo.test.BulkImportVolumeIT
- org.apache.accumulo.test.CleanWalIT
- org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT
- org.apache.accumulo.test.mapred.TokenFileIT
- org.apache.accumulo.test.InterruptibleScannersIT

This probably isn't all of them just the ones I saw.  Would be nice to fix these for 2.0 release. 

Here is the config file I used:
[config-file.properties.txt](https://github.com/apache/accumulo/files/3066026/config-file.properties.txt)

**Comment by milleruntime** [comment]
Some more:
org.apache.accumulo.test.functional.BigRootTabletIT
org.apache.accumulo.test.functional.BinaryStressIT
org.apache.accumulo.test.functional.BulkFileIT
org.apache.accumulo.test.functional.BulkIT
org.apache.accumulo.test.functional.BulkSplitOptimizationIT
org.apache.accumulo.test.functional.CompactionIT
org.apache.accumulo.test.functional.DeleteIT
org.apache.accumulo.test.functional.MasterFailoverIT
org.apache.accumulo.test.functional.ReadWriteIT
org.apache.accumulo.test.functional.RestartIT
org.apache.accumulo.test.functional.RestartStressIT
org.apache.accumulo.test.functional.ScanSessionTimeOutIT
org.apache.accumulo.test.functional.SessionBlockVerifyIT
org.apache.accumulo.test.functional.StartIT
org.apache.accumulo.test.functional.WriteAheadLogEncryptedIT
org.apache.accumulo.test.functional.WriteAheadLogIT
org.apache.accumulo.test.ImportExportIT
org.apache.accumulo.test.IteratorEnvIT
org.apache.accumulo.test.MetaConstraintRetryIT

**Comment by hkeebler** [comment]
I will take a stab at this one if nobody has any objections.

**Comment by hkeebler** [comment]
I will take a stab at this one if nobody has any objections.

**Comment by hkeebler** [comment]
Is it assumed that these worked, in standalone mode, for version 1.9?

**Comment by milleruntime** [comment]
> Is it assumed that these worked, in standalone mode, for version 1.9?

No they didn't work in 1.9 either.  There was some point in time with some version that they all worked perfectly :laughing:

**Comment by hkeebler** [comment]
5 of the tests ERROR because a temporary file that is created is not found.  The Standalone cluster returns a  HDFS "/tmp" path but subsequent processing tries to validate it as a file://  (or viceversa).  The MAC cluster seems to create regular files in the <testdir>/mini-tests and all is happy.I  Why does the Standalone config confuse things?  I am not sure but ideas are welcome.

**Comment by milleruntime** [comment]
> 5 of the tests ERROR because a temporary file that is created is not found. The Standalone cluster returns a HDFS "/tmp" path but subsequent processing tries to validate it as a file:// (or viceversa). The MAC cluster seems to create regular files in the /mini-tests and all is happy.I Why does the Standalone config confuse things? I am not sure but ideas are welcome.

I am not sure.  I can look at this tomorrow if you are still stuck, ping me!

**Comment by hkeebler** [comment]
The following tests are still producing either errors or failures.  Looked for some common themes.  An async timing thing may be part of the issue.  Should these tests be worked off using this ticket or should a separate git issue be created for each test or issue group?  I plan to check out the two TBD tests today.

**Test failures:**
- CleanWalIT -  a timing thing - the flush of accumulo.metadata does not get rid of log entries before the check - takes several seconds.
- AccumuloClientIT - thinks it is a server not a client - might be okay
- BinaryStressIT - a timing thing maybe but just does not do what is expected, i.e., split based on 10K threshold
- YieldScannersIT  - Iterator appears to not be cleaned/removed after test in standalone env - it continues to increment.

**TBD:**
- IteratorEnvIT
- ManyWriteAheadLogsIT

**This group produces a "file not found"** 
- BulkImportValumeIT 
- ImportExportIT 
- TokenFileIT 
- CompactionIT 
- BulkFileIT 

**This group times out**
- DeleteTableDuringSplitIT 
- MergIT 
- ReadWritIT 
- CreateInitialSplitsIT 
- BulkIT 
- ScanSessionTimeOutIT 
- BulkSplitOptimizationIT 
- SessionBlockVerifyIT
- FateStarvationIT 
- BigRootTabletIT
- RecoveryCompactionsAreFlushesIT

**Comment by hkeebler** [comment]
ReadWriteIT test fails loading the "accumulo.properties" file in the following section of code in the SunnyDay test.  It appears that it is trying to read an XML formatted file
`org.apache.hadoop.shaded.com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '#' (code 35) in prolog; expected '<'`
instead of a regular properties file BUT I do not think the code here is really even necessary and doesn't really test anything.  When removed the test runs with no issue.
```
if (getCluster() instanceof StandaloneAccumuloCluster) {
        StandaloneAccumuloCluster standaloneCluster = (StandaloneAccumuloCluster) getCluster();
        File accumuloProps =
            new File(standaloneCluster.getServerAccumuloConfDir(), "accumulo.properties");
        if (accumuloProps.isFile()) {
          Configuration conf = new Configuration(false);
          conf.addResource(new Path(accumuloProps.toURI()));
          String monitorSslKeystore = conf.get(Property.MONITOR_SSL_KEYSTORE.getKey());
          if (monitorSslKeystore != null) {
            log.info("Using HTTPS since monitor ssl keystore configuration was observed in {}",
                accumuloProps);
            scheme = "https://";
            SSLContext ctx = SSLContext.getInstance("TLSv1.2");
            TrustManager[] tm = {new TestTrustManager()};
            ctx.init(new KeyManager[0], tm, new SecureRandom());
            SSLContext.setDefault(ctx);
            HttpsURLConnection.setDefaultSSLSocketFactory(ctx.getSocketFactory());
            HttpsURLConnection.setDefaultHostnameVerifier(new TestHostnameVerifier());
          }
        } else {
          log.info("{} is not a normal file, not checking for monitor running with SSL",
              accumuloProps);
        }
      }
```

**Comment by hkeebler** [comment]
Assessment of "file not found" problem (but no fix yet):

In the test class , the below code returns a hdfs filesystem
`FileSystem fs = cluster.getFileSystem();`
When the testing action is executed like the below code
`c.tableOperations().importDirectory(testDir.toString()).to(tableName).load();`
it gets the filesystem from something like:
```
FileSystem fs =
        VolumeConfiguration.getVolume(dir, context.getHadoopConf(), conf).getFileSystem();
```
The HadoopConf in the former includes the local path files:  
_<your hadoop install>etc/hadoop/core-site.xml, <your hadoop install>etc/hadoop/hdfs-site.xml_
The HadoopConf in the latter does NOT and therefore doesn't seem to resolve "fs.defaultFS" to the hdfs path and returns a local path file:///

Its like the context is slightly different from the test class and the underlying code that being executed.

**Comment by milleruntime** [comment]
> ReadWriteIT ... I do not think the code here is really even necessary and doesn't really test anything. When removed the test runs with no issue.
> 
> ```
> if (getCluster() instanceof StandaloneAccumuloCluster) {
>         StandaloneAccumuloCluster standaloneCluster = (StandaloneAccumuloCluster) getCluster();
>         File accumuloProps =
>             new File(standaloneCluster.getServerAccumuloConfDir(), "accumulo.properties");
>         if (accumuloProps.isFile()) {
>           Configuration conf = new Configuration(false);
>           conf.addResource(new Path(accumuloProps.toURI()));
>           String monitorSslKeystore = conf.get(Property.MONITOR_SSL_KEYSTORE.getKey());
>           if (monitorSslKeystore != null) {
>             log.info("Using HTTPS since monitor ssl keystore configuration was observed in {}",
>                 accumuloProps);
>             scheme = "https://";
>             SSLContext ctx = SSLContext.getInstance("TLSv1.2");
>             TrustManager[] tm = {new TestTrustManager()};
>             ctx.init(new KeyManager[0], tm, new SecureRandom());
>             SSLContext.setDefault(ctx);
>             HttpsURLConnection.setDefaultSSLSocketFactory(ctx.getSocketFactory());
>             HttpsURLConnection.setDefaultHostnameVerifier(new TestHostnameVerifier());
>           }
>         } else {
>           log.info("{} is not a normal file, not checking for monitor running with SSL",
>               accumuloProps);
>         }
>       }
> ```

This part of the code may be broken for 2.0... I am not sure SSL works with the new Monitor.

**Comment by ctubbsii** [comment]
> This part of the code may be broken for 2.0... I am not sure SSL works with the new Monitor.

I haven't looked at this code, but TLS should work fine with the new monitor. I believe we have a MonitorSslIT to confirm this.

**Comment by milleruntime** [comment]
OK MonitorSslIT passes.  @hkeebler you should be able to update the code block you referred to in ReadWriteIT to work like MonitorSslIT.

**Comment by hkeebler** [comment]
@milleruntime  or @ctubbsii , for the tests that are timing out we can recommend in docs to add a timeout.factor to the mvn verify for standalone tests or I can update the specific tests and up the defaulttimeout in the tests.  Which do you prefer?

**Comment by ctubbsii** [comment]
> @milleruntime or @ctubbsii , for the tests that are timing out we can recommend in docs to add a timeout.factor to the mvn verify for standalone tests or I can update the specific tests and up the defaulttimeout in the tests. Which do you prefer?

Letting developers know of the timeout.factor isn't a bad idea. If they are doing development on weaker machines than what might be run on a server, they will almost certainly need to use it occasionally.

**Comment by milleruntime** [comment]
@ctubbsii maybe this shouldn't be a blocker for 2.0?  I thought it would be nice to have the standalone tests running but I think it will take a while to fix them all.

**Comment by ctubbsii** [comment]
> @ctubbsii maybe this shouldn't be a blocker for 2.0? I thought it would be nice to have the standalone tests running but I think it will take a while to fix them all.

I agree. I don't think it should be a blocker... but any tests fixed prior to 2.0 would be helpful.

**Comment by milleruntime** [comment]
Updating ticket with ITs that have been fixed

**Comment by hkeebler** [comment]
**Fixed ITs:**
- AccumuloClientIT
- ManyWriteaheadLogsIT 
- ReadWriteIT
- YieldScannersIT
- BadDeleteMarkersIT (and any others that failed with "null" prefix on command - unknown which ones there all were)
- BulkImportVolumeIT
- ImportExportIT
- CompactionIT
- BulkFileIT
- BulkIT
- BulkSplitOptimizationIT

**Many tests were fixed by using the larger uno footprint like**:
- BinaryStressIT
- CleanWalIT
For whatever reason the following are now **working**
- mapred.TokenIT
- mapreduce.TokenIT

**Tests timing out worked when the timeout.factor was increased.**   Note that atempting to run all the IT tests in standalone mode will likely timeout somewhere.  Deleting tablet files is super slow in the Uno instance.

**Comment by milleruntime** [comment]
Thanks @hkeebler.  Here is an updated list of ITs that are failing using a standalone instance:
BadDeleteMarkersCreatedIT
BigRootTabletIT
DeleteIT
MasterFailoverIT
RestartIT
RestartStressIT
ScanSessionTimeOutIT
SessionBlockVerifyIT
StartIT
WriteAheadLogEncryptedIT
WriteAheadLogIT
InterruptibleScannersIT
mapreduce.AccumuloFileOutputFormatIT
MetaConstraintRetryIT
RecoveryCompactionsAreFlushesIT

**Comment by hkeebler** [comment]
Mike, this list was generated because you ran these and they failed?

**Comment by milleruntime** [comment]
> do not error when run individually. 

I think this is a sign that the test could be improved upon.  After looking at the Tests closer we can determine a proper course of action for each... i.e. fix the test to work in standalone mode or remove the standalone category.

**Comment by milleruntime** [comment]
I am going to look into these 2 since I am familiar with them:
WriteAheadLogEncryptedIT
WriteAheadLogIT

**Comment by milleruntime** [comment]
> Many of these fell into the 'null" command prefix bunch

What do you mean by this?

**Comment by milleruntime** [comment]
Crossed out ITs I saw passing from the list above.

**Comment by hkeebler** [comment]
> Many of these fell into the 'null" command prefix bunch
The initial finding for these tests failing was due to the server prefix property not being set to "" in the accumulo-it.properties file.  This caused a "null" prefix on command line commands being executed.  When that was fixed any tests that required that server prefix were working.

**Comment by ctubbsii** [comment]
@milleruntime What's the status of this?

**Comment by milleruntime** [comment]
> @milleruntime What's the status of this?

A lot has changed in a year so I will have to re-run the ITs in Standalone mode.

**Comment by milleruntime** [comment]
Based on commit 530e3dec5, I ran the Standalone ITs using Uno with the 32GX4 profile on a single m5d.2xlarge EC2 instance.  Saw the following ITs fail:

- org.apache.accumulo.test.functional.ScanIteratorIT
- org.apache.accumulo.test.functional.ReadWriteIT
- org.apache.accumulo.test.functional.ScanIdIT
- org.apache.accumulo.test.functional.ConcurrencyIT
- org.apache.accumulo.test.functional.RestartStressIT
- org.apache.accumulo.test.functional.FateConcurrencyIT
- org.apache.accumulo.test.functional.MasterFailoverIT
- org.apache.accumulo.test.functional.SessionBlockVerifyIT
- org.apache.accumulo.test.functional.TimeoutIT
- org.apache.accumulo.test.functional.WriteAheadLogIT
- org.apache.accumulo.test.functional.CompactionIT
- org.apache.accumulo.test.functional.WriteAheadLogEncryptedIT
- org.apache.accumulo.test.functional.MasterMetricsIT
- org.apache.accumulo.test.functional.DeleteRowsIT
- org.apache.accumulo.test.functional.SummaryIT
- org.apache.accumulo.test.functional.BulkSplitOptimizationIT
- org.apache.accumulo.test.functional.ConstraintIT
- org.apache.accumulo.test.functional.BigRootTabletIT
- org.apache.accumulo.test.functional.DeleteIT
- org.apache.accumulo.test.functional.TabletStateChangeIteratorIT
- org.apache.accumulo.test.functional.ScannerIT
- org.apache.accumulo.test.functional.StartIT
- org.apache.accumulo.test.functional.RestartIT
- org.apache.accumulo.test.functional.ManyWriteAheadLogsIT
- org.apache.accumulo.test.functional.BinaryStressIT
- org.apache.accumulo.test.functional.DeleteRowsSplitIT
- org.apache.accumulo.test.functional.LargeRowIT
- org.apache.accumulo.test.CleanWalIT
- org.apache.accumulo.test.ScanFlushWithTimeIT
- org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT
- org.apache.accumulo.test.YieldScannersIT
- org.apache.accumulo.test.BadDeleteMarkersCreatedIT
- org.apache.accumulo.test.SampleIT
- org.apache.accumulo.test.TableOperationsIT
- org.apache.accumulo.test.UserCompactionStrategyIT
- org.apache.accumulo.test.IteratorEnvIT

**Comment by milleruntime** [comment]
Updated list after merging #1713 and copying the accumulo-test jar into lib directory of the running accumulo 21c7a0b9fea405b834f3c79b5df7de8fc80e184d. 

### Timeout failures
org.apache.accumulo.test.functional.SessionBlockVerifyIT
org.apache.accumulo.test.functional.ScanIteratorIT
org.apache.accumulo.test.functional.ReadWriteIT
org.apache.accumulo.test.functional.BulkSplitOptimizationIT
org.apache.accumulo.test.functional.DeleteRowsSplitIT

### Errors
org.apache.accumulo.test.functional.LargeRowIT
```
java.lang.Exception: # of table splits points out of range, #splits=0 table=LargeRowIT_run0 min=4 max=36
        at org.apache.accumulo.test.functional.FunctionalTestUtils.checkSplits(FunctionalTestUtils.java:120)
        at org.apache.accumulo.test.functional.LargeRowIT.test1(LargeRowIT.java:151)
        at org.apache.accumulo.test.functional.LargeRowIT.run(LargeRowIT.java:137)
```

**Comment by milleruntime** [comment]
With the exception of one, I saw all of the failing tests above pass on an instance that was less taxed and with a timeout.factor=3.  The only test that is now failing is SessionBlockVerifyIT, which I will disable so I can close this issue.
