### ISSUE TITLE
Consolidate/Simplify ServerOpts

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1090]
Most server types use the same set of options, but the SimpleGarbageCollector has two additional options which can be removed:

1. `verbose` - This prints to the console, but this should be entirely controlled by log4j settings. We do not need a custom command-line flag to print to the log AND the console, when the logging settings already have the capability to print specific log categories to different destinations.
2. `safeMode` - This should be an option that is possible to set in the configuration file. All configuration file options should be able to be specified on the command-line to override the config file.

In addition, ServerOpts trivially extends ConfigOpts, and is not needed. ServerOpts provides only the `address` option. However, this should also be configurable in the file, and override-able on the command-line. There is no need for a separate option only available on the command-line. Furthermore, when this is added to the config file, its behavior should be more well-defined (in other words, should this be the service advertisement address, or the bind address? currently, I believe it is both, but they should be configurable separately).

**Comment by hkeebler** [comment]
I'll take a stab at this if no one objects.

**Comment by ctubbsii** [comment]
@hkeebler No objection here. You should be able to self-assign the issue if your GitHub id is linked to your Apache id.

**Comment by hkeebler** [comment]
The verbose option only applies to safemode which basically only lists the files to delete.  One would not likely want to set all the log.info messages in this class to print to the console.  Would it make sense to have safemode default to both log and console.  The only time this option would be set is to review the output before doing a GC.  I'm inclined to think that safemode is not really a configuration file option.

**Comment by ctubbsii** [comment]
For the verbose flag, it can go away. The single print statement that the verbose flag currently controls need not be optional. We can always print that message.

For the safeMode flag, we can deprecate that and have it print a warning if used. It can be replaced by `gc.safeMode` configuration property option (or similar). Since configuration options can already be passed on the command-line, it makes sense to replace `--safeMode` with the standard way of passing options on the command-line as `-o gc.safeMode` (I believe that's the format), for consistency. Would need to make sure that boolean options passed this way are implicitly set to true.

**Comment by hkeebler** [comment]
It's a deal ;)

Now, in reference to the latter piece - cleaning up ServerOpts and creating a property(ies) for --address (NOTE: maybe I'm overthinking it):
This could be a generic address override like it is now "server.bind.address" or specific to the service like "tserver.bind.address".  I'm not sure how either of these could be represented in the config (accumulo.properties).  The "server.bind.address" is ambiguous and "tserver.bind.address" could be mulitple.  Yes, as overrides they make sense on the command line `-o server.bind.address=blah .`   Since these would really over ever be set on the command line then I think I vote for the generic form.

**Comment by ctubbsii** [comment]
> Since these would really over ever be set on the command line then I think I vote for the generic form.

I don't think it's the case that they would only be set on the command line, since the most common scenario is to set it to `0.0.0.0`, at least for the bind address. I think it should follow the current conventions of `{tserver,master,gc,monitor}.*`, so they can coexist in the same distributed configuration file. For the advertisement address.. that would probably be more common to set on the command-line, when it differs from the bind address, but even there, I think it's best to follow the current conventions.

Also, I haven't thought this through fully, but these address fields could also deprecate/replace the port option. That might be worth considering, since it'd be very intuitive to specify the bind address as `0.0.0.0:50095` rather than specify the bind address as `0.0.0.0`, and a separate field for the port as `50095`. Keeping the config non-breaking for current users, and the behavior when the port is specified in both locations would be figure out and define.
