### ISSUE TITLE
Set currentRow in PopulateMetadataTable

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1091]
While looking at #1060 I noticed two things about the following code.  First I think currentRow needs to be set when a new mutation is generated.  Second I think the two if stmts `if(m != null)` and `if (!currentRow.equals(metadataRow))` could be combined into one.

https://github.com/apache/accumulo/blob/903119dac631b36009b389193d9d0bc04ed7fb37/server/master/src/main/java/org/apache/accumulo/master/tableOps/tableImport/PopulateMetadataTable.java#L164

**Comment by DomGarguilo** [comment]
It also looks like `BatchWriter mbw` could be created within a try-with-resources block seeing how it is autoclosable. Additionally it does seem like the two mentioned if statements could be combined. I see this is an old ticket but you are assigned, @keith-turner. Are you working on this one?

**Comment by DomGarguilo** [comment]
Are you suggesting that currentRow is updated after the new mutation is created here:
https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/tableImport/PopulateMetadataTable.java#L169
Similar to how it is updated in the if block above it?

**Comment by keith-turner** [comment]
> Are you suggesting that currentRow is updated after the new mutation is created here:

@DomGarguilo yeah I think that is what I was thinking.  

For the comment about `if(m != null)` not exactly sure what I was thinking because I only see `if(m == null)`.   Maybe I was thinking the `if(m==null){...}` and `if(!currentRow.equals(metadataRow)){...}` could be combined but only calling `mbw.addMutation(m);` when `m!=null`.

**Comment by keith-turner** [comment]
> It also looks like BatchWriter mbw could be created within a try-with-resources block seeing how it is autoclosable.

@DomGarguilo  that would be good.  Wonder if it would be possible to put the and ZipInputStream in the try w/ resources also.

**Comment by DomGarguilo** [comment]
> Wonder if it would be possible to put the and ZipInputStream in the try w/ resources also.

Yea, it looks like they both implement closable/autoclosable so they both will work.

**Comment by DomGarguilo** [comment]
@keith-turner, I see you are currently assigned to this ticket. Are you working on this/plan to work on this? If not, I would like to be assigned please.
