### ISSUE TITLE
Replace custom log levels with named logger

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1109]
The class org.apache.accumulo.server.conf.TableConfWatcher uses custom log4j levels that prevents removal of direct log4j dependency.  The functionality can be replaced by using a named logger.

**Comment by ctubbsii** [comment]
I don't see that class using any custom log4j levels in the master/2.0 branch. Perhaps this was already removed? I do, however, see the persisted use of programmatic alteration of the log levels of certain loggers from Hadoop and ZooKeeper.... and we should be able to simply delete those. Users should configure those however they choose, without us interfering with them in our code.
