### ISSUE TITLE
Combine class loading factories

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1113]
I saw this class https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/util/format/FormatterFactory.java

And thought it would be good to combine it with:
https://github.com/apache/accumulo/blob/80aaf658a978d5805c8bda0209b2229795e71ad4/core/src/main/java/org/apache/accumulo/core/crypto/CryptoServiceFactory.java

Both classes are just loading a class from a property.

**Comment by ctubbsii** [comment]
These seem like very distinct factories. I don't see much overlap between them.

**Comment by milleruntime** [comment]
> These seem like very distinct factories. I don't see much overlap between them.

Distant?  Like across packages (joking)..  or functionality-wise?

**Comment by ctubbsii** [comment]
Distinct. :eyeglasses:  :smile:

**Comment by milleruntime** [comment]
Whoops!  Can't read good.

**Comment by milleruntime** [comment]
Combining these classes wouldn't really do much and would probably just make for a messier Factory
