### ISSUE TITLE
TABLET_LOAD error with prevEndRow >= endRow

### ISSUE THREAD

**Issue by adamjshook** [apache/accumulo#1116]
I'm seeing a `TABLET_LOAD` error in the Monitor UI with an exception of `prevEndRow () >= endRow ()` for two separate tables/tablets. The extent being referenced is the last tablet in the table, e.g. `abc;<`. Version 1.9.2.

I'll add that this was after some TServer restarts and recovery of WAL files, though it seems like the WAL files themselves are okay.

**Comment by adamjshook** [comment]
Actually, I was reading the metadata wrong.  They are the *first* tablets in the table.  It has `log` entries in the `accumulo.metadata` table, however a tool that I have reports that there are zero mutations in the WAL for the table.

**Comment by ctubbsii** [comment]
The monitor UI just receives logs from other services, for display. You'll probably have to look at the actual tserver logs and the metadata table to see what's going on.

I seem to recall a recently fixed bug in WALs could have brought back deleted data during WAL recovery. Is that possibly consistent with what you're seeing? (old metadata entries for tablets which don't exist any more) Or does this look like something new?

**Comment by adamjshook** [comment]
There wasn't anything helpful in the logs.  Not even a mention or stack trace in the tserver logs.  I swapped out the WALs with emptys and the issue still persisted.  Eventually ended up removing the `log` metadata entries so the tablets would be assigned.  I'll check the 1.9.3 release notes and changes a bit closer to see if I can blame it on an existing issue.  

To answer your question, these tablets do exist and have data, so I doubt it'd be old metadata entries.  I am wondering if the `check` call on `KeyExtent` has a false positive failure scenario in some situation where both `prevEndRow` and `endRow` are empty or there is no data to recover?  Would a `log` entry get added to `accumulo.metadata` for a tablet that has no data?  My limited understanding is that these `log` metadata entries should only get added when data is written to a tablet.  Maybe some kind of race condition?  These thoughts are all based on the exception message above where the rows are logged -- `prevEndRow () >= endRow ()` -- which shows that they are both empty.

**Comment by ctubbsii** [comment]
Usually people set up their log4j so that ERROR/WARN get forwarded to the monitor, but they still log locally. This message comes from KeyExtent's own constructor... so it could have occurred in the master or a tserver.

To your question about a possible race condition... I think @keith-turner did address one in 1.9.3 (#866), but this doesn't sound like that. Definitely check to see if the other WAL fixes in 1.9.3 might apply. https://accumulo.apache.org/release/accumulo-1.9.3/
