### ISSUE TITLE
Improve Retry code

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1119]
In our code, we often retry operations. So, we have an internal RetryFactory and a Retry object to handle that common pattern. The Retry object's `waitForNextAttempt` method does increment each wait time, by some fixed increment. However, this is problematic, in two ways:

1. It's not exponential, and it should be, and
2. There's no attempt to avoid repeated collisions.

I saw the impact of this on a cluster that was creating a lot of files, and it was slowed down significantly when multiple processes were trying to allocate blocks of names from the UniqueNameAllocator, and kept colliding.

It would be better to change the waitIncrement parameter to be a waitFactor, and to add some fuzziness.

So, instead of:

```java
  currentWait = Math.min(maxWait, currentWait + waitIncrement);
```

we could have something like:

```java
  currentWait = Math.min(maxWait, currentWait * (1+waitFactor+random.nextRandom()));
```

**Comment by jzgithub1** [comment]
Hold off on reviewing code.  I need to add one more interface to set the wait factor for the fluent API.

**Comment by jzgithub1** [comment]
Fluent API for "WaitFactor" is implemented.  Jitter is implemented.  Ready for code review and possible merge.
