### ISSUE TITLE
Remove observers from configuration

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1123]
https://issues.apache.org/jira/browse/ACCUMULO-4822

**Comment by DonResnik** [comment]
I would like to work on this one, but can someone explain why AccumuloConfiguration.getUpdateCount() returns 0?

Thanks

**Comment by DonResnik** [comment]
Ok, I get it now.  This method is meant to be overridden.

I will start to work on this.

**Comment by DonResnik** [comment]
After working on it for some time, it looks like it is more that I anticipated.  I am not ready to work on something this involved yet, so I am going to find another ticket.
