### ISSUE TITLE
Update to htrace-core4

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1126]
I'm working on upgrading to htrace-core4 to match what Hadoop 3 is using for our 2.0 release.

The work is progressing, building on what I did in #964

**Comment by jzgithub1** [comment]
I am looking at this too.

**Comment by ctubbsii** [comment]
@jzgithub1 I created this issue to document the fact that I'm working on this in order to close an older JIRA issue as a duplicate of this, but I don't think there's more to do than what I'm already working on.

**Comment by ctubbsii** [comment]
I tried to do this for 2.0, but I ran into too many API change problems. I'll revisit for 2.1, because I don't want to delay 2.0 further for this.

**Comment by dlmarion** [comment]
It appears that Hadoop is looking to remove HTrace. The HTrace functionality looks to be disabled in the 3.4.0 release (see https://issues.apache.org/jira/browse/HADOOP-17424). There is an umbrella ticket (https://issues.apache.org/jira/browse/HADOOP-15566) for moving to OpenTelemetry.

**Comment by dlmarion** [comment]
I think we should close this in favor of moving to OpenTelemetry (#2257)

**Comment by ctubbsii** [comment]
Closing in favor of #2257
