### ISSUE TITLE
Validate that hadoop2 metrics full covers legacy metrics so that legacy metrics can be removed 

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1133]
For 2.0 we should consider dropping the legacy metrics code - to do this, the first step is to validate that all metrics that are available in the legacy metrics are also available in the metrics that use Hadoop2 metrics package.

**Comment by hkeebler** [comment]
I can take a look at this and try to determine if it is all covered.

**Comment by EdColeman** [comment]
Sorry for the wall of text, but I wanted to provide you with additional background and some of my thoughts.  

This is related to https://github.com/apache/accumulo/pull/1172, which both I and Christopher have been working.  Removing the legacy metrics looks like it will also allow upgrading apache commons config too, so that makes this a blocker for 2.0, so any help is very welcome.

Christopher identified a couple of additional files that I particularly wanted to check that there was some kind of hadoop2 metrics equivalent - anything that extended AbstractMetricsImpl and especially the ThriftMetrics. You can look at the pull request 1172 and see which files seemed to be unused if the legacy code path is eliminated that we have identified so far.

If they are not currently covered, then we should be able to add equivalent hadoop2 metrics as replacements (probably as a separate issue / pull request), but something likely very desirable for releasing 2.0.

It may not be an exact match - I actually have some questions / reservations of the underlying calculations used in the legacy metrics - the way of calculating rolling averages and some others are not familiar to me and I cannot find any references, but they seem that they could be optimizations / light-weight methods for approximating those calculations.  If we "replace" them with standard hadoop2 metrics or something from apache math, then a review of the calculation weight vs code paths should be reviewed so as not to impact performance.  An example (and not implying that we would) but there are ways to calculate standard deviation in one pass vs the naive methods that keeps the samples and uses two passes, or otherwise suffer from stability problems. 

Slight differences should not be a show stopper if we document the differences as well as explain the "upgraded" calculations. Another option would be to pull those calculation methods forward. but report them through hadoop2 metrics. My personal preference is for something standard that is backed by experts in numerical calculations as long as everything else is equal.

From a quick look, the hadoop2 metrics seem well thought out and efficiently implemented, and they are likely okay, but there could have been hadoop assumptions that may make them less than ideal for specific circumstances. 

If we can get these issues examined and documented, then that will really clear the path for this for 2.0.

**Comment by hkeebler** [comment]
Thank you @EdColeman for status and background.  I'll try to get a handle on it this week.

**Comment by hkeebler** [comment]
Searched for unused classes in the remote branch in your pull request and could find no classes related to metrics - thats a good thing.  It looks like the Metrics2 are already implemented so maybe everything is covered.

**Comment by ctubbsii** [comment]
I talked to several users, and as far as I can tell, nobody is using the legacy metrics. So, if there is a gap in what the two implementations provide, it doesn't seem to be of significance to at least those users I interviewed. I think we can probably close this, and selectively add new metrics as needed.

**Comment by EdColeman** [comment]
I looked at one of the classes that I was concerned about (AbstractMetricsImpl) there is a metrics2 implementation and the calculations that it are doing are documents.  There synchronization in the method chain that we call, but being that it has been being used without reported issues I'm less concerned that it represents a significant performance hit.
The call chain ends up create a metrics2 SampleStat that generates equivalent status to the AbstractMetricsImpl and does not generate the extended metrics like stddev,... that are available with metrics2 - if those are needed by users the can generate them using the "raw" number that are being reported.
I agree with closing this.
