### ISSUE TITLE
Ensure 2.0.0 upgrade works properly when 1.9 tservers are still running

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1139]
Need to handle the following situation w/o issue.

 * Accumulo 1.9 is running and all tablets are assigned
 * Only the Accumulo 1.9 master is killed, leaving the Accumulo 1.9 tservers running
 * Accumulo 2.0 is started, what happens with upgrade?

Not completely sure what would happen in the above situation. Want to work through it ensure it does not cause any problems.

**Comment by keith-turner** [comment]
I ran this experiment and the 2.0 master was unable to authenticate with the 1.9 tserver.  I dug into why and its because the system token hashes all instance properties (including default values) to generate the system password.  Accumulo 2.0 has a new instance property `instance.crypto.service` that is not present in 1.9.  This new property is what caused authentication to fail.

There is also a wire version constant that is included in the system token.  I think it may make sense to bump this.

**Comment by ctubbsii** [comment]
Bumping the wire version probably makes sense.
