### ISSUE TITLE
Accumulo 2.0.0 create table options silently ignored by 1.9

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1141]
I tried running an Accumulo 2.0.0-SNAP shell and connecting to 1.9 servers.  I was able to scan and insert data.  For create table 2.0.0 has new options for creating a table with splits and offline. I tried using these new options and the table was created, but the options were silently ignored.

The problem is the following 1.9 code only expects two arguments, but ignores more than 2.  The 2.0.0 code will pass more than 2.

https://github.com/apache/accumulo/blob/rel/1.9.3/server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java#L147

I think argument handling in FateServiceHandler should be more strict, throwing an exception if there are extra arguments.  This should be done in 2.0 and possibly 1.9 if it would not break older 1.9 clients.

**Comment by ctubbsii** [comment]
Throwing an exception if there are unrecognized additional arguments, makes sense to me.
