### ISSUE TITLE
Fix DurabilityIT

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1159]
This IT is a performance IT which means its measuring performance but can fail quite frequently, depending on the situation.  The test testWriteSpeed is particularly flaky and should be rewritten. There are a few things that can be done to fix this IT.

1. Split out the Durability Unit Tests into a separate Test or IT
2. Drop the testWriteSpeed test and drop the performance aspect.

**Comment by keith-turner** [comment]
Another option is to create a performance test in accumulo-testing for it, and remove it from here.

https://github.com/apache/accumulo-testing#performance-test

**Comment by Manno15** [comment]
I am taking a look at Keith's option for this.

**Comment by Manno15** [comment]
Created a pull request with my performance test to hopefully replace the writeSpeed test in this IT.
Link to it below. 
https://github.com/apache/accumulo-testing/pull/74

**Comment by Manno15** [comment]
@milleruntime Should I go ahead and delete testWriteSpeed from here since I am creating a performance test of it in accumulo-testing?

**Comment by milleruntime** [comment]
> @milleruntime Should I go ahead and delete testWriteSpeed from here since I am creating a performance test of it in accumulo-testing?

Yes.

**Comment by milleruntime** [comment]
You could probably just drop the whole IT and not just that single test.

**Comment by Manno15** [comment]
Yeah, I can do that if they are no longer wanted.
