### ISSUE TITLE
Add configuration for minimum number of up tservers for assignment

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#1167]
I have seen this on multiple occasions on our cluster. When the system is brought up with tservers and master in close succession, the master begins its assignment work with a small subset of the tservers in its live tserver set. This causes the master to then have to assign all the tablets to that subset. If it is allowed to finish, it will then notice the other tservers and begin massive balancing.

This issue proposes to add an optional configuration for the minimum number of tservers alive in order to start assigning tservers. This way we could set this number high enough that the master would wait to assign until this threshold is met.

**Comment by milleruntime** [comment]
@alerman Is this what you are thinking? https://github.com/apache/accumulo/pull/1158

**Comment by alerman** [comment]
@milleruntime yes that was precisely what we wanted. I didn't see that before I put this in. I'll close this. Sorry!
