### ISSUE TITLE
Standalone IT with system property set improperly should fail

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1168]
While trying to run the ITs against a standalone cluster, the system properties "-Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties"
are required but if the path is wrong to the file or there are problems with the properties file, then the framework will default to Mini, and pass.  

It would be nice if these properties are set, most importantly the property file, that we do some validation and at the very least fail fast with a clear error ascertaining the problem.

**Comment by DonResnik** [comment]
I am going to work on this.  I will let you know if I run into any problems.

**Comment by DonResnik** [comment]
It looks like the class that needs to be updated is AccumuloClusterPropertyConfiguration.  Possibly throwing exceptions with additional info instead of just logging the exception.  However, I am not sure how to test this.  Is this part of the 'mvn verify' goal, or is there another way to test?  I was reading about 'mvn verify' but even if that does test this class, I am not sure how to create the error condition with the properties file so it shows my updates in the test.

Any info would be appreciated.  Thanks.

**Comment by milleruntime** [comment]
> Possibly throwing exceptions with additional info instead of just logging the exception. However, I am not sure how to test this. Is this part of the 'mvn verify' goal, or is there another way to test? I was reading about 'mvn verify' but even if that does test this class, I am not sure how to create the error condition with the properties file so it shows my updates in the test.

If the path is wrong to the file -Daccumulo.it.properties=/path/to/accumulo-it.properties that should create an error condition. If there are missing properties in the file that is another error condition.

**Comment by DonResnik** [comment]
I understand that and I am pretty sure I know where to update the code.  What I don't understand is what is the command that uses these arguments:

"-Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties"

I have been reviewing the docs on MAC but I don't see any place where these arguments are described or used in any example.  If you could provide an example or point me to some docs I have not found, I would appreciate it.

Thanks.

**Comment by Manno15** [comment]
The testing.md file in the standalone instance section has some useful info on how to configure and how to run the test. Link provided. 

https://github.com/apache/accumulo/blob
/master/TESTING.md

Let me know if you have any additional questions.

**Comment by EdColeman** [comment]
If I understand your question, those are being passed to maven / test plugins (failsafe / surefire) and to the test frameworks. Maybe the documentation at https://maven.apache.org/surefire/maven-failsafe-plugin/ helps?

 

-Dit.test= AccumuloClientIT  specifies to the plug in what IT test to run.

-Dtest=foo – passes a fake unit test so no unit tests actually get executed.

 

Not sure without looking what’s in the accumulo-it.properties.

**Comment by DonResnik** [comment]
Thanks for the comments.  After reading the recommended links I believe what I need to run is

man verify -Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties

or maybe 

mvn verify -Dfailsafe.groups=org.apache.accumulo.test.categories.StandaloneCapableClusterTests     -Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties

To get familiar with the mvn verify ITs I tried to run this off master:
mvn verify -Dfailsafe.groups=org.apache.accumulo.test.categories.MiniClusterOnlyTests

I thought I should see the MAC ITs complete before trying the standalone ITs, but I got this error:

[INFO] --- spotbugs-maven-plugin:3.1.7:spotbugs (spotbugs) @ accumulo-core ---
[INFO] Fork Value is true
     [java] The following errors occurred during analysis:
     [java]   Unable to locate method java.util.HashSet.forEach(Ljava/util/function/Consumer;)V
     [java]   Unable to locate method java.util.HashSet.removeIf(Ljava/util/function/Predicate;)Z
     [java]   Unable to locate method java.util.HashSet.stream()Ljava/util/stream/Stream;
     [java] Warnings generated: 1
     [java] Analysis errors: 3
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] <<< spotbugs-maven-plugin:3.1.7:check (run-spotbugs) < :spotbugs @ accumulo-core <<<
[INFO] 
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.7:check (run-spotbugs) @ accumulo-core ---
[INFO] BugInstance size is 1
[INFO] Error size is 3
[INFO] Total bugs: 1
[ERROR] Null passed for non-null parameter of ScannerOptions.fetchColumn(IteratorSetting$Column) in org.apache.accumulo.core.clientImpl.ScannerOptionsTest.testFetchNullColumn() [org.apache.accumulo.core.clientImpl.ScannerOptionsTest] At ScannerOptionsTest.java:[line 83] NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS
[INFO] 

I got the same error with:
mvn verify -Dfailsafe.groups=org.apache.accumulo.test.categories.StandaloneCapableClusterTests     -Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties

Please let me know what I am missing so these tests will complete.

Thanks.

**Comment by hkeebler** [comment]
Don,  first thing I would try is add a clean - mvn clean verify ......

**Comment by Manno15** [comment]
Also, which version of maven are you using? I have had issues running verify in the past when using an old version.

**Comment by DonResnik** [comment]
Thanks for all the responses.  Maven version is 3.6, so I think that is ok.  The mvn clean verify look like it is making a difference.  I am trying 

mvn clean verify -Dfailsafe.groups=org.apache.accumulo.test.categories.MiniClusterOnlyTests

but it has not finished yet.

I have  a 2013 mac book air with 8Gb.  Should I make sure to have no other apps running while running the ITs...does it need that many resources to complete?

**Comment by milleruntime** [comment]
> mvn clean verify -Dfailsafe.groups=org.apache.accumulo.test.categories.MiniClusterOnlyTests

This will run all the Tests and all the verification plugin checks, which will take a while.  I'd recommend running just a clean without any tests which should only take a few minutes.  Do that with this command:
`mvn clean verify -DskipTests -Dspotbugs.skip`

**Comment by DonResnik** [comment]
Mike,

mvn clean verify -DskipTests -Dspotbugs.skip worked, thx for that recommendation.  

I think I have a way forward to test the point of the ticket now.  I can just run this

mvn verify -Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties

with a bad/missing properties file and update the conditional handing of the file in accumulo so it does not just create a MAC.  It does not have to complete, I just have to know it made the correct type of cluster or surfaced an error.  Does that sound reasonable?  Thanks,

**Comment by DonResnik** [comment]
I am getting a lot closer, but I have another question.  Basically, I am working in this class

AccumuloClusterPropertyConfiguration

and changing the appropriate log statements to RuntimeExceptions.  It works with the example

mvn verify -Dit.test=AccumuloClientIT -Dtest=foo -Daccumulo.it.properties=/path/to/accumulo-it.properties

with an error saying the file cannot be found instead of just switching to the MAC.

Then I wanted to see it actually work, so I tried the same line but with the correct path to the accumulo-it.properties that is in my uno directory and I got this error:

[ERROR]   AccumuloClientIT.testClose:146 expected:<CLIENT> but was:<SERVER>

Am I supposed to use a different accumulo-it.properties and somehow designate it as a client?  I am not sure how to do that and I don't see it addressed in the docs.  Any help would be appreciated.

Thanks.

**Comment by DonResnik** [comment]
I just realized the error did not print correctly because it used gt lt brackets like html.  With those removed the error looks like:

[ERROR] Failures: 
[ERROR]   AccumuloClientIT.testClose:146 expected:CLIENT but was:SERVER

Am I supposed to use a different accumulo-it.properties and somehow designate it as a client? I am not sure how to do that and I don't see it addressed in the docs. Any help would be appreciated.

Thanks.

**Comment by hkeebler** [comment]
Don,  this is a know error with a fix submitted and waiting for merge.  NOte that I have yet been able to run the entire suite of IT tests for standalone in a single submission.  Something ultimately times out and/or deletiions get hung.

**Comment by DonResnik** [comment]
Thanks for the info.  Given that, I will focus on the error handling from the conditions outlined in the ticket and make sure they perform as expected, and not worry about all the ITs completing.

**Comment by DonResnik** [comment]
I can get the test to fail if I use a bad filename.  But I am unable to get it to fail by attempting to corrupt the file.  I removed all the equals signs and added a lot of chars I thought would cause it to fail (%^&*((), but all the tests still passed.

Does anyone have any ideas on how to corrupt the accumulo-it.properties file so it loads but fails on fileProperties.load(reader) AccumuoClusterPropertyConfiguration line 74.

Any ideas would be appreciated.  Thanks.

**Comment by milleruntime** [comment]
> I can get the test to fail if I use a bad filename. But I am unable to get it to fail by attempting to corrupt the file. I removed all the equals signs and added a lot of chars I thought would cause it to fail (%^&*((), but all the tests still passed.
> 
> Does anyone have any ideas on how to corrupt the accumulo-it.properties file so it loads but fails on fileProperties.load(reader) AccumuoClusterPropertyConfiguration line 74.
> 
> Any ideas would be appreciated. Thanks.

I wouldn't worry about that.  Validation can be done on the actual properties themselves.

**Comment by DonResnik** [comment]
Ok, then it seems like just replacing the log statements with RuntimeExceptions in the catch blocks will do what this ticket is looking for.  I will submit a pull request with that solution as a start and see what comments I get.  Thanks.

**Comment by ctubbsii** [comment]
Re-opening because there's more work to be done before the change can be merged (so it doesn't cause additional IT failures).
