### ISSUE TITLE
Clean up user/table creation/cleanup in AccumuloClusterHarness

### ISSUE THREAD

**Issue by hkeebler** [apache/accumulo#1171]
#1164  - Update the harness to create "test unique" users.prefixed with something (currently the tables are prefixed with the method name) so that each test can perform proper cleanup when finished.   The current  deleteusers code in the harness look for users prefixed with the method name to delete but that is not how they are created so the deletion does not work.

@keith-turner commented that the class name as a prefix is confusing because with inheritance and multiple classes its hard to know if you got it right. Maybe just use a constant like

public static final String HARNESS_USER_PREFIX="a1b1ae6bfef2ca11d92b86ab60930b3c56971f6e"

Then all code can just use that constant. I picked the latest commit hash on the master branch for the value. The constant could also be a classname, it does not really matter what it is as long its somewhat unique.

When this is completed all ITs implementing this class that use getUser(int) can remove all explicit user delete code.

**Comment by hkeebler** [comment]
After looking further into this they "whys" of how things are being done in MINI vs STANDALONE are too unclear - why can't STANDALONE create users the same way as MINI vs adding them to the config file?
Therefore I am deleting this ticket and leaving it up to resolutions made in ticket #1074

**Comment by ctubbsii** [comment]
Closing issue, upon recommendation of the reporter.
