### ISSUE TITLE
Password CLI Bug

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1190]
I was using a script I had written for TestIngest and it is now broken in 2.0.  It looks like "-p" no longer works.  "--password" seems to work just fine.  I will investigate further.

Here is what gets printed in the shell:
```
Was passed main parameter '-p' but no main parameter was defined in your arg class
```

**Comment by milleruntime** [comment]
Also seeing this with the "instance option"
```
Was passed main parameter '-i' but no main parameter was defined in your arg class
```

**Comment by ctubbsii** [comment]
Try: `shopt -s globstar; grep -R '"-p"' **/src/main/java/`

The output shows ShellIT and ShellServerIT both using `-p`, and those tests pass fine. Perhaps the issue is with your script?

**Comment by milleruntime** [comment]
> Try: `shopt -s globstar; grep -R '"-p"' **/src/main/java/`
> 
> The output shows ShellIT and ShellServerIT both using `-p`, and those tests pass fine. Perhaps the issue is with your script?

I think its with ``` TestIngest ``` since that is what the script is using.  Here is what is causing issues:

```
accumulo org.apache.accumulo.test.TestIngest -i uno -u root -p secret --rows "${ROWS}"
```

Checkout ``` shopt -s globstar; grep -R 'TestIngest' **/src/main/java/ ``` We using it in a bunch of Tests but doesn't look like we use it in the Shell tests.

**Comment by ctubbsii** [comment]
I suspect this is one of those ones that @mikewalch updated to use the client properties file. When I run your grep, I get a bunch that look like they are passing: `["-c", getClientPropsPath()]`, with the expectation that the password and instance information is in the client props file.

**Comment by milleruntime** [comment]
This isn't a bug. It was just a change in behaviour from 1.9 to 2.0.
