### ISSUE TITLE
Move Performance Tests to Testing Repo

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1200]
There are a few tests left in Accumulo labeled with the ```PerformanceTests``` category.  These should be moved to [Accumulo-Testing](https://github.com/apache/accumulo-testing).

- DeleteTableDuringSplitIT
- DurabilityIT
- RollWALProfrmanceIT
- ManySplitIT
- BalanceFasterIT

**Comment by elinaawise** [comment]
I'm looking at this.

**Comment by elinaawise** [comment]
DurabilityIT:  performance tests were moved to DurabilityWriteSpeedPT in accumulo-testing per issue #1159.  PerformanceTests annotation was left in DurabilityIT, which I'm removing.  Otherwise, there are no other changes to be done to this test from what I can tell.

**Comment by elinaawise** [comment]
DeleteTableDuringSplitIT:  I don't think performance tests exist in this class and will remove the PerformanceTests annotation.

**Comment by EdColeman** [comment]
I cannot speak directly to the performance test - but in the past, I seem to recall deleting a table while it was splitting (or compacting) could take a long time - I believe that there were changes to improve the time spent for the deletion to occur (I think it may have been related to issues where the delete would block, waiting for the operations to complete - which, being it was to be deleted didn't really matter if it finished or not)  Could it be that these "performance" tests were to validate those solutions?  Maybe this would help guide where / when these tests are run and signal their intention?  

Not saying that the change to remove the annotation is incorrect, just asking more questions.

**Comment by elinaawise** [comment]
I moved RollWALProformanceIT to accumulo-testing project.  However, I ran out of time and it needs to be double checked.

**Comment by lbschanno** [comment]
Taking a look at this. Given that ContinuousIngest is currently only referenced by RollWALPerformanceIT, is there any need to keep it in the accumulo repo? I noticed that it supports commandline args, and I can leave it if it's necessary for any non-programmatic interaction.

**Comment by milleruntime** [comment]
This was done in #1264
