### ISSUE TITLE
Create type for time to use when reading and write Accumulo metadata

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1210]
Currently when using Ample to read and write time to the Accumulo medata a String is used.  It would be better to use a type that encodes the time type and long.

**Comment by hkeebler** [comment]
I'll work on this.

**Comment by hkeebler** [comment]
As it turns out there is already a TabletTime abstract class with MillisTime and LogicalTime implementations.  The returned string value from this object is the "time string - ex. M12345678" passed to the metadata operations.  Is this too heavyweight to pass through instead of a string?

**Comment by hkeebler** [comment]
We would need to move TabletTime from the server module to core which kind of makes sense.

**Comment by keith-turner** [comment]
I took a look at TabletTime and it does not seem like a good fit because it also has functionality for tracking a tablets current time.  This tracking code is used by tablets as they processing incoming mutations.  The tracking code makes TabletTime mutable.  

I think it would be better to have a much simpler immutable POJO that represents the information stored in the metadata table.  Something like

```java
public class MetadataTime {
  private final TimeType type;
  private final long time;

  // TODO constructor, getters, hashcode, equals
}
```

Tablet time could be modified so that its constructed using this new POJO.

**Comment by hkeebler** [comment]
Yes.  That is what I started with until I saw TabletTime.  So I think we agree that TabletTime could use o r maybe just return a MetadataTime.   The Millisecond and Logical implementations use different constructs.  I'll play around with it.

**Comment by keith-turner** [comment]
> So I think we agree that TabletTime could use o r maybe just return a MetadataTime.

I think TabletTime is a bad fit for Ample because it has a lot of complex logic that goes way beyond the simple need to represent the data stored in the metadata table.

**Comment by hkeebler** [comment]
I'm considering the following update to TimeType and suggest using this instead of the single character checks for 'M' and 'L' in different places.
```
/**
 * The type of ordering to use for the table's entries (default is MILLIS)
 */
public enum TimeType {
  /**
   * Used to guarantee ordering of data sequentially as inserted
   */
  LOGICAL('L'),

  /**
   * This is the default. Tries to ensure that inserted data is stored with the timestamp closest to
   * the machine's time to the nearest millisecond, without going backwards to guarantee insertion
   * sequence. Note that using this time type can cause time to "skip" forward if a machine has a
   * time that is too far off. NTP is recommended when using this type.
   */
  MILLIS('M');

  public final char code;

  /**
   * Parses a char code into a TimeType - like valueOf on name
   * 
   * @param code
   * @return type matching code or null if not found
   */
  public static TimeType valueOfCode(char code) {
    for (TimeType type : values()) {
      if (type.code == code)
        return type;
    }
    return null;
  }

  /**
   * Enum constructor
   * 
   * @param code
   */
  private TimeType(char code) {
    this.code = code;
  }

}
```

**Comment by keith-turner** [comment]
@hkeebler I really like the proposed changes to TimeType, however TimeType is in the public API and the code is an internal implementation detail best left out of the public API.  I am not sure where to put it, but we should have an internal static method that is similar to the valueOfCode method.  Maybe something like

```java
package some non api package;

class TimeTypeImpl {
  public static TimeType valueOf(char code) {
     switch(code) {
        case 'M':
             return TimeType.MILLIS;
        case 'L':
              return TimeType.LOGICAL;
         default:
             throw new IllegalArgumentException("Unknown time type code : "+code);
     }
  }
}
```

**Comment by hkeebler** [comment]
Thanks.  How can one tell what is a public api package?

**Comment by keith-turner** [comment]
> Thanks. How can one tell what is a public api package?

The following page needs some updates for 2.0, but its the source.

https://accumulo.apache.org/api/

**Comment by hkeebler** [comment]
I added it as a static method to MetadataTime.  I think that works (??)
```
package org.apache.accumulo.core.metadata.schema;

import org.apache.accumulo.core.client.admin.TimeType;

public class MetadataTime {
  private long time;
  private TimeType type; // default type is M for milliseconds

  public MetadataTime(long time) {
    this(time, TimeType.MILLIS);
  }

  public MetadataTime(long time, TimeType type) {
    this.time = time;
    this.type = type;
  }

  public MetadataTime(String timestr) throws Exception {
    if (timestr != null && timestr.length() > 1) {
      type = TimeType.valueOfCode(timestr.charAt(0));
      time = Long.parseLong(timestr.substring(1));
    } else
      throw new IllegalArgumentException("Unknown metadata time value " + timestr);
  }

  /**
   * Converts timetypes to data codes used in the table data implementation
    * @param code
   * @return TimeType represented by code.
   */
  public static TimeType valueOf(char code) {
    switch(code) {
      case 'M':
        return TimeType.MILLIS;
      case 'L':
        return TimeType.LOGICAL;
      default:
        throw new IllegalArgumentException("Unknown time type code : "+code);
    }
  }

  /**
   * @return the single char code of this objects timeType
   */
  public char getCode(){
    switch(this.type) {
      case MILLIS:
        return 'M';
      case LOGICAL:
        return 'L';
      default:
        return 'M';
    }
  }
  public TimeType getType() {
    return type;
  }

  public void setType(TimeType type) {
    this.type = type;
  }

  public long getTime() {
    return time;
  }

  public void setTime(long time) {
    if (time < 0)
      throw new IllegalArgumentException();
    this.time = time;
  }

  @Override
  public boolean equals(Object o) {
    if (o instanceof MetadataTime) {
      MetadataTime t = (MetadataTime) o;
      return time == t.getTime() && type == t.getType();
    }
    return false;
  }

  @Override
  public int hashCode() {
    return 31 * ((31 * Long.valueOf(time).hashCode()) + (31 * type.hashCode()));
  }

  @Override
  public String toString() {
    return "" + getCode() + time;
  }


}
```

**Comment by keith-turner** [comment]
Looks good @hkeebler.  Few questions
 * Why can't MetadataTime be immutable?  Much easier to reason about immutable types.
 * Why have the constructor with no TimeType? Thinking its better to always be explicit.
 * Why have the constructor that does deserialization in a constructor?  Could this possibly be hidden away in private Ample code?

Also, you could possibly use Objects.hashCode to implement your hashCode method.
