### ISSUE TITLE
Determine why metric reported 4 quadrillion ms

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1222]
Saw the following while testing 2.0.0-SNAPSHOT.  Need to determine why the commit prep time metric was so high.

![update-time](https://user-images.githubusercontent.com/1268739/59799927-6868a300-92b3-11e9-9014-0659f4696c65.png)

**Comment by Manno15** [comment]
@keith-turner What tests were you running when getting these results? I want to see if I can reproduce these so I can get to the bottom of it.

**Comment by keith-turner** [comment]
I am not sure, but probably continuous ingest.  Possibly with tablet server agitation.

**Comment by ctubbsii** [comment]
The metrics code casts the size of the `updates.entrySet()` (which is an `int`) to a `double`, so it can be the divisor for the total time taken in millis (which is a `long`), presumably so it can keep some precision in the division, before it casts to a long to return the result.

I see two possibilities:

1. The entry set was empty, and casting it to a `0` to a double resulted in something very large when placing this "very close to, but not quite zero" value in the denominator, or
2. The system clock was updated and caused a bigger than expected time difference in millis when using `System.currentTimeMillis()`.

I think option 1 is more likely. We should probably guard against the set being empty before adding a metrics.

There are two methods that do this: https://github.com/apache/accumulo/blob/ebca8e13dd12fc866887ebbd773ceeacb69a2f3e/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java#L1156-L1162

**Comment by ctubbsii** [comment]
This should be a simple fix for 2.0. We just return in the above methods if `(size < 1)`.

**Comment by Manno15** [comment]
I'll add those changes and do some quick testing, doubt I can reproduce this bug consistently enough to guarantee it being fixed
