### ISSUE TITLE
Monitor log recovery says invalid date

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1223]
While running a very recent version of 2.0.0-SNAP I saw the following on the monitor during log recovery.  #917 is a similar issue that was fixed.  The output is now different.

![log-recovery](https://user-images.githubusercontent.com/1268739/59804747-38be9880-92bd-11e9-9d52-8fe2ae727e07.png)

**Comment by ctubbsii** [comment]
This could be due to the monitor updates I did for Java 11 to deal with the missing javax/EE stuff, so the monitor worked in Java 11 better. Hopefully the fix is just as simple as it was before. @jzgithub1 you fixed this in #1028 ; want to attempt it again?

**Comment by jzgithub1** [comment]
Sure thing.  I will get on it now.

**Comment by jzgithub1** [comment]
Looks like the move to Thrift Compiler 0.12.0 caused this.  Investigating.

**Comment by ctubbsii** [comment]
After a few minutes of my own investigation, I noticed that the original fix in #917 did not fix the problem. It mistakenly changed the variable from `time` to `runtime` (presumably on the belief that the underlying POJO being presented in the REST interface was the class `RecoveryStatusInformation`, but it was actually `TabletServerRecoveryInformation`).

The actual error was that the `time` field was being interpreted as an absolute time to be used with `new Date(time)`, when the `time` field was actually a time duration, and needed to be displayed as such.

I have a fix for this, and will push it shortly.

**Comment by ctubbsii** [comment]
![Screenshot from 2019-06-20 19-42-16](https://user-images.githubusercontent.com/1280725/59888057-d84e5a80-9393-11e9-9868-e7a492f8891a.png)
![Screenshot from 2019-06-20 19-42-48](https://user-images.githubusercontent.com/1280725/59888058-d84e5a80-9393-11e9-9e56-1592c01b52f3.png)

I fixed the issue in 41600678131dd30b1609ff7dc7f4b3476072bffa

**Comment by keith-turner** [comment]
@ctubbsii fixing the percentage made my day!

**Comment by jzgithub1** [comment]
Great catch @ctubbsii.   The original fix looked so obvious.
