### ISSUE TITLE
CyclicReplicationIT.dataIsNotOverReplicated fails frequently

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1226]
There's clearly a bug in the test (or in the replication code it is intended to test): `org.apache.accumulo.test.replication.CyclicReplicationIT.dataIsNotOverReplicated`

It fails frequently on every branch (currently: 1.9, 2.0, and master), and has done so for as long as I can remember (1.7?), and I've never had time to investigate it. I've grown accustomed to ignoring it, but lately it's been bothering me more than usual... (I've been running more tests, more frequently, lately, so I'm seeing this failure more often.)

This test's failures should be investigated and either fixed, or disabled.

**Comment by milleruntime** [comment]
This test is doing so much (along with some of the other Replication tests) that its almost like it should be its own testing suite in Accumulo Testing repo.

**Comment by Manno15** [comment]
I am going to try to look into why this is failing. So far the error hasn't occurred on the master branch on my end though. Ill try against the 2.0 branch next.

**Comment by ctubbsii** [comment]
> I am going to try to look into why this is failing. So far the error hasn't occurred on the master branch on my end though. Ill try against the 1.9 branch next.

You may have to run multiple times to reproduce. It doesn't fail every time.

**Comment by jzgithub1** [comment]
I see a lot of these warnings when I run CyclicReplicationIT:
2019-06-26 08:22:23,036 [rpc.ThriftUtil] WARN : Failed to open transport to <myhostname>:46607

But the test still passes.

**Comment by ctubbsii** [comment]
> I see a lot of these warnings when I run CyclicReplicationIT:
> 2019-06-26 08:22:23,036 [rpc.ThriftUtil] WARN : Failed to open transport to :46607
> 
> But the test still passes.

Those warnings are expected, because the tserver is killed as part of the test, and restarted. The test code issues that warning while it retries to connect.

When the test fails for me, it is often the case that the process never restarts and those warnings continue until the test times out. This happens on CentOS 7. It's possible that there's a better way to force the WAL to close, or at the very least, a more reliable way to restart the tserver.

**Comment by jzgithub1** [comment]
Those are good ideas on how I can improve the test.  I will look into implementing a forced WAL closure and reliable way to restart the tserver.
