### ISSUE TITLE
Seeing invalid date for GC on master monitor page

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1230]
Seeing invalid date for GC on the master monitor page.

![master_date](https://user-images.githubusercontent.com/1268739/59942835-bb1a9a00-942e-11e9-8a27-e9ef621d0660.png)

**Comment by hkeebler** [comment]
Is this in the 2.0 build?

**Comment by hkeebler** [comment]
@Manno15 said that restarting the GC will fix it.  The GC gets in some funky state that probably returns null for time.  So the question is what should be done when this happens?  Maybe return "unavailable" vs. invalid date?

**Comment by keith-turner** [comment]
@hkeebler  I am running a very recent version of 2.0.0-SNAPSHOT.  I just looked at and now I see a date.  I am running test with agitation where the master and tservers are being killed.  However I am not killing the GC process.

![master_date_2](https://user-images.githubusercontent.com/1268739/59944755-a12f8600-9433-11e9-8c9e-39c7b4a17679.png)

> So the question is what should be done when this happens? 

First determine whether this is a GC or monitor bug.    As far as what to display, I am not sure.  There are the following possible states :
  1. No GC process is running.  Could display `Unknown` for this state.
  2. GC process is running, but has never completed a GC cycle.  Could display `Never` for this state.
  3. GC process is running and has completed a GC cycle

**Comment by hkeebler** [comment]
@keith-turner curious if you could click through to the GC status page from the "INVALID" and what it displayed.

**Comment by hkeebler** [comment]
I think this can be bettered by a small change master.js .  The "lastGC" can be a finish time or Running, Waiting or down.  A parseInt is done and the status string values are lost.  I will commit this but will be out after today until Monday July 1st.
