### ISSUE TITLE
Annotate blip markers when exception happens during bulk import

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1247]
When an unexpected exception happens during bulk import it may be that not all files are imported.  This happened in #1231.  Bulk import are executed by FATE.  When FATE see's an unexpected exception it marks the transaction as failed and starts executing the Undo operations.  For bulk import, one of the undo steps could set a value of `FAILED` on the blip marker.  If this were done then a user could grep the `~blip` range for `FAILED` to find all bulk import directories that may have been partially imported.

Possible causes of unexpected exceptions are bugs and improperly handled zookeeper and hdfs exceptions.

**Comment by milleruntime** [comment]
Do you think this should be done for 2.0?  We could make this a part of the new bulk import feature.

**Comment by keith-turner** [comment]
Another way to solve this problem is to always put the FATE txid as the blip value. Then with a tool blip values could be cross referenced with FATE txid in ZK.  We could put that fate txid in now and create the tool later.

**Comment by milleruntime** [comment]
> > Do you think this should be done for 2.0?
> 
> I was unsure. I can create a PR and we can go from there.

I think it would be very useful to have as a debugging tool for the old and new bulk import.  Just to have to value there so admins can grep for it.
