### ISSUE TITLE
Allow FATE operations to report goal and status information.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1249]
It would be very useful if FATE operations could report goal and status information.  This information could be display via command line utilities and on the monitor page.  Alternatively the information could just be logged in a very consistent way.  Goal information would be what the FATE op is trying to do and should not change for lifetime of the FATE operation.  Status information changes as the FATE operations proceeds.  For example for bulk import, Goal and status information could look like the following.

 * Fate Transaction : 1f2e3d4c
 * Goal: Import files from `hdfs://nn1/userdir5` to table `mediumTable`
 * Status :
   * 07/04/19 20:33 Writing blip marker to metadata table
   * 07/04/19 20:34 Moving files from `hdfs://nn1/userdir5` to `hdfs://nn1/accumulo/table/5/b-678`
   * 07/04/19 20:37 Requesting tablet servers to import files

**Comment by ctubbsii** [comment]
That'd be very neat.

**Comment by keith-turner** [comment]
#1316 has overlapping goals.

**Comment by jmark99** [comment]
@EdColeman are you currently working on this task? If not, do you mind if I give it a go?

**Comment by EdColeman** [comment]
I'm working fate metrics, but have not started this.

**Comment by milleruntime** [comment]
@jmark99 are you still looking at this?

**Comment by jmark99** [comment]
@millerruntime yes, I’ve been away for two weeks on vacation. Just getting back today.

**Comment by milleruntime** [comment]
Here are some ideas for the displaying FATE status in the monitor (and an issue specific to the monitor, that can be done separately): https://issues.apache.org/jira/browse/ACCUMULO-809

**Comment by jmark99** [comment]
Removed myself from this ticket since I haven't had a chance to do much work on it lately and Keith may be addressing it with #1624.
