### ISSUE TITLE
Saw datatables error in monitor while agitating

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1258]
While agitating the master and tserver during a bulk import test I saw the following error when trying to look at the tserver page.  The error was transient.

```
DataTables warning: table id=tservers - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

**Comment by milleruntime** [comment]
I am not sure there is anything to be done here.  The Rest end point that was gathering the data most likely failed to get it from the Monitor.

**Comment by milleruntime** [comment]
Do you have a screen shot?  If not, where did you see this error?

**Comment by keith-turner** [comment]
The error popped up in a little dialog box at the top the web page.

**Comment by keith-turner** [comment]
I just checked and saw the error again.

![Screenshot from 2019-07-09 15-16-44](https://user-images.githubusercontent.com/1268739/60916636-e984db80-a25c-11e9-9281-cd98e0bfd5ca.png)

**Comment by milleruntime** [comment]
I killed the Master and found some other minor issues with the Monitor.  I will open up a PR with a few fixes.
