### ISSUE TITLE
Research if Ample should have sanity checks for no tablets seen

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1267]
While working on #1260 I realized that Ample could possibly check for the case of no tablets for a table seen and throw an exception.  This could be done when consistency checking is requested.  Not sure if this is worthwhile.  Need to look at code that scans metadata table and see if it would behave badly if for some reason the metadata scan returned nothing.

**Comment by milleruntime** [comment]
@keith-turner is this the same as https://github.com/apache/accumulo/issues/1507 ?  It sounds similar... perhaps just related.

**Comment by keith-turner** [comment]
@milleruntime I think this is more similar to #1377.  I was thinking of the case where the master and gc scan the metadata table and the scan returns zero tablets.  I think this issue is too vague and could be closed in favor of #1377
