### ISSUE TITLE
Clicking "Clear Logs" on 2.0 monitor /log page does not reset count in top bar

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1272]
Clearing the logs in the new monitor clears the table of logs, but leaves the count in the upper-right hand corner of the web page alone. This should be a simple javascript fix to update that part of the page after clearing the table, but I haven't investigated.

**Comment by hkeebler** [comment]
I'll take a look.

**Comment by hkeebler** [comment]
@ctubbsii I think I have a fix for this but do I check this into 2.0 or just master?
I haven't pushed a fix to a branch other than master before.

**Comment by ctubbsii** [comment]
A pull request against 2.0 is best for this one. When you open the pull request, GitHub offers a drop-down, where you can select to submit against the 2.0 branch.

**Comment by ctubbsii** [comment]
I added instructions on PR #1274 to change the current PR to 2.0.
