### ISSUE TITLE
Master prints unnecessary warnings about bulk import _SUCCESS and loadmap.json files

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1273]
Saw the following in the monitor (coming from the master logs) while testing 2.0.0 with accumulo-testing's `bin/cingest bulk`:

```
hdfs://burninator:8020/tmp/bt/15/files/_SUCCESS does not have a valid extension, ignoring
hdfs://burninator:8020/tmp/bt/15/files/loadmap.json does not have a valid extension, ignoring
```

I'm pretty sure these files are expected, and shouldn't trigger any warnings.

**Comment by hkeebler** [comment]
I believe this is coming from PrepBulkImport code below.  Only ".map" and ".rf" files are good to process.  Maybe to best this is to remove the "warning message" completely since we know that other types of files will be there or change the message to something like "{} exempt from processing, ignoring", fileStatus.getPath()

```
for (FileStatus file : files) {
      final FileStatus fileStatus = file;
      final Path originalPath = fileStatus.getPath();
      String[] fileNameParts = originalPath.getName().split("\\.");
      String extension = "";
      boolean invalidFileName;
      if (fileNameParts.length > 1) {
        extension = fileNameParts[fileNameParts.length - 1];
        invalidFileName = !FileOperations.getValidExtensions().contains(extension);
      } else {
        invalidFileName = true;
      }
      if (invalidFileName) {
        log.warn("{} does not have a valid extension, ignoring", fileStatus.getPath());
        continue;
      }
```

**Comment by keith-turner** [comment]
> Maybe to best this is to remove the "warning message"

Could also log it at debug instead of removing it.

**Comment by ctubbsii** [comment]
If they are created by the bulk import code itself, it definitely shouldn't give warnings about files it creates itself, but we don't want to lower the warning to "DEBUG" if it sees other unexpected files.

I don't know who created these files, or if they have a choice to put them elsewhere. Are these files created by the bulk import code or the testing code?

**Comment by hkeebler** [comment]
Bulk import creates the loadmap.json file.    We could create a list of "expected files to ignore" but would need to figure out what they all are.

**Comment by keith-turner** [comment]
#1255 is related

**Comment by hkeebler** [comment]
so...based on the 'like' should I look into implementing the "expected files" set?

**Comment by ctubbsii** [comment]
@hkeebler I haven't looked into it enough to know what the refactor should look like, but it would make sense for the checks in the master/fate code to be consistent with those in the clientImpl. However, looking at the change in #1255 , I'm not sure it's a good idea to have *all* unknown files logged at `debug`. I think some actually warrant `warn`.

There appear to be a few different file types and each probably requires a different action:

1. Expected files to bulk import: `*.rf`. (I'm not even sure we support map files anymore)
2. Directories (do we recurse or log that we're ignoring? I'm not sure the current behavior)
3. Well-known files that are not ours, but common from MapReduce and safe to ignore (`_SUCCESS`,  `_logs`?); logging these at debug probably makes sense
4. Files we create ourselves (or expect the user to provide): JSON loadmap files or rename mapping files; these can be ignored or we could log (at debug) that we're using them when we actually read them.
5. Completely unknown files that are not expected or typical. These should probably log at the `warn` level.

**Comment by hkeebler** [comment]
Based on a "refactor" of the process should this be moved to 2.1, not hold back 2.0 release.

**Comment by hkeebler** [comment]
My suggestion for now.  Maybe a refactor later.
Update BulkIMport.filterInvalid to public and change as below and replace the for loop that is checking in PrepBulkImport with a call to this.  
```
**public** static List<FileStatus> filterInvalid(FileStatus[] files) {
    ArrayList<FileStatus> fileList = new ArrayList<>(files.length);

    for (FileStatus fileStatus : files) {

      String fname = fileStatus.getPath().getName();

      if (fname.equals("_SUCCESS") || fname.equals("_logs")) {
        log.debug("Ignoring file likely created by map reduce : {}", fileStatus.getPath());
        continue;
      }

      if (fileStatus.isDirectory()) {
        log.debug("{} is a directory, ignoring.", fileStatus.getPath());
        continue;
      }

      **if (!FileOperations.getWorkingFiles().contains(fname) {
        //no logging necessary or maybe a debug
        continue;
      }**


      String[] sa = fname.split("\\.");
      String extension = "";
      if (sa.length > 1) {
        extension = sa[sa.length - 1];
      }

      if (!FileOperations.getValidExtensions().contains(extension)) {
        **log.warning("{}** does not have a valid extension, ignoring", fileStatus.getPath());
        continue;
      }

      fileList.add(fileStatus);
    }

    return fileList;
  }
```
Update FileOperations with 
```
private static final HashSet<String> workingFiles =
          new HashSet<>(Arrays.asList(Constants.BULK_LOAD_MAPPING, Constants.BULK_RENAME_FILE));
```

**Comment by hkeebler** [comment]
After running some of the Bulk load IT tests I saw that it also created a hidden version of files - prefixed with a "." and extension ".crc".  We could filter out hidden files or just extension .crc?  I could see that advantages to the former is in the future we could make any working files hidden files.

**Comment by hkeebler** [comment]
The previous comment is specific to the SharedMiniClusterBase.  I'm unable to find a current test that will exercise the code on a real instance.

**Comment by keith-turner** [comment]
> The previous comment is specific to the SharedMiniClusterBase.

I think that is the behavior of the Hadoop LocalFilesystem.   I suspect when you are listing files using the LocalFilesystem APIs you will never see these crc files.  May only see them when doing `ls`.  

The Hadoop distributed filesystem also computes crcs for blocks and stores them on the local filesystem.  When you poke around in a datanodes local dir you will see them.

**Comment by hkeebler** [comment]
Used the accumulo-testing cingest bulk to test this and did not receive any messages of "crc" files.  The approach I suggested will likely cover everything for now.

**Comment by ctubbsii** [comment]
A refactor might cause things to wait until 2.1, but I think it'd be good if we could clean up the user experience here for 2.0... bulk ingest is pretty important for Accumulo, and spamming the logs with unnecessary entries will be a big pain point for users.
