### ISSUE TITLE
Update TabletTime.maxMetadataTime(..) to use MetadataTime objects instead of string

### ISSUE THREAD

**Issue by hkeebler** [apache/accumulo#1281]
In TabletTime public static String maxMetadataTime(String mv1, String mv2) should  be updated to use MetadataTime objects instead of string.  This was identified in #1210.

**Comment by hkeebler** [comment]
This update is fairly small and straightforward.  
```java
public static MetadataTime maxMetadataTime(MetadataTime mv1, MetadataTime mv2) {
    // null value will sort lower
    if (mv1 == null || mv2 == null)
      return mv1 == null ? (mv2 == null ? null : mv2) : mv1;

    return mv1.compareTo(mv2) < 0 ? mv2 : mv1;
  }
```
The larger work is updating the calling methods to utilize the MetadataTime objects.  At this time the only class that uses this method is TabletGroupWatcher (other than tests).  To properly do it this class should be updated to use the ample metadata implementation.  I'm thinking of just doing it as part of this ticket rather than opening a new one.

**Comment by hkeebler** [comment]
Not using the ample metadata implementation results in updates to the TabletGroupWatcher like the following which isn't horrible but the time value should probably be parsed on initial read and retrieved from TabletMetadata.
```java
-          maxLogicalTime = TabletTime.maxMetadataTime(maxLogicalTime, value.toString());
+          maxLogicalTime =
+              TabletTime.maxMetadataTime(maxLogicalTime, MetadataTime.parse(value.toString()));
```

**Comment by keith-turner** [comment]
> This update is fairly small and straightforward.

For `maxMetadataTime(MetadataTime mv1, MetadataTime mv2)` would it make sense to throw an exception if the time types are not the same?  I am not sure how this method is used.  If the time types are expected to be the same (this would be the case it ifs only used to compare times from the same table) then `Long.max()` could be used after checking the time types.

**Comment by hkeebler** [comment]
the types are checked in the compareTo
```java
@Override
  public int compareTo(MetadataTime mtime) {
    if (this.type.equals(mtime.getType()))
      return this.time < mtime.getTime() ? -1 : this.time > mtime.getTime() ? 1 : 0;
    else
      throw new IllegalArgumentException(
          "Cannot compare different time types: " + this + " and " + mtime);
  }
```
The times do come from the same table.  I'm not sure I understand the Long.max() usage here.

**Comment by keith-turner** [comment]
I was thinking `Long.max()` could be used in `maxMetadataTime`, but I didn't realize that compareTo was already checking the type.  Could use `Long.compare(x,y)` in the `MetadataTime.compareTo()` method.

**Comment by hkeebler** [comment]
thanks :+1:

**Comment by hkeebler** [comment]
Changing my mind on including the TabletGroupWatcher ample updates in this ticket.  The class requires a "mulitple tablet" read which I do not think is implemented yet.  It has generated more questions for @keith-turner on the vision for ample. Created issue #1301 .
