### ISSUE TITLE
Clean up 1.9.3 BulkIngestExample

### ISSUE THREAD

**Issue by GreenCee** [apache/accumulo#1282]
Using the 1.9.3 tag ran into an error when running BulkIngestExample located
https://github.com/apache/accumulo/blob/rel/1.9.3/examples/simple/src/main/java/org/apache/accumulo/examples/simple/mapreduce/bulk/BulkIngestExample.java

It's failing with a classpath error.
java.lang.ClassNotFoundException: Class org.apache.accumulo.core.client.mapreduce.AccumuloFileOutputFormat not found​

I'm in the process of patching that test and verify the others as well. So far seems like minor tweaks contained in the examples directory is the blast radius

Other possible options: 
Since these were separated to separate repos in 2.x+, take the time to port a 1.9.x branch in those
Document the behavior and avoid touching 1.9.x tags

Any thoughts or strong opinions on the optimal way forward?

**Comment by hkeebler** [comment]
fyi - I recall, when running the examples having similar issues and the uno version would default to 2.0-alpha... It was necessary to explicitly point uno to my 2.0.0-SNAPSHOT build.

**Comment by milleruntime** [comment]
What verison of Hadoop are you running?

What example are you following?  The examples in 1.9 are all baked into the Accumulo release.  The example you are looking at follows this example here: https://github.com/apache/accumulo/blob/rel/1.9.3/docs/src/main/resources/examples/README.bulkIngest

**Comment by drewfarris** [comment]
I'm definitely interested in how hard it would be to backport the procedure described in [bulk-test.md](https://github.com/apache/accumulo-testing/blob/master/docs/bulk-test.md)  from [accumulo-testing/master](https://github.com/apache/accumulo-testing/tree/master) to [accumulo-testing/1.9](https://github.com/apache/accumulo-testing/tree/1.9) that might be a better/more comprehensive test.

**Comment by milleruntime** [comment]
> I'm definitely interested in how hard it would be to backport the procedure described in [bulk-test.md](https://github.com/apache/accumulo-testing/blob/master/docs/bulk-test.md) from [accumulo-testing/master](https://github.com/apache/accumulo-testing/tree/master) to [accumulo-testing/1.9](https://github.com/apache/accumulo-testing/tree/1.9) that might be a better/more comprehensive test.

That might not be too bad.  The bulk ingest command works with both versions:

```importdirectory /tmp/bt/$i/files true```
- is actually using the new bulk import technique.

```importdirectory /tmp/bt/$i/files /tmp/failure_directory true```
- would use the legacy bulk import.

**Comment by milleruntime** [comment]
> It's failing with a classpath error.
java.lang.ClassNotFoundException: Class org.apache.accumulo.core.client.mapreduce.AccumuloFileOutputFormat not found​

I was asking about what version of Hadoop because I know there were some classpath changes between the versions. We changed the way the classpath was setup in the scripts between 1.9 and 2.0

**Comment by GreenCee** [comment]
> It's failing with a classpath error.
> java.lang.ClassNotFoundException: Class org.apache.accumulo.core.client.mapreduce.AccumuloFileOutputFormat not found​
> 
> I was asking about what version of Hadoop because I know there were some classpath changes between the versions. We changed the way the classpath was setup in the scripts between 1.9 and 2.0

hadoop_version = 2.8.4
zookeeper_version = 3.4.14
accumulo_version = 1.9.3


I did a sanity check on the instructions you pointed out on a fresh cluster

History:
PKG=org.apache.accumulo.examples.simple.mapreduce.bulk
ARGS="-i muchos -z <> -u <> -p <>"
cd install/accumulo-1.9.3/
./bin/accumulo $PKG.SetupTable $ARGS -t test_bulk row_00000333 row_00000666
./bin/accumulo $PKG.GenerateTestData --start-row 0 --count 1000 --output bulk/test_1.txt
./bin/tool.sh lib/accumulo-examples-simple.jar $PKG.BulkIngestExample $ARGS -t test_bulk --inputDir bulk --workDir tmp/bulkWork
SUCCESS

History:
accumulo org.apache.accumulo.examples.simple.mapreduce.bulk.GenerateTestData --start-row 0 --count 1000 --output gen/test.txt
accumulo org.apache.accumulo.examples.simple.mapreduce.bulk.BulkIngestExample -i muchos -u root -p <> -t test_bulk --inputDir gen --workDir tmp/bulk
FAILURE


The latter was the one failing. So using the proper JAR results in success.

Closing the issue, user error
