### ISSUE TITLE
Add bulk import option to ignore empty dirs

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1293]
For the use case where a user process dies in the middle of a bulk import and then the user bulk imports again the source dir may be empty because the first import actually succeeded.  In this case an exception may be thrown because of #1292.

In the comments of #1286 it was decided that adding API and shell options to ignore empty dirs would support users who want to write idempotent bulk import code.

**Comment by EdColeman** [comment]
I'll try to add this along with the -t tablename option.

**Comment by EdColeman** [comment]
I incorrectly interrupted the scope of this and it is not appropriate to add to the current import directory command changes targeting 1.9.x - removed myself for now in case there is other interest before I have time to revisit.

**Comment by jmark99** [comment]
Fixed by #2039
