### ISSUE TITLE
Explore creating unique directories for sorted WAL recovery

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1303]
When a tablet server dies, its write ahead logs need to be sorted.  A random tablet server is chosen to sort the write ahead logs.  If the random tablet server doing the sort dies or times out, the sort may be started on another write ahead log.  This may lead to multiple tablet servers sorting the write ahead logs, possibly to the same directory.  Would probably be better if each tserver doing a sort wrote to a unique dir.

**Comment by tynyttie** [comment]
@ctubbsii I would like to take a look at this.

**Comment by milleruntime** [comment]
I think the unique directory would have to be added to the destination path here: 
https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/server/base/src/main/java/org/apache/accumulo/server/master/recovery/RecoveryPath.java#L45

It looks like that method `getRecoveryPath(Path walPath)` takes the WAL path and returns the recovery path for sorting.  So given something like:
`source = hdfs:/accumulo/wal/ip-10-113-12-25+9997/bd9a7597-b51f-415a-9648-0363913749d0` 
it will return `dest = hdfs:/accumulo/recovery/bd9a7597-b51f-415a-9648-0363913749d0`

**Comment by ctubbsii** [comment]
Closing based on conclusion in https://github.com/apache/accumulo/pull/1803#issuecomment-771883813
