### ISSUE TITLE
Remove accumulo-test jar containing ITs from binary tarball assembly

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1305]
I noticed while testing 2.0.0-rc2 that we still have the binary tarball assembly ship the accumulo-test jar. Since most of the useful downstream testing utilities are now in https://github.com/apache/accumulo-testing, this jar just contains our ITs... which isn't useful to ship in the tarball.

We should trim the fat and strip this out of any further releases after 2.0.0.

**Comment by Manno15** [comment]
Is this as simple as removing the dependency in the assemble pom file or does there need to be more trimming?

**Comment by ctubbsii** [comment]
> Is this as simple as removing the dependency in the assemble pom file or does there need to be more trimming?

I think so, but I would do a build to check for warnings from the assembly plugin to be sure, and verify the output tarball. There may need to be changes to the assembly descriptor xml file, too... but maybe not.

The main reason for posting this here, was to solicit feedback. May want to start a discussion on the dev list before taking action, to be sure nobody objects.

**Comment by Manno15** [comment]
Everything still seems to work as expected after doing a quick build and test. No warnings given.

**Comment by dlmarion** [comment]
@Manno15  - It seems like you may have done some work on this. Can this issue be closed?

**Comment by Manno15** [comment]
@dlmarion Yes. It apparently was removed from the pom in #1517.
