### ISSUE TITLE
Use -source-release.tar.gz instead of -src.tar.gz

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1306]
We do some crazy things in our maven build to relocate our source tarball from the root of the project into a child module with a different classifier. This isn't necessary if we're not strongly tied to the current file naming convention and the build can be simplified.

If we stop doing this, the binary tarball and source tarball will be located at slightly more divergent maven coordinates, and the filenames (to keep consistent with maven file naming conventions) will reflect this.

Instead of:

```
accumulo-2.0.0-bin.tar.gz # with top level directory /accumulo-2.0.0
accumulo-2.0.0-src.tar.gz # with top level directory /accumulo-2.0.0
```

They would instead be something like:
```
accumulo-2.0.0-bin.tar.gz # with top level directory /accumulo-2.0.0
accumulo-project-2.0.0-source-release.tar.gz # with top level directory /accumulo-project-2.0.0
```

The latter is the naming convention established ASF-wide with the Apache parent POM default build. It doesn't really matter that they have the same name.

See 
https://github.com/apache/accumulo/blob/0b34e30c34b7c31ebb84ca6b3b686c1b3e7b19af/pom.xml#L1468-L1487
and
https://github.com/apache/accumulo/blob/0b34e30c34b7c31ebb84ca6b3b686c1b3e7b19af/assemble/pom.xml#L501-L529
for where all this craziness is being enshrined in our build.

We can just delete these sections of the POM and discard our strict adherence to these particular directory and file naming conventions... since they don't really matter... to simplify our build process.

A simpler build makes it easier to maintain the build process, so that it's not dependent on the expertise of a single (or a small few) individual(s) if something breaks.

I noticed this when reviewing the 2.0.0-rc2, and I think we missed our opportunity, but we can make this change in 2.1 or 3.0. Only the source assembly would be affected (which isn't as critical, because it doesn't affect most users, only developers... who probably more often just check out the git tag anyway if they want the source).

**Comment by jmark99** [comment]
After discussion, concluded ticket no longer needs to be addressed.

**Comment by ctubbsii** [comment]
See #3125
