### ISSUE TITLE
Provide single-line output of tablet info.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1317]
Copied from ACCUMULO-2873 - It would be very useful to have a utility that generates single line tablet info.  The output of this could be fed to sort, awk, grep, etc in order to answer questions like which tablets have the most files.The output could look something like the following
 
```
$accumulo admin listTablets --table bigTable3
 #files #walogs #entries #size #status #location #tableid #endrow
 6 2 40,001 50M ASSIGNED 10.1.9.9 4:9997[abc]  3 admin
 3 1 50,002 40M ASSIGNED 10.1.9.9 5:9997[abc]  3 helpful
```

All of the information can be obtained by scanning the metadata table and looking into zookeeper. Could possibly contact tablet servers to get info about entires in memory.

**Comment by EdColeman** [comment]
I've take a first run at this - current available at: https://github.com/EdColeman/accumulo/tree/listTabletsCmd exploring what may be possible at to start a discussion.

**Comment by EdColeman** [comment]
This still needs addition work.
- What is the proper way to determine status?  One way would be to check if the tablet has a loc: assigned.  Is there something else that is more appropriate?
- The original ticket mentioned that some information could be pulled from zookeeper - with the
current implementation, all information is coming from the metadata table. What information is missing / would be helpful?
- Formatting of size and number of entries to allow human readable option.

**Comment by keith-turner** [comment]
> What is the proper way to determine status?

Could use [TabletLocationState.getState()][2].  One way to get TabletLocationState objects is via [TabletStateStore][1].  The set of live tservers can be obtained using [LiveTServerSet][3].

> The original ticket mentioned that some information could be pulled from zookeeper - with the current implementation, all information is coming from the metadata table. What information is missing / would be helpful?

[LiveTServerSet][3] pulls the set of active tablet servers from zookeeper.

[1]: https://github.com/apache/accumulo/blob/f39c2fef1c1c911e86985ce6352c5d1bc9967c5b/server/base/src/main/java/org/apache/accumulo/server/master/state/TabletStateStore.java

[2]: https://github.com/apache/accumulo/blob/f39c2fef1c1c911e86985ce6352c5d1bc9967c5b/server/base/src/main/java/org/apache/accumulo/server/master/state/TabletLocationState.java#L104

[3]: https://github.com/apache/accumulo/blob/f39c2fef1c1c911e86985ce6352c5d1bc9967c5b/server/base/src/main/java/org/apache/accumulo/server/master/LiveTServerSet.java

**Comment by milleruntime** [comment]
@keith-turner @ctubbsii I have been working on this as it seems like a very useful tool.  One of the issues I am running into is that the only way to get the current state of tablets is to use objects in the master and this introduces a dependency in the shell on accumulo-server-base.  There are other parts of the code that depend on accumulo-server-base, like the GC [here](https://github.com/apache/accumulo/blob/72e8bc41335ae542087cc70d80d2b7b7e8652575/server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectWriteAheadLogs.java#L95).  The information is coming from ZK and metadata so I was wondering if having something in Ample would be appropriate.  I am not sure what is the best solution.

**Comment by ctubbsii** [comment]
Ampl might be okay for this. It might also be okay to have a public API for the shell to use.

**Comment by keith-turner** [comment]
@milleruntime I suspect the code could be moved to accumulo core OR reimplemented in core (and existing code migrated to Ample). One possible way to add it to ample would be to modify TabletMetadata class to add a method like the following.

```java
TabletState getTabletState(Set<Location> liveTservers) {
   //use tablet metadata + liveTservers to determine the state of this tablet.
  // Location is an inner class TabletMetadata
}
```

Then maybe Ample could have a getLiveTservers() method.

**Comment by keith-turner** [comment]
For my previous comment, the Location type will not really work for this case.  Need a type that just encapsulates `(server,session)` for the set of live tservers. TabletMetadata.Location has those plus LocationType, which makes no sense for a live tserver.

**Comment by milleruntime** [comment]
> For my previous comment, the Location type will not really work for this case. Need a type that just encapsulates `(server,session)` for the set of live tservers. TabletMetadata.Location has those plus LocationType, which makes no sense for a live tserver.

What do you think about a new type in core.metadata (similar to what I did for TabletFile) that could be used everywhere?  And would we want to keep the ZK session Id?  @EdColeman and I were talking about the usefulness of storing the internal session ID.  It seems like its used as a unique identifier of the ephemeral ZooLock for that tserver.  This is a separate issue but I don't think we would want to have the session in this new type.

**Comment by milleruntime** [comment]
And I suppose it would need to replace this type here:
https://github.com/apache/accumulo/blob/d1b06d317983d460039861d4ab462d5a65ca3c11/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java#L191

**Comment by keith-turner** [comment]
>. What do you think about a new type in core.metadata (similar to what I did for TabletFile) that could be used everywhere? And would we want to keep the ZK session Id?

I like that. That Location type in TabletMetadata could possibly extend it.

**Comment by milleruntime** [comment]
> > . What do you think about a new type in core.metadata (similar to what I did for TabletFile) that could be used everywhere? And would we want to keep the ZK session Id?
> 
> I like that. That Location type in TabletMetadata could possibly extend it. Not sure about ZK session id would have to look at it. Using the same type to represent the same info throughout the code seems like a big win. Seems like it can follow the pattern of add it and then later adapt code to use it.

Instead of a new type, since the class is much simpler from TabletFile, I am playing around with just moving TServerInstance from master to core and using it.  https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/master/state/TServerInstance.java
