### ISSUE TITLE
Is checking disk status in FileSystemMonitor necessary?

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1325]
At this point, hoping for a discussion to determine requirements / scenarios that may warrant changes.  Scenario: When running on servers with multiple disks, the FileSystemMonitor will kill a tserver if a disk fails (goes read-only)  
- Is this necessary behavior - or could it be handled by terminating on appropriate IO Exceptions? 
- What are the Accumulo critical file / volume paths? Did this change when WALs moved to hdfs?
- How critical is "logging" and should a failure of slf4j/log4j to write a log cause a termination of a process (or could log frame be configure with multiple volumes for fail-over?)
- HDFS (data nodes) now supports allowing x volume (disk) failures before killing that data node - should we allow the same?
- Does containerization changes influence any other this?

**Comment by ctubbsii** [comment]
I don't think we need this behavior in Accumulo. Something like that would be more appropriate for an external cluster health monitoring service. If HDFS is happy with a failed disk, then we shouldn't care either. Perhaps we might still care if it was the OS disk(s) that went read-only... but I'm not sure we can reliably detect that from any other disk. I think it would make sense to drop this behavior.

**Comment by ctubbsii** [comment]
Since this feature is configurable, we have some options:

1. Change the default to false
2. Delete it entirely (#1328)
3. Deprecate it first, with a warning if used
4. Change its behavior to log an error instead of killing the tserver

Or some combination of these.

**Comment by belugabehr** [comment]
In branch 1.X, set to false by default is probably the safest bet
In branch 2.X remove

**Comment by ctubbsii** [comment]
That seems a bit aggressive to me. A significantly less surprising change might be to default to false in 2.1 and log a deprecation warning if set by the user, eventually dropping the feature in 3.0.

**Comment by belugabehr** [comment]
Ah, OK.  I didn't realize that 2.0 dropped a couple of weeks ago.  Congrats.

Yes. I agree with you on default off in 2.X and removed in 3.x

**Comment by belugabehr** [comment]
I've got two PRs at the ready:

#1328 - Remove FileSystemMonitor in master branch
#1332 - Disable FileSystemMonitor in 2.0

**Comment by ctubbsii** [comment]
The master branch is for 2.1 development right now. I don't think anyone's anticipating an 3.0 any time soon, so we could just leave #1328 open and unmerged until we're ready for 3.0 development, if we want to wait until then to remove the feature.
