### ISSUE TITLE
Add test to GarbageCollectorIT for continue point or remove continue point

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1351]
Accumulo garbage collection will read a batch of deletes into memory and process them.  When reading the next batch it uses the last path it saw as a continue point.  Need to ensure the continue point code covers all data.

Alternatively, instead of testing the continue point code it could be removed by refactoring the GC code as follows so that continue is not needed.  The code below keeps the iterator for the entire cycle instead of calling continue.

```java
Iterator<String> candidates = getContext().getAmple().getGcCandidates(level);

while(candidates.hasNext()){
     List<String> candidatesBatch =  readCandidatesThatFitInMemory(candidates);
    
    collectBatch(candidatesBatch);
}
```

**Comment by keith-turner** [comment]
https://github.com/apache/accumulo/pull/1344#discussion_r321812590

**Comment by cradal** [comment]
Looking at this issue now.
