### ISSUE TITLE
Anaylyze how MasterTime uses System.nanoTime

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1355]
The master time class persist the output of System.nanoTime to zookeeper.  System.nanoTime should only be used to compute elapsed times in a single process.  The following is from its javadoc.

```
     * This method can only be used to measure elapsed time and is
     * not related to any other notion of system or wall-clock time.
     * The value returned represents nanoseconds since some fixed but
     * arbitrary <i>origin</i> time (perhaps in the future, so values
     * may be negative).  The same origin is used by all invocations of
     * this method in an instance of a Java virtual machine; other
     * virtual machine instances are likely to use a different origin.
```

I noticed this while looking at #1354.  Maybe the use of System.nanoTime is appropriate, I am not sure.  Opening this issue to remember to analyze its use.

**Comment by milleruntime** [comment]
This was analyzed in #1442
