### ISSUE TITLE
RowLock reference counts may be incorrect

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1364]
The [ConcurrentMap.compute](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#compute-K-java.util.function.BiFunction-) function javadoc contains the following sentence

```
The default implementation may retry these steps when multiple threads attempt updates including potentially calling the remapping function multiple times.
```

If this is true for [ConcurrentHashMap.compute](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#compute-K-java.util.function.BiFunction-) then the changes in #1357 may lead to incorrect reference counts in the case where the mapping functions is executed multiple times.  The javadoc for ConcurrentHashMap does not say anything about executing the function multiple times and says its atomic, leading me to believe it may not.  However, I am not 100% about the behavior.

**Comment by keith-turner** [comment]
I found the following wording in [ConcurrentHashMap.computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-)

```
The entire method invocation is performed atomically, so the function is applied at most once per key.
```

None of the other functions have that wording.

**Comment by keith-turner** [comment]
I reached out to a JDK list (it was the wrong list, but some kind people helped me get to the right place).

https://mail.openjdk.java.net/pipermail/discuss/2019-September/005151.html

So far I am getting two different opinions about the at most once execution behavior.

**Comment by keith-turner** [comment]
A JDK issue was opened.

https://bugs.openjdk.java.net/browse/JDK-8231592

**Comment by ctubbsii** [comment]
Not a problem. Explained by comment added in #1380
