### ISSUE TITLE
InputConfigurator.validatePermissions checks for Table.READ but not Namespace.READ

### ISSUE THREAD

**Issue by reggert** [apache/accumulo#1370]
When reading a table via the Accumulo Shell or via `Scanner`/`BatchScanner`, it is sufficient for the user to have **either** `Table.READ` **or** `Namespace.READ` permission for the table or its namespace. However, when reading a table via `AccumuloInputFormat` (in Hadoop or Spark), prior to launching the job, `InputConfiguration.validatePermissions` checks only whether the user has `Table.READ` permission, ignoring any `Namespace.READ` permission that the user may have. This means that even if a user can read a table via a non-Hadoop client, reading the same table in Hadoop/Spark fails with the error "Unable to access table".

**Comment by ctubbsii** [comment]
This looks to be the result of some overly-aggressive fast-failure checks. We could remove the check entirely and let the tasks fail if the user doesn't have permission, or we can patch the check to allow `Namespace.READ` also. I'm inclined to do the latter, since the fast-failure is probably still useful.

**Comment by ctubbsii** [comment]
@reggert Are you interested in working on this?

**Comment by reggert** [comment]
Sure, I could take a stab at it. It seems like it should be a pretty straightforward fix.

Is there an existing function somewhere to extract the namespace from a table name? It wouldn't be hard to write one, but there's no point reinventing the wheel if it already exists.

**Comment by reggert** [comment]
Submitted pull request targeting the `1.9` branch.

**Comment by ctubbsii** [comment]
> Is there an existing function somewhere to extract the namespace from a table name?

Probably somewhere deep in the code, used internally. Nothing that is likely intended for reuse.
