### ISSUE TITLE
Could the preferred volume chooser support the init scope?

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1373]
While [experimenting with S3](https://accumulo.apache.org/blog/2019/09/10/accumulo-S3-notes.html) I tried to use the INIT scope with the Preferred volume choose and it did not work because of [PreferredVolumeChooser.java line 60](https://github.com/apache/accumulo/blob/f5314b7e2a49cd315a16a72fe93c6828f4c7ba98/server/base/src/main/java/org/apache/accumulo/server/fs/PreferredVolumeChooser.java#L60).   If I had been able to use the init scope, then that would have made the S3 instructions much simpler.  Would it be possible to make the init scope work with site configuration?

**Comment by karthick-rn** [comment]
I'm interested to work on this.
