### ISSUE TITLE
Make scan execution hints influence caching.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1383]
There are two use cases I was recently thinking through were I thought it would be nice to not cache data.  One was when the Accumulo garbage collector scans the metadata table for deletion and blip markers.  Another is when Fluo scan for notifications.  In both cases the data is only scanned sequentially and never accessed randomly. 

There are a few possible ways this could accomplished using execution hints.  

  1. The execution hints could be passed to the cache directly 
  2. Scan dispatchers could disable cache for a scan based on execution hints.
  3. A new per table plugin could be created that makes caching decisions based on execution hints.

Options 1 would probably lead to the cache (which is currently a tablet server level entitiy) needing per table config.  Options 2 and 3 do not have this problem.

For notifications scans, Fluo is already [setting a hint](https://fluo.apache.org/blog/2019/09/30/scan-executors/) of `scan_type=fluo-ntfy`.  So if cache could be configured to be diabled this scan_type, thne Fluo could benefit.

**Comment by ctubbsii** [comment]
The option I like the best is 2. There's a typo in the DispatchParameters object anyway, so we can fix that typo and evolve the API to return an object that is more than just the ScanExecutor's name... it can contain additional ScanExecutor execution environment with decisions from the dispatcher. This additional environment can be passed down into the cache code, which can skip the cache if certain flags are set.

**Comment by keith-turner** [comment]
There was a discusion about this issue at the hack day.  One thing that came out of that is that would be good to also consider the use case of scan hints influencing file system read flags, with any refactoring.

**Comment by keith-turner** [comment]
https://issues.apache.org/jira/browse/HADOOP-16317

**Comment by GreenCee** [comment]
Digging in, it doesn't appear that Hadoop has reached a stable enough point to have a common API applications can use to inform the IO patterns across s3a, abfs, etc.
Talking through this at Hack Day also doesn't seem like this would be the right integration point for that anyhow

**Comment by ctubbsii** [comment]
While there may not be an integration point available in Hadoop for informing IO patterns at this time, the fact that we know there are potentially other use cases for these hints at various layers can help inform API decisions around these hints, in order to design in a future-resilient way.

**Comment by GreenCee** [comment]
That's very true. Stepping back this would be the path should there be a nice high level all-DFS option in the future. For any application (Accumulo) to share it's intention to the underlying store as described in the HADOOP-16317 that would be signaled by the scan. 
In some cases Accumulo may have special knowledge of the data and use like metadata table, but that won't be hard and fast and anything adaptive we'd build out of knowledge gained from explicit hints.

On the original issue, option 2 is the one I like the best as the scan seems to be the right integration to hint the intention. 

3 use cases I see that would be enabled. 

1 and 2 seems similar enough
3 warrants a follow-on issue to this one so we don't chunk out too much work in this issue?

1. Internal processes like garbage collector as mentioned by Keith

2. Maintenance scan-type activities
Every installation I've worked on seems to always have those low-priority, low-throughput scans doing something. It'd be nice to deprioritize via scan executor and keep the cache clean

3. Long running ML-type scan workloads that don't have performance SLAs 
Known to be latency tolerant, but will generate a lot of sequential scans that don't benefit the cache. Additionally there is existing query load that needs to be preserved.

**Comment by kubina** [comment]
I think adding a table level option to flag if the results of a scan should be cached or not would be a great way to help the cache from being polluted by queries that are scanning and returning a lot of single use data. It would be very useful for those tables that are scanned to satisfy user generated queries and scanned by applications to return a large collection of records that will be saved off for a data science research and development project. The latter query will often return a lot of records, take a long time to execute, and be executed vary rarely; so having a flag to indicate the such scan results should not be cached would ensure the cache maintains the results from the user generated queries.

**Comment by ctubbsii** [comment]
I think we've taken steps in recent years to put more scan-time configuration in the scan API, rather than put them in table configs. This puts more responsibility on users, but is easier for us to maintain while satisfying user expectations (because expectations are explicit in each scan, from a table config which may not be consistent across a cluster and could be in flux). Certainly, at this point, I'd prefer people use scan-time iterators rather than table-configured iterators, and I think I feel the same way for other configs, such as execution hints. That said, I think it might make sense to have something like `table.scan.defaults.execution-hints`, and other `table.scan.defaults.*` properties for scans which don't set these options explicitly.

**Comment by dlmarion** [comment]
@keith-turner  - it looks like your PR #1440 resolved this. Can this be closed or is there more work?

**Comment by keith-turner** [comment]
@dlmarion this can be closed.
