### ISSUE TITLE
Hold time is reported differently in Tables and TServers UI

### ISSUE THREAD

**Issue by arvindshmicrosoft** [apache/accumulo#1395]
Background: on a test cluster we had a user error wherein an ageoff filter was misconfigured (and Shell did not validate user input) and prevented MinCs, thereby driving up hold time. Separate issue, I will log a distinct issue on what we saw there.

Current issue: I see the hold time is reported in a not-human-friendly manner in the Tables UI:
![MNotationTables](https://user-images.githubusercontent.com/16342666/67606479-66699180-f736-11e9-937f-0768df708471.PNG)

Whilst the TServers UI shows a human-readable version.
![ReadableHoldTime](https://user-images.githubusercontent.com/16342666/67606524-7d0fe880-f736-11e9-9a12-da5d6717d8c9.PNG)

**Comment by milleruntime** [comment]
Thanks @arvindshmicrosoft this should be an easy fix for the new 2.0 monitor.

**Comment by milleruntime** [comment]
@arvindshmicrosoft are you seeing the ugly time on any other pages?  How about the Master Server page?

**Comment by arvindshmicrosoft** [comment]
Thanks @milleruntime I appreciate your prompt help on this! Will keep you posted if we see any other occurrences.

**Comment by milleruntime** [comment]
> Thanks @milleruntime I appreciate your prompt help on this! Will keep you posted if we see any other occurrences.

No problem.  FYI I just pushed the second part of the fix in 1fe2705.  With both commits, the issue should be fixed now.
