### ISSUE TITLE
Transition from instance.dfs.{uri,dir} to instance.volumes on upgrade

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1397]
In 1.7.0, `instance.dfs.uri` and `instance.dfs.dir` were deprecated in favor of `instance.volumes`. These worked by resolving relative paths in the metadata, with a number of fallback mechanisms (including falling back to HDFS config files to resolve the `defaultFS` for the URI).

These should be replaced with an explicit resolution, similar to `instance.volumes.replacements`, but using a property specific to this upgrade process (`instance.upgrade.volume.relative.prefix`?)

All occurrences of relative paths in the metadata should be converted to absolute paths during upgrade.

In summary:

* Explicit property for resolving relative paths
* Mandatory upgrade of metadata to remove all relative paths
* Remove old properties (this requires MiniAccumuloCluster use `instance.volumes`)

This issue supersedes: [ACCUMULO-3535], [ACCUMULO-3023], [ACCUMULO-3537], and [ACCUMULO-3573] from JIRA.

[ACCUMULO-3535]: https://issues.apache.org/jira/browse/ACCUMULO-3535
[ACCUMULO-3023]: https://issues.apache.org/jira/browse/ACCUMULO-3023
[ACCUMULO-3537]: https://issues.apache.org/jira/browse/ACCUMULO-3537
[ACCUMULO-3573]: https://issues.apache.org/jira/browse/ACCUMULO-3573

**Comment by milleruntime** [comment]
In addition to above, we should only require the new property if relative paths exist and check the existence of all files before renaming relative paths.  We need to make sure the value in the new property is absolutely correct before renaming metadata paths.

Also need to check delete markers for relative paths.

**Comment by milleruntime** [comment]
Unassigned myself as I am currently not working on this.  The replacement of relative paths on upgrade and removal of relative path code is done.  Removal of the old properties still needs to be done.
