### ISSUE TITLE
trace server advertising default bind address (0.0.0.0) in zookeeper

### ISSUE THREAD

**Issue by etseidl** [apache/accumulo#1398]
While trying to get traces from my tservers, I noticed that the trace server was advertising its address as 0.0.0.0 in zookeeper.  This appears to be due to obtaining the address to advertise from the server socket address (tracer.TraceServer around line [225](https://github.com/apache/accumulo/blob/9c7e91c5129a595f6b0896c9a99aebfc7e51fea4/server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java#L225)), rather than looking up the address up via the InetAddress local host (as appears to be done in [server.rpc.TserverUtils](https://github.com/apache/accumulo/blob/9c7e91c5129a595f6b0896c9a99aebfc7e51fea4/server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java#L651)).   Similarly, when ZooTraceClients are [instantiated](https://github.com/apache/accumulo/blob/9c7e91c5129a595f6b0896c9a99aebfc7e51fea4/server/tracer/src/main/java/org/apache/accumulo/tracer/AsyncSpanReceiver.java#L96), they appear to use the 0.0.0.0 address that is the default for a server address (this appears to be the same issue as discussed in #1090).  Testing for 0.0.0.0 and replacing with InetAddress.getLocalHost().getHostAddress() clears up the problem for me.

**Comment by ctubbsii** [comment]
@etseidl Thanks. I see you created this, and then immediately created a PR within minutes. For future reference, it is not necessary to create a separate issue since, on GitHub, PRs are also issues and have their own trackable issue number. Sometimes it is useful to have a separate issue to track a problem before a fix is complete, but you can often skip that if it's not necessary, since we don't require it.

**Comment by etseidl** [comment]
@ctubbsii sorry, I wasn't sure if this one would turn into a bigger fix.  Thanks for the info.

**Comment by ctubbsii** [comment]
> @ctubbsii sorry, I wasn't sure if this one would turn into a bigger fix. Thanks for the info.

No worries. That is one of many perfectly legitimate reasons to create an issue first. :smiley_cat: . I just wanted to make sure you (and others) don't do it because you think you *have to* (as some holdover from JIRA days, for example).
