### ISSUE TITLE
Update Apilyzer to treat core.iterators as SPI

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1415]
Refactoring done for #1390 requires the Apilyzer plugin to run on core.iterators, ensuring there is no internal types in the API.

**Comment by ctubbsii** [comment]
This should be a simple single line addition to the apilyzer-maven-plugin configuration in `core/pom.xml`

**Comment by milleruntime** [comment]
I modified the core/pom.xml as so:
```
-                <include>org[.]apache[.]accumulo[.]core[.]iterators[.]IteratorUtil[$]IteratorScope</include>
+                <include>org[.]apache[.]accumulo[.]core[.]iterators[.].*</include>
```
And saw the following failures:
```
  METHOD_RETURN        org.apache.accumulo.core.iterators.IteratorEnvironment       getServiceEnv(...)                  org.apache.accumulo.core.spi.common.ServiceEnvironment
  FIELD                org.apache.accumulo.core.iterators.user.VisibilityFilter     cache                               org.apache.commons.collections4.map.LRUMap
  FIELD                org.apache.accumulo.core.iterators.user.TransformingIterator log                                 org.slf4j.Logger
```
I added the first method to IteratorEnvironment as a replacement for AccumuloConfiguration.  It seems that SPI has now entered into the quasi-API limbo, where iterators have lived for some time.  Perhaps SPI should be declared as public API along with iterators.  Even if SPI doesn't affect data like iterators do, it has a nice way to access server configuration.

It seems like the LRUMap was made protected so users could override it with a different implementation. Whatever the case, I think this type could be a java.util.Map.

The logger should probably just be private.

**Comment by ctubbsii** [comment]
Could add an "allows" line for the service environment instead of promoting it to public API. It might be okay to have it leak into the public API, as long as it's documented carefully, and just treat it as an excepted case.

**Comment by milleruntime** [comment]
After some discussion with @keith-turner and @ctubbsii, I think we should treat iterators as SPI.  They are pluggable server mechanisms, that can be affected by internal server changes, similar to the other plugins in the SPI.   I think, along with the other SPI packages, we should only guarantee compatibility across bug fix versions.

**Comment by keith-turner** [comment]
>  Perhaps SPI should be declared as public API along with iterators.

Pluggable interfaces in SPI related to scan execution and caching are tightly coupled to Accumulo's internal model for executing scans.  If these interfaces are in the API it could make it very difficult to change the internal execution model for scans.  The reason is because it may require going through a deprecation cycle where a single release supports an old and new model of executing scans, which may not be practical.  Also the interfaces related to scan execution and caching only impact scan performance, never scan data returned.

**Comment by keith-turner** [comment]
> They are pluggable server mechanisms, that can be affected by internal server changes, similar to the other plugins in the SPI.

I thought it made sense to place iterators in the public API because they can change the data returned by scans and are tightly coupled to a users data and queries.  I can take a stab at this.

**Comment by keith-turner** [comment]
I took created a draft PR #1426 where I attempted to pull iterators in to the API from Apilyzer perspective.  I also attempted to document/define SPI in that PR.

**Comment by milleruntime** [comment]
Related to #1390

**Comment by milleruntime** [comment]
Done in #1426
