### ISSUE TITLE
Remove DefaultMap and use computeIfAbsent instead.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1418]
I think [DefaultMap](https://github.com/apache/accumulo/blob/bbee47b8b95d230ba9def235917013dcfeaf7c38/server/base/src/main/java/org/apache/accumulo/server/util/DefaultMap.java) could be removed from the code.  There are currently two places in the code that create a DefaultMap.  I think these could instead create a HashMap and when `get()` is called on that hasmap use `computeIfAbsent()` creating whatever DefaultMap would have created.

Its only used in two places.  For the usage in `Master.getMasterMonitorInfo()` I think only the `get()` in that method needs to be replaced, nowhere else.  For the usage at `Master.badServers` I think only usage in `Master.gatherTableInformation()` needs to be updated.

**Comment by at1012** [comment]
Started taking a look at this during Accumulo hack day. Will work on this.
