### ISSUE TITLE
Use StandardCharsets.UTF_8

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1419]
There are a few places in the code where the UTF-8 charset can be replaced with the static equivalent from java.nio.charset.StandardCharsets.  The following classes should have
 ```Charset.forName("UTF-8")``` replaced with ```StandardCharsets.UTF_8```:

- org.apache.accumulo.core.cryptoImpl.AESCryptoService
- org.apache.accumulo.core.cryptoImpl.NoFileEncrypter
- org.apache.accumulo.core.data.KeyBuilder
- org.apache.accumulo.server.util.ConvertConfig
- org.apache.accumulo.test.ShellServerIT
- org.apache.accumulo.tserver.MemValueTest

**Comment by mandarinamdar** [comment]
I will work on this
