### ISSUE TITLE
HTTP 500 error when viewing the REST/XML status on the monitor

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1429]
When attempting to view the monitor's REST/XML output, I get a HTTP 500 server side error.

In the monitor logs, I see that there is a `ClassNotFoundException` for `com.sun.istack.Pool` coming from jersey.

It appears that we are missing some jars at runtime on the class path. I discovered that the class is contained in jaxb-core:

```xml
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-core</artifactId>
  <version>2.3.0.1</version>
</dependency>
```

This does not appear to be listed in the output of `mvn dependency:tree`, but it may be an optional runtime dependency of the version of jersey we are using. Fixing this may be a simple matter of adding the jaxb-core as a runtime dependency of the monitor, and including it in the tarball assembly, but I have not tested it.

FWIW, I know this worked at some point in the past, so I'm not sure what changed.

**Comment by ctubbsii** [comment]
This issue is marked a "good first issue" because it doesn't really involve any code, just class path and build tooling. However, it will likely require some familiarity with Maven, the maven-assembly-plugin, and class paths in general. It will also be best if the contributor who works on this already knows how to run Accumulo, say in [Uno](https://github.com/apache/fluo-uno).

**Comment by mandarinamdar** [comment]
I was about to report this. I will take this

**Comment by ctubbsii** [comment]
@mandarinamdar Cool. Don't hesitate to ask for help if you have any issues.

**Comment by mandarinamdar** [comment]
Have tested with Uno deployment. Output from http://127.0.0.1:57965/rest/xml as below..(snip)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><stats><servers><server id="man-dev:9997"><hostname>man-dev:9997</hostname><lastContact>6211</lastContact><responseTime>0</responseTime><osload>0.37</osload><version>2.1.0-SNAPSHOT</version><compactions.........</stats>
