### ISSUE TITLE
Limit the size of new table names

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1430]
Giant table names can take down ZooKeeper and the master server. There should be a reasonable limit on table name sizes. This can be imposed on the server side for creating tables, renaming tables, and cloning tables. Existing tables need not be affected.

Client code can be updated for fast-failure (and to limit the number of invalid requests sent to the server-side).

For reference, the information I found while searching the web (not necessarily accurate, but good enough to give us an idea) gives the following limits to identifier sizes:

| Item | Number of characters (or sometimes, bytes) |
| ---- | ---- |
| Oracle DB table names | 30 |
| MySQL table names | 64 |
| PostgreSQL table names | 63 |
| DNS identifier | 63 |
| Most filesystem file names (EXT/XFS/ZFS/exFAT/HFS+/Brtfs/NTFS | 255 |
| EXT4 max path | 4096 |
| Java identifiers | unlimited |
| longest English word | 45 |
| "supercalifragilisticexpialidocious" | 34 |

My original opinion was 63, because this is what DNS uses, and because it is similar to what common relational databases use which, like us, have a very DNS-like naming convention of dot-separated components, as in `namespace.tablename` or `database.tablename`

However, I think that's probably going to be too limiting, so I think 255 is a more reasonable limit.

The server-side code for validating table names is located in the `FateServiceHandler` class, in a method called `validateTableNameArgument`. However, that method is currently being used for existing tables, in order to validate the parameters sent over the wire to the server. A similar method would have to be created to specifically validate *new* destination table names from creating, renaming, or cloning a table. That way, we don't impose the name limit on existing tables, only on new ones. For existing tables, it may be worth adding a warning log message to the current validator method that the table name is longer than what Accumulo now supports, and it may cause unexpected behavior if not renamed to something shorter.

(Originally reported at [ACCUMULO-2366](https://issues.apache.org/jira/browse/ACCUMULO-2366))

**Comment by ctubbsii** [comment]
I marked this issue as a "good first issue", because adding the limit is relatively simple. However, the code changes are in an area that may be somewhat unfriendly to approach, so it's slightly more challenging than other possible "good first issues". Perhaps this might be a "good second issue". Either way, it's a small amount of code to be changed and should be easy to implement and create simple test cases for.

**Comment by ctubbsii** [comment]
Upon completion of this issue, a good follow-up PR would be to implement the same restrictions in the size of namespace names.

**Comment by keith-turner** [comment]
>  the code changes are in an area that may be somewhat unfriendly to approach

@ctubbsii where do you think a change should be made for this?

**Comment by EdColeman** [comment]
Do we know what the impact / actual limit is?  The might be quite a gap between "giant" and  255.  Depending on how tables are created, it is not hard to get larger than 255.  Throw in a base name, a yarn job name and a timestamp or two and you can get a generated name that is not user friendly, but does encode some system runtime info that can be useful.

Whatever limit is "chosen" an approach could to have it as a configuration parameter with a sensible default and some guidance on what the "real" max should be considered to be.  Sort of like the zookeeper jute buffer parameter.

**Comment by keith-turner** [comment]
Nevermind @ctubbsii , the information I was asking about is in the description.

**Comment by ctubbsii** [comment]
@EdColeman I think adding a configuration parameter makes this issue more complex than something I would be comfortable asking a first-time contributor to do. That could be done as a follow-on issue, if it's in high demand. However, I do think we should keep in mind that the table name is primarily for humans, and should be within reason for humans to read, memorize, type in the shell, view on the monitor, see in the logs, etc.

I do think you make a good point about it easy to get above 255, with a naming convention that is composed of a few different external sources. If 1024 is more reasonable than 255, I'd be happy to support that instead.

**Comment by cradal** [comment]
Currently working on this one.

**Comment by ctubbsii** [comment]
Awesome @cradal . Let me know if you run into any issues.

**Comment by cradal** [comment]
Here is a possible non-time-based  solution, although it is admittedly naive and has a pitfall. What about appending the Accumulo version number that the table was created under to the table name? We could set the user limit to 1024 characters, but have the internal limit to 1027 where the last three chars identify the Accumulo version (e.g. ...tablename1.9). In this way, the validation function could discern between an older table that breaks the new limit and a new table that is compliant by checking the final 3 chars.

There is a clear pitfall here, though. There might be older tables that happen to have '1.9' as their last three characters. It is probably less likely that these would be the 1025, 26, and 27th chars, but possible nonetheless. 

I don't think using the ServerUtil class to detect upgrades will help because, once folks upgrade to the new version with the new limit, there still won't be a way to delineate between tables created pre-upgrade and those created post-upgrade.

I will keep looking for identifying info, maybe from ZK or Master, that we can leverage.

**Comment by ctubbsii** [comment]
> Regarding how to discern between the older tables and new ones with the length limit:

The primary action for this issue is to simply impose the limit for new table names. There is no need to distinguish between tables created prior to the restriction being imposed, and after.

An optional secondary action is to log a warning with a recommendation to rename tables with names longer than the current limit. For that, there length of the current name is sufficient. There is still no need to distinguish between tables created before and after the limit.
