### ISSUE TITLE
Support external compactions in containers

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1451]
For use cases like large scale filtering data on an accumulo table, it may be useful to support running compactions externally from a tserver in a system like kubernetes. This feature could support the following operations and behaviors.

 * Client side Accumulo API that selects tablets and files to compact that returns serializable+runnable objects for each external compaction. The objects can be serialized and run anywhere that has access to DFS.
 * A lease for every file that has been selected for external compaction.  This lease prevents other compactions from processing the files.
 * A client side API for listing, committing, and canceling outstanding external compactions. 

If all of the selection decisions for tablets and files to compact are made in the client side, then a user could pass a lambda to Accumulo to make these decisions.  This approach would avoid having to put that code on tservers.  The Accumulo client code could make RPCs to bring all needed information to the client side. Accumulo could also automatically handle the case of things changing and call the lambda again.

External compactions could have early or late binding for the set of files to compact.  Early binding is much easier to implement and run idempotently on a cluster.  There is one problem with early binding : leases could be held on lots of small file for a long time negatively impacting scans.  One possible way to avoid this would be compact all files less than size X on tserver before starting an external compaction and then only select files over size X for the external compaction.

**Comment by EdColeman** [comment]
Concerning leases and lease management.  The apache river / jini project has a lease manager specification that may provide some guidance with this type of functionality.

See https://river.apache.org/release-doc/current/specs/html/leaseutil-spec.html

**Comment by ivakegg** [comment]
A few comments:
1) I would imagine that this is primarily for handling larger files that may not be compacted using the configured compaction manager.
2) Using something like yarn instead of kubernetes might be a good initial implementation.
3) I would like to add the ability to do this while accumulo is off line.  This might be very difficult since we still need to make modifications to the accumulo metadata but there might be a way using fate operations, conditional mutations, zookeeper, other....

**Comment by ivakegg** [comment]
Now that I think about it, doing this while accumulo is off line might not be worth the effort.  Doing this for an off-line table may be reasonable however.

**Comment by keith-turner** [comment]
> Using something like yarn instead of kubernetes might be a good initial implementation.

The Accumulo API's will return a list of serializeable runnables.  Then a user could run those wherever they want.  This could lead to multiple little bridge projects that help run compactions in different execution environments.  This is an approach we took with Fluo when creating [fluo-yarn](https://github.com/apache/fluo-yarn) and [fluo-docker](https://github.com/apache/fluo-docker).

Ideally some of these bridge projects would be created before releasing Accumulo to facilitate testing the new API.

**Comment by keith-turner** [comment]
An alternative approach : apache/accumulo-website#223

**Comment by dlmarion** [comment]
Updated design document located at https://github.com/apache/accumulo-website/pull/266

**Comment by keith-turner** [comment]
> Updated design document located at apache/accumulo-website#266

This supersedes apache/accumulo-website#223.  One major difference between #223 and #266 is the  per tablet compaction queue stored in the metadata table is replaced with a compaction coordinator process that maintains per tserver summary information.  Per tablet information is not tracked by the coordinator, it only tracks enough information to know which tserver to contact next.  Tservers track per tablet information for internal and external compactions.

 We are working on prototyping this new design in the following branch.

https://github.com/apache/accumulo/tree/1451-external-compactions-feature
