### ISSUE TITLE
Create a single node (per context) for configuration in ZooKeeper

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1454]
Configuration in ZooKeeper is currently stored in a tree of ZooKeeper nodes under some `conf/` directory. In order to reduce the number of watches, support atomic configuration changes in ZooKeeper, and generally make the configuration code simpler, we should serialize the configuration for each table, as well as the system-wide configuration, into a single node (each).

The serialization formation should be human-readable (JSON), and indicate a serialization format version (in case we change the serialized format later).

This is a sub-task of #1225.

This also relates to https://issues.apache.org/jira/browse/ACCUMULO-1568 and https://issues.apache.org/jira/browse/ACCUMULO-4052

**Comment by ctubbsii** [comment]
This also supersedes https://issues.apache.org/jira/browse/ACCUMULO-4050

**Comment by milleruntime** [comment]
I created an issue #1809 for one of the bugs I think this change will fix.

**Comment by ctubbsii** [comment]
https://issues.apache.org/jira/browse/ACCUMULO-2861 is another related issue that describes storing it in a human-readable way. After discussions with @EdColeman, who has been working on this, it seems more likely that we'll need a tool to read/update config easily, rather than rely on it being human-readable. That way, we can get some compression.
