### ISSUE TITLE
Move TabletsMetadata builder to Ample

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1473]
Ample has methods to read the metadata for a single tablet.  In order to read the metadata for multiple tablets, the method `TabletsMetadata.builder()` must be used. The following is an example of some current code.

```java
    Iterable<TabletMetadata> tmi = TabletsMetadata.builder().forTable(tableId)
        .overlapping(startRow, endRow).fetch(FILES, LOCATION, LAST, PREV_ROW).build(ctx);
```

It would be nice if this were hanging off of Ample to make it discover-able.  This might look like the following.

```java
    Iterable<TabletMetadata> tmi = ctx.getAmple().readTablets().forTable(tableId)
        .overlapping(startRow, endRow).fetch(FILES, LOCATION, LAST, PREV_ROW).build();
```

There is one possible road block to making this change.  Currently the TabletsMetadata.builder() has two `build()` methods one that takes a context and another that takes an Accumulo client.  Need to handle the client case somehow.

**Comment by keith-turner** [comment]
The reason this code is the way it is is that TabletsMetadata was created first as an abstraction layer for reading tablet metdata.   Later Ample was created as an abstraction layer for reading and writing all Accumulo metadata.   Not everything in TabletsMetadata has been transitioned to Ample

**Comment by cradal** [comment]
@keith-turner I would like to delve into this issue. However, I can only see one build() method in TabletsMetadata, the one that takes a client. Has some work on this already been done?

**Comment by keith-turner** [comment]
@cradal  looking at history, I think the changes in 8c9a4e1 removed the other build method.  This changes is still valid and the changes in 8c9a4e1 may make this change easier.

**Comment by ctubbsii** [comment]
@cradal I've set the assignee to you, since you have expressed interest in this. :smiley_cat:

**Comment by cradal** [comment]
@keith-turner My idea for this is to define readTablets in the Ample interface, where it would take the TableId vice the KeyExtent as a parameter. Then an Options object can be built forTable(tableId) in the implementation.

**Comment by keith-turner** [comment]
@cradal are you thinking of adding something like :

```java
   TableOptions readTablets()
```

Where TableOptions is like the following except it does not have `forTablet(KeyExtent extent)`?

https://github.com/apache/accumulo/blob/a7251c3e970e815dfc8e49685a207ff7f5696ab8/core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java#L266

I think that is the direction I would start with if I were working on it. Not sure what surprises there will be along the way.  If you create just the new interfaces for Ample w/o implementing them and post a draft PR I would be happy to take a look at it.

**Comment by cradal** [comment]
@keith-turner How about something like this?:
    TableRangeOptions builder = TabletsMetadata.builder().forTable(tableId);
If I understand correctly, this will obtain a Range that corresponds to all the tablets for a partitioned table. Then, Ample.readTablets() could be implemented in AmpleIMpl, without modifying TabletsMetadata.

**Comment by keith-turner** [comment]
@cradal if I were attempt this I think I would take the builder interfaces in TabletsMetadata and move them to Ample.  I would leave the implementation of the interfaces in TabletsMetadata.  Not sure if this approach will work, but its what I would try to start with.

**Comment by cradal** [comment]
@keith-turner @ctubbsii I spent some time the last few days tracing through the function calls, just to get a better overall understanding of how TabletsMetaData is being used. I will generate a Work-In-Progress PR to show an example interface def and impl.
