### ISSUE TITLE
Broken tests in 1.x

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1482]
In 1.9 branch builds, I'm getting the following tests consistently failing:

* org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT.test
* org.apache.accumulo.test.proxy.ProxyDurabilityIT.testDurability

Both are timeouts. It's possible that the test timing needs to be tuned a bit, but it's also possible that there's something else going on that is preventing the tests from passing. I have not yet investigated.

(These test failures are in addition to the long-time flakey replication ITs, which I omitted here)

**Comment by ctubbsii** [comment]
On #1481, @milleruntime mentioned that VerifySerialRecoveryIT was also timing out on 1.x builds.

**Comment by Manno15** [comment]
I can do some investigating as well this week.

**Comment by milleruntime** [comment]
I opened #1483 which should fix a few of the recovery tests.

**Comment by milleruntime** [comment]
> I opened #1483 which should fix a few of the recovery tests.

I saw those 3 tests pass on my branch with the timeout.factor=3.  Here were the times I got:
```
[INFO] Running org.apache.accumulo.test.proxy.ProxyDurabilityIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 190.034 s - in org.apache.accumulo.test.proxy.ProxyDurabilityIT
[INFO] Running org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 100.596 s - in org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT
[INFO] Running org.apache.accumulo.test.VerifySerialRecoveryIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 174.864 s - in org.apache.accumulo.test.VerifySerialRecoveryIT
```
Running Ubuntu 18 VM on EC2 m4.2xlarge

**Comment by milleruntime** [comment]
I think adding 2 minutes to the timeout for these 3 tests is appropriate.  They are all doing recovery, which now basically has a 45 second waiting period since the recovery cache change here: 828a3219fd4234dfa045c8a63e02285170afda96

Once I merge #1483 I will increase the timeout for these tests in 1.10 and master.

**Comment by milleruntime** [comment]
The only non replication test I am now seeing consistently fail is RollWALPerformanceIT.  This test was dropped in 2.x so maybe we should just drop it since it is nondeterministic.

**Comment by ctubbsii** [comment]
It was removed from 2.x in 9d78365d8f4d7a97a7ca4f104fa107e1f900e5f9 because it was added to the accumulo-testing repo in apache/accumulo-testing#90 ; the accumulo-testing repo is only applicable to the 2.x code. We left the testing code for 1.x where it was. So... I'm not sure if we should remove it or not. I'm okay with leaving it for now as long as it passes regularly in CI.

**Comment by ctubbsii** [comment]
For this issue, I'm going to review all our default timeouts on my laptop... which I think has reasonable specs, and bump any that consistently fail. We should be able to run ITs on reasonable developer hardware. For reference, my laptop has an Intel i7-5500U CPU, 8G RAM, and an SSD.

**Comment by milleruntime** [comment]
Ah right.  I thought this was one of the tests we ended up just dropping.  This one is probably affected by the increase in recovery time with the 45 second cache.  It will probably need to be re-written.
