### ISSUE TITLE
AccumuloITBase should enforce a default timeout 

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1493]
Our builds can sometimes get stuck for long periods of time or forever (until killed). We should enforce a default timeout for all our integration tests by updating the `defaultTimeoutSeconds()` method in `AccumuloITBase` to enforce a global default timeout (5 minutes?).

Some tests may be taking longer than this default, so all tests should be run after applying the new default, and overrides established where needed for longer-running tests.

**Comment by milleruntime** [comment]
>  to enforce a global default timeout (5 minutes?).
> 
> Some tests may be taking longer than this default, so all tests should be run after applying the new default, and overrides established where needed for longer-running tests.

5 minutes seems a little short, since there are many that run around the 4 minute mark... we should probably just go with the max test timeout (if its reasonable).  Quick at the overrides and seems like 10 minutes.
