### ISSUE TITLE
Make branch 1.9 compatible with ZooKeeper 3.5

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#1503]
In ZooKeeper 3.5, the zookeeper jar has been moved from ZOOKEEPER_HOME to ZOOKEEPER_HOME/lib. Some things that need to be fixed in the 1.9 branch to support ZK 3.5 are:
- The start-all.sh script validates the existence of the jar at maxdepth 1, which could be changed to maxdepth 2 to locate the jar for 3.5: https://github.com/apache/accumulo/blob/1.9/assemble/bin/start-all.sh#L48
- The general.classpaths could be modified to include zookeeper jars in the ZK lib dir: https://github.com/apache/accumulo/blob/1.9/assemble/conf/templates/accumulo-site.xml#L141

**Comment by karthick-rn** [comment]
@billierinaldi, Can I start working on this?

**Comment by billierinaldi** [comment]
Sure! Thanks, @karthick-rn.
