### ISSUE TITLE
Throw Exception to prevent incorrect metadata

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1507]
Follow on work for #1501.  With the new TabletFile, we can now prevent metadata paths being incorrectly written (or not deleted) if an exception is thrown.  One way to do this is to have different methods on TabletFile to get the metadata entry depending if it is needed for reading, updating, inserting, or deleting.  If the path is needed for reading or inserting, we can use the normalized path.  If the path is needed for updating or deleting, then it has to be the original metadata entry (what was read) and TabletFile should throw an error if it is null.

**Comment by cradal** [comment]
@milleruntime Hello. I was looking at this issue as my possible next task, but I see some things which indicate some work might have already been done. For example, the metadataEntry field in TabletFile errors out if an attempt is made to instantiate it with a null metadataEntry. Hence, it seems that any call to getMetaDataEntry() will return something. Also, getMetadataEntry() is already being called on createDeleteMutation and minor/major compactions. Has this issue already been worked?

**Comment by milleruntime** [comment]
Yes it is almost completed in #1519.  Thanks for the ping though I had forgotten I created an issue!
