### ISSUE TITLE
ITs failing since introduction of tablet event logging

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1508]
MergeStateIT and VerifySerialRecoveryIT have been failing since d73e3af870.  I think this is a bug with  this change (that hasn't been fixed by subsequent changes) since the tests were passing before this commit.

**Comment by milleruntime** [comment]
I think VerifySerialRecoveryIT was broken with a different change in 87ad69931f79c0755ac967d74ad3c9ca3868fa40

**Comment by milleruntime** [comment]
After doing some git bisect, I think VerifySerialRecoveryIT is failing due to #1480

**Comment by milleruntime** [comment]
> After doing some git bisect, I think VerifySerialRecoveryIT is failing due to #1480

The same for MergeStateIT

**Comment by ctubbsii** [comment]
I can confirm that reverting #1480 (e22ea93786281324702e36b1dc0c151a6be1fa7c) fixes both tests.
