### ISSUE TITLE
CombinerTest shouldn't test by trying to capture logs

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1512]
The CombinerTest uses a questionable mechanism to test the expected logging behavior. It tries to hijack the log4j system, dynamically reconfiguring the logger with an appender that tries to capture log messages for the test.

This is unreliable and prevents upgrading to log4j2, which does not support such dynamic reconfiguration of logging, and whose APIs have changed significantly from log4j 1.2.

I'm working on this issue, and created this to track it, as part of my larger attempt to migrate to log4j2.

**Comment by milleruntime** [comment]
Looked at this test briefly and I think it is overly complicated.  I will look at it again but I think we can just remove the log4j stuff and test the cache if the error was logged.

**Comment by ctubbsii** [comment]
@milleruntime I initially assigned it to myself, because I expected to work on it, but if you have a good idea for how to improve it, I'd be happy to pass it off to you. I think you're right that it should be sufficient to check the cache.

**Comment by milleruntime** [comment]
OK I have a fix which removes the log4j and just checks the size of the cache to see if it was logged or not.  I think that is sufficient.  There is no need to check the string of the logger to make sure the error was logged.

**Comment by ctubbsii** [comment]
Awesome! Thanks @milleruntime !
