### ISSUE TITLE
Support ZK 3.5 in Accumulo 2.x

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#1513]
To make the accumulo-env.sh script work out of the box for ZooKeeper 3.5 and earlier versions, we need to add the ZooKeeper lib directory to the classpath alongside the ZooKeeper home directory which we already have: https://github.com/apache/accumulo/blob/master/assemble/conf/accumulo-env.sh#L62. We should try out the modified script with ZK 3.4 and 3.5 to make sure it works for both.

**Comment by ctubbsii** [comment]
It may be sufficient to add `$ZOOKEEPER_HOME/lib/*` to the `CLASSPATH`, but should be tested.

**Comment by thanujayalath** [comment]
@billierinaldi Can I work on this?

**Comment by karthick-rn** [comment]
@ctubbsii @billierinaldi - I can work on this.
