### ISSUE TITLE
Convert Translators to lambdas

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1533]
The custom paramaterized classes [Translators](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/clientImpl/Translators.java) and [Translator](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/clientImpl/Translator.java) can now be replaced with Java built in Lambda functions.

**Comment by ron-rico** [comment]
Please assign this issue to me.

**Comment by plainolneesh** [comment]
please assign this to me

**Comment by lbschanno** [comment]
@plainolneesh has requested that I take over this ticket. I've submitted a PR with the fix.
