### ISSUE TITLE
Use batching strategy for SimpleGarbageCollector candidate memory utilization

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1543]
The SimpleGarbageCollector tries to gather, check, and delete candidate files for garbage collection without running out of memory. It currently tries to do this by monitoring its own memory utilization when filling up its internal data structure of candidates, and then processing them before memory is full (or near full), clearing, and resuming collection of more candidates.

This makes the SGC handle as many candidates as possible in each pass. However, it makes memory utilization less predictable, and unstable.

A similar problem occurred in trying to test Upgrader9to10's memory utilization and was fixed in #1441 by adopting a strategy of batching candidates in approximately 8MB chunks rather than runtime memory monitoring.

The SimpleGarbageCollector should be changed to employ a similar batching strategy. The batch size could be configurable to give system administrators more control over maximum memory utilization by the SGC.

**Comment by Manno15** [comment]
@ctubbsii I think I have the changes made in #1441 transferred over to the SimpleGarbageCollector. Do you have an idea on the best way to test this? I don't think the current test for out of memory in the unit test is applicable anymore and I am struggling on a replacement for it and still keeping it as a unit test.
