### ISSUE TITLE
Explore alternatives for metrics.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#1561]
The [micrometer metrics facade](https://micrometer.io/) may be an alternative to hadoop metrics2 that might be able to simplify / enhance our current metrics.  This issue is to document what changes this would require.

**Comment by ctubbsii** [comment]
Since this is kind of open-ended exploration, I think we can leave off the 2.1.0 tag, since exploration isn't necessarily tied to any specific target version.

**Comment by EdColeman** [comment]
Okay with removing the tag - my intention was to signal that this was something that could go into 2.1.  Being is still speculation, but if it would work out / be accepted, then it could be tagged with a version then.

**Comment by DomGarguilo** [comment]
Not sure if I would call this a duplicate but it seems very similar to #1134. Might be able to merge the discussion of these two and remove one of them.

**Comment by EdColeman** [comment]
Good catch - I think 1134 was first written to see what was viable, and this one was created once micrometer seemed to meet our requirements - no preference to which one is used going forward.

**Comment by ctubbsii** [comment]
I'll close this one as a duplicate of #1134
