### ISSUE TITLE
Update importTable to represent directory list Set<String> instead of String

### ISSUE THREAD

**Issue by drewfarris** [apache/accumulo#1576]
In #1060 we add the ability to specify multiple directories for the `importTable` command. The current API for `importTable` expects multiple directories to be specified as a single, possibly comma-delimited `String`. @keith-turner raised the fact that the API should more explicitly reflect reality of the data it seeks to represent and take a `Set<String>` instead of a `String`. 

We should try to get this in for 2.1.0

**Comment by ctubbsii** [comment]
Seems like a good idea, but I'd suggest `Set<String>` instead of `String[]`

**Comment by drewfarris** [comment]
Per @arvindshmicrosoft comment on #1060, this will include documentation updates for the `importTable` workflow.

**Comment by drewfarris** [comment]
Missed something, `ImportExportIT` failed in https://jenkins.revelc.net/job/2.1/75/
