### ISSUE TITLE
Move ThriftClientHandler into a separate file.

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#1581]
TabletServer is very big. Moving ThriftClientHandler into a separate file would cut its size almost in half. This would also make it easier to continue refactoring TabletServer at a later date. They will still be very tightly coupled.

I can do this if it would be acceptable.

**Comment by ctubbsii** [comment]
@andrewglowacki I agree. Go ahead and submit a pull request. Please keep the change as minimal as necessary to refactor the class out, in order to lessen the burden on any code reviewers. Any subsequent improvements can be handled in follow-on tasks.

**Comment by andrewglowacki** [comment]
Sounds good, thanks!
