### ISSUE TITLE
Warning message during start/stop of Accumulo master

### ISSUE THREAD

**Issue by karthick-rn** [apache/accumulo#1587]
During start/stop of Accumulo master, a warning message appears on the console as highlighted below. I have already updated this warning message during discussion on #1578 and like I mentioned creating this issue to check if anyone else seen this? May be something that #1586 is uncovering. Operational wise I tested accessing the ashell and tried inserting rows into the new table  - all works fine & don't see any odd behaviours. Let me know if you have any further thoughts or pointers on what might be causing this? Thanks

<pre>
[knarendran@kn-snap-0 ~]$ accumulo-service master start
Starting master on kn-snap-0
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/muchos/install/accumulo-2.1.0-SNAPSHOT/lib/log4j-slf4j-impl-2.13.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/muchos/install/apache-zookeeper-3.5.7-bin/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2020-04-13T21:36:29,859 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /opt/muchos/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
2020-04-13T21:36:32,121 [server.ServerUtil] INFO : Attempting to talk to zookeeper
2020-04-13T21:36:32,637 [server.ServerUtil] INFO : ZooKeeper connected and initialized, attempting to talk to HDFS
2020-04-13T21:36:32,655 [server.ServerUtil] INFO : Connected to HDFS
<b>2020-04-13T21:36:32,691 [zookeeper.ZooCache] WARN : Unhandled: WatchedEvent state:Closed type:None path:null</b>
</pre>

**Comment by ctubbsii** [comment]
This is a new ZooKeeper client-side generated event added as part of https://issues.apache.org/jira/browse/ZOOKEEPER-2368 (apache/zookeeper#529), added in ZK 3.5.5 and 3.6.0.

Our code has not been updated to recognize it yet, but I think it's probably safe to ignore. It would be good for us to update our watchers to handle this explicitly, though.

**Comment by karthick-rn** [comment]
@ctubbsii Thanks for the update. I'll keep this as a low priority issue and work on it. You can assign it to me.

**Comment by DomGarguilo** [comment]
I am unable to reproduce this. Has this been looked into recently? @karthick-rn

**Comment by ctubbsii** [comment]
It looks like I fixed this as part of 55ed4c19b0b514bfb7397f09a3a37f0bbbc7bbde / #1800 / #1817
