### ISSUE TITLE
Support per compaction service metrics

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1612]
In #1605 compaction services with multiple thread pools were added.  Having metrics for the queue size and number of running compactions would be very useful. Not sure of the best way to do this, but it would be nice if the metrics included the compaction service name and thread pool/executor name within the service.

```
compaction.task.<service name>.<executor name>.queued=<num queued>
compaction.task.<service name>.<executor name>.running=<num running>
```

Having access to this information will be very important for tuning compaction service configuration.

**Comment by keith-turner** [comment]
I have implemented this at the following branch.  

https://github.com/keith-turner/accumulo/tree/accumulo-1612

Plan to submit a PR after #1605 is merged.

**Comment by EdColeman** [comment]
Keith I took a cursory glance and have a question that I hope you can answer of the top of your head.  In CompactionExecutorsMetrics, what is the cardinality of the CompactionExecutorId?  

I'll try to look at this in more detail later.

**Comment by keith-turner** [comment]
> what is the cardinality of the CompactionExecutorId?

That is the number of compaction executors across compactions services configured by users.  With the default configuration there will be 7 :

  * Compaction service for root tablet has 2 executors
  * Compaction service for metadata tablets has 2 executors
 * Compaction service for user tablets has 3 executors

**Comment by EdColeman** [comment]
Would the ids persist and be consistent across restarts?  The reason that I'm asking is that some metrics systems will create a separate time series for each metric "name"  Things that are unbounded (which seems this is not) cause issues - if the id are not consistent, then performing metric queries of a time-series that would cross restart boundaries could be misleading.  (Anyone / System querying over a time range may not be aware of the restart) 

If that would be the case, then rolling the values up into root, metadata and users may be more meaningful to a metrics system.  If there is still interest in each ceid at runtime, then maybe logging?

**Comment by keith-turner** [comment]
> Would the ids persist and be consistent across restarts?

Yeah.  The ids are based on user provided names in configuration.  For example the following configuration will create a compaction service named `cs1` with three executors named `small`,`medium`,large`.  

```
tserver.compaction.major.service.cs1.planner=org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner
tserver.compaction.major.service.cs1.planner.opts.executors=[{"name":"small","maxSize":"16M","numThreads":3},{"name":"medium","maxSize":"128M","numThreads":2},{"name":"large","numThreads":2}]
```

This would result in the following metrics : 

 * prefix_cs1_small_running
 * prefix_cs1_small_queued
 * prefix_cs1_medium_running
 * prefix_cs1_medium_queued
 * prefix_cs1_large_running
 * prefix_cs1_large_queued

Not sure what the actual prefix would be, would need to dig around in the code.
