### ISSUE TITLE
Investigate TODO in exception message in new Bulk Import

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1618]
Investigate this [exception](https://github.com/apache/accumulo/blob/3951d98aeffc20fa4318d14d03ef3f0c8be56876/core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java#L618).  Figure out if there is work to be done, if not, then provide a better description of the scenario to the user.

**Comment by cradal** [comment]
@millerruntime I traced through the logic for mergeOverlappinh() in BulkImport. It appears that the only scenario in which a merge will occur is if the overlapping KeyExtent (oke) fits lexicographically within the the previousEndRow and endRow of the KeyExtent (ke). The function will throw the exception if either end of oke extends beyond ke. It does not seem like anyone intended the function to do anything else. Perhaps we should change the exception message to read something like this:
"Unable to execute merge. Key extent " + oke.toString() +  " extends beyond the range of Key extent " + ke.toString() + ". Out of range data would be lost."

**Comment by milleruntime** [comment]
@cradal thanks for looking into this message.  Please open a PR with an idea of what the message should say.

**Comment by cradal** [comment]
@milleruntime The latest PR should only have the needed changes.

**Comment by milleruntime** [comment]
Thanks @keith-turner and @cradal for figuring this out!
