### ISSUE TITLE
Add method to get properties with prefix to PluginEnvironment.Configuration

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1627]
[PluginEnvironment.Configuration](https://github.com/apache/accumulo/blob/db9c2b975f2db1b3903402dea69e32a014d122da/core/src/main/java/org/apache/accumulo/core/client/PluginEnvironment.java#L39) is a stable interface that allows plugins to access Accumulo's configuration.  Sometimes plugins need all properties with a certain prefix which currently requires iterating over all properties.  Accumulo's internal configuration class efficiently supports this in some cases.  It would be nice to add a method that supports efficiently getting props with a prefix to PluginEnvironment.Configuration.

Noticed this while working on the TooManyDeletesSelector as part of #1605 which needs to get all summarizer properties.

**Comment by jkosh44** [comment]
Hey @keith-turner is this still relevant? If so I'd like to give it a shot.
