### ISSUE TITLE
Add test where compaction selector sporadically throws an exception.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1628]
Add test that does the following to org.apache.accumulo.test.CompactionIT

 * Create a compaction selector that only compacts file names that match a pattern and throws an exception randomly 50% of the time.
 * Initiate a compaction of a subset of file using above selector.  Confirm subset if compacted.
 * Add files and run above step a few times.

This test will ensure that compaction selector is retried when it throws an exception and a single exception does not cause compactions to hang.

**Comment by tynyttie** [comment]
I will look at it.

**Comment by tynyttie** [comment]
@keith-turner   Is this ticket still relevant base on your new updates to Compaction? If so, what components do I directly affect to accomplish the task? Plus, what was your expected result?

**Comment by ivakegg** [comment]
@tynyttie As far as I can tell this ticket is still relevant.  You would still be creating a CompactionSelector implementation as described and initiating the compaction.

**Comment by keith-turner** [comment]
@tynyttie I would add the test to the following class.

https://github.com/apache/accumulo/blob/main/test/src/main/java/org/apache/accumulo/test/CompactionExecutorIT.java

The test could do something like the following.  Could create BuggySelector as a static public class in CompactionExecutorIT 

```java
@Test
public void testBuggySelector(){
     //TODO create table bst and Accumulo client

    // add 3 files to table... 
    addFile(client, "bst", 1, 1000, false);
    addFile(client, "bst", 1, 500, false)
    addFile(client, "bst", 1, 250, false)
 
  // get the current files
   var files = getFiles(client, "bst");

   // TODO somehow select a random subset of files from above set
  randomSubset = ....
  String rsl = .... somehow join randomSubset into a comma sep list

  // configure compaction to use BuggySelector. BuggySelector should select the files passed in the option fileToCompact and it should sometimes randomly throw an exception.
   var cc1 = new CompactionConfig()
       .setSelector(
           new PluginConfig(BuggySelector.class.getName(), Map.of("filesToCompact", rls)))
       .setWait(true);  
   
     client.tableOperations().compact("bst", cc1);

     var files2 = getFiles(client, "bst");
     // TODO verify that files does not contain anything from randomSubset
}

```

**Comment by tynyttie** [comment]
@keith-turner Thank you for replying back to me. My issue is when the unchecked exception is thrown, where in Compaction Manger hierarchy should I appropriately handle it in order for Accumulo to re-kick and select a new compact-able? Should it be in the Compaction Manger Class, Compaction Executor class or Compaction Service class?

**Comment by keith-turner** [comment]
> My issue is when the unchecked exception is thrown, where in Compaction Manger hierarchy should I appropriately handle it in order for Accumulo to re-kick and select a new compact-able?

@tynyttie my hope is that it already works, but the test will let us know if it actually works.  The following code is where files are selected.

https://github.com/apache/accumulo/blob/18ba45e144ea8213a9637fe36bf0d8a68c3f15f5/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L328

If an exception is thrown, the following should catch and hopefully reset things to a good state so that future compactions can run if an exception is not thrown.

https://github.com/apache/accumulo/blob/18ba45e144ea8213a9637fe36bf0d8a68c3f15f5/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L353
