### ISSUE TITLE
Looking into marking tablet as chopped in compaction mutation

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1630]
While working on #1605 I noticed that chop compactions write out two mutations to the metadata table.   One mutation changes the tablets set of files.  The second mutation marks the tablet as chopped.  May be better to do this in a single mutation.  This behavior exist before and after #1605.

**Comment by ctubbsii** [comment]
A single mutation, if possible, is a good idea. Also, for reference only, there's an open ticket to remove chop compactions entirely: #1327

**Comment by ddanielr** [comment]
Closing this issue since #1327 is completed.
