### ISSUE TITLE
Tablet in memory compaction ID is updated before metadata write

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1631]
While working on #1605 I noticed that the tablets in memory tracking of the compaction ID (via `Tablet.setLastCompactionID()`) was updated before updating the metadata table.  If the metadata table update fails then this could lead to tablet server/FATE disagreement about a compaction being completed causing the FATE op to hang.  This is similar to the more general issue described in [ACCUMULO-18](https://issues.apache.org/jira/browse/ACCUMULO-18).

**Comment by ctubbsii** [comment]
I edited the original post to link to the JIRA issue.
