### ISSUE TITLE
Collect possible new names for the Accumulo Master

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1638]
The community [discussed](https://lists.apache.org/thread.html/redcea10fc3c705491b9792b2b0bafa12b9bd246b64394c4dea2d9be0%40%3Cdev.accumulo.apache.org%3E) renaming the Accumulo Master.  To rename it, we must decide on a new name.  The purpose of this issue is to track proposed names.  The following names have been proposed so far in the discussion and on [ACCUMULO-2844](https://issues.apache.org/jira/browse/ACCUMULO-2844).

 * Coordinator 
 * Conductor
 * Admin
 * AdminServer
 * Director
 * Root
 * Nucleo 
 * Cervello
 * Manager
 * Conductor

The issue only exists to collect proposed names, so please feel free to add to the list.  Another issue will opened under the [project](https://github.com/apache/accumulo/projects/14) to discuss the name selection process.

**Comment by EdColeman** [comment]
I saw some news articles concerning Linux adopting inclusive terminology.  I believe this is the [(original source)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb) For quick reference, these are the term selected:

> 
> For symbol names and documentation, avoid introducing new usage of 'master / slave' (or 'slave' independent of 'master') and 'blacklist / whitelist'.
> 
> Recommended replacements for 'master / slave' are:
>     '{primary,main} / {secondary,replica,subordinate}'
>     '{initiator,requester} / {target,responder}'
>     '{controller,host} / {device,worker,proxy}'
>     'leader / follower'
>     'director / performer'
> 
> Recommended replacements for 'blacklist/whitelist' are:
>     'denylist / allowlist'
>     'blocklist / passlist'
>

**Comment by ctubbsii** [comment]
I'm going to put several of these names in separate comments, so people can "thumbs up" those they like the best... it's not an official vote or anything, but it can make it slightly more convenient to narrow down the choices of those that seem to have the most consensus behind them.

**Comment by ctubbsii** [comment]
Proposal: Coordinator

**Comment by ctubbsii** [comment]
Proposal: Conductor

**Comment by ctubbsii** [comment]
Proposal: Admin

**Comment by ctubbsii** [comment]
Proposal: AdminServer

**Comment by ctubbsii** [comment]
Proposal: Director

**Comment by ctubbsii** [comment]
Proposal: Root

**Comment by ctubbsii** [comment]
Proposal: Nucleo

**Comment by ctubbsii** [comment]
Proposal: Cervello

**Comment by ctubbsii** [comment]
Proposal: Manager

**Comment by ctubbsii** [comment]
Proposal: Conductor

**Comment by milleruntime** [comment]
@ctubbsii I noticed a duplicate (Conductor) so deleted the second one.  There were no votes on this one.

**Comment by ctubbsii** [comment]
Current tallies:

* 6 - Manager
* 5 - Coordinator
* 2 - Conductor
* 2 - Director
* 1 - AdminServer
* 1 - Nucleo
* 1 - Root
* 0 - Admin
* 0 - Cervello

I'll close this issue now and start a vote on the mailing list to decide between the top two choices, "Manager vs. Coordinator".

**Comment by ctubbsii** [comment]
The name agreed to in a vote on the mailing list was 'manager'.
