### ISSUE TITLE
Determine process for selecting a new name

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1639]
#1638 was opened to collect new possible names.  The community needs to agree on a process of actually selecting a name.  In the mailing list [discussion](https://lists.apache.org/thread.html/redcea10fc3c705491b9792b2b0bafa12b9bd246b64394c4dea2d9be0%40%3Cdev.accumulo.apache.org%3E) a ranked vote was proposed.  Need to determine if there are other possibilities and when action should be taken.  This issue was opened to discuss the process.

**Comment by ctubbsii** [comment]
On #1638, I put the proposals in separate comment fields, so people can informally declare their preferences by "thumbing up" a comment. After we gather some feedback informally, I'm happy to initiate a vote thread with the most popular names.

I'm not sure we need a separate issue open for this, though. Can we close this issue?

**Comment by ctubbsii** [comment]
Closing based on lack of response to previous comment. Please re-open if this is necessary.

**Comment by ctubbsii** [comment]
The name agreed to in a vote on the mailing list was 'manager'.
