### ISSUE TITLE
Rename master references in public API

### ISSUE THREAD

**Issue by brianloss** [apache/accumulo#1643]
Once a new name is selected, we'll need to rename master references in the public API. Per [semver](https://semver.org/), the existing references will need to be deprecated for at least a release, and then the deprecated methods can be removed in a major release. Identify all public API references to master. At least the following exist:

- [Instance.getMasterLocations](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/Instance.java#L48)
- [ZooKeeperInstance.getMasterLocations](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java#L137)

**Comment by ctubbsii** [comment]
The name agreed to in a vote on the mailing list was 'manager'.

**Comment by jkosh44** [comment]
I have a couple questions on this. 

- Do we just want to change the method names or all references? 
- What about variable names, enum values, and constants? 
- Do we just care about public API methods are do we also want to change internal methods? 
- What about class names? For example `MasterClient`. One solution could be to refactor this to `ManagerClient`, then have a subclass called `MasterClient` that just delegates all methods to `ManagerClient`.
- It looks like there are some files called master or that have the word master in it (https://github.com/apache/accumulo/blob/main/minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java#L56 for example). How should those be treated? It seems like renaming the file could break existing instances.

**Comment by ctubbsii** [comment]
For this issue, I would focus *only* on public API.

**Comment by ctubbsii** [comment]
This is partially done. The final removal will need to occur in a 3.0.0 release, because of the API breakages.
