### ISSUE TITLE
Accumulo Monitor UI not displaying ZK metrics 

### ISSUE THREAD

**Issue by karthick-rn** [apache/accumulo#1645]
I configured TLS on ZK and found the Accumulo Monitor was not displaying ZK stats as shown in the below pic

![image](https://user-images.githubusercontent.com/7976585/86039867-00f34080-ba3b-11ea-8044-8a6382698f25.png)

Accumulo Monitor currently uses the ZK 4LW `stat` to display `MODE` & `CLIENTS` on the UI. 
Based on the [link](https://zookeeper.apache.org/doc/r3.6.1/zookeeperAdmin.html#sc_zkCommands), the 4LW will be deprecated & are disabled by default(since ZK 3.5.5). Also, 4LW doesn't seem to work with secure client port.

## Solutions:
1. Document to whitelist the 4LW in `zoo.cfg` using `4lw.commands.whitelist` but that will only work with un-secure client port. 
2. Make the Accumulo Monitor use [Adminserver](https://zookeeper.apache.org/doc/r3.6.1/zookeeperAdmin.html#sc_adminserver) as suggested by ZK community. Using Adminserver requires a code change. Supporting TLS with Adminserver will likely require additional code changes in Accumulo.
3. Remove ZK monitoring from Accumulo Monitor page and let users consult Adminservers directly for the metrics.

I & @keith-turner discussed and we came up with the above solutions and think option 2 or 3 will be the best way forward, would like to get others thoughts or solutions as well on this?

**Comment by ctubbsii** [comment]
I am in favor of option 3. It makes the most sense to me. We don't need to be in the business of being the monitoring solution for external services we rely on. We should, however, have some basic information available about what ZooKeepers are configured (the ZK host:port list), perhaps in the "About" dialog box, next to the Accumulo instanceId.

**Comment by EdColeman** [comment]
The documentation was updated in April (under the troubleshooting section) describing the need to add the stat command to the allowed-list while a longer-term solution is worked.

**Comment by ctubbsii** [comment]
> The documentation was updated in April (under the troubleshooting section) describing the need to add the stat command to the allowed-list while a longer-term solution is worked.

The referenced update was apache/accumulo-website#226

**Comment by dkurzaj** [comment]
Hello, this new behaviour of Zookeeper seems to also impact the Accumulo Mini Cluster which relies on the `ruok` 4-letters command to establish handshake with the started Zookeeper server. Starting the mini cluster seems to always fail for me now that I updated my Zookeeper dependency. The mini cluster config for Zookeeper should probably add a line to whitelist this keyword.

**Comment by ctubbsii** [comment]
> Hello, this new behaviour of Zookeeper seems to also impact the Accumulo Mini Cluster which relies on the `ruok` 4-letters command to establish handshake with the started Zookeeper server. Starting the mini cluster seems to always fail for me now that I updated my Zookeeper dependency. The mini cluster config for Zookeeper should probably add a line to whitelist this keyword.

That has already been done in 2f28816d40778df60508e5ed9c3f0f496173b997 and will be available in 2.1.0. If you need it sooner, you can backport the changes to your builds.

**Comment by dkurzaj** [comment]
Oh excuse me for the inconvenience, thank you! :)
