### ISSUE TITLE
Combiner option setReduceOnFullCompactionOnly not honored

### ISSUE THREAD

**Issue by sixfootbeard** [apache/accumulo#1678]
Combiner option setCombineAllColumns(..., true) prevents the other option setReduceOnFullCompactionOnly(..., true) from being honored. The issue is likely related to the init() method bailing out once the first option is determined to be true instead of continuing to parse the initialization options. 

https://github.com/apache/accumulo/blob/9f29f37d87809ac6a86f185348c517a104b7dec6/core/src/main/java/org/apache/accumulo/core/iterators/Combiner.java#L281

**Comment by milleruntime** [comment]
Thanks @sixfootbeard for creating the issue.  What version of Accumulo are you seeing this issue?  It looks like this issue exists in 1.9 as well.

**Comment by sixfootbeard** [comment]
I'm using version 1.9.3.
