### ISSUE TITLE
Post-vote release tasks for 1.10.0

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1699]
- [Git](https://github.com/apache/accumulo) tasks
  - [x] Create a signed `rel/<version>` tag (and push it)
  - [x] Merge `<version>-rc<N>-next` branch into a maintenance branch (if maintenance is expected),
        and then into the `main` branch (and push them)
  - [x] Remove `*-rc*` branches
- [Nexus](https://repository.apache.org) tasks
  - [x] Release the staging repository corresponding to the successful release candidate (use "release" button)
  - [x] Drop any other staging repositories for Accumulo (do *not* "release" or "promote" them)
- [SVN / dist-release](https://dist.apache.org/repos/dist/release/accumulo) tasks
  - [x] Upload the release artifacts (tarballs, signatures, and `.sha512` files) for the mirrors
  - [x] Remove old artifacts from the mirrors (**after** updating the website)
- [Board reporting tool](https://reporter.apache.org/addrelease?accumulo)
  - [x] Add the date of release (the date the release artifacts were uploaded to SVN `UTC+0000`)
- Verify published artifacts
  - [x] In [Maven Central](https://repo1.maven.org/maven2/org/apache/accumulo/accumulo-core/)
  - [x] In [ASF Downloads](https://downloads.apache.org/accumulo)
  - [x] In [several mirrors](https://www.apache.org/dyn/closer.lua/accumulo)
- Update the [staging website](http://accumulo.staged.apache.org/)
  - [x] Release notes
  - [x] Add `LTS: true` to the release notes front-matter for LTS releases
  - [x] Navigation
  - [x] Downloads page
  - [x] DOAP file
  - [x] Add manual/examples/javadoc
  - [x] Jekyll config
  - [x] Grep for, and update any links to previous version to now point to the new version
  - [x] Update any older release notes front-matter to indicate they are either `archived: true` or `archived_critical: true`
  - [x] [Publish to production](https://github.com/apache/accumulo-website#publishing-staging-to-production)
- Announcement email
  - [x] Prepare and get review on dev list (see examples [from previous announcement messages](https://lists.apache.org/list.html?announce@apache.org:gte=1d:accumulo))
  - [x] Send to announce@apache.org and user@accumulo.apache.org
- GitHub wrap-up
  - [x] Close this issue
  - [x] Create a 1.10.1 project on GitHub (if necessary) and move any open 1.10.0 issues to that project
  - [x] Close the 1.10.0 project on GitHub

**Comment by milleruntime** [comment]
This is great, thanks @ctubbsii.  Feel free to update or push these to https://github.com/apache/accumulo-website/pull/239

**Comment by ctubbsii** [comment]
> This is great, thanks @ctubbsii. Feel free to update or push these to [apache/accumulo-website#239](https://github.com/apache/accumulo-website/pull/239)

I was actually thinking about making an issue template in the repo, so that we can easily create this type of issue again in future, to create a better workflow to obviate the need for too many detailed instructions.
