### ISSUE TITLE
Continuous verification script fails with ZK version 3.5 & above

### ISSUE THREAD

**Issue by karthick-rn** [apache/accumulo#1712]
We ran into this when testing 1.10 RC2 & at the time we manually copied the `zookeeper-*.jar` from `zk_home/lib` to  `zk_home/` directory to workaround the issue. The script needs to be modified to look for `zookeeper-*.jar` files inside the `/lib` directory for ZK versions 3.5 & above.

**Comment by ctubbsii** [comment]
This issue seems relates to https://github.com/apache/accumulo/issues/1695#issuecomment-696930091

**Comment by karthick-rn** [comment]
#1695 is mainly to address the empty arguments. I thought I'll create a separate issue to address the ZK directory problem. Let me know if I can club both the work in a single PR? If so, we can close this issue.

**Comment by ctubbsii** [comment]
> #1695 is mainly to address the empty arguments. I thought I'll create a separate issue to address the ZK directory problem. Let me know if I can club both the work in a single PR? If so, we can close this issue.

A single PR can close both issues. These are both pretty small changes, probably. I only linked to the other issue, for easy reference to related issues.

**Comment by karthick-rn** [comment]
> > #1695 is mainly to address the empty arguments. I thought I'll create a separate issue to address the ZK directory problem. Let me know if I can club both the work in a single PR? If so, we can close this issue.
> 
> A single PR can close both issues. These are both pretty small changes, probably. I only linked to the other issue, for easy reference to related issues.

Ok, makes sense. I'll close this issue.

**Comment by ctubbsii** [comment]
@karthick-rn It's okay if this is open. What I meant was: when the PR is made, it can address two issues, and it can be closed when that PR is merged.

**Comment by ctubbsii** [comment]
I believe this is fixed by #1716
