### ISSUE TITLE
Standalone ITs failing due to new compaction changes

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1713]
**Describe the bug**
Multiple ITs are now failing when run as a Standalone cluster due to recent changes with compactions.  Related to #1084 

**Versions (OS, Maven, Java, and others, as appropriate):**
- Defaults configured with Accumulo 2.*

**To Reproduce**
Run the ITs against a standalone cluster.  Directions can be found in TESTING.md

**Additional context**
The following ITs have compaction related failures:

- org.apache.accumulo.test.IteratorEnvIT
- org.apache.accumulo.test.RecoveryCompactionsAreFlushesIT
- org.apache.accumulo.test.UserCompactionStrategyIT
- org.apache.accumulo.test.functional.CompactionIT
- org.apache.accumulo.test.functional.MasterMetricsIT
- org.apache.accumulo.test.functional.SummaryIT
- org.apache.accumulo.test.TableOperationsIT

Most of the failures are likely caused by a ClassNotFoundException.  Here are the missing classes: 

- Failed to load constraints 4k java.lang.ClassNotFoundException: org.apache.accumulo.test.constraints.NumericValueConstraint
- java.lang.ClassNotFoundException: org.apache.accumulo.test.IteratorEnvIT$ScanIter
- java.lang.ClassNotFoundException: org.apache.accumulo.test.SampleIT$IteratorThatUsesSample
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.AuthsIterator
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.BadCombiner
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.BadIterator
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.DropModIter
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.SlowIterator
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.SummaryIT$BigSummarizer
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.SummaryIT$BuggySummarizer
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.SummaryIT$FooCounter
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.SummaryIT$KeySizeSummarizer
- java.lang.ClassNotFoundException: org.apache.accumulo.test.functional.YieldingIterator
- java.lang.ClassNotFoundException: com.bogus.iterator

**Comment by ctubbsii** [comment]
Is it possible these tests are no longer suitable for Standalone mode? I have not seen failures during a regular build. Perhaps they merely need to have their JUnit Category annotation updated?

**Comment by milleruntime** [comment]
> Is it possible these tests are no longer suitable for Standalone mode? I have not seen failures during a regular build. Perhaps they merely need to have their JUnit Category annotation updated?

Yes that's definitely possible.  I was thinking that looking at all the ITs now failing in #1084.  It looks like the contents of ```AccumuloClusterHarness``` are mainly for dealing with a Standalone cluster.  Perhaps a lot of the ITs could extend ```AccumuloITBase``` instead.  This may be a lot of work though.

**Comment by milleruntime** [comment]
I don't think its feasible to change the parent class of these ITs away from ```AccumuloClusterHarness```.  There is a lot of ```MiniAccumuloCluster``` baked into that type, everything is based on whether its a MINI or STANDALONE cluster type.  We may be able to just override the cluster type to MINI for ITs that we know won't run on a Standalone cluster.  I will look into that.

**Comment by milleruntime** [comment]
Looks like we already have that power!  
https://github.com/apache/accumulo/blob/618ba7a9f88342ea7c8d692ce19df34d88bf07c8/test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java#L366

**Comment by EdColeman** [comment]
Some of those tests - MasterMetricsIT may be failing if the stand-alone is not configured to generate metrics (metrics prop file on the class path)

**Comment by milleruntime** [comment]
I discovered that a lot of the ITs that were failing due to missing classes will run in standalone if you simply copy the test jar into the accumulo lib folder of the running instance.  This may allow some of these ITs to run in standalone mode.  I will have to re-run them with the test jar present.
