### ISSUE TITLE
Have Standalone fail fast when no Accumulo instance

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1718]
Some ITs that run in standalone mode will still run if they can't connect to the Accumulo instance.  It would be nice if a check was added to ```AccumuloClusterHarness``` during setup that did a sanity check to make sure Accumulo is running and fail quickly if the connection can't be made.

**Comment by Manno15** [comment]
I took a look at this and have some follow up questions. Is the main intent of this to fail fast when the entire standalone suite is run? Since each individual test has it's own timeout anyways it would just crash when that is reached.  

I also wonder if you have any ideas on the best way to implement this? From what I can tell, there are multiple reasons as to why it can't connect to an accumulo instance and for an IT to hang. Whether it is just the Manager service (I think that is the new name), zookeeper, or if a tserver is down (assuming . I can check for these cases and more individually, but I couldn't find an already implemented way to check if an accumulo instance is active and running or imaybe we don't want to check for every possible instance. Thats where I am stuck at for this ticket at the moment.

**Comment by milleruntime** [comment]
I was thinking have the test to fail similar to what we did with checking the properties file: https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java#L68
Except this would be to just test a connection to AccumuloClient based on the properties in that file.   I think the quickest we would be able to fail would be the default ZK connection timeout.

**Comment by Manno15** [comment]
Is there a way to limit the 2x zookeeper timeout period? As it stands, most of the tests will timeout before the zookeeper timeout is reached.

**Comment by ctubbsii** [comment]
> Is there a way to limit the 2x zookeeper timeout period? As it stands, most of the tests will timeout before the zookeeper timeout is reached.

@Manno15 Not a good way for an existing (standalone) cluster, no. Even if there was an easy way to time out before that, we would probably end up with false negatives (we conclude that ZK is not running when it really is, but we didn't give it enough time to connect). If tests are set to time out before 2x ZK timeout, I'm surprised we don't have more flaky tests. I would consider 2x ZK timeout to be the minimum time we should wait for a test to finish (but it's not worth changing it if they are working today).

**Comment by ctubbsii** [comment]
It's possible there's not a good way to fail fast, and there's nothing to be done for this ticket.

**Comment by milleruntime** [comment]
You should be able to set the ```.zkTimeout()``` [here](https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/test/src/main/java/org/apache/accumulo/harness/conf/StandaloneAccumuloClusterConfiguration.java#L110) on the ClientInfo.  I am not sure if that will get overridden by the framework though.  If that works, we could add the timeout as another property in the standalone config file.

**Comment by ctubbsii** [comment]
> You should be able to set the `.zkTimeout()` [here](https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/test/src/main/java/org/apache/accumulo/harness/conf/StandaloneAccumuloClusterConfiguration.java#L110) on the ClientInfo. I am not sure if that will get overridden by the framework though. If that works, we could add the timeout as another property in the standalone config file.

Based on [the docs](https://zookeeper.apache.org/doc/r3.4.14/zookeeperAdmin.html), the minimum session timeout that the client is able to negotiate is determined by a server-side setting, and defaults to 2x the `tickTime`. So, setting something in our client lower than that would be limited by the minimum. This is what I thought @Manno15  was referring to. However, reading back, I'm not sure if he was referring to that when he said "2x zookeeper timeout period" or something else.

**Comment by Manno15** [comment]
I am not quite sure on the terminology but from what I noticed and based on the error message, it runs through our default zookeeper timeout twice before failing. The default instance.zookeeper.timeout is 30s and will throw my exception 2x that time. I had difficulties trying to lower the default timeout client side but I will look at what Mike mentioned tomorrow.

**Comment by Manno15** [comment]
This is the specific thing I am talking about: 
```Failed to connect to zookeeper (localhost:2181) within 2x zookeeper timeout period 30000```

That 2x timeout period.

**Comment by milleruntime** [comment]
No practical solution within the current build system and test framework.
