### ISSUE TITLE
Per Table problem links not working in Monitor

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1719]
On the Monitor if there are table problems (Debug menu -> Table problems) the page will get populated with links.  The links in the Summary table under the "Table" column do not work.  The links in the "Table" column in the Details table do work though and will take you to the table status page for that table. See screenshot.

![per-table-problem-bug-marked](https://user-images.githubusercontent.com/11872539/94571476-092b6980-023e-11eb-9d5f-b3b986d3be0d.png)

**Comment by milleruntime** [comment]
I did some research on the old monitor and it seems like the links that aren't working in the summary Table column were used to filter the Details table below.  The Table column links in the Details table has changed, it also used to filter the Details table where now it will take you to the Table page.

**Comment by milleruntime** [comment]
I am thinking we should update the tables on the problems page to use the Datatables JavaScript.  It will be consistent with the other pages, we get all the benefits of Datatables and then won't have to worry about links for filtering the tables.

**Comment by ctubbsii** [comment]
What do the bad links look like, as compared to the good links?

**Comment by milleruntime** [comment]
> What do the bad links look like, as compared to the good links?

This link works: ```http://localhost:9995/tables/!0```
This link is broken: ```http://localhost:9995/problems?table=!0```

**Comment by ctubbsii** [comment]
Hmm, that looks like we were trying to have a page view that shows only one specific table's problems. I don't even know if the underlying code supports that. In any case, your suggestion to use datatables.js instead would resolve this, as we don't need to have separate views for each table if the javascript can filter the single view adequately. If we do have code on the backend to support separate views for each table, we can probably just remove that.

**Comment by milleruntime** [comment]
> Hmm, that looks like we were trying to have a page view that shows only one specific table's problems. I don't even know if the underlying code supports that. 

I looked at the old monitor on a production system and both links filter the bottom table to show only the problems for that table.

I think converting the tables to datatables will fix multiple issues and we will benefit from the added features.
