### ISSUE TITLE
1.10: build_native_library.sh fails on alpine due to mktemp template format mismatch

### ISSUE THREAD

**Issue by larsw** [apache/accumulo#1731]
Re.

https://github.com/apache/accumulo/blob/314f2aa6639449bf99db9191d3255349f84c5b61/assemble/bin/build_native_library.sh#L43

A fix for this is to update the script with:
```bash
# Make a directory for us to unpack the native source into
# We need to check if this is a busybox-based distro (alpine) in order
# to use the right mktemp template format.                            
if [ $(readlink `which /bin/mktemp`) == "/bin/busybox" ]; then
    TMP_DIR=$(mktemp -d /tmp/accumulo-native.XXXXXX) || exit 1
else                                                          
    TMP_DIR=$(mktemp -d /tmp/accumulo-native.XXXX) || exit 1  
fi 
```

**Comment by ctubbsii** [comment]
What are the requirements of the busybox version of `mktemp`? Does it have to be exactly 6 `X`s or can it be longer?

I'd prefer to avoid the conditional, so we have one line that works for everybody. If that means making the template exactly 6 `X`s or longer, that's fine, or we can just omit the `TEMPLATE` name entirely, and have it be generated randomly by `mktemp`.

Feel free to submit a PR to fix.
