### ISSUE TITLE
Unreleased Resource: Sockets

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/accumulo#1733]
https://github.com/apache/accumulo/blob/3dae7d3357248e97193acb3bbac0448183df165e/server/tracer/src/main/java/org/apache/accumulo/tracer/ZooTraceClient.java#L186

The program can potentially fail to release a socket.

**Comment by ctubbsii** [comment]
For context, this socket is used in the thrift client in AsyncSpanReceiver to send spans to the tracer service. The thrift client appears to be cached for reuse, but it does not appear to ever be closed. I'm not sure this is a serious issue, and I think I would prefer to remove the tracer service entirely, as it isn't well-maintained, and it'd be better to send spans to a span receiver for a sink that is more well maintained (outside this project).

**Comment by DomGarguilo** [comment]
Looks like this can be closed since the changes made in #2259 removed this file.
