### ISSUE TITLE
CreateTable FaTE operation may not clean up splits files if operation is killed

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1739]
The CreateTable FaTE operation creates files in DFS for storing split points, if the user is creating a pre-split table. If the task completes, it should delete these files. However, if the job fails, it may not delete one or both. The `undo` method for the `ChooseDir` step should delete one of the files, but nothing seems like it will delete the other one, unless the operation completes successfully.

Found on main/2.1.0-SNAPSHOT branch while working on PR #1738 ; it may affect other versions as well

**Comment by Manno15** [comment]
Is there a good way to force a pre-split to fail? I want to confirm things on my end so I have a better idea on what to look for.

**Comment by ctubbsii** [comment]
I can't think of a great way to do it. However, I'm not that familiar with the FaTE code right now. I was thinking that you might have to introduce a delay to test it (insert a long Thread.sleep in the CreateTable.call method, just to force it to take a long time... and then remove it when you're done testing). While it is sleeping, you could fail the fate operation (I think you can do that in the shell, but I'd have to check), and then restart the master service so the operation won't complete.

However, I don't actually know that this would work, and there may be different cleanup behavior if the fate operation is canceled and if it fails on its own. I'm not sure how that works.

I do know that these temporary files names are different in #1738, so whatever you do for this issue, you may need to adjust slightly after that PR is merged.

**Comment by Manno15** [comment]
Okay, I will test that out. Thanks.

**Comment by Manno15** [comment]
I did confirm that your suggestion works. I was able to fail the fate operation in the shell while master service was down and the split files were still in DFS. I created a simple delete function that's called after table is created to check if those files still exist and then delete them if they do.

**Comment by ctubbsii** [comment]
@Manno15 The files should not exist after the table is created. There is already a cleanup step at the end of creating a table. The current cleanup step might be broken, but it should work after my changes in #1738 are complete and merged. The issue identified in this ticket is only to address cleanup of these files if the table creation fails... not if it finishes, because that's already handled.

**Comment by Manno15** [comment]
I misspoke in my previous comment. It is called after the create table call. Regardless if it completed or not. So if it fails, the files are still cleaned up.
