### ISSUE TITLE
Better Use of forEach on Scanner to simplify iteration

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1742]
It would be nice if we could reduce some of the boiler plate when iterating using Scanner.  It feels like Scanner should be able to use the [forEach](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html#forEach-java.util.function.Consumer-) method introduced in Java 1.8 better than the way it works now.  For example, since Java 1.8 I can use the forEach to iterate over a Map nicely like so:
```
Map<Key,Value> myMap = new HashMap<>();
      myMap.forEach((k,v) -> {
        Text cf = k.getColumnFamily();
        int size = v.getSize();
      });
```
But I can't do that with the Accumulo Scanner, the best I can do is:
```
for (Entry<Key,Value> entry : scanner) {
        if (entry.getKey().getColumnFamily().equals(CurrentLocationColumnFamily.NAME)) {
          assigned.put(entry.getKey(), entry.getValue());
        } else if (entry.getKey().getColumnFamily().equals(FutureLocationColumnFamily.NAME)) {
          future.put(entry.getKey(), entry.getValue());
        }
      }
```
I am not sure if it is possible with our API but it would be nice, if that code could look like this:
```
scanner.forEach((k,v) -> {
        if (k.getColumnFamily().equals(CurrentLocationColumnFamily.NAME)) {
          assigned.put(k, v);
        } else if (k.getColumnFamily().equals(FutureLocationColumnFamily.NAME)) {
          future.put(k, v);
        }
      }
```

**Comment by ctubbsii** [comment]
In ScannerBase, something like the following should work fine:
```java
    default void forEach​(BiConsumer<? super Key,​? super Value> keyValueConsumer) {
      for (Entry<Key, Value> entry : this) {
        keyValueConsumer.accept(entry.getKey(), entry.getValue());
      }
    } 
```

**Comment by keith-turner** [comment]
Could also consider stream support.  This would give forEach and more.

https://issues.apache.org/jira/browse/ACCUMULO-4562

**Comment by ctubbsii** [comment]
> Could also consider stream support. This would give forEach and more.
> 
> https://issues.apache.org/jira/browse/ACCUMULO-4562

I was thinking about that also. However, a `Stream` would only give us a stream of `Entry<Key, Value>`, and a `forEach` for that wouldn't be as useful as one with a `BiConsumer`, like the `Map` interface provides. It might be nice to have both eventually. However, this can be done independently without worrying about all the messiness that comes with decisions about streams (like what to do with `.stream().parallel()`).

**Comment by keith-turner** [comment]
>  However, a Stream would only give us a stream of Entry<Key, Value>, and a forEach for that wouldn't be as useful as one with a BiConsumer

Good point. BiConsumer is really nice and stream of Entry is a bit cumbersome.
