### ISSUE TITLE
The `listcompactions` command error is not helpful

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1760]
One improvement for the `listcompactions` command could be to provide a tserver parameter and only list the compactions on that tserver.

**Comment by keith-turner** [comment]
I was looking at the code after seeing this issue and opened #1764

**Comment by milleruntime** [comment]
> I was looking at the code after seeing this issue and opened #1764

Thanks, I was originally thinking this command was slow because of that impl.

**Comment by DomGarguilo** [comment]
Was looking into this issue and was wondering if what you are looking for differs from the `tserverOption` in [ListCompactionsCommand.java](https://github.com/apache/accumulo/blob/ca58658cce43d4758fe3b0dfcc0653cb11791850/shell/src/main/java/org/apache/accumulo/shell/commands/ListCompactionsCommand.java#L87)? From the description, it seems as though this option allows for a tserver to be passed as an argument to display the compactions of only that tserver.

**Comment by ctubbsii** [comment]
@DomGarguilo I think you're right. This already exists. @milleruntime can you double-check to make sure we're not missing something here? Thanks.

**Comment by milleruntime** [comment]
@DomGarguilo you a right!  I think @ctubbsii 's improvement in #1783 made this no longer an issue, since the main problem was with how we were getting the information.

I did notice that the error printed when the command does not find the tserver is not helpful:
<pre>
root@uno> listcompactions -ts ip-10-113-12-25
2020-12-03T08:53:52,805 [Shell.audit] INFO : root@uno> listcompactions -ts ip-10-113-12-25
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
ip-10-113-12-25 ERROR null
</pre>

I changed the title of this ticket so we can at least improve the error that gets printed.

**Comment by DomGarguilo** [comment]
@Manno15 and I were looking into this and found where the error is coming from. It appears that the error is an `IllegalStateException` which is being [caught here](https://github.com/apache/accumulo/blob/391cfbff3a29f735fb80ddd0695f50b06dd72f28/shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java#L88) with `Exception e` while trying to retrieve the active compactions for a non-existant tserver. The `null` is coming from the `e.getMessage()` which is not helpful. Not quite sure how to proceed from here. Should this unhelpful message be replaced by information detailing why we think this error is being thrown (specified tserver does not exist)?

**Comment by milleruntime** [comment]
> @Manno15 and I were looking into this and found where the error is coming from. It appears that the error is an `IllegalStateException` which is being [caught here](https://github.com/apache/accumulo/blob/391cfbff3a29f735fb80ddd0695f50b06dd72f28/shell/src/main/java/org/apache/accumulo/shell/commands/ActiveCompactionHelper.java#L88) with `Exception e` while trying to retrieve the active compactions for a non-existant tserver. The `null` is coming from the `e.getMessage()` which is not helpful. Not quite sure how to proceed from here. Should this unhelpful message be replaced by information detailing why we think this error is being thrown (specified tserver does not exist)?

It might be better to let the exception be thrown all the way up to the shell and just catch the IllegalStateException.  You could print a helpful message for the Exception with the empty message and let everything else go up to Shell.  The execute method throws Exception. I am not sure this is possible with the stream though, so perhaps that's why we are hiding the exceptions in the List of compaction strings.

**Comment by ctubbsii** [comment]
I'm not sure we should let it be thrown all the way up to the shell. That could be confusing, because of the way this code gathers up all the responses and orders them. The error may be harder to debug. That said, we could definitely format this message better. For one, it would be nice if the whole stack trace was included. We could use something like https://stackoverflow.com/a/1760673 and use `e.printStackTrace(ps)` to get the full stack trace as part of the message, rather than just getting `e.getMessage()`, which isn't very helpful. At the very least, doing this would help us track down where the message is occurring, so we may be able to emit a better exception or something wherever the IllegalStateException is originating today.

**Comment by DomGarguilo** [comment]
I added the stack trace to the message which now reads:
<pre>root@uno> listcompactions -ts nonExistantTserver
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
ERROR: null. The specified tServer, 'nonExistantTserver', was not found.
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at org.apache.accumulo.core.util.HostAndPort.getPort(HostAndPort.java:108)
	at org.apache.accumulo.core.rpc.TTimeoutTransport.create(TTimeoutTransport.java:67)
	at org.apache.accumulo.core.rpc.ThriftUtil.createClientTransport(ThriftUtil.java:373)
	at org.apache.accumulo.core.clientImpl.ThriftTransportPool.createNewTransport(ThriftTransportPool.java:737)
	at org.apache.accumulo.core.clientImpl.ThriftTransportPool.getTransport(ThriftTransportPool.java:676)
	at org.apache.accumulo.core.rpc.ThriftUtil.getClient(ThriftUtil.java:131)
	at org.apache.accumulo.core.rpc.ThriftUtil.getTServerClient(ThriftUtil.java:178)
	at org.apache.accumulo.core.clientImpl.InstanceOperationsImpl.getActiveCompactions(InstanceOperationsImpl.java:176)
	at org.apache.accumulo.shell.commands.ActiveCompactionHelper.activeCompactionsForServer(ActiveCompactionHelper.java:88)
	at org.apache.accumulo.shell.commands.ActiveCompactionHelper.lambda$stream$1(ActiveCompactionHelper.java:119)
-------------------------- hit any key to continue or 'q' to quit --------------------------
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37)
	at java.base/java.lang.Thread.run(Thread.java:834)</pre>
Not sure if anything else should be added to the message or if this formatting is okay.

**Comment by ctubbsii** [comment]
> I added the stack trace to the message which now reads:
> 
> root@uno> listcompactions -ts nonExistantTserver
>  TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
> ERROR: null. The specified tServer, 'nonExistantTserver', was not found.
> java.lang.IllegalStateException
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
> 	at org.apache.accumulo.core.util.HostAndPort.getPort(HostAndPort.java:108)
> 	at org.apache.accumulo.core.rpc.TTimeoutTransport.create(TTimeoutTransport.java:67)
> 	at org.apache.accumulo.core.rpc.ThriftUtil.createClientTransport(ThriftUtil.java:373)
> 	at org.apache.accumulo.core.clientImpl.ThriftTransportPool.createNewTransport(ThriftTransportPool.java:737)
> 	at org.apache.accumulo.core.clientImpl.ThriftTransportPool.getTransport(ThriftTransportPool.java:676)
> 	at org.apache.accumulo.core.rpc.ThriftUtil.getClient(ThriftUtil.java:131)
> 	at org.apache.accumulo.core.rpc.ThriftUtil.getTServerClient(ThriftUtil.java:178)
> 	at org.apache.accumulo.core.clientImpl.InstanceOperationsImpl.getActiveCompactions(InstanceOperationsImpl.java:176)
> 	at org.apache.accumulo.shell.commands.ActiveCompactionHelper.activeCompactionsForServer(ActiveCompactionHelper.java:88)
> 	at org.apache.accumulo.shell.commands.ActiveCompactionHelper.lambda$stream$1(ActiveCompactionHelper.java:119)
> -------------------------- hit any key to continue or 'q' to quit --------------------------
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Not sure if anything else should be added to the message or if this formatting is okay.

This stack trace implies that the error we're seeing in this example is that `HostAndPort.java`'s `getPort` method should use the version of `checkState` that allows us to provide a more meaningful message, such as `the address does not include a port`.

Seeing the stack trace is useful for finding out where we can improve the messages, such as that one, but I'm not sure we want to keep the full stack trace here once we've improved the messages. Maybe we can log the stack trace as a warning, but otherwise keep the regular listing with just with the message from the exception.

**Comment by DomGarguilo** [comment]
Would something like this work better?
<pre>
root@uno> listcompactions -ts myTserver
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
ERROR java.lang.IllegalStateException: null. No port was defined for given address: myTserver
</pre>
The error message "null" is still printed, but the error name and a description of what caused the error was added while the stack trace is removed.

**Comment by ctubbsii** [comment]
@DomGarguilo I think if you use `checkState(boolean expression, String errorMessageTemplate)` version of `checkState` in `HostAndPort.getPort`, then you get the message instead of the `null`, at least in this case. We'd still want to check the output if you pass in something that has a port, but is still an invalid server.

**Comment by DomGarguilo** [comment]
I ran some tests to see the rest of the error messages and it seems as though the only unhelpful message is when a tserver address (valid or unvalid) is passed without a port. The combinations I tested are: (valid and invalid tserver address) in conjuntion with: (no port passed, valid port passed and invalid port passed). I will list the results from my tests below.

**Valid tserver address with valid port (control)**
<pre>
root@uno> listcompactions -ts thor:9997
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
            thor:9997 |     477ms |  FULL | SYSTEM |     0 |     0 | img_thor_143943_1607455627757 | 2;d800;d700                              |     4 |        /2/t-000000l/A000010g.rf_tmp |        [] | {}
...
</pre>

**Any terver address(valid and invalid) with no port passed (error message of interest)**
<pre>
root@uno> listcompactions -ts thor
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
thor ERROR null
</pre>
**Invalid tserver address with invalid port**
<pre>
root@uno> listcompactions -ts NotThor:9898
2020-12-08T14:31:35,262 [rpc.ThriftUtil] WARN : Failed to open transport to NotThor:9898
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
NotThor:9898 ERROR org.apache.thrift.transport.TTransportException: java.net.UnknownHostException
</pre>
**Valid tserver address with invalid port**
<pre>
root@uno> listcompactions -ts thor:9898
2020-12-08T14:33:21,232 [rpc.ThriftUtil] WARN : Failed to open transport to thor:9898
 TABLET SERVER        | AGE       | TYPE  | REASON | READ  | WROTE | TABLE           | TABLET                                   | INPUT | OUTPUT                              | ITERATORS | ITERATOR OPTIONS
thor:9898 ERROR org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
</pre>

**Comment by ctubbsii** [comment]
Based on this, it looks like most possibilities already have meaningful messages. So it may be only the missing port case that needs a better message. I don't think we need to keep the stack traces visible if that case is addressed. However, it may still be useful to log the exception at DEBUG anyway, when it is caught.

**Comment by DomGarguilo** [comment]
> Based on this, it looks like most possibilities already have meaningful messages. So it may be only the missing port case that needs a better message. I don't think we need to keep the stack traces visible if that case is addressed. However, it may still be useful to log the exception at DEBUG anyway, when it is caught.

I was able to change the checkState version to include a more helpful message which now reads: `mytserveraddress ERROR The given address does not include a port`. 
@ctubbsii, by stack trace in this situation, do you mean the exceptions (e.g. `org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused`) included in the message, or were you referring to the full stack trace that I had included (and have since removed) in the initial revision of the print out when no port is passed? If its the prior, I can work to remove those from the error messages if that would be helpful and have the exceptions at DEBUG instead.

**Comment by ctubbsii** [comment]
@DomGarguilo I mean we don't need the full stack trace you had included. If you have already removed it, then we're on the same page. For the exceptions logged at DEBUG, I was thinking we could do that in addition. If you open a PR with your fix for this issue, I can make more specific suggestions in a code review, if necessary.
