### ISSUE TITLE
Flaky test: SimpleTimerTest

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1763]
**Test name(s)**
 - org.apache.accumulo.server.util.time.SimpleTimerTest.testFailure

**Describe the failure observed**
Stacktrace
```java
java.lang.AssertionError
	at org.apache.accumulo.server.util.time.SimpleTimerTest.testFailure(SimpleTimerTest.java:98)
```
Standard Output
```
2020-10-29T03:28:54,071 [time.SimpleTimer] WARN : Asked to create SimpleTimer with thread pool size 2, existing instance has 1
```

**Testing Environment:**

 - ASF Jenkins
 - Commit ea5fa7d1da90da9dfe1128c9561022d310102777
```
Executing Maven:  -B -f /home/jenkins/workspace/Accumulo/main/pom.xml -V -e -ntp clean verify -Dstyle.color=always -Dfailsafe.rerunFailingTestsCount=5
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/asfpackages/maven/apache-maven-3.6.3
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/local/asfpackages/java/jdk-11.0.6
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-74-generic", arch: "amd64", family: "unix"
```

**What have you tried already?**
I re-ran the test and it usually passes.

**Additional context**
There's a good chance this is just a flaky test, because of resource contention on the server. The warning seems related to the `testSingleton` test case, and not the `testFailure` test case that failed.

One thing that might be possible to do to is to wrap the assert statement in a loop, with a delay of `PAD`, until it passes, and then add a JUnit timeout to the test of some reasonable length (5 seconds?). That way, if the pass condition isn't met immediately, the test won't fail, as long as it is met within the timeout period.

**Comment by DomGarguilo** [comment]
I am looking into implementing the fix you suggested and am running into the issue of looping over an assert statement. From my understanding it is not possible to stop the loop based on the condition that an assert statement has passed(or failed for that matter). In other words, the assert statement would be called continuously, within the loop, until an added JUnit timeout occurs. Apparently there are ways to add "rules" to tests which could add the ability to loop until a test passes, but I'm not sure if this is something we want to use ([example](https://stackoverflow.com/questions/8295100/how-to-re-run-failed-junit-tests-immediately?rq=1)).

**Comment by ctubbsii** [comment]
@DomGarguilo Thanks for your interest in working on this issue. I have assigned this ticket to you in response to that interest. You are correct that you can't have the assert statement execute repeatedly in a loop. However, what you can do is do a simple `if` check inside the loop and similar checks inside the loop. If the loop is an infinite loop, the only way the test won't time out is if the conditions are met. For extra measure, you can add additional assert statements after the loop. I don't think we need to resort to any complex JUnit features for this kind of thing.

Here's an example of us doing a similar kind of check in an existing test: https://github.com/apache/accumulo/blob/cccac86255cd2d0ecd49e791162ca5cdf07512b6/server/base/src/test/java/org/apache/accumulo/server/master/balancer/DefaultLoadBalancerTest.java#L198-L209
