### ISSUE TITLE
Analyze DeleteTable FATE for race condition

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1773]
On a cluster with a lot of tables being created and deleted (and bulk imports occurring), it is possible for table delete operations to "get stuck" and not complete.  During periods with a high number of FATE transactions, there may be a race condition or something in the delete FATE operation that is not repeatable.  The work around is to change the Table state in ZK to online and then issue another delete command for the table.  The FATE framework should be able to handle this situation. This ticket is for someone to look closely at the Delete FATE operation, to see if something can be done to prevent deletes from getting stuck.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.10, 2.0

**Comment by dlmarion** [comment]
While working on #1808 I noticed that Fate runs transactions in Threads with no UncaughtExceptionHandler. I fixed this in #1818 . It's possible this could be contributing to this issue.

**Comment by milleruntime** [comment]
> While working on #1808 I noticed that Fate runs transactions in Threads with no UncaughtExceptionHandler. I fixed this in #1818. It's possible this could be contributing to this issue. Did you happen to notice any ERROR log entries starting with `Uncaught exception in FATE runner thread` ?

Unfortunately I did not get a stacktrace for this issue.  @EdColeman did you remember ever seeing this error?

**Comment by EdColeman** [comment]
I do not recall seeing this exception - however, there would generally be a considerable period between when the exception might have been thrown and when it was detected that the table deletion was not progressing.  If the exception was thrown once, then even if it was present, the connection might have not been made between the events. But again, I don't recall this exception being in the master log at any time.

**Comment by milleruntime** [comment]
I wonder if this could be related to a change made in 1.9.3 https://github.com/apache/accumulo/pull/727

**Comment by ctubbsii** [comment]
@milleruntime Given the possibility that this was already fixed, and presumably, you haven't been able to reproduce it, should this be closed as "Cannot reproduce"? We can always reopen if it is observed again and more information is available.

**Comment by milleruntime** [comment]
I don't know that it was fixed (or that there is a problem).  The issue that I was referring to in #727 was #587 and had to do with metadata pollution.  I will try and talk to the admins reporting it to see if they are still seeing the problem in their deployment of 1.9.3.  It could be a lack of insight as to what is going on in the cluster since there isn't an easy way to get the state of Tablets.  I may be able to backport #1821 to version 10 so they can use it.

**Comment by milleruntime** [comment]
Since this ticket was mainly for analysis, I will close it as I was unable to find a bug.  I did come up with some ideas for improvements that I opened in #1872
