### ISSUE TITLE
Monitor not reporting killed tserver

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1775]
When a tserver reaches its max hold time and is killed, it is not showing up in the monitor under "Dead Tablet servers".  The error message that is reported is coming form the Master here: https://github.com/apache/accumulo/blob/80a5d253249359f8863ad1b54126852e958820d4/server/manager/src/main/java/org/apache/accumulo/master/Master.java#L854

This was reported in 1.9.3 but I wanted to open a ticket to test if it is still occurring in the new monitor.

**Comment by karthick-rn** [comment]
@milleruntime Hi, I tested this scenario in Accumulo 2.0.1-rc1 by changing `tserver.hold.time.max` from `5m` (default) to `5s`, after few minutes of running cingest the below warning appeared in the monitor logs but the dead tablet server was not showing up in the tablet server status page & also the dead tablet server count remains '0' in the overview page. Therefore, the issue still occurs in the new monitor.
> 2020-12-24 14:55:32,420 [master.Master] WARN : Tablet server kn-host-4:9997[10000071d0d0005] exceeded maximum hold time: attempting to kill it

**Comment by milleruntime** [comment]
@karthick-rn I would be curious to know if you are still seeing this error on a more recent build of Accumulo snapshot.  I have been running CI on an Uno cluster with modified hold time but have been unable to reproduce this failure.  The commit I built off of was bbd87a6693fc5cdbbe947b0821a4f05a18cf905b

**Comment by milleruntime** [comment]
Ah whoops... its probably the part `tserverStatus.size() > 1` which I am unable to pass using Uno with 1 tserver:
https://github.com/apache/accumulo/blob/80a5d253249359f8863ad1b54126852e958820d4/server/manager/src/main/java/org/apache/accumulo/master/Master.java#L853

**Comment by karthick-rn** [comment]
> @karthick-rn I would be curious to know if you are still seeing this error on a more recent build of Accumulo snapshot. I have been running CI on an Uno cluster with modified hold time but have been unable to reproduce this failure. The commit I built off of was [bbd87a6](https://github.com/apache/accumulo/commit/bbd87a6693fc5cdbbe947b0821a4f05a18cf905b)

@milleruntime I can test this on the latest build and let you know. In the past, I was able to repro this issue with '1' tserver. Do you want me to do the same or try with '2' tservers?

**Comment by milleruntime** [comment]
I was finally able to reproduce this error.  I ran CI on Uno with 2 tservers with these properties:
<pre>
tserver.hold.time.max=500ms
tserver.memory.maps.max=5%
</pre>

**Comment by ctubbsii** [comment]
This was backported to 1.10 in 48e483b6fab9006a224b4630dfdc3449110cb9a0
