### ISSUE TITLE
Accumulo 1.9.3 RegexExample job failed because of Exception  org/apache/commons/configuration/CompositeConfiguration

### ISSUE THREAD

**Issue by metsy** [apache/accumulo#1836]
I tried to run this example 
`bin/tool.sh lib/accumulo-examples-simple.jar org.apache.accumulo.examples.simple.mapreduce.RegexExample -u root -p 1 -i project -t rya_po --rowRegex 'Prot.*' --output output`

but I got this Exception 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/CompositeConfiguration

I use this versions:
accumulo-1.9.3, hadoop-3.1.2, zookeeper-3.4.14

and I added the Hadoop class paths to accumulo-site.xml

any suggestions please?
I've to use those versions because I'm using Apache Rya with'em

**Comment by ctubbsii** [comment]
Hi @metsy . Based on the exception, it seems you are missing commons-configuration on your class path. Without a full stack trace, it will be hard to determine which specific part of our code was looking for commons-configuration. However, if you put that on your class path, it should solve your problem. The tool.sh script was written to help add some things to your local class path, as well as the class path for the submitted MapReduce job. Perhaps it isn't picking up your commons-configuration jar? Or perhaps there's a conflict with the version that ships with Hadoop or ZooKeeper?

It looks like Accumulo 1.9.3 was built with commons-configuration 1.6, based on what we had in our pom.xml, but please note that 1.9.3 has been superseded by 1.10.0, and is no longer supported.

I hope this response helps answer your question. If you have any further questions, please consider subscribing to our user list and asking on that forum, as this issue tracker is primarily for tracking issues during development. Other users may have experienced similar issues, and solved them already, and may be able to help you further on the user list. See https://accumulo.apache.org/contact-us/ for more information about subscribing to our mailing lists.

**Comment by metsy** [comment]
Thanks @ctubbsii
