### ISSUE TITLE
HostRegexTableBalancer property confusion

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#1838]
The HostRegexTableBalancer.parseConfiguration() will pull the related properties from all of the tables configurations and merges them together.  The table name is actually pulled from the table property.  The result is that you can override the host regex property for one table in a different table's configuration.  This was particularly bad for one installation where we changed the property at the system level and then could not understand why it was not getting picked up even after rebooting the master process.  This has been there since the inception of this feature.

So to reproduce this, startup an accumulo instance with multiple tservers and multiple tables.  Define the host regex for one table in a separate tables configuration.  Observe that the tablets balance appropriately.  Then change that same property at the system level or in the correct table configuration and depending on the order of the table ids in the table id map, the system may or may not actually react to the change.

I believe that the table name for the regex should be derived from the property and then ONLY used if being pulled from that table's configuration.

**Comment by ivakegg** [comment]
This is a dup of the previous ticket.  Sorry.

**Comment by ctubbsii** [comment]
Duplicate of #1837
