### ISSUE TITLE
Update column name in the monitor UI

### ISSUE THREAD

**Issue by karthick-rn** [apache/accumulo#1848]
Following the conversation with @ctubbsii on slack, I'm creating this improvement work.

~~**Description:** The overview page in Accumulo monitor displays the total no of tablet servers configured as highlighted in the below screenshot. In the event of a tablet server failure, this count still displays the total tablet servers. If we can change this behaviour to display the no of tablet servers online during the time instead of the total, it would be more appropriate. Also, this change is only required in the current main branch, as Accumulo 1.x already behaves in this way.~~

**Updated description:**
Instead of changing the behaviour, we agreed to change the column name from "Tablet Servers" to "Total Known Tablet Servers"

![image](https://user-images.githubusercontent.com/7976585/103038473-6fd2d180-4566-11eb-9b9e-2b48839193e6.png)

**Comment by karthick-rn** [comment]
When Accumulo master kills the tserver due to exceeding maximum hold time, in which case the highlighted field displays the active no. of tablet server and not the total. Found this when testing #1775. I think we need to make this behaviour consistent across  different tserver failures, currently when Agitator kills the tserver it displays the total and when master kills the tserver it displays the active no. of tservers.

**Comment by ctubbsii** [comment]
Rather than change the behavior, would it suffice to update the column header to clarify by changing "Tablet Servers" column to something like "Total Known Tablet Servers" or similar?

**Comment by karthick-rn** [comment]
@ctubbsii I agree, changing the header name makes sense than changing the behaviour. I'd change the name to "Total Known Tablet Servers" as you suggested. Thanks!

**Comment by karthick-rn** [comment]
PR: https://github.com/apache/accumulo/pull/1859
