### ISSUE TITLE
Azure datalake integration

### ISSUE THREAD

**Issue by Viv1986** [apache/accumulo#1849]
Hello,

found article for accumulo 2.0 with azure datalake setup
https://accumulo.apache.org/blog/2019/10/15/accumulo-adlsgen2-notes.html

but when I do config same as article I get 
Caused by: Configuration property xxx.dfs.core.windows.net not found

I set at accumulo.properties
instance.volumes=hdfs://first.xxx.cloudapp.net:8020/apps/accumulo/data,abfss://accumulo2@xxx.dfs.core.windows.net/accumulo

Tried accumulo 2.0 and 2.0.1, result are same, HELP!

**Comment by ctubbsii** [comment]
I believe this was closed in favor of #1850
