### ISSUE TITLE
Monitor should use long instead of integer for "Scan (Entries/s)" graph

### ISSUE THREAD

**Issue by brianloss** [apache/accumulo#1858]
When running Accumulo 1.10 on a large cluster with a very high scan rate, the "Scan (Entries/s)" graph flatlined at 2,147,483,647. Looking at the [Monitor code](https://github.com/apache/accumulo/blob/6bf3f406481a392c5bcffc15d44ccdfd52c2b577/server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java#L157), it appears that the queryRateOverTime and scanRateOverTime lists use an Integer instead of a Long to store the rates. Changing to a Long should solve the problem.

**Comment by ctubbsii** [comment]
This issue was fixed in 1.10 by #1860 . However, it is not yet merged to the main branch for 2.1.0. I don't know if 2.1 is similarly affected, but I assume so. So, this issue should stay open until it is fixed there (or determined to be unnecessary there).
