### ISSUE TITLE
Create new "jshell" convenience entry point

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1870]
**Is your feature request related to a problem? Please describe.**
The new `jshell` command in Java 9 and later is super convenient for quick tasks with Accumulo. However, it is frustrating that one must first set up the `CLASSPATH`, and then import a bunch of Accumulo API classes in order to started using it.

**Describe the solution you'd like**
I would like to see the ability to easily start `jshell`, so that it starts up in a state that is ready-to-use for Accumulo, with the `CLASSPATH` already configured and the public API (or at least, a useful chunk of it) already imported. That way, one can get started right away with `var client = Accumulo.newClient(). ... .build()`

Enough classes should be imported so that most, if not all, of the public API reachable via a client can be used without adding additional imports (in addition to common Java imports).

For example, if we had an `contrib/accumulo-public-api-imports.jsh` file containing the relevant imports, a user could simply run:

```bash
CLASSPATH=$(bin/accumulo classpath) jshell contrib/accumulo-public-api-imports.jsh
```
or (to override the default imports with our own, instead of appending)
```bash
CLASSPATH=$(bin/accumulo classpath) jshell --startup contrib/accumulo-public-api-imports.jsh
```

The main task for this issue would be to create the `.jsh` file that could be used for such a thing, so that it contains the relevant import statements for [our public API](https://accumulo.apache.org/api/).

While composing this `.jsh` file, it would be helpful if we could automate the process of keeping it up-to-date during a build, so that if we add/remove sub-packages from our public API, this file will stay up-to-date with all the necessary imports.

**Describe alternatives you've considered**
A slight alternative to simply constructing the `.jsh` file in the `contrib/` directory for users to manually use is to bake the `CLASSPATH` setup and `jshell` execution with the appropriate configuration file argument directly into `bin/accumulo` as either `bin/accumulo jshell` or maybe `bin/accumulo jsh`. Doing this, it should use the `CLASSPATH` from `conf/accumulo-env.sh` (just like other processes launched with `bin/accumulo`) and the initial startup file from the `conf/` directory as well (`conf/jshell-init.jsh` or similar?). It should also take any additional arguments the user puts on the command line and pass them along to `jshell`.

**Additional context**
There is a conflict with trying to import Scanner from Accumulo's public API, if `java.util.Scanner` is already imported, which it appears to be by default:

```java
jshell> /list -all

  s1 : import java.io.*;
  s2 : import java.math.*;
  s3 : import java.net.*;
  s4 : import java.nio.file.*;
  s5 : import java.util.*;
  s6 : import java.util.concurrent.*;
  s7 : import java.util.function.*;
  s8 : import java.util.prefs.*;
  s9 : import java.util.regex.*;
 s10 : import java.util.stream.*;
```

**Comment by ctubbsii** [comment]
@slackwinner had expressed interest in working on this.

**Comment by slackwinner** [comment]
@ctubbsii I have integrated the Accumulo jshell command into "bin/accumulo". In addition, I am currently working on automating the import process for the Accumulo public API into jshell. Will push over a working version of the modified files soon.
