### ISSUE TITLE
Stop waiting during Table Delete CleanUp

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1872]
The final step to the FATE TableDelete operation is CleanUp and can take a long time in certain situations.  This step will wait for all Tablets to be `TabletState.UNASSIGNED` until it can complete the delete operation.  It is necessary to wait for Accumulo to unassign all the tablets in order to the metadata to be cleaned up properly.  I think there is a more efficient way that the Table Delete operation can be completed.  The master is performing work on a Table which already has been deleted and since the delete action overrides all other behavior, we should prevent processes from acting on a deleted table.  If the Table Delete operation was able to mark the table deleted in the metadata, the master would see this during its assignment check and immediately drop the table.  Allowing the Table Delete to finish without having to wait for anything would also free up FATE resources.

**Comment by milleruntime** [comment]
The motivation for this enhancement came from the work around for #1773, when Deletes are taking too long on a cluster with lots of activity.  The work around is to offline and then online the table, which will allow the delete to finish. I am not sure exactly why this works but my guess was that it short circuits the delete steps, bypassing the typical transition path tablets take when deleted.

**Comment by keith-turner** [comment]
I wonder if delete table unnecessarily waits on tablets that are running compactions.  There are mechanisms in the code to cancel a running compactions, can't remember when its called though.

**Comment by milleruntime** [comment]
Compactions being the big hang up seems likely because the offline/online FATE code is very similar to the DeleteTable step, which both call `TableManager.transitionTableState()`, changing the state in Zookeeper.

**Comment by keith-turner** [comment]
I looked around in the code, in 2.1.0-SNAP there is an attempt to cancel any running compactions. 

https://github.com/apache/accumulo/blob/0bfa4251930dc763ffabd9c2ece4b45f36ae6bc9/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1197

In 1.10 there is also some code w/ the intent to cancel compactions.

https://github.com/apache/accumulo/blob/018756754ff0f289a8b30f846af8b7092270318d/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1365

Wonder if these are working as intended.

**Comment by milleruntime** [comment]
Looking at where `Tablet.close()` is happening in `UnloadTabletHandler`, there is a chunk of code that could wait, preventing the close from being called:
https://github.com/apache/accumulo/blob/bbd87a6693fc5cdbbe947b0821a4f05a18cf905b/server/tserver/src/main/java/org/apache/accumulo/tserver/UnloadTabletHandler.java#L66-L72

**Comment by milleruntime** [comment]
Would it be possible to have deadlock on `server.openingTablets` if Accumulo is trying to load and unload a tablet at the same time?

**Comment by keith-turner** [comment]
> Would it be possible to have deadlock on server.openingTablets if Accumulo is trying to load and unload a tablet at the same time?

Maybe, if not deadlock it could get stuck there a long time.   Thinking maybe the method could just return if the tablet is currently opening instead of waiting.   Another unload message will be sent later.

One approach to this issue is to try to add enough debugging info so that if the issue does happen again, can see where things are gummed up. For example could possibly add some logging to the unload handler.

**Comment by milleruntime** [comment]
I added a log info statement before waiting in the UnloadTabletHandler #1881

**Comment by milleruntime** [comment]
I did some testing with Uno running MultiTable RW and have yet to see the log statement I added in #1881.  I was able to see the delete FATE `CleanUp` waiting briefly and it was usually for compactions. So I think your theory of waiting for compactions is more likely.

From the master log:
<pre>
2021-01-25 10:16:20,209 [tableOps.CleanUp] DEBUG: Still waiting for table(1k) to be deleted; Target tablet state: UNASSIGNED, Current tablet state: HOSTED, locationState: 1k<;9@(null,localhost:11000[1000072ccc80003],localhost:11000[1000072ccc80003])
</pre>
From tserver log:
<pre>
2021-01-25 10:16:19,508 [tablet.MinorCompactor] DEBUG: Begin minor compaction hdfs://localhost:8020/accumulo/tables/1k/default_tablet/F0000265.rf_tmp 1k<;9
2021-01-25 10:16:20,202 [tablet.Tablet] DEBUG: initiateClose(saveState=false queueMinC=false disableWrites=false) 1k<;9
2021-01-25 10:16:20,202 [tablet.Tablet] DEBUG: completeClose(saveState=false completeClose=true) 1k<;9
2021-01-25 10:16:21,375 [tablet.Compactor] DEBUG: Compaction 1k<;9 14,027 read | 14,027 written |  7,889 entries/sec |  1.778 secs |   47,299,377 bytes | 26602574.241 byte/sec
2021-01-25 10:16:21,377 [tablet.Tablet] DEBUG: Logs for memory compacted: 1k<;9 localhost:11000/hdfs://localhost:8020/accumulo/wal/localhost+11000/bbbd0052-911d-4204-990b-ddfef97738bf
2021-01-25 10:16:21,377 [tablet.Tablet] DEBUG: Logs to be destroyed: 1k<;9 localhost:11000/hdfs://localhost:8020/accumulo/wal/localhost+11000/bbbd0052-911d-4204-990b-ddfef97738bf
2021-01-25 10:16:21,386 [tablet.DatafileManager] TABLET_HIST: 1k<;9 MinC [memory] -> hdfs://localhost:8020/accumulo/tables/1k/default_tablet/F0000265.rf
2021-01-25 10:16:21,386 [tablet.DatafileManager] DEBUG: MinC finish lock 0.00 secs 1k<;9
2021-01-25 10:16:21,436 [tablet.Tablet] TABLET_HIST: 1k<;9 closed
2021-01-25 10:16:21,437 [tserver.TabletServer] DEBUG: Unassigning 1k<;9@(null,localhost:11000[1000072ccc80003],null)
2021-01-25 10:16:21,441 [tserver.TabletServer] INFO : unloaded 1k<;9
</pre>

While looking at this code path, I also found another point where it could be waiting and that was for active scans during the `Tablet.close()`. 
https://github.com/apache/accumulo/blob/9c957ab55f28f10dde1321eb613a9ec3e2fa5322/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1439-L1446

**Comment by milleruntime** [comment]
Instead of messing with the current delete work flow, another idea would be to enhance the delete command for the client.  We could have an option for the client wait for delete to complete.  We could then provide information as to what it is waiting on (scans, compactions, etc). While this wouldn't change any behavior in Accumulo, it would provide feedback directly to the client and allow them to make better decisions.

**Comment by EdColeman** [comment]
When you say client, are you thinking the shell?  How would you handle this for automated clients? Feedback could be an intermediate step, but I think the desired behavior in almost all cases would be to terminate any outstanding operations and delete as quickly as possible.  

Is there any value in waiting for a compaction to complete if the next thing to happen is that the table / file is deleted?

**Comment by milleruntime** [comment]
> When you say client, are you thinking the shell? How would you handle this for automated clients? Feedback could be an intermediate step, but I think the desired behavior in almost all cases would be to terminate any outstanding operations and delete as quickly as possible.

I was thinking of adding to the API, which could definitely be added to the Shell as a new command. We could add another API method (similar to how `flush` evolved) to evolve the current delete method.

In TableOperations.java:
`  @Deprecated  
void delete(String tableName)`
`@since 2.1
void delete(String tableName, boolean wait)`

> Is there any value in waiting for a compaction to complete if the next thing to happen is that the table / file is deleted?

No that I know of but perhaps Keith may know of a reason.  There are checks in place for the compaction to cancel (see Keith's comments above) but I don't think they are foolproof since it depends on where along in the compaction process the delete occurs.

**Comment by milleruntime** [comment]
> I think the desired behavior in almost all cases would be to terminate any outstanding operations and delete as quickly as possible.

I agree but I think we are seeing that this isn't always realistic since a highly active cluster can become gummed up with the way Accumulo is designed to cautiously delete tables and clean up afterwards.

**Comment by milleruntime** [comment]
Created one potential improvement for this here: https://github.com/apache/accumulo/pull/1887

**Comment by milleruntime** [comment]
Another area I want to look into is here in Tablet.completeClose():
https://github.com/apache/accumulo/blob/fd001c9ec3a55aa6427667c4143f1d6772739c86/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1260

It looks like every bulk import call to a tablet will increase `writesInProgress`. So if a tablet has a lot of Bulk Imports or one large one, it could cause the close to wait there for a while.

**Comment by EdColeman** [comment]
Is it feasible to cancel bulk imports if a table is being deleted?  Could save a lot of work / waiting for a bulk import to complete and then just turn around and throw it away.  If you wonder how this could happen?  If someone had asynchronous processes that handled bulk imports and a second process that scheduled deletions - unless those processes are communicating it seems feasible that if a table had a bulk import that was taking a long time and for whatever reason that table became obsoleted, then the "deleter" could issue the delete while that bulk import was still being performed.  While it's not unreasonable to expect users to have better coordination of their processing - have Accumulo optimize efforts when feasible would not be a bad thing in this case.

**Comment by milleruntime** [comment]
> Is it feasible to cancel bulk imports if a table is being deleted? Could save a lot of work / waiting for a bulk import to complete and then just turn around and throw it away. If you wonder how this could happen? If someone had asynchronous processes that handled bulk imports and a second process that scheduled deletions - unless those processes are communicating it seems feasible that if a table had a bulk import that was taking a long time and for whatever reason that table became obsoleted, then the "deleter" could issue the delete while that bulk import was still being performed. While it's not unreasonable to expect users to have better coordination of their processing - have Accumulo optimize efforts when feasible would not be a bad thing in this case.

We already have the `BulkImportCacheCleaner` so it may not be bad to modify it to handle cancelled bulk imports or look for a deleted flag.

**Comment by milleruntime** [comment]
> In 1.10 there is also some code w/ the intent to cancel compactions.
> 
> https://github.com/apache/accumulo/blob/018756754ff0f289a8b30f846af8b7092270318d/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1365
> 
> Wonder if these are working as intended.

I was able to see a compaction cancelled while testing 1.10. This exception was thrown in the compactor:
https://github.com/apache/accumulo/blob/0a9837f3f8395d89c5cd7bab7805c4aae28919be/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java#L406
```
master.log: 2021-02-05 10:25:34,235 [tables.TableManager] DEBUG: Transitioning state for table e from ONLINE to DELETING
tserver_2.debug.log:2021-02-05 10:25:33,463 [tablet.Tablet] DEBUG: Starting MajC e<;9 (NORMAL) [hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000ms.rf, hdfs://localhost:8020/accumulo/tables/e/default_tablet/A00000g5.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mr.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mv.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mq.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mw.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mt.rf, hdfs://localhost:8020/accumulo/tables/e/b-00000mp/I00000mu.rf] --> hdfs://localhost:8020/accumulo/tables/e/default_tablet/A00000g6.rf_tmp  []
tserver_2.debug.log:2021-02-05 10:25:34,402 [tablet.Tablet] DEBUG: initiateClose(saveState=false queueMinC=false disableWrites=false) e<;9
tserver_2.debug.log:2021-02-05 10:25:34,828 [tablet.Tablet] DEBUG: Major compaction canceled, extent = e<;9
tserver_2.debug.log:2021-02-05 10:25:34,828 [tablet.Tablet] DEBUG: completeClose(saveState=false completeClose=true) e<;9
tserver_2.debug.log:2021-02-05 10:25:34,828 [tablet.Tablet] TABLET_HIST: e<;9 closed
tserver_2.debug.log:2021-02-05 10:25:34,828 [tserver.TabletServer] DEBUG: Unassigning e<;9@(null,localhost:11000[100007e21d80002],null)
tserver_2.debug.log:2021-02-05 10:25:34,841 [tserver.TabletServer] INFO : unloaded e<;9
```

**Comment by milleruntime** [comment]
I merged another related improvement here: https://github.com/apache/accumulo/pull/1931

**Comment by milleruntime** [comment]
With the various improvements I made for deletes, I am going to close this issue. The only other path I didn't really explore was for cancelling Bulk imports during a delete. I can't seem to create a long enough running bulk import locally using the new bulk import so it may no longer be an issue. And now that we have the new bulk import, I don't want to waste time testing the old one since it is deprecated.
