### ISSUE TITLE
License and notice review for 2.x

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#1898]
I noticed that the LICENSE and NOTICE need to be updated in the main branch. (I can't recall now if it was just the L&N for the binary tarball, or if the source tarball L&N also needed updates.) We should address this before the next 2.x release.

**Comment by ctubbsii** [comment]
@billierinaldi Do you happen to remember what was wrong with the one you saw?

**Comment by billierinaldi** [comment]
I started looking into it, but have not completed an exhaustive analysis. It looked like DataTables and Bootstrap were added to the monitor source and do not appear in the source tarball license file. In the binary tarball, I started looking at the included jars and it seemed like there were a number of them that might require inclusion in the license or notice file.

**Comment by billierinaldi** [comment]
Thanks @ctubbsii!
