### ISSUE TITLE
Better document Upgrader9to10

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1922]
It would be good to better document `Upgrader9to10` as it has grown to include lots of changes in the latest version. The javadoc at the top only contains a single line "Handles upgrading from 2.0 to 2.1". With all the changes now included, I think we could put references to github tickets in the javadoc, that will tie certain parts of the upgrade code to its particular code change. If something goes wrong with the upgrade code it may be difficult to track down the change tied to that code.

**Comment by milleruntime** [comment]
@brianloss while it is still fresh in memory, can you add something to the `Upgrader9to10` javadoc for your recent master to manager renames?

**Comment by ctubbsii** [comment]
I'm not opposed to this idea, but what's wrong with `git log -p **/Upgrader9to10.java`?

**Comment by milleruntime** [comment]
> I'm not opposed to this idea, but what's wrong with `git log -p **/Upgrader9to10.java`?

While that works great for you, the people performing the upgrade have a much better chance of looking at the documentation where the error in the file occurred than they do of taking the extra steps on that file to use git to track the history.
