### ISSUE TITLE
SharedRateLimiterFactory.create() method does not correctly use WeakHashMap

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1924]
**Describe the bug**
While looking at our use of WeakHashMap throughout our code, I observed that the SharedRateLimiterFactory uses a WeakHashMap called `activeLimiters`. However, it uses `activeLimiters.put(name, new SharedRateLImiter(name, ....))`, and the constructor stores a strong reference to `name` as a member variable. Therefore, it is impossible for `activeLimiters` to ever garbage collect and remove references once added.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT (probably others... only looked at this one)

**Comment by DomGarguilo** [comment]
> the constructor stores a strong reference to `name` as a member variable

Which constructor are you referring to?

**Comment by ctubbsii** [comment]
> > the constructor stores a strong reference to `name` as a member variable
> 
> Which constructor are you referring to?

`new SharedRateLImiter`

**Comment by ctubbsii** [comment]
@DomGarguilo The `WeakHashMap` already uses weakly referenced keys. However, the objects in the value are strong references by default. The way to ensure the values in the hashmap don't retain strong references to the keys in the map is to wrap the values themselves in a `WeakReference`. So, instead of a `WeakHashMap<String,SharedRateLimiter>`, you would simply wrap the values and make them `WeakHashMap<String,WeakReference<SharedRateLimiter>>` instead.  See the implementation note in the [`WeakHashMap` javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/WeakHashMap.html) for a similar explanation.
