### ISSUE TITLE
Flaky test: LargestFirstMemoryManagerTest

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1928]
**Test name(s)**
 - org.apache.accumulo.tserver.memory.LargestFirstMemoryManagerTest.test

**Describe the failure observed**
```java
java.lang.AssertionError: expected:<1;g<> but was:<1;f<>
	at org.apache.accumulo.tserver.memory.LargestFirstMemoryManagerTest.test(LargestFirstMemoryManagerTest.java:113)
```

This error occurred on Jenkins while testing an unrelated PR, but when I tried to reproduce it manually, the test passed. It's not clear to me how this could happen, but should be investigated.

**Comment by DomGarguilo** [comment]
@ctubbsii is this different from #1789?

**Comment by ctubbsii** [comment]
> @ctubbsii is this different from #1789?

Looks the same. I will close as duplicate.

**Comment by milleruntime** [comment]
The line numbers in the error on this one match up with the latest revision. The line numbers in the older error in #1789 are out of date due to changes to the file on 12/8/20.
