### ISSUE TITLE
Deprecate ScriptCommand in Accumulo shell

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1949]
The default script engine in Java has changed from rhino, which has been removed, to nashorn, which is now also scheduled for removal. Users may still be able to plug in their own JSR-223 compatible script library, but the utility of this feature in the Accumulo shell is significantly diminished/impaired.

Additionally, much of the use case for having this script command is likely able to be replaced by Java 11's JShell feature, and Java's ability to execute single-file Java programs without a separate compile step. Users can extend either of these options to create their own scripting language REPL, if they wish using their own JSR-223 compatible script library, or just by scripting Java code directly.

As such, the script command in the shell should be deprecated, and removed in a future major release of Accumulo.

References:
* https://github.com/apache/accumulo/pull/1910#issuecomment-786020529
* https://openjdk.java.net/jeps/174
* https://openjdk.java.net/jeps/335
* https://openjdk.java.net/jeps/372
* https://www.jcp.org/en/jsr/detail?id=223

**Comment by ctubbsii** [comment]
Deprecation basically just involves marking it deprecated, adding a log message to warn about deprecation when it's used, and updating documentation/release notes.

**Comment by harjitdotsingh** [comment]
I would like to start working on this. Which files/methods need to be deprecated?

**Comment by ctubbsii** [comment]
@harjitdotsingh I've assigned it to you, based on your interest. The ScriptCommand is the relevant java class. For reference, the DebugCommand is one that is already deprecated, as is the DeleteScanIterCommand. The former models deprecating the class with an annotation and the description for the help documentation in the shell, while the latter models printing a warning message when it is used (I'm not sure why the latter doesn't also deprecate the class itself; it probably should be annotated as deprecated also, but that's a separate issue). Deprecating this command should involve performing both steps... annotation/description update and a warning when used. A separate PR should be made against the draft release notes in the website repository at https://github.com/apache/accumulo-website/blob/main/_posts/release/2020-01-19-accumulo-2.1.0.md for updating the release notes.

**Comment by harjitdotsingh** [comment]
@ctubbsii - I have updated the files. Let me know if there is anything else that needs attention on this PR.

**Comment by ctubbsii** [comment]
@harjitdotsingh Thanks! I will try to take a look tomorrow.
