### ISSUE TITLE
Throw IllegalArgumentException in public API when table names aren't valid

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#1953]
For many public API operations, we accept a table name or namespace name argument. These are often sent to the server as-is, where an exception may be generated and returned to the client because the argument is not in the correct format.

In our API, wherever we accept a table or namespace name as an argument, we should validate it on the client side to see if it even makes sense, and throw an `IllegalArgumentException` with an appropriate message when it doesn't. This would allow for fast failure, and achieve consistent behavior when a table or namespace name doesn't make sense.

Table names (without a namespace, or in the default namespace) and namespace names (except the default namespace, which is an empty string) should match: `^\w{1,1024}$`

A fully-qualified table name is a name that consists of a namespace name, plus a dot separator, and then a table name.

`Constants.java` currently contains constants for the maximum lengths of the namespace and table name components, and the current validation code is somewhat scattered between several different classes. I found existing validation code in `Namespaces.java`, `Tables.java`, `FateServiceHandler.java`, and `TableValidators.java`. There may be more.

(originally: https://issues.apache.org/jira/browse/ACCUMULO-2133)

**Comment by slackwinner** [comment]
@ctubbsii Per our conversation, I would like to be assigned to this task.

**Comment by Akshit6828** [comment]
Hi @EdColeman. I am looking forward to working more on this project. Please let me know if any new contributions would be needed. For my skills and ability, please visit my profile and let me know if can contribute.
I would ❤️  to contribute more.
Thank you 😄

**Comment by ctubbsii** [comment]
This was fixed in #2156 and #1971
