### ISSUE TITLE
Setting a table config using "-t" while in the table context silently fails

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#1977]
**Describe the bug**
Setting a table config property using "-t" while in the table context silently fails.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. In the shell, enter a table context with the command: "table <name>"
2. Try to set a property using "-t"
3. Look for the property to be set

<pre>
root@uno nofoo> config -t nofoo -s table.classpath.context=cx1
root@uno nofoo> config -f classpath
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.classpath.context ............ | 
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
root@uno nofoo> config -s table.classpath.context=cx1
root@uno nofoo> config -f classpath
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                 | VALUE
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.classpath.context ............ | 
system     |    @override ....................... | cx1
-----------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
root@uno nofoo> 
</pre>

**Comment by jmark99** [comment]
I'm not sure this is failing as much as the return from the config -f call is failing to display result properly. If you set the context then then use the -t option along with the -f option it appears to be set.

<pre>
root@uno> createtable foo
root@uno foo> config -t foo -s table.classpath.context=cx1
root@uno foo> config -f classpath -t foo
-----------+----------------------------+-----------------------------------------------------------------
SCOPE      | NAME                       | VALUE
-----------+----------------------------+-----------------------------------------------------------------
default    | table.classpath.context .. | 
table      |    @override ............. | cx1
-----------+----------------------------+-----------------------------------------------------------------
root@uno foo> config -f classpath
-----------+-------------------------------+--------------------------------------------------------------
SCOPE      | NAME                          | VALUE
-----------+-------------------------------+--------------------------------------------------------------
default    | general.classpaths .......... | 
default    | general.dynamic.classpaths .. | 
default    | general.vfs.classpaths ...... | 
default    | table.classpath.context ..... | 
-----------+-------------------------------+--------------------------------------------------------------
root@uno foo> config -f classpath -t foo
-----------+-------------------------------+--------------------------------------------------------------
SCOPE      | NAME                          | VALUE
-----------+-------------------------------+--------------------------------------------------------------
default    | table.classpath.context ..... | 
table      |    @override ................ | cx1
-----------+-------------------------------+--------------------------------------------------------------
</pre>

**Comment by ctubbsii** [comment]
If you're setting it to the same value at the per-table scope that it is set to at the system scope, then the per-table value won't be displayed. That's because the way configs inherit from their parent in the config hierarchy makes it impossible to tell the difference between a table config being set at the table scope or inherited from the system scope. It's possible with some implementation changes to detect this, but there really isn't a reason to, since the display shows `overrides` only, and not merely that something is `set`. For something to be an `override`, it has to actually change the value in some way.

**Comment by milleruntime** [comment]
> I'm not sure this is failing as much as the return from the config -f call is failing to display result properly. If you set the context then then use the -t option along with the -f option it appears to be set.

Ah interesting, thanks. It looks like this isn't a bug as just an oddity of the way Accumulo configuration and the shell commands work.

**Comment by milleruntime** [comment]
On the topic of setting config in the shell... why doesn't this work?
<pre>
root@uno> config -s general.context.class.loader.factory=org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory
2021-03-26T17:12:20,561 [shell.Shell] ERROR: org.apache.accumulo.core.util.BadArgumentException: Property cannot be modified in zookeeper near index 10
config -s general.context.class.loader.factory=org.apache.accumulo.core.classloader.DefaultContextClassLoaderFactory
          ^
</pre>

Looking at the validation code in [Property](https://github.com/apache/accumulo/blob/0781550076f04d12716650fd64881d8b9d041afa/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L1343), only properties that start with "general.custom" can be modified with the config command?

**Comment by ctubbsii** [comment]
> On the topic of setting config in the shell... why doesn't this work?

We are very selective about which properties are configurable in ZooKeeper, because some don't make sense to be read from ZooKeeper after a service has started up, or can cause problems. What you linked in the code is a curated allow list for such properties. The error in the shell reflects the documentation about these properties at https://accumulo.apache.org/docs/2.x/configuration/server-properties that marks them as `zk mutable` (with possible values of `no`, `yes`, and `yes but requires restart of <X service>`). The properties that generate an error in the shell are properties which would be documented as `zk mutable: no`.
