### ISSUE TITLE
Review logic in Compactor.getRunningCompaction() 

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#1987]
It's possible that the DeadCompactionDetector that runs in the Coordinator could be stuck waiting on a Compactor that is trying to reserve a compaction. Review the logic around the use of the currentCompactionId variable.

**Comment by keith-turner** [comment]
@dlmarion made some changes related to this 75274ab29b5399788a8a61e4973acde3defa74bf. If those changes look good to you I think we could close this.
