### ISSUE TITLE
Integration tests for External Compactions

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#1990]
Need to figure out a good way to write the tests

**Comment by keith-turner** [comment]
We have been manually testing changes so far.  This is going to be fun to figure out how to write ITs for.  One approach to look into could be using the good old slow iterator, giving a chance to observe external compaction metadata in an IT.  However timing  like that is still iffy and makes ITs unstable.

**Comment by milleruntime** [comment]
Maybe have a separate utility for testing external compactions in accumulo-testing?

**Comment by keith-turner** [comment]
> Maybe have a separate utility for testing external compactions in accumulo-testing?

We could use the existing code in accumulo-testing and run continous ingest w/ configuration to use external compactions for large compactions.  Run that for a day or two and then verify it looking for lost data.

**Comment by dlmarion** [comment]
I think we have pretty good coverage now. Going to close this.
