### ISSUE TITLE
Decide behavior of external compactions when a table is taken offline.  

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#1998]
Currently external compactions continue running when a tablet is closed for any reason (balancing or table taken offline).  External compactions can gracefully deal with a tablet being offline when the compaction finishes.  So there is not problem to let external compactions run for an offline table.  Need to decide if this is the behavior we want.

**Comment by dlmarion** [comment]
Are there sanity checks in place that verify that the input files for the external compaction are still in the current set of files for the tablet when the external compaction is committed? I'm thinking about the case where more than one external compaction is in progress when the table is offlined and we need to commit the compactions in order when the table is brought back online.

**Comment by milleruntime** [comment]
We will have to take in consideration all offline operations as they currently make assumptions about the state of the table when it is offline. For example, An Admin offlines a table in order to perform an exportTable. The exportTable behavior will now have to take in consideration external compactions. Ideally, this new consideration won't make the Admin's life more difficult.  

If we allow external compactions to continue when a table is offline, I think we will also have to modify all the offline operations to check for running external compactions and handle them in some way. I have no idea how difficult this would be as offline behavior is rather mysterious and elusively sprinkled across different operations. For example, a new table created offline is probably not be affected but I am not sure about exportTable, table clone, bulk imports, or the offline scan map reduce option. Also didn't we add offline splits as well?

**Comment by keith-turner** [comment]
>Are there sanity checks in place that verify that the input files for the external compaction are still in the current set of files for the tablet when the external compaction is committed?

Yeah that is done by the following sanity check which existed before external compactions.

https://github.com/apache/accumulo/blob/183387ab6de5c82ed23f9b236a76ea7fce669be4/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java#L424

> For example, a new table created offline probably won't be affected but I am not sure about exportTable, table clone, bulk imports, or the offline scan map reduce option. Also didn't we add offline splits in 2.0 as well?

As currently implemented external compactions running against a table that is offline do not commit (update tablet metadata) until the table comes back online.  So this should not impact any of those operations.  Also if when the table comes back online the tablet for the ext compaction no longer exists for some reason (like split/merge), then the commit operation will be a no-op.

I think all of these cases you mentioned are good reasons to never commit an external compaction in an offline table.  Which was something I was uncertain about.

**Comment by keith-turner** [comment]
> Can you give a brief summary of what happens when an external compaction completes?

1. The compactor makes an RPC call the compaction coordinator to let it know the compactions completed
2. The coordinator writes an entry to the ~ecomp section of the metadata table recording the compaction completed AND queues up an async RPC to the tablet to let it know the tablet completed.
3. The coordinator periodically scans the ~ecomp section of the metadata table looking for tablets to notify
4. When the tablet recieves the message that an external compaction completed, it does some sanity checks and if everything looks ok it will :
   1. Update tablets in memory list of files
   2. Update tablet metadata (deleting the tablets information about the external compaction and updating the files atomically in a single mutation)
   3. Delete ~ecomp entry from metadata table

**Comment by EdColeman** [comment]
On a commit are you using KeyExtent prevRow and endRow to determine if the range is that same to check if split / merge has occurred?

**Comment by keith-turner** [comment]
> On a commit are you using KeyExtent prevRow and endRow to determine if the range is that same to check if split / merge has occurred?

Yes.  Each external compaction has a UUID that identifies it.  Each tablet records running external compactions in the tablets metadata using the UUID.   A commit message references the UUID and tservers map that to a tablet.  That reminds we need to ensure that when a tablet splits or merges, that no external compaction metadata propagates.

**Comment by keith-turner** [comment]
I opened #2011 and #2012 based on previous comment.

**Comment by keith-turner** [comment]
Currently external compactions can not commit when a table is offline.  However they can run and complete inserting a final state marker in the metadata table.  I think this behavior is ok.  When a table is brought back online, any compactions that completed while offline would commit.
