### ISSUE TITLE
Per table encryption

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2001]
I want to be able to configure the CryptoService to encrypt on a per table basis.

This will probably require new properties and new information to be passed into the CryptoEnvironment. This also might require changing the CryptoService configuration from `instance` properties to use `general` properties instead.

**Comment by milleruntime** [comment]
@ctubbsii A big problem that I have run into while trying to make the CryptoService table aware (with an implementation like the balancer) is providing the tableName (or tableId) through the RFile client classes. For example, I want to create an RFile for bulk import, there won't be a table associated with it yet so there is no way to know that when writing the file. The balancer doesn't have this problem because no users are creating balancers outside of Accumulo, where an RFile can exist separately from a table, outside of Accumulo.

**Comment by milleruntime** [comment]
I was able to discuss with @ctubbsii a design alternative to the minimal approach I was taking. The idea we came up with was to add a factory layer (something like CryptoServiceFactory) to handle the table -> CryptoService association. The file utilities that handle reading and writing to RFiles will still be ignorant of their table but just know whether a file is encrypted or not. Either way I think we will have to rename the properties to use the `general` prefix.

**Comment by milleruntime** [comment]
> I want to create an RFile for bulk import, there won't be a table associated with it yet so there is no way to know that when writing the file.

I had an idea for this table awareness problem. We could have a guard on any table that is configured for encryption to fail a bulk import if any file in the directory is unencrypted.

**Comment by keith-turner** [comment]
> I had an idea for this table awareness problem. We could have a guard on any table that is configured for encryption to fail a bulk import if any file in the directory is unencrypted.

That made me wonder if it would be possible to write a [CompactionSelector](https://github.com/apache/accumulo/blob/af2d2d630094fc06e0ac1d6702a9a49d30ec1e94/core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionSelector.java#L42) that selects unencrypted files for compaction.  This could be used in two ways.  First it could be configured on a user initiated compaction as a one time operation to encrypt all unencrypted files.  Second it could be configured on a table to continually select unencrypted files for compaction.  The second case may be an alternative to what you suggested for bulk imports, but its a more error prone because a user has to configure the selector on the table.  The first case would be useful for the case where someone wants to encrypt an existing table that is partially encrypted already.

**Comment by ctubbsii** [comment]
> That made me wonder if it would be possible to write a [CompactionSelector](https://github.com/apache/accumulo/blob/af2d2d630094fc06e0ac1d6702a9a49d30ec1e94/core/src/main/java/org/apache/accumulo/core/client/admin/compaction/CompactionSelector.java#L42) that selects unencrypted files for compaction.

That would be cool, but right now, there isn't a way to determine how files were encrypted without reading a bit of the file metadata.

**Comment by milleruntime** [comment]
Would it be useful to add an encrypted flag to the metadata table in `DataFileColumnFamily`? Or perhaps an even bigger change would be to store the file differently and have something in `TabletFile`? Every tablet file directory now starts with "t-0003".  What if we stored encrypted files in directories starting with "e-0003"?

**Comment by keith-turner** [comment]
> That would be cool, but right now, there isn't a way to determine how files were encrypted without reading a bit of the file metadata.

I was wondering about that.  Looking at the code each compaction service has single thread that does selection and planning, however I think the code would easily support multiple threads.  This thread pool size is currently not configurable, but it could be. User compactions would examine each file once, if this were done in a thread pool with lots of threads that may be ok.  For the case of a per table selector, would probably want the class to have a cache of info about previously examined files to avoid examining them over and over.

**Comment by keith-turner** [comment]
> Every tablet file directory now starts with "t-0003". What if we stored encrypted files in directories starting with "e-0003"

For the case of selecting files for compaction in order to encrypt, thinking it may be best to open the files and examine them IF that examination can determine wether the files encryption config differs from the tables encryption config.
