### ISSUE TITLE
Determine whether CompactionCoordinator::update should cancel running compactions

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2003]
@keith-turner - can you check this method, it pre-dates the work you did with putting the compaction information in the metadata table. I don't think we need to cancel these running compactions when a tserver goes down anymore, the tablet will just be re-hosted.

**Comment by keith-turner** [comment]
yeah I can look at it

**Comment by dlmarion** [comment]
@keith-turner - we talked about this last week, right? TServer going down should not cancel external compaction that is running, right? If so, I can take this over and make the necessary code mods.

**Comment by keith-turner** [comment]
Right, it should not cancel them.
