### ISSUE TITLE
Unit tests should reuse forks

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2004]
Original Jira ticket https://issues.apache.org/jira/browse/ACCUMULO-2781

Currently, neither unit tests nor IT's reuse forks with maven. This can be changed for unit tests with only a few exceptions that can be excluded.

**Comment by Manno15** [comment]
I am running into a few inconsistent test failures with these changes. Namely, `AssignmentWatcherTest`. A few are consistently failing which are the ones being excluded.

**Comment by ctubbsii** [comment]
@Manno15 Just keep in mind, the test that fails may not be the one that's actually the problem. It might be a previous test that messed with some internal static state.

**Comment by Manno15** [comment]
Good point. I will keep that in mind.
