### ISSUE TITLE
Pass KeyExtent to tablet for commit RPC

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2012]
The coordinator knows of the extent and UUID when it makes the RPC to commit a compaction. However it only passes the UUID.  It could also pass the Extent to allow for another sanity check on the tserver when it maps the UUID to an extent.

**Comment by dlmarion** [comment]
@keith-turner  - I modified the TServer and Coordinator pass the Extent to the TServer on compaction completion. I left two CBUG comments in CompactionManager as a reminder to complete the wiring up of the sanity checks.
