### ISSUE TITLE
Fix race condition in external compaction commit

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2013]
When an external compaction commits and the tablet is not present, it [deletes the marker](https://github.com/apache/accumulo/blob/75d7f67fef54771061b0fff45fdea507ebbf4ca9/server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/CompactionManager.java#L458-L460).   There is a race condition where if a tablet was recently unloaded, it would delete the final state marker resulting in the work of an external compaction being lost and probably redone later.

**Comment by keith-turner** [comment]
I think tablet servers should not delete the external compaction final state markers when they do not know about the external compaction.  They should only delete these markers when they are hosting the tablet related to the compaction and the tablet knows about the compaction.

For final state markers that point reference external compactions that no longer exists or tablets that no longer exist, the coordinator could periodically look for these and clean them up.  This periodic detection would be similar to what the dead compaction detection is currently doing, but would be looking for the inverse.  The periodic algorithm could do the following.

  1. Scan the final states markers in metadata table (~ecomp section) and store them in a set w/ UUID (compaction id) as key.
  2. Scan the metadata tablets section looking for compactions tablets think are running and remove them from the set.
  3. Delete any final state markers in the set since these reference tablets and/or external compactions that no longer exists.

**Comment by dlmarion** [comment]
@keith-turner - You moved this to Done, but it's still open. Is this good to close?
