### ISSUE TITLE
Modify Compactor so that it does not check for compactions every ms

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2026]
Put some backoff in the loop when checking for compactions. Incrementally wait longer between checks, maybe up to 3 seconds.

**Comment by dlmarion** [comment]
Added Compactor.getWaitTimeBetweenCompactionChecks which currently waits 3 seconds between checks for the next compaction job. @keith-turner was talking about a different implementation based on the number of Compactors.

**Comment by keith-turner** [comment]
I was thinking of making the sleep time a function of the # of compactors.  Hoping to achieve something where on average a few compactors check in with the coordinator every second.  Thinking this can be done by increasing each compactors sleep time as the total number of compactors increases.  I'll take a crack at this.

**Comment by keith-turner** [comment]
@dlmarion can you review the changes in 022f4b9e25c34cabeb2562b678cc9f065b4d12ed

I tested this locally.  I started and stopped compactors and saw the trace message reflect the number of compactors.

**Comment by dlmarion** [comment]
LGTM
