### ISSUE TITLE
Make private fields in Violations.CVSKey final

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2033]
There are two private fields: `String className` and `short vcode` in the private class `CVSKey` in `Violations` that can be made final.

**Comment by alimustafashah** [comment]
Can you assign this task to me?

**Comment by milleruntime** [comment]
@alimustafashah thanks for your interest, I can definitely assign you the task. I had opened this issue for the Open Source hackathon that is going on later this week. Would you be participating in that? Here is the link: https://www.eventbrite.com/e/open-source-hackathon-tickets-150583967701

**Comment by alimustafashah** [comment]
I am a newbie in open source. Would I be a good fit for it?

**Comment by milleruntime** [comment]
Sure! The hackathon is an opportunity for people of all skill levels and backgrounds to collaborate and make a big impact by creating code that benefits the OSS. The goal of the hackathon is to promote Open-Source contributions by people from diverse backgrounds.

**Comment by Amisha328** [comment]
Hey,
Can I contribute to this issue?

**Comment by EdColeman** [comment]
@Amisha328 - thank you for your interest, but someone already fixed this issue.

**Comment by milleruntime** [comment]
@Amisha328 @alimustafashah the registration for the Open Source Hackathon is closed but if you are interested in participating  please email hackathonoss@gmail.com. Information about it can still be found here: https://www.eventbrite.com/e/open-source-hackathon-tickets-150583967701

**Comment by alimustafashah** [comment]
Okay I am emailing : )

**Comment by Amisha328** [comment]
@milleruntime  I have already registered.
Thanks for informing me.

**Comment by Amisha328** [comment]
I will do it.
Thanks for informing @milleruntime

**Comment by alimustafashah** [comment]
I emailed but I did not get any response.

**Comment by EdColeman** [comment]
@alimustafashah the group running the hackathon is independent of Accumulo - we are participating as a community, but have no involvement with the registration.
