### ISSUE TITLE
Rename ArrayList in ConstraintChecker

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2034]
The name of the ArrayList in the class `ConstraintChecker` has a typo. The ArrayList object is called _constrains_ when it should have been called `constraints`. This ticket is to simply rename the private variable.

**Comment by Umang228** [comment]
Sir, I would like to assigned to this task.

**Comment by Umang228** [comment]
Sir, I would like to get assigned to this task.

**Comment by milleruntime** [comment]
@Umang228 thanks for your interest, I can definitely assign you the task. I had opened this issue for the Open Source hackathon that is going on later this week. Would you be participating in that? Here is the link: https://www.eventbrite.com/e/open-source-hackathon-tickets-150583967701

**Comment by Amisha328** [comment]
Hey, can I contribute to this issue?

**Comment by Umang228** [comment]
The event has ended. What i am supposed to do?

**Comment by EdColeman** [comment]
@Amisha328 - someone is already working on this issue.

**Comment by Amisha328** [comment]
Okay, @EdColeman  no issue

But I have already fixed the issue and if you wish I can push the code now if you assign me.

**Comment by EdColeman** [comment]
@Umang228 submitted https://github.com/apache/accumulo/pulls/Umang228 - but there are request changes - maybe you could hold off for a bit and see if those can be addressed?

**Comment by Amisha328** [comment]
Okay, sure.
Thank You!

**Comment by EdColeman** [comment]
Closed with PR: #2037
