### ISSUE TITLE
Use Map.forEach() in LocalityGroupUtil.java

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2041]
Recently Java introduced the `Map.forEach()` method.  Using this in conjunction with a lambda results in more succinct and efficient code compared to looping over `Map.entrySet()`.  One place in the Accumulo source code where `Map.forEach()` could improve the source code is [here](https://github.com/apache/accumulo/blob/9afab2c1b931d100ed6bad5cfe028c28da944427/core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java#L380).

**Comment by ctubbsii** [comment]
Some blocks of code can't be converted in this way, because the `forEach` method would allow a lambda that throws a checked exception. So, any candidates for making this change that throw a checked exception will need to remain the way they are now. This is just something for whoever works on this to pay attention to.

**Comment by lawynnj** [comment]
Hello, I would like to pick up this issue, if possible.

**Comment by ctubbsii** [comment]
@lawynnj Are you still interested in working on this?

**Comment by lawynnj** [comment]
@ctubbsii unfortunately I am not. Sorry!

**Comment by slackwinner** [comment]
If this task still needs to be done, I can complete it.

**Comment by ctubbsii** [comment]
@slackwinner , @jjmar11 had expressed to me that they were interested.

**Comment by slackwinner** [comment]
@ctubbsii I was about to send a PR to fix this issue but will stand down to allow @jjmar11 to work on this.

**Comment by slackwinner** [comment]
My mistake. I accidentally hit the draft PR button. I'll close out the PR I made.

**Comment by ctubbsii** [comment]
@slackwinner I think it's fine. Go ahead and re-open your PR. It's a small task, and you've already started on it. It doesn't matter that much.
