### ISSUE TITLE
Replace assertTrue with assertArrayEquals in KeyTest

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2042]
The test class `KeyTest` has a few places in the code where `assertTrue` is used with the `Arrays.equals()` comparison. These assertions can be simplified to use the `assertArrayEquals` test. 

For example, the following line of code:
`assertTrue(Arrays.equals(row, key.getRowBytes()));`
can be replaced with the equivalent:
`assertArrayEquals(row, key.getRowBytes());`

**Comment by vallari118** [comment]
Hi. Can I take this issue ?

**Comment by vallari118** [comment]
We have to do this wherever assertTrue is done for Array.equals am I right ?

**Comment by milleruntime** [comment]
Hi @vallari118 thanks for you interest in this ticket. Are you participating in the OSS hackathon on 4/29-4/30? If you are not, please send an email to hackathonoss@gmail.com to see if there are any spots left.

**Comment by milleruntime** [comment]
> We have to do this wherever assertTrue is done for Array.equals am I right ?

Yes, correct. I was looking at KeyTest but there may be other places in the code as well that could be included.

**Comment by vallari118** [comment]
I was not participating in hackathon. I won't be able to attend maybe because of work. But I would like to take some small tasks.

**Comment by milleruntime** [comment]
OK that is not a problem. I assigned the ticket to you anyway since you showed interest. If you have any questions, feel free to ask.

**Comment by vallari118** [comment]
Sure I will complete this change by Weekend. Thanks !

**Comment by vallari118** [comment]
@milleruntime  Please check I have added the pull request

**Comment by Akshit6828** [comment]
is this issue still open? @milleruntime  . If yes, please can I contribute to it? if no, then please help me with some good first issues as I want to contribute to open-source projects.

**Comment by EdColeman** [comment]
@Akshit6828 there has been a PR submitted, waiting for comments to be addressed.

**Comment by Akshit6828** [comment]
ok thanks, @EdColeman . I'll be waiting for some other good first issues.

**Comment by EdColeman** [comment]
@Akshit6828 - take a look at https://github.com/apache/accumulo/issues/2078

**Comment by Akshit6828** [comment]
Thanks, @EdColeman for mentioning the issue. 😃
