### ISSUE TITLE
Fix javadoc for LongCombiner

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2047]
The javadoc for LongCombiner has some inaccurate information about the supported types [on lines 48-49](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/iterators/LongCombiner.java#L48). Based on the [Type enum](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/iterators/LongCombiner.java#L59-L73), the actual supported types are VARLEN, FIXEDLEN, and STRING, which are provided by the VarLenEncoder, FixedLenEncoder, and StringEncoder. The javadoc should be updated to describe the correct types.

**Comment by Umang228** [comment]
Assign this to me...

**Comment by EdColeman** [comment]
Please correct your issues on https://github.com/apache/accumulo/issues/2049 first.

**Comment by lawynnj** [comment]
Hello, I would like to pick up this issue.
