### ISSUE TITLE
Typo in CompactableFileImpl method name

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2048]
There is a typo in one of the method names in [CompactableFileImpl](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/metadata/CompactableFileImpl.java#L62). The method name is getStortedTabletFile when it should be getStoredTabletFile. This ticket is to rename the method.

**Comment by nicolasalarconrapela** [comment]
Can i change it?

**Comment by billierinaldi** [comment]
Hi @nicolasalarconrapela, yes you can fix this issue. Let me know if you have any questions.
