### ISSUE TITLE
Rename method in SingletonManager

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2049]
There is a typo in a method name in SingletonManager. The method is named releaseRerservation when it should be releaseReservation. This ticket is to [rename the method](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/singletons/SingletonManager.java#L142).

**Comment by Umang228** [comment]
Assign this to me...

**Comment by alimustafashah** [comment]
Can you assign this task to me?

**Comment by ctubbsii** [comment]
Fixed in #2061
