### ISSUE TITLE
Rename field in TabletServerResourceManager

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2053]
The field name [summaryParitionPool in TabletServerResourceManager](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java#L101) has a typo. The field should be named summaryPartitionPool. The field is used multiple times in this class, so all uses will need to be fixed.

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue

**Comment by Amisha328** [comment]
Is this issue still Open. Can I contribute to it?

**Comment by EdColeman** [comment]
@Amisha328  - would you be interested 2066? This one may be in progress.

**Comment by Amisha328** [comment]
Sure, I will be working on 2066.

**Comment by ctubbsii** [comment]
Fixed in #2055
