### ISSUE TITLE
Fix typo in ClientOpts option description

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2054]
The description of the password option in ClientOpts has a typo. It says [conection](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java#L155) instead of connection. This ticket is to update the description to say connection.

**Comment by sjyang18** [comment]
Let me work on this simple fix.

**Comment by ctubbsii** [comment]
Fixed in #2056
