### ISSUE TITLE
Field map in org.apache.accumulo.core.util.MapCounter can be final

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2066]
The declaration of [map in MapCounter](https://github.com/apache/accumulo/blob/c180b344789fc74c7f5d2387c8a49f71df8e5892/core/src/main/java/org/apache/accumulo/core/util/MapCounter.java#L34) on line can be final.

**Comment by alimustafashah** [comment]
Can I take this? Also, can you specify the file?

**Comment by EdColeman** [comment]
@Amisha328 has been trying to find an issue - I'd like to see if they would like to try.

**Comment by Amisha328** [comment]
@EdColeman  Yes, I would like to work with this issue.

**Comment by alimustafashah** [comment]
> @Amisha328 has been trying to find an issue - I'd like to see if they would like to try.

Sure : )

**Comment by EdColeman** [comment]
Closed with #2071
