### ISSUE TITLE
Variables in org.apache.accumulo.fate.FATE class can be final.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2078]
The fields store, environment and executor can be marked final in [FATE](https://github.com/apache/accumulo/blob/552fd33407f9346fba45525f3abb36864de2ea09/core/src/main/java/org/apache/accumulo/fate/Fate.java#L51)

**Comment by Akshit6828** [comment]
Hi @EdColeman  can i work on this issue?

**Comment by EdColeman** [comment]
My mistake - executor cannot be final - the other filed that can be final is keepRunning - would you correct and push the changes to your PR - sorry for the confusion.

**Comment by Akshit6828** [comment]
Sure @EdColeman  . Yeah, I saw the checks. It's generating an error as: cannot assign a value to a final variable executor.

**Comment by Akshit6828** [comment]
No problem @EdColeman  sir. I'll fix this up and submit a PR.
