### ISSUE TITLE
Rewrite history test in ShellServerIT

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2091]
There are a few problems with the `history` test in ShellServerIT. The test should be rewritten to create a table with a unique name and then look for that unique name using the history command.

**Comment by Manno15** [comment]
What I have noticed so far is that the history file isn't properly created inside the IT.

**Comment by Manno15** [comment]
Correction, the history file isn't properly created for the `history` test. For some reason, tests that use an input, i.e. `ts.input.set("name1")`, will show up in the history file (the string inside the parentheses that is). This does not work in the history function though. 

It does seem that the exec commands do not properly show up in the history file as expected so the IT does not correctly simulate shell functionality that way.
