### ISSUE TITLE
Use lower cardinality type for compaction priority

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2094]
Compaction Jobs currently use a long for compaction priority.  For external compactions this could potentially cause problems in the compaction coordinator if millions or billions of distinct priorities were actually used.  Instead of telling people not do that, it would probably be better to change the type for priority from a 64 bit integer to an 8-bit or 16-bit integer.

**Comment by dlmarion** [comment]
@keith-turner - I think we can remove this from the External Compactions project.

**Comment by keith-turner** [comment]
I moved it out of the the external compaction project to a 2.1.0 blocker because I think it can be done after external compactions are merged, but should be done before a 2.1.0 release as it would change SPIs that are new in 2.1.0
