### ISSUE TITLE
Make LogReader more discoverable

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2100]
I am not sure how many know about it but I just discovered the utility called `LogReader` for reading the WALs. It would be nice if it was more discoverable and easier for Admins to run. I think some documentation at the minimum and perhaps an Admin command to run it from the `accumulo` command.

**Comment by ctubbsii** [comment]
Could have a KeywordExecutable, like we have for `rfile-info`. Could be `wal-info`.
