### ISSUE TITLE
JSON properties displayed with different quotes in Shell

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2105]
Setting properties that take JSON as a value in the Shell is cumbersome. It took me several tries to finally figure out that the entire option passed to the "-s" parameter needs to be in quotes. For example, if i want to change a value in the compaction property
`tserver.compaction.major.service.meta.planner.opts.executors`, I have to enter the entire string and modify the value I want to change:
<pre>
root@uno testTable> config -s "tserver.compaction.major.service.meta.planner.opts.executors=[{'name':'small','maxSize':'32M','numThreads':2},{'name':'huge','numThreads':3}]"
</pre>

Perhaps we could have a separate utility for setting compaction properties and print a message to use this utility instead. Or may add a new "-json" parameter that is more user friendly.

**Comment by ctubbsii** [comment]
The quoting in the shell may be a little quirky, but I don't think it's so inconvenient as to require writing and maintaining a whole new feature to avoid quoting. Perhaps we could improve the error message from whatever you tried the first time? Or provide a debugging log message, to show what it thinks you entered so you can find the problem with quoting more quickly?

**Comment by milleruntime** [comment]
One of the issues right now is that the default values get displayed with two kinds of quotes:
<pre>
root@uno> config -f compaction.major.service
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                                               | VALUE
-----------+--------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------
default    | tserver.compaction.major.service.default.planner ................. | org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner
default    | tserver.compaction.major.service.default.planner.opts.executors .. | [{'name':'small','maxSize':'32M','numThreads':2},{'name':'medium','maxSize':'128M','numThreads':2},{"name":"large","numThreads":2}]
default    | tserver.compaction.major.service.default.planner.opts.maxOpen .... | 10
default    | tserver.compaction.major.service.default.rate.limit .............. | 0B
default    | tserver.compaction.major.service.meta.planner .................... | org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner
default    | tserver.compaction.major.service.meta.planner.opts.executors ..... | [{'name':'small','maxSize':'32M','numThreads':2},{"name":"huge","numThreads":2}]
default    | tserver.compaction.major.service.meta.planner.opts.maxOpen ....... | 30
default    | tserver.compaction.major.service.meta.rate.limit ................. | 0B
default    | tserver.compaction.major.service.root.planner .................... | org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner
default    | tserver.compaction.major.service.root.planner.opts.executors ..... | [{'name':'small','maxSize':'32M','numThreads':1},{"name":"huge","numThreads":1}]
</pre>
It wouldn't be so bad to copy and paste the JSON blob but right now I have to modify at least half of the quotes.

**Comment by ctubbsii** [comment]
Single quotes are not considered proper JSON. Many JSON parsers are forgiving in this regard, but it's technically not valid to use single quotes in JSON. The values should only use double-quotes in the first place. Then, you can use single-quotes to quote the entire value in the shell. We could also make the output of the shell show copy/paste friendly quoting, so quotes are already escaped and values are already quoted. However, that could get very ugly and confusing.

**Comment by milleruntime** [comment]
> The quoting in the shell may be a little quirky, but I don't think it's so inconvenient as to require writing and maintaining a whole new feature to avoid quoting. Perhaps we could improve the error message from whatever you tried the first time? Or provide a debugging log message, to show what it thinks you entered so you can find the problem with quoting more quickly?

I found the issue fairly quickly. I guess my issue is with the JSON in the first place. We are basically asking users to write scripts in order to set these properties and that worries me. Maybe its not that big of deal on a large cluster but I guess it would depend on how a user does configuration management of their cluster in the first place.

**Comment by keith-turner** [comment]
>  I guess my issue is with the JSON in the first place.

I didn't easily settle on using json.  However I saw it as an option between the following

```
tserver.compaction.major.service.root.planner.opts.executors ..... | [{'name':'small','maxSize':'32M','numThreads':1},{"name":"huge","numThreads":1}]
```

or the following

```
tserver.compaction.major.service.root.planner.opts.executors.e1.name=small
tserver.compaction.major.service.root.planner.opts.executors.e1.maxSize=32M
tserver.compaction.major.service.root.planner.opts.executors.e1.numThreads=1
tserver.compaction.major.service.root.planner.opts.executors.e2.name=huge
tserver.compaction.major.service.root.planner.opts.executors.e2.numThreads=1
```

and thought that json would be better than the exploded options.  Also the JSON is not intrinsic to Accumulo, its just something the default planner plugin uses.  One could write another planner that does not use json for its options.

**Comment by milleruntime** [comment]
I opened https://github.com/apache/accumulo/pull/2109 so the JSON is properly displayed. Then users can at least copy and paste the JSON that gets returned when changing the default values.
