### ISSUE TITLE
Need to test rebuild of selected set on tablet load.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2111]
When a tablet it initiates a user compaction it selects a set of file and then works to get those files compacted across possibly multiple compactions.  For external compactions the set of selected files file is rebuilt when a tablet unload and reloads on another tserver.  If possible this scenario should be tested, if its not already.

**Comment by keith-turner** [comment]
Could try to test the end-to-end functionality works in an IT.  The code that rebuilds the selected set of files has a lot of sanity checks.  Could refactor the code so that all of these sanity checks can be exercised in a unit test.

**Comment by milleruntime** [comment]
I assigned this to myself as a reminder TODO next but anyone feel free to tackle in the meantime as I am not actively working this issue.

**Comment by milleruntime** [comment]
@dlmarion you recently refactored the ExternalCompaction ITs, do you know if they cover this scenario?

**Comment by keith-turner** [comment]
I actually started working on some unit test that are related to this this morning.  Should be posting a PR shortly
