### ISSUE TITLE
Unit test converting client props to BatchWriterConfig

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2115]
A simple unit test to ensure client props are reliably converted to a batch writer config object could be added for [this method](https://github.com/apache/accumulo/blob/af2d2d630094fc06e0ac1d6702a9a49d30ec1e94/core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java#L286)

Maybe refactor the code as follows for unit testing.

```java
  public static BatchWriterConfig getBatchWriterConfig(Properties props) {
    //take code from existing method
  }
  public BatchWriterConfig getBatchWriterConfig() {
    ensureOpen();
    if (batchWriterConfig == null) {
      batchWriterConfig = getBatchWriterConfig(info.getProperties());
    }
    return batchWriterConfig;
  }
```

**Comment by DomGarguilo** [comment]
I created #2131 after looking into this.
