### ISSUE TITLE
Return a Map instead of an Iterable with getProperties

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2120]
Based on Jira ticket: [ACCUMULO-3107](https://issues.apache.org/jira/browse/ACCUMULO-3107) 

The getProperties functions in `TableOperations` ([here](https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java#L621)) and `NamespaceOperations` ([here](https://github.com/apache/accumulo/blob/4f35e6aff1763d4b19d1e93036260094b47cc589/core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java#L207)) currently returns an Iterable. As the ticket suggests, this (along with the function implementation) can be changed to return a Map instead. The current iterable getProperties can also be deprecated and the deprecation tag, `@Deprecated(since = "2.1.0")`, should be added along with a reference to the deprecation and the new function that replaces it inside the java docs. A good example of how to deprecate a function is the `create` function inside `TableOperations` found [here](https://github.com/apache/accumulo/blob/1dc72fce2c781dee597c8c11876a3bc6c321c199/core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java#L106-L109)

**Comment by foster33** [comment]
I am interested in working on this issue if no one else is. Seems like it would be a good first issue to work on.
