### ISSUE TITLE
Broken or Flaky tests after compaction changes: CompactionIT, KeywordStartIT, DeprecatedPropertyUpgrade9to10IT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2137]
**Test name(s)**
 - ~~org.apache.accumulo.test.functional.CompactionIT.testBadSelector - test timed out after 240 seconds~~
 - ~~org.apache.accumulo.test.functional.CompactionIT.test - assertion error at at `CompactionIT.java:207`~~
 - ~~org.apache.accumulo.test.start.KeywordStartIT.testExpectedClasses - `expected:<co[nvert-config]> but was:<co[mpaction-coordinator]>~~
 - ~~org.apache.accumulo.test.upgrade.DeprecatedPropertyUpgrade9to10IT.testZookeeperUpdate - `Unable to create external compaction paths`~~

**Describe the failure observed**
Ran full ITs after #2096 / #1451 was merged and saw 4 test failures that failed for two runs in a row.

**Testing Environment:**
 - Version of this project: 2.1.0-SNAPSHOT
 - First commit known to fail (or current commit): c11ee7bc71a7212a0ba009e8df419e5427a5c136
 - OS: Fedora 34
 - Java: 11
 - Maven: 3.6.3
 - Other environment details: AWS / m4.2xlarge

**What have you tried already?**
Re-ran the ITs

**Additional context**
N/A

**Comment by dlmarion** [comment]
Looking at these

**Comment by Manno15** [comment]
I have a fix for `KeywordStartIT`. The one appears to be relatively straightforward.

**Comment by dlmarion** [comment]
I figured out the issue with CompactionIT, PR incoming

**Comment by milleruntime** [comment]
I saw these same failures after I rebased #2117 on main today.

**Comment by dlmarion** [comment]
@ctubbsii  - I believe all of the issues have been resolved.

**Comment by ctubbsii** [comment]
Verified latest commit builds without these errors.
