### ISSUE TITLE
Provide uniform Property name string in external compaction properties

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2142]
**Is your feature request related to a problem? Please describe.**
Reviewing recent PR related to the external compaction feature I noticed that some of the new properties being added (mainly coordinator, but there could be others) did not have COMPACT in the property name.

**Describe the solution you'd like**
It may allow for easier searching and grouping of properties if there was a uniform naming convention that had COMPACT or something that would signal these properties are grouped together as well as allow grep to be used to filter for those values.

**Describe alternatives you've considered**
The downsides is that this might make the names ridiculously long and from the coordinator context not adding much value if it is understood that the coordinator is related to compaction.

**Comment by milleruntime** [comment]
FYI every property related to compaction (prior to external compactions) appears to have the word `compaction` in the property name.
