### ISSUE TITLE
Revaluate Sunny Test profile

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2147]
The sunny test profile feel a little incomplete as it is currently only running 4 ITs (@Category(SunnyDayTests.class):
<pre>
test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/rpc/ThriftBehaviorIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java:@Category(SunnyDayTests.class)
</pre>

I think we could add a few ITs to make sure we have basic functionality covered. I think including ITs dealing with compactions, the metadata table, bulk import or write ahead logs would be good.

**Comment by ctubbsii** [comment]
As long as it's limited to basic functionality. The idea is that these tests should be very limited, and be a very quick sanity check to make sure that core functionality isn't broken. They should be fast to run, highly reliable and never flaky, and be able to run on meager hardware.

**Comment by milleruntime** [comment]
I missed some when I opened this ticket. There are actually 7 Sunny day ITs. The 4 above plus these:
<pre>
main/java/org/apache/accumulo/test/ShellIT.java:@Category({MiniClusterOnlyTests.class, SunnyDayTests.class})
main/java/org/apache/accumulo/test/functional/ReadWriteIT.java:@Category({StandaloneCapableClusterTests.class, SunnyDayTests.class})
main/java/org/apache/accumulo/test/ShellServerIT.java:@Category({MiniClusterOnlyTests.class, SunnyDayTests.class})
</pre>

This is a lot better than what I initially thought. Maybe a bulk import and WAL test would be nice.
