### ISSUE TITLE
Properties from 'config' command return unordered

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2149]
**Describe the bug**
The `config` command inside the accumulo shell returns the properties unordered.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT. Appears to be from commit: 4ea9bf1ac916d66896eaaba329da04714a1e8cba

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. With the commit mentioned above, start-up an accumulo instance.
2. Go into the accumulo shell
3. Run the `config` command

**Expected behavior**
The properties should be returned ordered alphabetically. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29436247/121096628-9311d600-c7c0-11eb-8f35-0678f99acb98.png)

**Additional context**
Each new instance has a different order of properties.

**Comment by ctubbsii** [comment]
It looks like this is from the use of `Map.copyOf()` to replace populating a `TreeMap` in some places. In some places, this probably doesn't matter, but for the shell it would be nice. Unfortunately, there's no `SortedMap.copyOf()` or anything like that. The easiest fix is probably to use Guava's `ImmutableSortedMap.copyOf()` instead. There might be a few other places where TreeMap was replaced as well.

**Comment by Manno15** [comment]
Yep, that appears to be correct. A quick test with `ImmutableSortedMap.copyOf()` worked.

**Comment by foster33** [comment]
I would like to work on this if no one else is.
