### ISSUE TITLE
TableOperationsIT and NamesapceIT test failures.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2151]
**Describe the bug**
Running the full set of tests - these two have failed so far and look to be errors that are not transient

TableOperationsIT and NamespaceIT test fail with IllegalStateException

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: current main (58a559fa6)

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
Run the tests

**Expected behavior**
The tests pass

**Screenshots**

**Additional context**
```

[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 124.504 s <<< FAILURE! - in org.apache.accumulo.test.TableOperationsIT
[ERROR] org.apache.accumulo.test.TableOperationsIT.createTableWithTableNameLengthLimit  Time elapsed: 19.371 s  <<< ERROR!
java.lang.IllegalArgumentException: tableName must only contain word characters (letters, digits, and underscores) and cannot exceed 1024 characters

INFO] Running org.apache.accumulo.test.NamespacesIT
[ERROR] Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 63.835 s <<< FAILURE! - in org.apache.accumulo.test.NamespacesIT
[ERROR] org.apache.accumulo.test.NamespacesIT.createNamespaceWithNamespaceLengthLimit  Time elapsed: 1.115 s  <<< ERROR!
java.lang.IllegalArgumentException: namespace must only contain word characters (letters, digits, and underscores) and cannot exceed 1024 characters

```

**Comment by ctubbsii** [comment]
I'm working on this as follow on from #1971
