### ISSUE TITLE
Tablet.closeConsistencyCheck should check lastFlush and lastCompact IDs

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2153]
Taken from Jira ticket:  [ACCUMULO-1290](https://issues.apache.org/jira/browse/ACCUMULO-1290)
There is also a TODO in `Tablet.java` regarding this and can be deleted once this is completed. It is here: https://github.com/apache/accumulo/blob/5d3344dbb488d602025ce8f2acb5f807969f45ec/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1407

**Describe the solution you'd like**
A consistency check for lastFlushID and lastCompactID should be added to `closeConsistencyCheck` following the same format as the rest of the consistency checks. 

**Additional context**
I believe this ticket to be straight forward which is why I marked it as `good first issue`. `Tablet.java` contains a function to get both flush ID and compact ID as well as an object that holds the lastFlushID and lastCompactID. 

One thing to note, if a table hasn't been flushed or compacted before it was closed then the last IDs will be -1 while the `getFlushID` and `getCompactID` will be 0. So the consistency check should check for this before comparing the two.

**Comment by shreelakshmijoshi** [comment]
Hi @Manno15 ,
I am a new open source contributor and would like to work on the issue, would you provide some more reference to help me understand the problem better ?
Is this issue open for contribution ?

**Comment by EdColeman** [comment]
Are you able to build the base (main) branch?  Some helpful documentation can be found at [building accumulo](https://accumulo.apache.org/contributor/building).  When you submit a PR, there are a set of validations that will run - if you can follow the build instructions, running:
```
mvn clean verify package javadoc:jar -Psec-bugs -DskipITs=true -DskipTests=true
``` 
Will run the complete set of validations that the build process will run, skipping tests - running those successfully before submitting a PR will catch issues that would fail the process. If your PR adds or modifies tests, then you will want to make sure that your exercise those (again, see the building Accumulo for more details)

If you have question with the issue, maybe ask direct questions where things are unclear?

**Comment by Manno15** [comment]
> I am a new open source contributor and would like to work on the issue, would you provide some more reference to help me understand the problem better ?
Is this issue open for contribution ?

Hey, @shreelakshmijoshi! I would be more than glad to assist you. Yes, this issue is open for contribution if you wish to take it on.  There is a `closeConsistencyCheck` function inside `Tablet.java` (as seen below). In there, we do multiple checks to make things are consistent as expected. This issue would like to add two more checks in that function, one for lastFlushID and one for lastCompactID. Let me know if you need any further explanation or help!

 https://github.com/apache/accumulo/blob/5d3344dbb488d602025ce8f2acb5f807969f45ec/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1345

**Comment by foster33** [comment]
I would like to work on this issue.

**Comment by ctubbsii** [comment]
I reverted the change in PR #2397 in 664b5a5dd137a58e4df47915c8f5f209a530cd8a because it caused a reproducible test failure in DeleteRowsIT, and it needs further work before applying. I'm re-opening this issue so it can be investigated, fixed, and the patch (with fixes) re-applied.
