### ISSUE TITLE
Look into making Ample only return exact matches for KeyExtents

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2154]
The ample methods [here](https://github.com/apache/accumulo/blob/92a4dd3874b906a87166ae329c7f8d33e74a5a93/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java#L154), [here](https://github.com/apache/accumulo/blob/92a4dd3874b906a87166ae329c7f8d33e74a5a93/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java#L140), and [here](https://github.com/apache/accumulo/blob/92a4dd3874b906a87166ae329c7f8d33e74a5a93/core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java#L307) all take KeyExtent.  These methods have the behavior that they may return tablet metadata for a different KeyExtent.  The impl looks up a tablet using only the table id and end row in the extent, so this could result in finding a tablet in the metadata table that has a different prev end row than the one passed to Ample.  This behavior seems confusing to me and like it could possibly lead to incorrect code.  Seems like it wold be better to return nothing in the case where the prev end rows do not match, which would be a simple change.  However before this change would need to survey all code using this methods and make sure the change in behavior does not break anything.  Noticed this while working on #2152.  If a changes is made, would also need to change the new method from #2152.

**Comment by DomGarguilo** [comment]
> Seems like it wold be better to return nothing in the case where the prev end rows do not match

@keith-turner Do you think it would be best to just check that the prevEndRows match once the metadata has been returned (in AmpleImpl.readTablet), or only return metadata whose prevEndRows match in the first place? Either router seems doable.

> If a changes is made, would also need to change the new method from #2152.

Which portion of #2152 do you think would need to be changed?
