### ISSUE TITLE
Update CheckForMetadataProblems utility output.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2166]
**Is your feature request related to a problem? Please describe.**
Update the output of the CheckForMetadataProblems utility.  The current output shows a mix of table ids and names and seems to predate the renaming of some of the system tables like root, metadata...)

**Describe the solution you'd like**
```
The current output:

> accumulo org.apache.accumulo.server.util.CheckForMetadataProblems -u root

All is well for table !0
No problems found
Checking table: accumulo.metadata
All is well for table +rep
All is well for table 1
All is well for table 2
All is well for table 3
No problems found

This might be improved with something like:

Checking root table
All is well for accumulo.root (+r)
Checking table: accumulo.metadata
All is well for accumulo.metadata (!0)
All is well for table accumulo.replication (+rep)
All is well for table trace (1)
All is well for table table_A (2)
All is well for table table_B (3)
No problems found

And any errors could report the table name if available.
```

**Comment by ctubbsii** [comment]
Here's a slight variation on what @EdColeman proposed. This version correctly shows the metadata table consistency as part of checking the root table, and user table consistency as part of checking the metadata table. It also adds a blank line in between.

```
Checking tables whose metadata is found in: accumulo.root (+r)
...All is well for accumulo.metadata (!0)
No problems found in accumulo.root (+r)

Checking tables whose metadata is found in: accumulo.metadata (!0)
...All is well for table accumulo.replication (+rep)
...All is well for table trace (1)
...All is well for table table_A (2)
...All is well for table table_B (3)
No problems found in accumulo.metadata (!0)
```

**Comment by Manno15** [comment]
Once this issue is resolved, the website should be updated to match the expected output. Similar to what was done in PR [accumulo-website#285](https://github.com/apache/accumulo-website/pull/285).

**Comment by foster33** [comment]
I am interested in working on this issue.
