### ISSUE TITLE
Make listscans show #of files

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2174]
**Is your feature request related to a problem? Please describe.**
First posted on Jira Ticket: [here](https://issues.apache.org/jira/browse/ACCUMULO-385)

Quote from the Ticket:

    Look into making the list scans shell command show the number of files in use by the scan.

Wanted to recreate this ticket to elicit discussion.

**Comment by DomGarguilo** [comment]
I would like to be assigned to this ticket.

**Comment by DomGarguilo** [comment]
After some investigation, it seems this feature may be harder to implement than I originally anticipated. It looks like most of the work to make this happen would need to be done to the scan command rather than the listscans command. As it stands (unless I am overlooking something, which is very possible) there is no apparent clean or easy way to display the file count for a given scan. Before continuing I wanted to see if there is still any desire for this feature or see if anyone had ideas that might make implementing this easier/better/etc.

**Comment by milleruntime** [comment]
You could add a new method to `ActiveScan` class and use it to get the number of files. This [class](https://github.com/apache/accumulo/blob/3fd5cad92f9b63ac19e4466f3f2d5237b905262c/core/src/main/java/org/apache/accumulo/core/client/admin/ActiveScan.java) is returned by the getActiveScans() method on the `InstaceOperations` API. This would probably also require adding another value on the thrift endpoint as well in [tabletserver.thrift](https://github.com/apache/accumulo/blob/cd2dfa12943a1fce279c8399c68e1b7f4f752958/core/src/main/thrift/tabletserver.thrift#L83)

**Comment by DomGarguilo** [comment]
@milleruntime The problem is getting the file count. It seems like the file count is something that would need to be measured as the scan itself is taking place. I'm not sure of a way to determine which files were scanned given the info available from an activescan.

**Comment by EdColeman** [comment]
If the file count needs to be added, it might make sense to also public those as some sort of metric. Just raising this as a question - I'm not sure if this would be a useful metric or not  - but it might be worth checking.

**Comment by DomGarguilo** [comment]
After further investigation and discussion it seems that this change would require more work than it is worth. Instead, the number of files in a scan may be added as a metric.
