### ISSUE TITLE
Typo in putByteSquence method

### ISSUE THREAD

**Issue by billierinaldi** [apache/accumulo#2200]
There is a typo in the putByteSquence method in RowColumnSampler. The method name should be putByteSequence. All uses of the method name should be changed. Since it is a private method, this is the only file that needs to be changed.
https://github.com/apache/accumulo/blob/f9f1d3f6578c400862e9f0e8d82a49bf9c4a5392/core/src/main/java/org/apache/accumulo/core/client/sample/RowColumnSampler.java#L107

**Comment by classickartik** [comment]
I would like to work on this issue
