### ISSUE TITLE
Remove use of JLine outside of accumulo-shell

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2203]
JLine is used for a REPL command-line tool in accumulo-shell. However, we seem to also be using it for trivial line reading for non-REPL use cases. This is overkill, and makes it more likely that JLine upgrades will break code that doesn't need to depend on it. For many of these cases, a simple `System.console().readLine()` (or `.readPassword()`) will do.

JLine should be removed from all simple line reading parts of our code, and used only where it is actually needed (most likely, the only place it's actually needed is in accumulo-shell and test code).

**Comment by harjitdotsingh** [comment]
@ctubbsii  - I can take this.
