### ISSUE TITLE
Move TabletServer.checkTabletMetadata() to AssignmentHandler and improve messages

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2208]
The static method [TabletServer.checkTabletMetadata()](https://github.com/apache/accumulo/blob/f5df4f9681736d35e14b92c58033a1cf062b3d4e/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java#L926) is only called by [AssignmentHandler](https://github.com/apache/accumulo/blob/f5df4f9681736d35e14b92c58033a1cf062b3d4e/server/tserver/src/main/java/org/apache/accumulo/tserver/AssignmentHandler.java#L106) when loading a tablet.   This method could be moved to the AssignmentHandler class.  All of the error messages in the methods could be improved to provide information that the problems were seen when trying to load a tablet.  For example could change the following :

```java
    if (!extent.equals(meta.getExtent())) {
      log.info("Tablet extent mismatch {} {}", extent, meta.getExtent());
      return false;
    }
```

to the following

```java
    if (!extent.equals(meta.getExtent())) {
      log.info("Saw metadata issue when loading tablet : Tablet extent mismatch {} {}", extent, meta.getExtent());
      return false;
    }
```

**Comment by SivaTharun** [comment]
@keith-turner can i work on this issue?
