### ISSUE TITLE
Provide support for Intel QuickAssist Hadoop Codec

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2219]
**Is your feature request related to a problem? Please describe.**
Intel QuickAssist is a compression and cryptography hardware accelerator. A Hadoop compression codec exists at https://github.com/Intel-bigdata/IntelQATCodec/tree/master/hadoop_qat_wrapper, but Accumulo only supports specific, hardcoded codecs.

**Describe the solution you'd like**
Add support for the QuickAssist codec to the list of supported codecs.

**Describe alternatives you've considered**
There are no alternatives as support for codecs is hardcoded.

**Comment by EdColeman** [comment]
Probably out of scope for this change, but is there any movement towards also supporting zstd as a compression scheme.

**Comment by ctubbsii** [comment]
> Probably out of scope for this change, but is there any movement towards also supporting zstd as a compression scheme.

That was already added in #456 for 2.0. It shouldn't be backported to 1.10, because it's not a forward-compatible change suitable for a bugfix release.

**Comment by dlmarion** [comment]
Apparently my assumption that the QATCodec could read data written by the GzipCodec is incorrect. The `qzip` utility can read/write `gzip` compatible files, but it looks like the QAT-based codec works differently. Details at https://github.com/Intel-bigdata/IntelQATCodec/issues/33.
