### ISSUE TITLE
Tablet may write chop information to the metadata table after its closed.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2222]
**Describe the bug**

When CompactableImpl writes chop information [here](https://github.com/apache/accumulo/blob/a9100ac35f3d72677b767d7670dfb032c7e7d733/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L691) it could happen after [close()](https://github.com/apache/accumulo/blob/a9100ac35f3d72677b767d7670dfb032c7e7d733/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L1384) was called.  When a tablet calls `CompactableImpl.close()` it expects the call to block until all ongoing metadata writes related to compactions are complete AND prevent any new writes from occurring after the `close()` call returns.  This expectation is not being met when writing chop information to the metadata table.

**Expected behavior**

`CompactableImpl.close()` will block if there are any ongoing metadata chop writes and prevent any new ones from starting after it returns.

**Comment by DomGarguilo** [comment]
> expects the call to block until all ongoing metadata writes related to compactions are complete

For this condition I'm wondering if adding a check to the while loop in `close()` would account for this. Maybe something like:
```java
fileMgr.chopStatus != FileSelectionStatus.NOT_ACTIVE
```
> AND prevent any new writes from occurring after the `close()` call returns

For this condition maybe adding a check  [here](https://github.com/apache/accumulo/blob/a9100ac35f3d72677b767d7670dfb032c7e7d733/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L690). Something like:
```java
if (completed && !closed)
```
