### ISSUE TITLE
Add support for basic escaping of characters inside Shell commands

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2227]
**Is your feature request related to a problem? Please describe.**
Original Jira ticket: https://issues.apache.org/jira/browse/ACCUMULO-2929

Excerpt from ticket: 
```
For commands that have a -c option (e.g. InsertCommand, GrepCommand, ScanCommand),
 there is currently no way to specify a column family that contains a colon as it is
 interpreted as the delimiter between the column family and column qualifier 'cf[:cq]'.

It would be very simple to support a basic escape '\' character that would allow 
users to use column families which contain colons in the shell.
```

**Describe the solution you'd like**
It would be a useful feature to allow escaping of special characters, specifically a ' : ' in this instance. Alternatively, extra options such as -cf and -cq could be added instead.

**Additional context**
The specific function inside `ScanCommand` (utilized by `GrepCommand` and others) that fetches the Columns. 
https://github.com/apache/accumulo/blob/3da639ac6c49ad1b9671230e3443632d27887f75/shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java#L274-L275

**Comment by harjitdotsingh** [comment]
Please assign in to me. Would love to work on this
