### ISSUE TITLE
Display more compaction information in the monitor

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2230]
**Is your feature request related to a problem? Please describe.**
Original JIRA ticket: https://issues.apache.org/jira/browse/ACCUMULO-3154

Important excerpt: 
<pre>
Showing the age of the longest running scan...is helping users to understand their system better.
 It was suggested that showing the oldest compaction would be useful, too...
</pre>

**Describe the solution you'd like**
An 'Active Compactions' page in the monitor similar to that of 'Active Scans' where the server, count, and oldest age is displayed.

**Comment by milleruntime** [comment]
@Manno15 have you done anything with this? I started looking at it and it should be pretty straightforward.

**Comment by Manno15** [comment]
@milleruntime No, I haven't.

**Comment by milleruntime** [comment]
It would be nice to include how many are queued as well, like how we do on the tables and table status pages.
