### ISSUE TITLE
CompactionPlanner thread dies during continuous ingest

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo#2239]
**Describe the bug**
Found this bug while reviewing PR https://github.com/apache/accumulo-testing/pull/149. The CompactionPLanner thread dies after failing a sanity check set to confirm that the compacting files are expected files.

<details>

```
Caught an Exception in Thread[CompactionPlanner-Worker-4,5,main]. Thread is dead.

java.lang.IllegalArgumentException: Compacting not in set of all files [[A000006h.rf, 973 35], [F000006i.rf, 581 5]] [[A000006b.rf, 963 33], [F000006f.rf, 667 11]]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at org.apache.accumulo.tserver.compactions.Compactable$Files.<init>(Compactable.java:78)
	at org.apache.accumulo.tserver.compactions.Compactable$Files.<init>(Compactable.java:58)
	at org.apache.accumulo.tserver.tablet.CompactableImpl.getFiles(CompactableImpl.java:1008)
	at org.apache.accumulo.tserver.compactions.CompactionService.planCompaction(CompactionService.java:247)
	at org.apache.accumulo.tserver.compactions.CompactionService.lambda$compact$4(CompactionService.java:233)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT

**To Reproduce**
1. Create a table on a cluster via the shell
2. Run continuous ingest on this table with the accumulo-testing repo 
3. Wait a few minutes and then the error will show up in the monitor logs

**Screenshots**
![image](https://user-images.githubusercontent.com/29436247/130274017-901000df-ad37-44b3-a132-4d8877212978.png)
![image](https://user-images.githubusercontent.com/29436247/130273932-75b1c3ea-c73c-406a-8027-9ed3c77ad365.png)

**Additional context**
I have run multiple tests with various compaction opts (including the default opts and the example on the website) and the error occurs consistently for each test.
See discussion on the PR for additional details (https://github.com/apache/accumulo-testing/pull/149#issuecomment-902785315).
Code throwing the error: https://github.com/apache/accumulo/blob/8a636a3ba91f5dae1d8b09b095178889a7d79c1d/server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/Compactable.java#L78-L79

**Comment by dlmarion** [comment]
AccumuloUncaughtExceptionHandler for the win!

**Comment by Manno15** [comment]
To help differentiate between all files and compacting files, I edited the log message slightly: 
![image](https://user-images.githubusercontent.com/29436247/130479252-6f2f57c9-50a7-4cf2-998e-45fd673978ab.png)

**Comment by DomGarguilo** [comment]
> ```
> Compacting not in set of all files
> ```

Unrelated to this bug, it seems that this message could be changed to be more evident in what it refers to. I find its meaning unclear.

**Comment by Manno15** [comment]
I wonder if this is a timing issue. I added some log messages and it appears the compacting files were indeed at one point in the set of 'allFiles' but not when the sanity check took place.

**Comment by milleruntime** [comment]
> I wonder if this is a timing issue. I added some log messages and it appears the compacting files were indeed at one point in the set of 'allFiles' but not when the sanity check took place.

It may be that this is a common occurrence on a highly active system. If that is the case, it's probably worthwhile to check the files sooner, before the constructor, [as soon as we get the set](https://github.com/apache/accumulo/blob/a9100ac35f3d72677b767d7670dfb032c7e7d733/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactableImpl.java#L986). Then maybe just put a debug statement. 

It may still be a bug though, I don't know the code well enough to know the intent behind the two sets of files.

**Comment by Manno15** [comment]
> It may be that this is a common occurrence on a highly active system. If that is the case, it's probably worthwhile to check the files sooner, before the constructor, as soon as we get the set. Then maybe just put a debug statement.

Good idea, I will take a look at it.

> It may still be a bug though, I don't know the code well enough to know the intent behind the two sets of files.

Neither do I, unfortunately.

**Comment by milleruntime** [comment]
I ran the configuration from the testing branch CI locally just using Uno and I was surprised how quickly this error showed up.  It happened after only running CI for a few minutes. I will take a closer look at this code again.

**Comment by milleruntime** [comment]
> To help differentiate between all files and compacting files, I edited the log message slightly:
> 
> ```
> Compacting not in set of all files [[C00000o6.rf, 30685229 787039], [F00000on.rf, 1723078 46410], [A00000ed.rf, 34076028 870729]],
>  compacting files [[C00000k7.rf, 10046277 266635], [C00000mz.rf, 9978439 255846], [F00000ny.rf, 2311671 61351], [C00000h4.rf, 7956997 203207]]
> ```

@Manno15 can you push this improvement up to main? I think it would be a good start to improve the log message.

**Comment by Manno15** [comment]
Yeah, I will do that.

**Comment by Manno15** [comment]
@milleruntime I created PR #2243 for this. Was easier to do it this way instead of looking for my password token.

**Comment by keith-turner** [comment]
@Manno15  would you happen to know the specific commit you were using for Accumulo 2.1.0-SNAP?

**Comment by Manno15** [comment]
The latest commit should still have the error occur.
