### ISSUE TITLE
SimpleTimer replacement is not a Singleton

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2280]
ThreadPools.createGeneralScheduledExecutorService replaced SimpleTimer, but a new ThreadPoolExecutor is being created for each call instead of re-using a singleton ThreadPoolExecutor for that property.

**Comment by milleruntime** [comment]
Your mention of singleton usage reminded me of a class @keith-turner created to manage static singletons, the `SingletonManager`. I don't know if it applies or not but I thought it was worth mentioning. https://github.com/apache/accumulo/blob/323bbea9a48930a6aa39546dc7f15943a1574e60/core/src/main/java/org/apache/accumulo/core/singletons/SingletonManager.java

**Comment by ctubbsii** [comment]
> Your mention of singleton usage reminded me of a class @keith-turner created to manage static singletons, the `SingletonManager`. I don't know if it applies or not but I thought it was worth mentioning. https://github.com/apache/accumulo/blob/323bbea9a48930a6aa39546dc7f15943a1574e60/core/src/main/java/org/apache/accumulo/core/singletons/SingletonManager.java

The SingletonManager stuff is quite complicated. It's not intended to manage all singletons, but rather to manage closable singleton lifecycles, and I would argue against reusing it for more singletons. It's primary use case is for implementing a singleton lifecycle for the closeable AccumuloClient, when legacy Instance/Connector APIs are used, so we can clean up the internal AccumuloClient when there are no more legacy Instance/Connector objects in use. I anticipate the SingletonManager class and related complex code will be removed when we remove those deprecated APIs from our code base.

**Comment by keith-turner** [comment]
> It's primary use case is for implementing a singleton lifecycle for the closeable AccumuloClient, when legacy Instance/Connector APIs are used, so we can clean up the internal AccumuloClient when there are no more legacy Instance/Connector objects in use. I anticipate the SingletonManager class and related complex code will be removed when we remove those deprecated APIs from our code base.

That is not quite right. The Instance/Connector code could be removed and we would still need the singleton manager.  Its needed to manage singletons in the implementation that were never moved into the client context.  Once these singletons are moved into the client context we can remove the SingletonManager.  Instance/Connector does not prevent this from movement from happening, its just that no one has ever done the work.  If this work were done, I think it would be easy to refactor the Instance/Connector code to use a singleton client context object.

**Comment by ctubbsii** [comment]
Thanks for the clarification, @keith-turner ; my misunderstanding was based on how/when we use the various SingletonManager modes. In case it helps others looking at this, the best way to understand what singletons are being managed is to see which SingletonService objects are registered with the SingletonManager. (`grep -Rl SingletonManager.register **/*.java`)

**Comment by milleruntime** [comment]
@keith-turner or @ctubbsii do you know if there a ticket for this work?

**Comment by ctubbsii** [comment]
> @keith-turner or @ctubbsii do you know if there a ticket for this work?

There is a general informal initiative spearheaded by some of us, reflected in our contributions, to try to remove our static resources in favor of managing resources with lifecycles. This was the basis of many decisions in 2.0, such as the creation of AccumuloClient, and before that, the creation of ClientContext and ServerContext. But, I do not think there is any specific tickets to complete the transition, for either the singletons managed by SingletonManager or for any other static resources elsewhere. It's mostly just a "adopt this principle and fix as we go" sort of thing, as far as I can tell.

**Comment by keith-turner** [comment]
> @keith-turner or @ctubbsii do you know if there a ticket for this work?

Would probably make sense to open an issue for each thing that [registers with the singleton manager](https://github.com/apache/accumulo/blob/d4cb0ebacddcad11a520e87829714f3f67dc71d5/core/src/main/java/org/apache/accumulo/core/singletons/SingletonManager.java#L115) to explore moving it to client or server context.
