### ISSUE TITLE
MergeIT timing out on some machines

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2295]
MergeIT is consistently timing out on my instance. It seems like a resource issue, perhaps with the GC because I saw a warning in the logs. One tserver reported this warning during the second test ran, mergeTest:
<pre>
TabletServer_512107.out [server.GarbageCollectionLogger] WARN : Running low on memory
</pre>

**Comment by milleruntime** [comment]
This IT didn't have any problems until recent ThreadPool changes, beginning with https://github.com/apache/accumulo/pull/2274

**Comment by dlmarion** [comment]
I believe I have found the culprit [here](https://github.com/apache/accumulo/pull/2278/files#diff-467b6cb7af0f7b7339d81d3112329b8e19557e685a3c659bc623160826c8f01dL64). Fate.TransactionRunner would sit in a loop until the Fate transaction was successful. Now, it runs once, and if `op.isReady` returns <> 0, then it bails.

**Comment by Manno15** [comment]
That was my suspicion as well. I reverted some of the changes in Fate, including that one, and the ITs pass.

**Comment by dlmarion** [comment]
Putting up a PR shortly
