### ISSUE TITLE
Add parameter to Merge command to cancel blocking fate operations

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2328]
**Is your feature request related to a problem? Please describe.**
The merge operation tries to get a write lock on the table. It can't get a write lock if there are any other fate transactions that have the read lock or write lock. There are cases where a merge operation needs to be done now as opposed to when it can get the lock.

**Describe the solution you'd like**
A parameter to the merge command that when supplied will cancel or fail any/all fate transactions that are blocking the merge command from getting the write lock on the table

**Describe alternatives you've considered**
The current mechanism for doing this is to shut down the master (to release the fate lock) and manually fail/cancel the transactions on the table. Another option would be to add a new command that would pause all activity on a table so that administrative actions could be performed, but this seems much more complex.

**Additional context**

**Comment by dlmarion** [comment]
I'm thinking about closing #2329 and attacking this in a different way. Talking with some users that have this type of issue it would be useful to:

  1. Print the list of blockers for a FaTE transaction in the manager log when the transaction is first created.
  2. Allow a user to delete/cancel a FaTE transaction without taking down the manager.

**Comment by ctubbsii** [comment]
> @keith-turner @ctubbsii - is there a reason that the Shell fate commands modify ZK directly instead of making modifications via the Manager?

It's probably because the idea is that when you are doing "surgery" on fate, you're probably doing it when there's a problem, in which case you probably don't want the Manager running and executing fate transactions. At least, I think that was the motivation for having the separate FateAdmin utility, whose functions were rolled into the Shell.

**Comment by dlmarion** [comment]
I created #2462 so that users will have a better idea of the state of their `merge` transaction and what other transactions may be blocking it. With this change, `fate print` should show which transactions are running for a table and which ones are waiting to be run. If a user has submitted a `merge` command and its not running, they should have a better idea of which transactions they need to delete to get their `merge` command to run.

**Comment by dlmarion** [comment]
I created #2467 so that users can attempt to cancel FaTE transactions that have been created without taking down the Manager. The user, in the Shell, would run the command `fate fail-live <txid> <txid>`. The Shell would connect to the Manager and call the cancelFateOperation method on the Thrift API. I think with the changes in #2462 and #2467 users should be able to more easily identify Fate transactions that are running on a table and which ones have been submitted so that they can then cancel all of the running and submitted to get the preferred transaction to run.
