### ISSUE TITLE
OutOfMemoryError During BinMutations cause stuck BatchWriter

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#2331]
**Problem**
The first step in flushing mutations from the Batch Writer to the Tablet Servers involves binning mutations by destination tablet server. If the tablet server throws an OutOfMemoryError or any non-Exception based Throwable, the error will be thrown on the client side. The error will not be caught and will cause the bin thread to die without reporting the fact that an error occurred. This is unrecoverable and leaves the batch writer stuck waiting for mutations get flushed that never will.

**Affected versions**
1.10.x, main

**To Reproduce**
Not easily reproducible.
One could write a rogue iterator that throws an OutOfMemoryError when the metadata table is being scanned.

**Bug Location**
https://github.com/apache/accumulo/blob/5f20e38628abd6385a5ee652634f4d748ecd013f/core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java#L706

this:
`catch (Exception e) {`
should be changed to:
`catch (Throwable e) {`

**Comment by andrewglowacki** [comment]
After looking main over more closely, I see what @dlmarion was talking about with regard to changes in #1840. I decided not to do anything on main since #1840 explicitly prevented TabletServerBatchWriter from catching Throwbles.

However, after considering the discussion in #1840, I think the changes there were all made from the server's perspective even though TabletServerBatchWriter is primarily a client API. It seems TabletServerBatchWriter (and possibly other classes used by the client) should be more cognizant of the environment it is running in when deciding whether to report Throwables to the client verses halting the JVM. I don't think libraries should be making these kinds of decisions for their user.

**Comment by dlmarion** [comment]
> I think the changes there were all made from the server's perspective even though TabletServerBatchWriter is primarily a client API.

Fair point about the client API, but I'm struggling with how to deal with this. Suggestions would be welcome. The [api](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Error.html) docs say " a reasonable application should not try to catch" Error's. The [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-11.html#jls-11.3) says that "... catching errors from which recovery is typically not possible."

If we want the client application to handle Error's, maybe the right approach is:

  1. Only halt the VM in the AccumuloUncaughtExceptionHandler when it's running in the Accumulo server processes. Is there currently a way to determine this? One thought would be to set a system property in the AbstractServer constructor.
 
  2. For threads in the client, allow the thread to die, and check to see whether or not it's still alive. Or maybe there is a client side uncaught exception handler.

**Comment by andrewglowacki** [comment]
Yeah it's a tricky. Unfortunately in this situation the error is recoverable and handling it is required in order to prevent resource leaks (stuck threads in this case).

In either case, I think the system property is probably the easiest way to determine whether or not to halt. As far as notifying the user, I think the cleanest way is to use the existing mechanism (in 1.10.x) where the Throwable is re-thrown. Alternaively, it could be provided to a client side ucaught exception handler, but the BatchWriter/BatchScanner/etc would still have to be closed so the user thread is freed.

**Comment by ctubbsii** [comment]
Trying to recover from Errors seems like the moldy bread of the Java world. Yeah, sure, *maybe* you can cut around the problem, and continue eating safely, but it's not a great idea. When mold occurs, you can't trust that there's not mold in smaller, less visible amounts on the rest of the loaf. Similarly, when an Error occurs, I don't see how you can trust the rest of the state of the JVM... especially something like OutOfMemoryError, which can have cascading effects on other threads in the JVM, possibly really important ones in your dependent libraries or even internal to Java itself. Errors aren't just something you can catch, clean up, and have confidence that all is fine afterwards... they reflect a serious problem with the overall state of the application. Java's own documentation says that these are likely not recoverable, so I have a hard time understanding the desire to try to recover from them, or the confidence that one will actually be able to pull it off reliably without unforeseen consequences.

Even if we were to make OutOfMemoryError in these particular threads not terminal, we can't assume Errors in the general case are safe enough to try to handle. So, we'd have to start baking in heuristics to try to determine which of the "likely not recoverable" errors we believe are more likely than others to be able to recover from, and we have to include assumptions about what triggered the Error as part of those heuristics. Or, we have to treat them all the same, and pass these through to calling client code, to let them decide what to do. Either way, that seems likely to increase code complexity, to support highly questionable behavior.

If there's a high demand or strong use case for it, I suppose I could support the idea of making the uncaught exception handler pluggable via client API. But, it really seems like a bad idea to me... just like moldy bread.

**Comment by dlmarion** [comment]
So, two other related thoughts here:

1. There are many flavors of OutOfMemoryError. I imagine that you are trying to handle the case where it's "java heap space" by trying to create a smaller object (From what I read, Java heap space is thrown based on a pre-calculation of the size of the object being allocated and the max heap size, thus the VM didn't really run out of memory). It's not clear to me how you would handle other flavors of OutOfMemoryError: direct memory, metaspace, gc overhead limit exceeded, etc.

2. I don't see how you can effectively handle the "java heap space" OOME when it occurs in another thread. The asynchronous nature of this definitely increases the complexity.

A lot of the recommendations for handling OOME's deal with finding memory leaks and/or changing VM parameters. There is also the case where it's not a leak and the application is trying to allocate more memory than it was given, which leads back to changing VM parameters.

This is also a good time to remind that there are new VM [options](https://bugs.openjdk.java.net/browse/JDK-8258058) for exiting the VM on OOME, which seem handy, but do [not](https://bugs.openjdk.java.net/browse/JDK-8155004) work when the reason for OOME is the inability to create a new native thread.

**Comment by dlmarion** [comment]
@ctubbsii  - do you have any thoughts on not halting the VM from the AccumuloUncaughtExceptionHandler when it's being used in a client application? I do agree with @andrewglowacki that libraries should not be shutting down the VM.

**Comment by ctubbsii** [comment]
> libraries should not be shutting down the VM

The library didn't cause the OutOfMemory. The alternative is that the library intentionally leaves the client in a bad, likely unrecoverable, state. I'm not sure that's any better. This isn't that different from a segfault in a library that causes a process to die. Or, a memory-hogging native process to cause another process in the OS to be killed by the OOM-killer. No, a library shutting down the VM isn't good... but there aren't reliably good outcomes under Error conditions, by definition... that's why they are an Error instead of an Exception.

> Edit - I see now, you said:
> 
> > If there's a high demand or strong use case for it, I suppose I could support the idea of making the uncaught exception handler pluggable via client API.

I'd support this approach. But, I have two standing concerns:

1. Enabling users to accidentally shoot themselves in the foot (and possibly "blame" Accumulo, because the errors appear to originate in Accumulo threads, and mishandling of the errors could lead to user code being affected), and
2. Increased code complexity to support this use case (that we might not even recommend users exercise).

**Comment by dlmarion** [comment]
> This isn't that different from a segfault in a library that causes a process to die. Or, a memory-hogging native process to cause another process in the OS to be killed by the OOM-killer. 

There are good examples.

**Comment by keith-turner** [comment]
>  I do agree with @andrewglowacki that libraries should not be shutting down the VM.

The uncaught handler that hlts seems to be setup by Threads.createThread(...).  One possible way to make this not halt for client code is to move this to client context.  So client context could have a create thread method that does not halt in the createThread method and server context could override createThread and halt in the uncaught handler.

**Comment by andrewglowacki** [comment]
@dlmarion exactly there are many flavors of OOM error.
@ctubbsii OOM errors are recoverable in certain situations.

1. The one I see regularly is the 'direct memory' flavor. This one occurs when you try to allocate a direct byte buffer, but you've reached your pre-configured direct memory limit. This happens because direct memory is only freed after DBBs are GC'd. This is unlike normal resources where you can call close() and the resource is freed immediately. DBBs are used in Hadoop (and Thrift apparently) to improve I/O performance. Therefore, as long as you wait a little while, direct memory OOM errors will eventually go away and they don't have anything to do with normal JVM memory.

2. The other case is less exact but I still encounter it frequently. Suppose you have N threads each executing a high memory consuming operation local to the thread. Then suppose you run out of memory or reach the GC overhead limit in one or more of them, provoking a OOM error. In this situation, once the thread is terminated, the GC can run, and the JVM will have plenty of memory free again.

Either way, it doesn't matter who caused the OOM error. It is up to the library maintainer to ensure resources are properly freed *in all cases*. The JVM itself does this with the try-with-resources construct. It doesn't stop to verify whether or not the exception that's unrolling the stack is a Error. It just closes the resource it's managing.

**Comment by andrewglowacki** [comment]
Sorry I think I've gotten this issue quite a bit off topic. Clearly main's batch writer will not become stuck in this case, so my single PR resolves this issue. 

I will (or someone can if they think it's still worth addressing) can open a separate issue for Error handling in client APIs on main.

**Comment by dlmarion** [comment]
> The uncaught handler that hlts seems to be setup by Threads.createThread(...). One possible way to make this not halt for client code is to move this to client context. So client context could have a create thread method that does not halt in the createThread method and server context could override createThread and halt in the uncaught handler.

This makes sense, but then I would have to wire up the Context in all the places, possibly modifying even more code where a Thread is created but there is no reference to the Context. If we want to make it such that an Error does not halt the client VM, then it looks like the `SingletonManager.getMode()` might do what I need. `SingletonManager.setMode(Mode.SERVER)` is only called from `ServerInfo`. If the value is `Mode.SERVER`, then halt the VM on Error. Otherwise, just log the fact that the Thread has died. To be clear this would allow the Thread to die, as would happen prior to 2.1.0, in clients. This would not propagate the Error back to the caller so that they could handle the Error.

**Comment by keith-turner** [comment]
> then it looks like the SingletonManager.getMode() might do what I need

That would work perfectly, I like it.  Its internal code so it could always be improved later if we think of a better way to solve the problem,  But it would be nice to fix the problem before release.

I am not sure its appropriate for this particular case but one thing to consider in general from an API perspective is letting users pass in ExecutorServices and Thread Factories.  The new bulk load API accepts an ExecutorService, giving users more control over background task that execute on the client side as part of a bulk load.  I did look around a bit to see if passing in a ThreadFactory would be better than letting a user pass in an uncaught exception handler and did not come to a conclusion.

**Comment by ctubbsii** [comment]
> @ctubbsii OOM errors are recoverable in certain situations.

I agree that some are. I just don't think we can *reliably* distinguish between them, or that it's worth adding substantial code complexity to try to add in heuristics to try to distinguish. It may be worth adding minimal code complexity to allow users to decide, though.

**Comment by dlmarion** [comment]
#2554 includes a change in 2.1.0 that provides a default UncaughtExceptionHandler in the client that only logs exceptions / errors, it does not terminate the VM like the AccumuloUncaughtExceptionHandler does on the server side. #2554 also provides the user the ability to supply their own UncaughtExceptionHandler implementation.
