### ISSUE TITLE
PerTableVolumeChooser config error is misleading

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2353]
When trying to configure a PerTableVolumeChooser, if you don't set the properties correctly, an error gets printed that is misleading:
<pre>
2021-11-10 13:37:15,981 [thrift.ProcessFunction] ERROR: Internal error processing waitForFateOperation
org.apache.accumulo.server.fs.VolumeChooser$VolumeChooserException: Property volume.chooser or volume.chooser.default must be a valid VolumeChooser to use the PerTableVolumeChooser
</pre>

This error message neglects to consider the "table.custom" and "general.custom" prefixes for the properties.

**Comment by ctubbsii** [comment]
It looks like there's a couple places in that class that only show the property without the suffix in the error message and/or logs.
