### ISSUE TITLE
Remove unused code in DatafileManager

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2355]
In DatafileManager,java, there is a while-loop whose condition, a boolean value, is always false - meaning the loop will never be entered. The boolean is instantiated as false and never changed. My first thought was to just remove the unused loop and its boolean condition however I first wanted to see if anyone knew what was supposed to be going on here.

The boolean value:
https://github.com/apache/accumulo/blob/52e80b1d11f0093a07a2d886d85aa74f7998096b/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java#L84

The while loop (only places that the above boolean is used):
https://github.com/apache/accumulo/blob/52e80b1d11f0093a07a2d886d85aa74f7998096b/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/DatafileManager.java#L95-L101

**Comment by Manno15** [comment]
Seems some code was removed in #1490 that did change the value of `reservationsBlocked to true.

**Comment by ctubbsii** [comment]
The code in #1490 looks like it became vestigial after fixing issue #936 in PR #1313. The code here is now also vestigial. It was only ever used for scanning the root tablet when we relied on HDFS being the canonical source of truth for the files the root tablet was using. Since #1313, that is no longer needed. This can be cleaned up.

**Comment by milleruntime** [comment]
> The code in #1490 looks like it became vestigial after fixing issue #936 in PR #1313. The code here is now also vestigial. It was only ever used for scanning the root tablet when we relied on HDFS being the canonical source of truth for the files the root tablet was using. Since #1313, that is no longer needed. This can be cleaned up.

I had a feeling this was the case but wasn't able to confirm it looking at the code. Thanks for looking at this!

**Comment by filipedfr** [comment]
Worked this out in PR #2418. Sorry if I forgot to request assignment first.
