### ISSUE TITLE
Push tablet partitioning based on DataLevel to Ample

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2373]
In  #2320 we partition tablets based on their DataLevel into two groups: one set who's DataLevel is USER and another containing the remaining tablets (those who's DataLevel is ROOT or METADATA). This needs to happen so we can use `.readTablets()` on the DataLevel.USER tablets in order to reduce RPCs.

This partitioning logic should be pushed to ample.

EDIT: this will need to wait until #2320 is merged.

**Comment by DomGarguilo** [comment]
For context, here is the comment where this change was first suggested:

https://github.com/apache/accumulo/blob/6cfb9180a0d3e5115922314ff2062e0706ef0795/core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletsMetadata.java#L324-L328

So if the tablet server was serving the root or metadata tablets, then it would throw an exception for this.  Could partition the tablets into user and non-user (root,metadata) tablets.  Can use readTablets() w/ the user tablets.  For the non-user would have to call readTablet() one at a time.  Could do that partitioning in the tablet server code for now and in a later PR push it down into Ample and remove it from the tablet server code.

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/2320#discussion_r747057650_

**Comment by keith-turner** [comment]
@DomGarguilo are you working on this still? I was thinking of taking a look into it.

**Comment by DomGarguilo** [comment]
> @DomGarguilo are you working on this still? I was thinking of taking a look into it.

Go ahead, I took a quick look but then got sidetracked.
