### ISSUE TITLE
`accumulo-cluster start` does not start remote tablet servers

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2379]
**Describe the bug**
Running `accumulo-cluster start` does not start TabletServers running on other nodes. It appears that there is an extra parameter being passed in the ssh command after the class name. This is in the tabletserver error file:

```
Was passed main parameter '' but no main parameter was defined in your arg class
```

This is in the tabletserver out file:

```
Usage: tserver [options]
  Options:
    -a, --address
      address to bind to
    -h, -?, --help, -help

    -p, -props, --props
      Sets path to accumulo.properties.The classpath will be searched if this 
      property is not set
    -o
      Overrides configuration set in accumulo.properties (but NOT system-wide 
      config set in Zookeeper). Expected format: -o <key>=<value>
      Default: []
```

The workaround is to go to the remote node and run `accumulo-cluster start-here`.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: `HEAD` of `main`
 - OS: CentOS 7
 - Others:

**To Reproduce**
Create a two node cluster, run `accumulo-cluster start`

**Comment by DomGarguilo** [comment]
@Manno15 and I also ran into this while setting up a cluster yesterday. Our workaround was to run `accumulo-service tserver start` on the nodes.

**Comment by dlmarion** [comment]
I believe the problem is [here](https://github.com/apache/accumulo/blob/main/assemble/bin/accumulo-cluster#L134) when there is no 4th argument
