### ISSUE TITLE
Cancel specific external compaction

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2386]
A user can call "compact --cancel" on a table which will cancel all compactions for that table. It would be nice to be able to cancel a specific compaction, which I think can now be done easily using the ECID. I think this will only work with external compactions though as we don't have a way to specify an internal compaction.

**Comment by keith-turner** [comment]
What are the use cases for this?

**Comment by milleruntime** [comment]
> What are the use cases for this?

I have a long running compaction that I want to cancel but I don't want to cancel all compactions on a table. My configuration has changed since the long running compaction started and a new compaction with the proper config has started.

**Comment by dlmarion** [comment]
Based on [this](https://github.com/apache/accumulo/blob/main/server/compactor/src/main/java/org/apache/accumulo/compactor/Compactor.java#L196), you can remove the ecid row from tablet metadata

**Comment by keith-turner** [comment]
> I have a long running compaction that I want to cancel but I don't want to cancel all compactions on a table.

Cancel in the context of the compact command currently has the meaning that it interrupts user compactions and prevents new ones from starting.   May not want to overload this.  Could possibly do something like `compact --restart <table>[<optional start row>:<optional end row>]` which would restart any compactions on a table within for tablets that fall within a given range.

**Comment by keith-turner** [comment]
> Based on this, you can remove the ecid row from tablet metadata

Also for internal compactions can kill the tserver running it

**Comment by milleruntime** [comment]
> and prevents new ones from starting.

Do you mean that it prevents new ones from starting until all compactions have stopped?

**Comment by milleruntime** [comment]
@dlmarion @keith-turner are you giving ideas for implementing this enhancement or advocating for alternatives?

**Comment by dlmarion** [comment]
My comment was an idea for implementation. Deleting the `ecid` row from the tablet metadata should cause the Compactor to stop compacting. Not sure what would happen on the tablet server though...

**Comment by milleruntime** [comment]
I was thinking of a way to make this easier for the user to call but since the external compactions are experimental I didn't want to introduce anything into the public API yet. I thought I could create a server utility to cancel compactions or modify the Compaction Coordinator to accept a parameter to call a method, something that could be called using the scripts. I am not sure what is the best approach. Thoughts?
