### ISSUE TITLE
Revise what happens when a mismatch in tablet metadata is discovered

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2404]
As a follow on to #2320, it was suggested that the action taken when a mismatch in tablet metadata is discovered, be revised. Currently, an error is just logged. I wanted to create a ticket to discuss possibilities of what to do in this situation. Below is from the original discussion:

> Probably do not want to throw an exception here as it will not lead to anything useful since this is being called by a timer thread.  For now logging the error seems good.  

> Would probably be good to look into opening up a follow on issue about taking automated action when this is detected (something more than logging an error). Not sure what automated action would be best to take, but could imagine many possible actions (could make the tablet non-functional, report something on the monitor, etc).

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/2320#discussion_r752627377_

**Comment by DomGarguilo** [comment]
For context, the following is the portion of code in question:
https://github.com/apache/accumulo/blob/1687ede211888da0dcd40323c894eff0e00fce26/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1423-L1429
Specifically, the question is, what should be done instead of/in addition to the error log here?

**Comment by dlmarion** [comment]
@DomGarguilo  - this code was modified in #2574 . Do you think more needs to be done here?

**Comment by DomGarguilo** [comment]
> @DomGarguilo - this code was modified in #2574 . Do you think more needs to be done here?

Nothing more needs to be done as far as I'm concerned. It looks like @keith-turner, who originally suggested re-evaluationg this case, has already taken another look at the code and made changes so I think this can be closed.
