### ISSUE TITLE
bin/accumulo-util load_jars_hdfs does not set NUM_TSERVERS from cluster.yaml

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2440]
**Describe the bug**
The load_jars_hdfs function in accumulo-util does not use the new cluster.yaml file, it uses the old tservers file.

**Versions (OS, Maven, Java, and others, as appropriate):**

**To Reproduce**

**Expected behavior**
load_jars_hdfs should parse the cluster.yaml configuration like accumulo-cluster does.

**Screenshots**

**Additional context**

**Comment by ctubbsii** [comment]
load_jars_hdfs seems like a cluster-management function and should probably be moved to accumulo-cluster, or deleted entirely, as people can upload their own jars without our help; we don't necessarily need to be responsible for a basic file copy tool that isn't directly related to Accumulo's functionality. I believe this was primarily used with the VFS classloader, which was offloaded into a separate pluggable SPI
