### ISSUE TITLE
NativeMapIT is having issues

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2450]
**Describe the bug**
An error occurs when running `NativeMapIT`.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [main]
 - OS: [EC2 Ubuntu 20.04]

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Run `mvn clean verify -Dit.test=NativeMapIT -Dtest=foo -Dspotbugs.skip -Drat.skip -Dformatter.skip -Dcheckstyle.skip -Dmodernizer.skip -Dimpsort.skip -Dsortpom.skip -DfailIfNoTests=false`
2. See error.

<pre>
[ERROR] Please refer to /home/mike/workspace/accumulo/test/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/mike/workspace/accumulo/test && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /home/mike/workspace/accumulo/test/target/surefire/surefirebooter17189022590803230439.jar /home/mike/workspace/accumulo/test/target/surefire 2022-02-01T14-41-43_964-jvmRun1 surefire10656440039417701399tmp surefire_08533247163755836578tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.accumulo.test.functional.NativeMapIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:301)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:249)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
...
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/mike/workspace/accumulo/test && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /home/mike/workspace/accumulo/test/target/surefire/surefirebooter17189022590803230439.jar /home/mike/workspace/accumulo/test/target/surefire 2022-02-01T14-41-43_964-jvmRun1 surefire10656440039417701399tmp surefire_08533247163755836578tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] Crashed tests:
[ERROR] org.apache.accumulo.test.functional.NativeMapIT
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:690)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:447)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:423)
[ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
</pre>

**Expected behavior**
The Test to pass

**Comment by milleruntime** [comment]
This is due to missing native maps
<pre>
2022-02-01T14:42:51,375 [memory.NativeMapLoader] ERROR: FATAL! Accumulo native libraries were requested but could not be be loaded. Either set 'tserver.memory.maps.native.enabled' to false in accumulo.properties or make sure native libraries are created in directories set by the JVM system property 'accumulo.native.lib.path' in accumulo-env.sh!
</pre>

**Comment by ctubbsii** [comment]
It looks like maybe this escaped notice because it was frequently run in a reused JVM where the native maps had been loaded by another test. In any case, I know what's wrong and will have a fix soon.
