### ISSUE TITLE
Explore moving Fate isReady Logic to call methods

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2466]
Some of the operations in FATE perform business logic (aka do more then just check state) in their `isReady` methods. I think it would be good to try and move the logic of these operations to their `call()` methods since we tend to assume the `isReady` method is just checking state. It looks like the worst offenders are: BulkImport, Compact and the ShutdownTServer operations

**Comment by jmark99** [comment]
After examining ticket, the `isReady` methods successfully perform steps that need to be performed before the execution of the `call` methods. The use of the 'deferTime' delay makes refactoring much of the logic out of the `isReady` problematic. Given that there are no issues with the current state of the code, this ticket is going to be closed.  If someone wishes to address the issue at a later time, the ticket can be re-opened or a new ticket created.
