### ISSUE TITLE
FateLogger bug

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2469]
The Fate logger will log properties set in ZK but the method in `ZooStore` appends to the property name `"/prop_" + prop` so what is logged by the logger won't match up what is in ZK.
https://github.com/apache/accumulo/blob/aab34a980d7a9ccad63797913b99b331c5cbbaae/core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java#L128-L132

**Comment by Manno15** [comment]
Are you suggesting that the log statement in `FateLogger` include the prop_? Beyond that, the log statements do vary quite a bit. 

```
zoostore /accumulo/c1103b36-2a1b-42c2-90e0-27e1bc895a6b/fate/tx_60ab6ecd10fcdfed/prop_debug [83, 32, 67, 114, 101, 97, 116, 101, 84, 97, 98, 108, 101] OVERWRITE
```
vs what is in FateLogger: 

```
setProperty FATE[60ab6ecd10fcdfed] debug CreateTable
```

A small change to include more info on what debug stands for in the latter log message could be useful.

**Comment by milleruntime** [comment]
Yes, anything else in the logs would be more useful

**Comment by ctubbsii** [comment]
This appears to be addressed in #2805. It was reopened, but it's not clear why it was reopened. I'm re-closing for now, because it looks like it was reopened accidentally. If not, please add more detail on why it is being reopened.

**Comment by EdColeman** [comment]
#2805 added a little more information - but this issue is requesting additional changes to the Fate logging that would provide additional information / context that help troubleshooting issues beyond the fate transaction id.

**Comment by milleruntime** [comment]
> #2805 added a little more information - but this issue is requesting additional changes to the Fate logging that would provide additional information / context that help troubleshooting issues beyond the fate transaction id.

Ed is correct but the issue still exists. I will fix this issue since it seems to have caused a lot of confusion.
