### ISSUE TITLE
Document Fate zookeeper layout

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2479]
Fate has a specific layout in zookeeper. It should be documented.

Originally a JIRA issue: https://issues.apache.org/jira/browse/ACCUMULO-1298

**Comment by EdColeman** [comment]
Addressed in https://github.com/apache/accumulo-website/pull/328

**Comment by EdColeman** [comment]
Closed with https://github.com/apache/accumulo-website/pull/328
