### ISSUE TITLE
Compaction cancellation might not be working in 1.x

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2482]
**Describe the bug**
It's been reported that the compaction cancel command does not work in 1.x

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.x

**Additional context**
For comparison, in 2.x the FileCompactor.compactLocalityGroup method calls CompactionEnv.isCompactionEnabled() to determine if the Compaction has been cancelled.

**Comment by ctubbsii** [comment]
1.10.2 is pretty far along. It doesn't change the status quo with respect to compactions. If this is true, then we can easily release a 1.10.3 once it is fixed. I don't think we need to hold up 1.10.2 for something that is not yet known to be a problem, never mind a fix being started or completed.

**Comment by dlmarion** [comment]
1.x is EOL. I'm closing this.
