### ISSUE TITLE
Update checkstyle to ban "string1" + "string2"

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2511]
**Is your feature request related to a problem? Please describe.**
Sometimes when we edit code, some strings wrap differently than they did before we changed it. So, we sometimes get something like: `String myMessage = "some part of message " + "the rest of the message";` when we could just have `String myMessage = "some part of message the rest of the message";`
This can occur if previously the second half of the message had wrapped onto the next line, so we needed the concatenation to make it look okay, but now the strings are being concatenated on the same line.

**Describe the solution you'd like**
Find and fix all occurrences where two string literals are concatenated, replacing all `"a" + "b"` with `"ab"` (only considering concatenations that are on the same line; concatenations that exist to wrap a string onto the next line are okay).
Add a regular expression to the checkstyle config to ban the sequence `" + "` in our code to detect and prevent new occurrences, with a reasonable error message when the pattern is seen.

**Describe alternatives you've considered**
Could just ignore since it's not particularly harmful, it's just ugly.

**Additional context**
N/A

**Comment by KikiManjaro** [comment]
Hi :)

I'm trying to add :

`
<module name="RegexpStringToStringConcatenation">
                                    <property name="format" value="&quot; + &quot;" />
                                    <property name="message" value="Concatenation from string to string is not needed"/>
                                </module>
`

to the pom.xml inside

`
<checkstyleRules>
                        <module name="Checker">
`

but it's not working, did i missed something ?

**Comment by ctubbsii** [comment]
> but it's not working

Can you explain what's not working? What problem did you encounter?

**Comment by KikiManjaro** [comment]
While running maven task `checkstyle:check` an error is thrown:
`
Element type "property" must be followed by either attribute specifications, ">" or "/>".
`
I think it come from the Regex itself but not sure.

**Comment by ctubbsii** [comment]
Try this one:

```xml
                <module name="RegexpSinglelineJava">
                  <!-- double escape quotes because checkstyle passes these through another xml parser -->
                  <property name="format" value="&amp;quot; [+] &amp;quot;" />
                  <property name="message" value="Unnecessary concatenation of string literals" />
                </module>
```

**Comment by KikiManjaro** [comment]
That was it thanks :D !
