### ISSUE TITLE
Test metrics showed up in logs

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2527]
I am not sure why this happened but a target directory with test-metrics.metrics showed up in the logs directory when I was testing in Uno. It is possible this has something to do with my branch and the changes I am working on.
<pre>
09:48:54 {main} ~/workspace/uno/install/logs/accumulo$ ll target/
total 8
drwxrwxr-x 2 mike mike 4096 Feb 25 09:35 ./
drwxrwxr-x 3 mike mike 4096 Feb 25 09:48 ../
-rw-rw-r-- 1 mike mike    0 Feb 25 09:35 test-metrics.metrics
</pre>

**Comment by ctubbsii** [comment]
We have no such file present in our repository or mentioned in any of our code. I do not know where this could have come from. It is most likely specific to your working branch / dev environment and not a problem with the project.

**Comment by DomGarguilo** [comment]
It looks like this file name is referenced here:
https://github.com/apache/accumulo/blob/b63e51de09db8518302f88705d9b1eb7c503a6e6/test/src/main/resources/log4j2-test.properties#L149

Does the file contain anything? @milleruntime

**Comment by milleruntime** [comment]
No the file is empty. I was using the testing repo to create a CI table so its possible its coming from there.

**Comment by ctubbsii** [comment]
> No the file is empty. I was using the testing repo to create a CI table so its possible its coming from there.

I think by default the `log4j2-test.properties` file [will take precedence over other log4j2 config files](https://logging.apache.org/log4j/2.x/manual/configuration.html#Automatic_Configuration), if it's found on the class path. However you packaged up the test jar, it seems you may have picked up a config file that was only intended to be part of our `accumulo-test` integration test jar.

**Comment by ctubbsii** [comment]
> OK thanks. I will close this and chalk it up as Log4j shenanigans.

Were you able to figure out how the file got on your Uno class path? Was the accumulo-test jar put on the class path (it shouldn't be)? Or did it get there some other way?

**Comment by milleruntime** [comment]
> Was the accumulo-test jar put on the class path

I copied it to the accumulo lib directory. I was using the `SlowIterator` to test FATE transactions.

**Comment by ctubbsii** [comment]
> > Was the accumulo-test jar put on the class path
> 
> I copied it to the accumulo lib directory. I was using the `SlowIterator` to test FATE transactions.

Cool. That explains it. This is related to my observations in #2497. It's possible we could move that log4j config file out of the root, and instead put it in a subdirectory where it won't automatically get picked up. We can set some config in the maven-failsafe-plugin to explicitly set the log4j location property for our tests, so they can find the config, but it won't leak into the jar if it gets used elsewhere. If I remember correctly, this and `shellit.shellit` are the last files to move after your changes in #2499 . This one was causing problems this time, but `shellit.shellit` can also be moved.

**Comment by ctubbsii** [comment]
> and instead put it in a subdirectory where it won't automatically get picked up

Or anywhere outside of `test/src/main/resources`

**Comment by ctubbsii** [comment]
Re-opening to relocate the log4j test config to a different directory, as proposed above.

**Comment by ctubbsii** [comment]
@milleruntime I see you self-assigned. I can do it if you don't want to. Just let me know.

**Comment by milleruntime** [comment]
Since I made the other changes, I was going to try and knock it out today.

**Comment by milleruntime** [comment]
> We can set some config in the maven-failsafe-plugin to explicitly set the log4j location property for our tests, so they can find the config

@ctubbsii I will concede this ticket and let you use your maven-fu powers on it :smile:
