### ISSUE TITLE
Provide insight into Recovery

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2566]
**Is your feature request related to a problem? Please describe.**
When Accumulo is restarted, there is a lot of work involved in recovery. This can take a long time on bigger clusters and users can only tell what is going on by looking at the logs.

**Describe the solution you'd like**
Maybe create a page on the monitor for Recovery. Or perhaps provide Metrics to the user. I don't _think_ we have any metrics about recovery times yet.

**Describe alternatives you've considered**
Do nothing. More savvy admins can scan debug logs for progress of tservers.

**Additional context**
As part of the recovery process, tservers will read Write Ahead Logs (WALs), sort them and write them out into temporary files. In 2.1 work was done to change the Recovery process to write these temporary files as R-Files.

**Comment by milleruntime** [comment]
Apparently we already have some of the framework for this, its just being underutilized. 
http://localhost:9995/rest/tservers/recovery

**Comment by milleruntime** [comment]
Any objections to providing something in the Monitor? My idea was to have some sort of indicator when a tserver is in recovery. I was thinking either a separate table on the tservers page, similar to the Dead Tablet Servers table, for when a tserver is recovering it can be displayed in the "Recovery" table. Another idea I had was to put a flag on the tservers table, perhaps an icon on the row of the tserver. Or we could highlight the rows of the tservers that are recovering in orange to indicate a special status.

I think this would be very helpful since while a tserver is starting up in Recovery, it can't do much else and on larger clusters tservers can take quite some time to recover.

**Comment by DomGarguilo** [comment]
@milleruntime, it looks like a table already exists on `/manager` that displays this information. Do you think that is enough or should the other options mentioned be considered as well?

**Comment by milleruntime** [comment]
Well the table you are looking at on the `/manager` page displays a table of tables. I was thinking since Recovery is done per tablet server, you could put an icon next to the status of the tablet server. So perhaps on the `/tservers` page, we could highlight the row or have some indicator that the tserver is in recovery mode.
