### ISSUE TITLE
Add check to ensure new tests are JUnit5 tests

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2586]
**Is your feature request related to a problem? Please describe.**
Since the recent migration to JUnit5 ([tracked here](https://github.com/apache/accumulo/issues/2441)), there have been several tests that have slipped through the cracks for one reason or another that use JUnit4 imports. For example #2572 and #2585 have been created to fix  JUnit4 tests whose modules have already been converted to JUnit5.

**Describe the solution you'd like**
It would be nice to add a checkstyle rule, or something similar, to warn of JUnit4 usage on certain modules that have already been fully converted to JUnit5. At this point not all modules are fully converted to JUnit5 so we would need to be able to ignore the check on certain modules.

**Describe alternatives you've considered**
Manually searching each module to see if any tests use JUnit4.

I'm not too sure how this can be achieved but to find these tests, I search within a module for the imports that are not `junit.jupiter` which I do in my IDE with the regex "org.junit.[^j]". Something like the import checks done [here](https://github.com/apache/accumulo/blob/main/pom.xml#L1112-L1127) might work for this but I am not sure how to omit specific modules from being checked.

**Comment by ctubbsii** [comment]
> Something like the import checks done [here](https://github.com/apache/accumulo/blob/main/pom.xml#L1112-L1127) might work for this but I am not sure how to omit specific modules from being checked.

It is possible to create a second execution of the plugin, with more narrow config, and that specific execution can be overridden or skipped in modules where JUnit4 is still used. Or, we could use a command-line grep in the GitHub Actions tasks. Or, we can just wait until all modules are JUnit5, to keep it simple.
