### ISSUE TITLE
Implement consistent Namespace and Table property handling

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2633]
As a follow-on to single node property storage in ZooKeeper (issue #1454)

The code contains classes NamespacePropUtil and TablePropUtil that have a lot of overlap - one issue is that the setProperties() methods handle invalid properties differently. On setting an invalid property:

- on a namespace, the method throws an exception on invalid property value
- on a table, the method ignores the invalid property value

If one method was chosen, then duplicate code could be removed by combining the functionality into a single class used by namespace and tables.

**Comment by keith-turner** [comment]
Throwing an exception seems like the way to go. I am working through reviewing #2569 and saw a comment about this.  The code before #2569 would check the return value from TablePropUtil .setProperties() and throw an exception : https://github.com/apache/accumulo/blob/50b9267f526736fc2c510a2626693b072ca4dd04/server/manager/src/main/java/org/apache/accumulo/manager/ManagerClientServiceHandler.java#L428
