### ISSUE TITLE
Prevent multiple creation of multiple PropStore instances.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#2635]
As a follow-on to single node property storage in ZooKeeper (issue https://github.com/apache/accumulo/issues/1454)

Currently ZooPropStore exposes the cache builder to facilitate testing. It may be possible that future code could create multiple ZooPropStores instead of sharing a common instance.  (The code would work, just be using unnecessary resources)

As a follow-on, the builder could be made private or better protected if tests extended / override the builder to expose the builder for mock injection.

**Comment by EdColeman** [comment]
While working on adding version check refresh it looks like we are creating multiple server contexts so this has a higher priority and will look at this next.

**Comment by EdColeman** [comment]
Addressed in PR #2781

**Comment by milleruntime** [comment]
@EdColeman Can this be closed?
