### ISSUE TITLE
Improve Console Logging in Monitor

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2659]
**Is your feature request related to a problem? Please describe.**
The Monitor is a very useful Admin tool but has evolved into a complex Web Application that spans the server back end (Java, REST, Jackson, etc) and web display front end (JS, Jquery, Datatables). There is plenty of server logging done on the back end but it would be nice to have more logging at the front end in the Browser.

The best way (that I know of) to do this is through the Javascript `console.log()`. https://developer.mozilla.org/en-US/docs/Web/API/console/log

The most frequently-used feature of the console is logging of text and other data. There are four categories of output you can generate, using the [console.log()](https://developer.mozilla.org/en-US/docs/Web/API/console/log), [console.info()](https://developer.mozilla.org/en-US/docs/Web/API/console/info), [console.warn()](https://developer.mozilla.org/en-US/docs/Web/API/console/warn), and [console.error()](https://developer.mozilla.org/en-US/docs/Web/API/console/error) methods respectively. Each of these results in output styled differently in the log, and you can use the filtering controls provided by your browser to only view the kinds of output that interest you.

**Comment by milleruntime** [comment]
One good place to start would be `function.js`. There are a lot of Jquery REST calls here, so each function could display some data about the REST call. We could log part of the URL to the REST call and where in the session storage that we are putting the data. For example:
<pre>
/**
 * REST GET call for the server status, stores it on a sessionStorage variable
 */
function getStatus() {
  return $.getJSON('/rest/status', function(data) {
    sessionStorage.status = JSON.stringify(data);
  });
}
</pre>

A call to `console.info()` could be added to the above function printing what gets put into the JSON string and where it is put:
<pre>
console.info("Call to '/rest/status'");
  return $.getJSON('/rest/status', function(data) {
    var str = JSON.stringify(data);
    sessionStorage.status = str;
    console.info("REST call stored: sessionStorage.status = " + str);
  });
</pre>

**Comment by tchaie** [comment]
I can start looking into this.

**Comment by tchaie** [comment]
@milleruntime Because of the nature of the Monitor, the logs are constantly refreshing and updating in the console. Where there are many REST calls being made (e.g. the front "Accumulo Overview" page), the console can get quite long. Is this the intention?

**Comment by ctubbsii** [comment]
> @milleruntime Because of the nature of the Monitor, the logs are constantly refreshing and updating in the console. Where there are many REST calls being made (e.g. the front "Accumulo Overview" page), the console can get quite long. Is this the intention?

I read that in some browsers, console.info, console.debug, and console.log are all treated identically, but in other browsers, these may be organized. From what I've read, in recent versions of Google Chrome, console.debug messages are only shown if you have the "Verbose" option selected, which is not the default. So, if you use console.debug for the messages that represent the background work, the console is less noisy by default, but it'd be easy to show everything if you wanted. I would recommend using console.info for less noisy foreground tasks and console.debug for more noisy background tasks. But, this is a just a rough guideline. It may not be obvious which are which, though I'd suspect most AJAX requests are background.
