### ISSUE TITLE
Gatherer class for summaries has convoluted use of Futures

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2696]
Gatherer creates a future, then calls `thenRun` to create a new CompletableStage that is then ignored, because the Runnable inside is calling a synchronized method to update the future, which then checks to see if it's done without error (which it always is in this case), which in turn calls the instantiateFuture method, which replaces the future, which does this all over again. It's like recursion, but with asynchronous executors and synchronous blocks to ensure the result of the previous future stage is done.

I'm not an expert on CompletableFuture workflows, but this seems like a mess to me and I'm pretty sure this could be cleaned up quite a bit, with some better uses of the CompletableStages.

**Comment by EdColeman** [comment]
You can use maven to specify specific unit and IT tests.  For example to run just the RFileClientTest

```
mvn verify -Dspotbugs.skip -Dit.test=skip_its -Dtest=RFileClientTest -Dspotbugs.skip -Drat.skip -Dformatter.skip -Dcheckstyle.skip -Dmodernizer.skip -Dimpsort.skip -Dsortpom.skip -DfailIfNoTests=false
```

You can look for tests that exercise the Gather / Summaries.  To run specific ITs, replace skip_its in the above command with individual IT tests that you want to run.  I'm not sure what tests best exercise the Gatherer functionality to recommend a more specific set of tests that would be best to run.

Similarly you can run just the QA checks that are automatically run on PR  submission with:

```
mvn --color=always clean verify package javadoc:jar -Psec-bugs -Perrorprone -DskipITs=true -DskipTests=true 
```

Running a version of this before submitting a PR reduces common formatting and other errors that will cause the build to fail.

To run a full set of tests and ITs:

```
mvn --color=always clean verify -Psunny 
```

**Comment by nosewings** [comment]
In addition to the PR I've submitted, I also have a non-recursive version that just runs the retry logic inside a loop in one Future. I don't like that version as much, though, because it involves calling `Future.get()` inside the body of a `CompletableFuture`, which makes exception-handling messy and generally seems unidiomatic.

**Comment by dlmarion** [comment]
@nosewings - I'd like to see the iterative solution if that's ok. I'm going to drop a few comments on #2752, but honestly I'm not familiar with the code and I'm not familiar with the concurrent objects being used. The lack of comments in the original implementation doesn't help the situation. Hopefully @keith-turner  can look at this, I think he will understand it better.

**Comment by nosewings** [comment]
@dlmarion Sure. The iterative solution is at nosewings/accumulo@cfc35ab.
