### ISSUE TITLE
Beatify JS code

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2713]
**Is your feature request related to a problem? Please describe.**
The JS code in the Monitor does not have consistent formatting.

**Describe the solution you'd like**
I want to run a tool from the command line once to clean up the JS code and have it all consistently formatted. There is a Node JS tool that can be run, it is called `js-beautify`. https://www.npmjs.com/package/js-beautify

**Describe alternatives you've considered**
We can just leave it as is. Or any other JS formatting tool.

**Comment by kitswas** [comment]
Run the following powershell script at the repo root to format all JavaScript files under `$Directory`. 

```powershell
# Recursive_format using js-beautify

npm -g install js-beautify

$Directory = \server\monitor

Get-ChildItem -Path $Directory -File -Recurse | Where-Object { $_.Extension -eq '.js' } | Foreach-Object { 
	js-beautify $_.FullName -r
}

```

The differences can be tracked using Git.

**Comment by ctubbsii** [comment]
> Run the following powershell script at the repo root to format all JavaScript files under `$Directory`.

A similar bash script:

```bash
#! /usr/bin/env bash
npm install js-beautify
~/node_modules/js-beautify/js/bin/js-beautify.js -n -j -s 2 server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/*
```

**Comment by DomGarguilo** [comment]
> > Run the following powershell script at the repo root to format all JavaScript files under `$Directory`.
> 
> A similar bash script:
> 
> ```shell
> #! /usr/bin/env bash
> npm install js-beautify
> ~/node_modules/js-beautify/js/bin/js-beautify.js -n -j -s 2 server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/*
> ```

It looks like this can be simplified further using npx. Borrowing from @ctubbsii's script:
```
npx js-beautify -r -n -j -s 2 server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/*
```
Adding -r: `-r, --replace    Write output in-place, replacing input`
