### ISSUE TITLE
Explore possible performance problem with rpc thread pool

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#2745]
**Describe the bug**

Saw the following problem during scan server testing.  Do not fully understand it, but disabling the thread timeout resulted in a massive performance difference in the scan servers.  The same code is used by tablet servers, so its possible it could impact them also.

https://github.com/apache/accumulo/pull/2665/files/973ffe55c90bf404bcb01fe49710ab39f7524e67#r884056358

**Expected behavior**

Not seeing client connections have erratic long pauses when many 100's of threads are trying to scan.

Need to better understand this problem and see what if anything should be done.   Also may want to look at how 1.10 and 2.0 handles this in code and w/ its default config.  I have done this type of heavy load testing in 1.10. and 2.0 before w/o encountering a similar issue.

**Comment by dlmarion** [comment]
The properties for managing thread timeout have different default values. SSERV_MINTHREADS_TIMEOUT defaults to 10s, but TSERV_MINTHREADS_TIMEOUT defaults to 0s. Maybe we make the default value that same, or increase the default for SSERV_MINTHREADS_TIMEOUT dramatically (like 5m).

**Comment by keith-turner** [comment]
> The properties for managing thread timeout have different default values. SSERV_MINTHREADS_TIMEOUT defaults to 10s, but TSERV_MINTHREADS_TIMEOUT defaults to 0s. Maybe we make the default value that same, or increase the default for SSERV_MINTHREADS_TIMEOUT dramatically (like 5m).

@dlmarion  I changed the default to 0s for the sserver to make in consistent w/ the tserver in your sserver branch. I think we can close this for now.
