### ISSUE TITLE
Upgrade Monitor to Bootstrap 5

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2749]
Upgrade the Monitor to Bootstrap 5. https://getbootstrap.com/docs/5.0/getting-started/introduction/
We are currently on Bootstrap v3.4.1 (https://getbootstrap.com/).
Files located under:
`src/main/resources/org/apache/accumulo/monitor/resources/external/bootstrap`

**Comment by nosewings** [comment]
I have this in an ugly-but-working state at [this branch](https://github.com/nosewings/accumulo/tree/bootstrap).

Some things work thinking about:
- Bootstrap v5 no longer comes with the Glyphicon Halflings set, which we use in at least one place. There are some alternative sets out there.
- The styling is significantly different in some places (generally for the worse). This is due both to conflicts with `screen.css` (fixable) and changes in the way Boostrap does things by default (harder to fix). It's also worth noting that the `bootstrap-style.css` file is gone; I don't know whether we were doing custom styling with that.

**Comment by AlbertWhitlock** [comment]
I have put up a PR (#2847) regarding this ticket.

**Comment by DomGarguilo** [comment]
> I have put up a PR (#2847) regarding this ticket.

I'll assign you to this ticket
