### ISSUE TITLE
Provide Script for commons-vfs issues

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2783]
There have been many issues with the commons-vfs dependency over the years, most recently reported by https://github.com/apache/accumulo/issues/2775. It was suggested that a script could be used as an alternative to the VFS classloader built into Accumulo. This script could be created as a bug fix for 1.10.3 and placed in the contrib directory.

**Comment by ctubbsii** [comment]
I don't think there's anything for us to do here. The suggestion was that users could write a very simple startup script for their specific situation. For example, they could have a systemd unit that copies dependencies from remote storage to local, and that unit would be depended upon by a systemd unit that starts an Accumulo service. Or, they could run it some other way. The remote location, the local destination, what to copy, and which command to use to do the copying, etc., would all be very user specific.

If users need to manage their class path on startup this way, then I think that this is something they would need to do for themselves, based on their specific situation.

**Comment by ctubbsii** [comment]
Closing this since there hasn't been any further comments since my last observation that this is too user-dependent.
