### ISSUE TITLE
Deprecate ScanInterpreter

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2787]
Since we now have use of JShell, I think it would be reasonable to just deprecate and eventually drop the scan interpreter stuff (especially since it's not even spelled correctly). It's a bit weird to have shell-specific config stored in the per-table config on the server-side anyway. JShell is a much more powerful and flexible tool, and a lot less work to support, than these quirky shell behaviors.

Closes https://github.com/apache/accumulo/issues/2210

**Comment by cshannon** [comment]
It looks like the scan interpreter stuff was already deprecated in #1140, should it just be removed now?
