### ISSUE TITLE
Add offline option for ImportTable

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2849]
A new API method for importTable was added in #1579 to include a set of directories. Another parameter should be added as well that will allow for more options when creating the new table. I am thinking that we could just use `NewTableConfiration` as the additional parameter. This would allow users to set `createOffline()` and set table properties when using importTable.

**Comment by milleruntime** [comment]
Turns out `NewTableConfiguration` would not be a good type to use for import table because the whole point of export/import commands is to copy the configuration and metadata. We could provide a new type, `ImportTableConfiguration` with the options of keeping the table offline and keeping the temporary files for validation before bringing the table online.

**Comment by drewfarris** [comment]
For reference, here's some code I was working on for v1.9 that never got merged in: https://github.com/drewfarris/accumulo/commit/5c72ca48c764e4508d518f442eaa52141849ecda

**Comment by milleruntime** [comment]
I was thinking that we would want to set exclude and include properties, the same way that we do in clone configuration, but I am not sure we need to with import table. With the offline option, users can easily configure the table as they see fit before bringing it online and the main goal of the table export/import process is to migrate the config to another table.
