### ISSUE TITLE
MetricsUtil.initializeMetrics throws Exception

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2851]
Modify method to throw more narrow exceptions.

**Comment by rohanshankar** [comment]
I can work on this if no one else is!

**Comment by dlmarion** [comment]
@rohanshankar - I don't think anyone else is working on this. Contributions are appreciated.

**Comment by rohanshankar** [comment]
> 

Great, Ill try me best

**Comment by dlmarion** [comment]
[This](https://accumulo.apache.org/how-to-contribute/#example-contribution-workflow) might be helpful.

**Comment by rohanshankar** [comment]
Created a PR
