### ISSUE TITLE
ServerAmpleImpl should throw more narrow exceptions

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2853]
Almost every method in ServerAmpleImpl throws RuntimeException. Modify to throw more narrow exceptions.

**Comment by cshannon** [comment]
@dlmarion - As I am sure you are aware, using more narrow exceptions would add the checked exceptions to the methods of the interface [Ample.java](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java) which would cause a lot of cascading effects and require changes in several other places of the code to now handle all the checked exceptions (not to mention it would be a breaking change but that is probably ok since it's server side and not in the client). I assume that's fine and that is the intent here?

**Comment by cshannon** [comment]
Looking at this more the other issue is that there are other implementations of Ample that wouldn't necessarily throw the same checked exceptions (in fact the default methods in the interface throw unsupported exceptions) so adding checked exceptions to the interface doesn't seem like a good idea. Maybe we need to create or just use some more existing narrow runtime exceptions instead to prevent having to add checked exceptions to the interface?

**Comment by dlmarion** [comment]
> As I am sure you are aware, using more narrow exceptions would add the checked exceptions to the methods of the interface [Ample.java](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java) which would cause a lot of cascading effects and require changes in several other places of the code to now handle all the checked exceptions (not to mention it would be a breaking change but that is probably ok since it's server side and not in the client). I assume that's fine and that is the intent here?

@cshannon - I will let @ctubbsii respond to that, this issue was spawned from a comment he made on #2665 .

**Comment by ctubbsii** [comment]
The comments were very specific to the code I had commented on. I know we have overly broad exception handling and throwing. The original comments were to avoid introducing new such occurrences... not to rewrite all the existing code to fix it everywhere.

**Comment by dlmarion** [comment]
See https://github.com/apache/accumulo/pull/2665/files#r938956933 and https://github.com/apache/accumulo/pull/2665/files#r938957079

**Comment by ctubbsii** [comment]
> See https://github.com/apache/accumulo/pull/2665/files#r938956933 and https://github.com/apache/accumulo/pull/2665/files#r938957079

Links to comments should take the form `https://github.com/apache/accumulo/pull/2665#discussion_r938955552`. I'm not sure what your links are intended to take the user to, but they don't seem to work for me.
