### ISSUE TITLE
Running sets tests via -Dfailsafe.groups no longer works

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2883]
**Describe the bug**
There are a few `@Tag`s that are used to create sets of tests that should be able to be run when their tag is specified in a maven command. There are currently 4 `@Tag`s defined below:

https://github.com/apache/accumulo/blob/bf9b0f69cf72c854aac2ca12af03f4ec33e5bf04/test/src/main/java/org/apache/accumulo/harness/AccumuloITBase.java#L49-L52

These are used to tag tests like so:
https://github.com/apache/accumulo/blob/bf9b0f69cf72c854aac2ca12af03f4ec33e5bf04/test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java#L85-L86

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0
 - OS: Pop!_OS 22.04 LTS

**To Reproduce**
Run the following command with any tag and it will fail since it is not picking up on any tests to run
`mvn clean verify -Dtest=none  -DfailIfNoTests=true -Dfailsafe.groups=SunnyDay`

**Expected behavior**
All tests with the specified tag should be run.

**Comment by EdColeman** [comment]
Is / was the SunnyDay tag replace or superseded with the the sunny profile? I think the following will run the sunny day marked tests:

```
mvn clean verify -Psunny
```

**Comment by DomGarguilo** [comment]
> Is / was the SunnyDay tag replace or superseded with the the sunny profile? I think the following will run the sunny day marked tests:
> 
> ```
> mvn clean verify -Psunny
> ```

Yea that still works. It has its own profile:
https://github.com/apache/accumulo/blob/bf9b0f69cf72c854aac2ca12af03f4ec33e5bf04/pom.xml#L1509-L1516

Oddly enough this works by using the failsafe.groups, the same thing that the manual maven command fails on.

**Comment by DomGarguilo** [comment]
> Oddly enough this works by using the failsafe.groups, the same thing that the manual maven command fails on.

Looking closer, I don't think `-Psunny` has been running the tests that we expect it to be running. Matching up the tests that have the `@Tag` (formerly `@Category` in JUnit4) to the tests that are actually run, they are different. I'm not sure where the group of tests `Psunny` runs is coming from but as far as I can tell its the wrong set of tests.

**Comment by Manno15** [comment]
So part of the initial failure is the fact the first category that gets run with `mvn verify` (accumulo project) has no tests (sunny or otherwise). I am not sure if the command is enough to have maven skip certain sections or not. 

As it currently stands, just running `mvn clean verify -Psunny` will run all the unit tests but I did get just the sunnyDay tests by running `mvn clean verify -Dtest=foo -Psunny`. Right now that profile doesn't exclude anything which is why it will run everything else beforehand.

**Comment by DomGarguilo** [comment]
> I did get just the sunnyDay tests by running `mvn clean verify -Dtest=foo -Psunny`. Right now that profile doesn't exclude anything which is why it will run everything else beforehand.

Good catch. Something must have changed at some point (maybe surefire/junit version update) that changed this behavior. I was able to get just the `@Tag`ed SunnyDay tests to run with the command you mentioned or by adding the following property to the `sunny` profile: `<test>foo</test>`.

I'm not too sure what all we want to have run with the `sunny` profile but running the options above on my machine take about 20 minutes where as before I remember -Psunny taking about 6/7

This also works to run the groups of tagged tests i.e., `mvn clean verify -Dtest=foo -Dfailsafe.groups="<tag name>"`

**Comment by DomGarguilo** [comment]
I think I'll close this ticket since it has been found that running groups of tests via their tag does work. If we want to open a separate ticket/PR to modify the `sunny` profile we can do that.
