### ISSUE TITLE
Log4j2 Async Logging may not log error before Process terminates

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2885]
Was setting up a new install of 2.1.0-SNAPSHOT. I added the property for the context class loader factory class to accumulo.properties with the default value. This was a mistake on my part as it sends the code down the wrong path and a NoSuchMethodException was being thrown from ClassloaderUtil as part of the server startup. The problem was that nothing was logged and all of the server processes were terminating at the same exact place. Disabling the log4j2 async logging, by commenting out [this](https://github.com/apache/accumulo/blob/main/assemble/conf/accumulo-env.sh#L107) property, enabled the exception to be logged before the process exited.

I wonder if there is a way to programmatically turn on async logging after the server process initializes.

**Comment by EdColeman** [comment]
Would using stderr at places where we call exit to dump a stack trace be practical - that would eliminate the dependency on an loggers.

**Comment by dlmarion** [comment]
I think that can be done. It looks like sync and async logging can be used (ref: https://logging.apache.org/log4j/2.x/manual/async.html). But it looks like that is done per logger. I'd like to be able to configure that all `errors` are logged synchronously.

**Comment by dlmarion** [comment]
Someone else reported something similar: https://issues.apache.org/jira/browse/LOG4J2-2267
