### ISSUE TITLE
Refactor `OpTimerTest.verifyExceptionCallingStartWhenRunning` to improve the test experience

### ISSUE THREAD

**Issue by Codegass** [apache/accumulo#2886]
I am looking at test case, [`verifyExceptionCallingStartWhenRunning`](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L101-L117).My understanding is that it tests that when an `OpTimmer` is started for a second time, an `IllegalStateException` should be thrown. 

The `try-catch` block between [lines 106 and 111](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L106-L111), and the assert on [113](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L113), seem to add unnecessary complexity to the test case. If an exception happens in the try block, [line 113](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L113) will fail the test case, since the timer is interrupted. We can remove[ line 106 to line 111](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L106-L111) (try-catch block and the assert), and only keep [line 107](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L107) for equivalent failure. When an exception happens on[ line 107](https://github.com/apache/accumulo/blob/c74928d47a0ca8114697926700967ce4fdb8e404/core/src/test/java/org/apache/accumulo/core/util/OpTimerTest.java#L107), JUnit handles the exception automatically and raise a failure. Junit even provides additional information of the exception with running trace.

#### Before Refactoring
```java
@Test
  public void verifyExceptionCallingStartWhenRunning() {

    OpTimer timer = new OpTimer().start();

    try {
      Thread.sleep(50);
    } catch (InterruptedException ex) {
      log.info("sleep sleep interrupted");
      Thread.currentThread().interrupt();
    }

    assertTrue(timer.isRunning());

    // should throw exception - already running
    assertThrows(IllegalStateException.class, timer::start);
  }
```
#### After Refactoring
```java
@Test
  public void verifyExceptionCallingStartWhenRunning() throws InterruptedException {

    OpTimer timer = new OpTimer().start();
    Thread.sleep(50);

    // should throw exception - already running
    assertThrows(IllegalStateException.class, timer::start);
  }
```

This change will benefit the test case in two ways: 1) removing the try-catch makes the test case read simpler; 2) the information about the test failure becomes more clear.

Please let me know if this makes sense. Any comments are welcome and appreciated.

**Comment by EdColeman** [comment]
Seems reasonable - can you submit a PR against the main branch?

**Comment by Codegass** [comment]
Thank you for the reply! I will try to submit a PR today.

**Comment by DomGarguilo** [comment]
It looks like a few other test cases in OpTimerTest could get the same treatment too.

Also, if you are interested in further improving these tests, you could optionally add descriptive messages to the assert statements and assert that the expected message is returned from `assertThrows`.

**Comment by ctubbsii** [comment]
Is somebody working on this?

**Comment by Codegass** [comment]
Sorry about the delay, I was being busy for the last week, I will try to submit the PR in this week. Thanks a lot for the advice!
