### ISSUE TITLE
ShellServerIT.exporttableImporttable is failing

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2929]
**Describe the bug**
ShellServerIT.exporttableImporttable creates a table and sets property `table.split.threshold=345M`. It exports the table, then imports it. It looks for `345M` in the config output of the new table, but does not find it.

**To Reproduce**
Run Sunny Tests on the command line (`mvn clean verify -Psunny`). When run from Eclipse, this test passes

**Expected behavior**
Test to pass

**Comment by DomGarguilo** [comment]
How often does this fail for you? Does it only fail when running `Psunny` or also when you run the test on its own?

I think I have seen this one fail before as well, but can't reproduce the failure at the moment.

**Comment by dlmarion** [comment]
I saw it in the output of one of the most recent CI builds, then I saw it just before writing this ticket. I'm running `sunny` again right now to see if it fails again and to check the logs. I was thinking that maybe it was a ZK sync issue, but this test is configured to run 1 tserver with a comment for that exact issue.

**Comment by dlmarion** [comment]
Failed again, same place. The test sets the `table.split.threshold` property to `345M`, which calls `TableOperationsImpl.setProperty`, which sets the property via the `Manager`. Then it calls `TableOperationsImpl.exportTable`, which starts a FaTE operation in the Manager. I looked at the `table_config.txt` file in the export metadata zipfile and the `table.split.threshold` property is not in there. Seems like there might be a sync issue in the Manager....

**Comment by EdColeman** [comment]
Merged https://github.com/apache/accumulo/pull/2778 - which may help

**Comment by dlmarion** [comment]
I think this fixed it. `sunny` got past ShellServerIT twice locally and was failing before this commit.
