### ISSUE TITLE
External Compactions table broken in Monitor

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2934]
The bootstrap 5 update broke one of the tables in the Monitor on the new External Compactions page. The table background is missing. See screenshot.
![Screenshot from 2022-09-16 11-09-39](https://user-images.githubusercontent.com/11872539/190671815-5b1e66f9-51f0-4b79-817c-f9750aa36ed3.png)

**Comment by AlbertWhitlock** [comment]
@milleruntime ......this is the way that data has always been displayed (for some reason). This Bootstrap upgrade didn't affect it.

If we want it in a table (and I don't know why we wouldn't!), let me know if I should do that.

**Comment by milleruntime** [comment]
Yeah it should be in a table.

**Comment by milleruntime** [comment]
FYI this table doesn't have to be a datatables table since its not dynamic but it doesn't hurt to make it one.
