### ISSUE TITLE
Monitor table problems clear button doesn't work because error in sanitize function

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2941]
**Describe the bug**
On the monitor, clicking on "clear table problems" yields the following exception in JavaScript:

```
 Uncaught TypeError: sanitize is not a function
    at doLoggedPostCall (functions.js:318:12)
    at clearDetailsProblems (functions.js:475:3)
    at clearDetailsProblemsTable (problems.js:152:3)
    at <anonymous>:1:1
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0-SNAPSHOT
 - OS: Fedora 36
 - Others: Chrome 105.0.5195.125

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Create a table, insert an entry in the shell, flush
2. Rename flushed file in HDFS
3. Try to scan
4. Check monitor "table problems" page under debug menu to confirm a table problem has occurred
5. Rename the file back to its original, so scan completes
6. Try to clear the table problems by clicking on the link on the monitor
7. Notice it doesn't do anything, but generates an error in the browser's JavaScript console

**Expected behavior**
Table problem should clear from the monitor

**Comment by DomGarguilo** [comment]
I will take a look into this
