### ISSUE TITLE
Monitor instance name in upper left should not change style on mouseover

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#2944]
**Describe the bug**
A recent change to the monitor seems to have added an underline style to the instance name in the upper left corner that takes you back to the main monitor page, when you mouseover. It should not change style when you mouseover. This seems may be related to the recent bootstrap updates, but I have not investigated thoroughly. This seems like it would be relatively trivial to fix.

**Comment by DomGarguilo** [comment]
Screenshot for context where "uno" is my instance name:
![image](https://user-images.githubusercontent.com/47725857/191337757-4f8aeeb6-e343-4648-a294-bb478ba2cf46.png)
