### ISSUE TITLE
Broken or Flaky test: ShellServerIT.testFateSummaryCommandWithSlowCompaction

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#2948]
**Test name(s)**
[ERROR] org.apache.accumulo.test.shell.ShellServerIT.testFateSummaryCommandWithSlowCompaction  Time elapsed: 4.365 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
reportTime present in root@miniInstance ns1.ShellServerIT_testFateSummaryCommandWithSlowCompaction0> fate -summary -np json -t NEW IN_PROGRESS FAILED
 was not true ==> expected: <true> but was: <false>

**Comment by milleruntime** [comment]
I haven't looked at the test but my guess is it should probably be removed. Unless you or Ed want to move it to another IT to test the new summary command in Admin. We have the unit test AdminTest but it will probably be a PITA to mock everything in a unit test.

**Comment by EdColeman** [comment]
I'll look at moving it.

**Comment by EdColeman** [comment]
Is there a similar test / potential problem with moving the cancel command?

**Comment by dlmarion** [comment]
I didn't see one. I'm working on a new test now.
