### ISSUE TITLE
CreateEmpty utility that works with encryption

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2952]

**Comment by ctubbsii** [comment]
Non-encrypted files should be possible to read when encryption is turned on, so it should be fine to only create empty files without encryption.

**Comment by milleruntime** [comment]
> Non-encrypted files should be possible to read when encryption is turned on, so it should be fine to only create empty files without encryption.

Good point. I didn't think we needed a ticket for this but when I clicked the circle button next to the list on #2930 it created a ticket for me.

**Comment by milleruntime** [comment]
Tested the CreateEmpty and it works with the NoCryptoServiceFactory with a table that is encrypted.
