### ISSUE TITLE
Fate Admin print doesn't filter on status

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#2974]
The status filter on the new Admin fate command does not change the results:
<pre>
04:26:21 {main} ~/workspace/uno/install/logs/accumulo$ accumulo admin fate -p -s IN_PROGRESS
2022-09-27T16:26:29,795 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/mpmill4/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
2022-09-27T16:26:31,085 [metrics.MetricsUtil] INFO : Metric producer PropStoreMetrics initialize
TABLE_BULK_IMPORT2 txid: 6324179035588914  status: SUBMITTED          locked: []              locking: [R:3]           op: PrepBulkImport  created: 2022-09-27T20:25:40.716Z
TABLE_COMPACT   txid: 4d7bf30c0676eb5d  status: SUBMITTED          locked: [R:+default]    locking: [R:3]           op: CompactRange    created: 2022-09-27T20:26:09.732Z
TABLE_BULK_IMPORT2 txid: 0176dfaebcec9591  status: SUBMITTED          locked: []              locking: [R:3]           op: PrepBulkImport  created: 2022-09-27T20:26:10.648Z
TABLE_MERGE     txid: 1eeba54e6e769e7c  status: IN_PROGRESS        locked: [R:+default, W:3] locking: []              op: TableRangeOpWait created: 2022-09-27T20:25:39.58Z
TABLE_COMPACT   txid: 09760433eb43a5ce  status: IN_PROGRESS        locked: [R:+default, R:1] locking: []              op: CompactionDriver created: 2022-09-27T20:26:00.977Z
TABLE_MERGE     txid: 37d000bf5948ab30  status: SUBMITTED          locked: [R:+default]    locking: [W:1]           op: TableRangeOp    created: 2022-09-27T20:26:25.915Z
</pre>

**Comment by milleruntime** [comment]
I think we should also make the options the same. For example, Admin uses `fate -p -s IN_PROGRESS` while the Shell command uses `-t` for filtering on status Type.

**Comment by DomGarguilo** [comment]
> make the options the same. For example, Admin uses `fate -p -s IN_PROGRESS` while the Shell command uses `-t` for filtering on status Type.

which option do you think is better?

**Comment by milleruntime** [comment]
Yeah I like `-s` better, like Ed said. So we can just change that one. But this ticket was more for making sure the filter actually works.

**Comment by DomGarguilo** [comment]
It looks like the filter is not getting picked up properly and for some reason the value is null by the time the filtering actually occurs.

**Comment by milleruntime** [comment]
> It looks like the filter is not getting picked up properly and for some reason the value is null by the time the filtering actually occurs.

Right. I have a simple fix ready to go but was waiting on #2976 since that is also breaking the command.

**Comment by ctubbsii** [comment]
Do we really need this? I feel like a user can just use `grep` themselves, if each item is already printed on separate lines.

**Comment by milleruntime** [comment]
> Do we really need this? I feel like a user can just use `grep` themselves, if each item is already printed on separate lines.

Not really. Now that its in Admin you can easily pipe it to grep. The only thing that is kinda nice is that the description also prints all the possible types:
<pre>
          -s, --state
            <state>[ -s <state>...] Print transactions in the state(s) {NEW, 
            IN_PROGRESS, FAILED_IN_PROGRESS, FAILED, SUCCESSFUL}
            Default: []
</pre>
