### ISSUE TITLE
Multiple compactors fail to start

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#2998]
**Describe the bug**
When I attempt to start two compactors, only one starts and an exception gets logged to the compactor that fails to start:
```
Thread 'compactor' died.
java.lang.RuntimeException: Failed to start the compactor client service
	at org.apache.accumulo.compactor.Compactor.run(Compactor.java:628)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.UnknownHostException: Unable to find a listen port
	at org.apache.accumulo.server.rpc.TServerUtils.startServer(TServerUtils.java:221)
	at org.apache.accumulo.compactor.Compactor.startCompactorClientService(Compactor.java:335)
	at org.apache.accumulo.compactor.Compactor.run(Compactor.java:626)
	... 2 more
2022-10-04T12:31:37,506 [rpc.TServerUtils] WARN : Error attempting to create server at localhost:9133. Error: Could not create ServerSocket on address localhost/127.0.0.1:9133.
```
I made sure there was nothing running on that port before starting. This happens every time i try,

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0 75a7018844793cfddc42cde00e5ccb22fb4c9628
 - Apache Maven 3.6.3
 - Maven home: /usr/share/maven
 - Java version: 11.0.16, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64 
 - Default locale: en_US, platform encoding: UTF-8
 - OS name: "linux", version: "5.19.0-76051900-generic", arch: "amd64", family: "unix"

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. setup a cluster via fluo uno
2. stop or kill the cluster
3. uncomment the compactor config in the cluster.yaml file
4. start the cluster back up via `uno start accumulo`

**Expected behavior**
Both compactors should start without issue.

**Comment by dlmarion** [comment]
Like the other server components, each has a defined port and then there is a port search property that will allow the server to search for an open port if the configured port is not open. When running more than one compactor on a host, you will need to set the [compactor.port.search](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L1378) property from its default of `false` to `true`.

**Comment by DomGarguilo** [comment]
> When running more than one compactor on a host, you will need to set the [compactor.port.search](https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L1378) property from its default of `false` to `true`.

That did the trick, thanks. Closing this as a non-issue.
