### ISSUE TITLE
Unable to get table configuration after #2994

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3010]
So, I merged #2994 after multiple successful IT builds. Created a new cluster using Terraform and the head of `main`. Created the `ci` table, then I went into the shell to check that the encryption properties that I set it the configuration were there. And, permission denied. Even thought according to `userpermissions` I have the correct ones.

```
 root@accumulo-testing> userpermissions
System permissions: System.GRANT, System.CREATE_TABLE, System.DROP_TABLE, System.ALTER_TABLE, System.CREATE_USER, System.DROP_USER, System.ALTER_USER, System.SYSTEM, System.CREATE_NAMESPACE, System.DROP_NAMESPACE, System.ALTER_NAMESPACE, System.OBTAIN_DELEGATION_TOKEN

Namespace permissions (accumulo): Namespace.READ, Namespace.ALTER_TABLE

Table permissions (accumulo.metadata): Table.READ, Table.ALTER_TABLE
Table permissions (accumulo.replication): Table.READ
Table permissions (accumulo.root): Table.READ, Table.ALTER_TABLE
Table permissions (ci): Table.READ, Table.WRITE, Table.BULK_IMPORT, Table.ALTER_TABLE, Table.GRANT, Table.DROP_TABLE, Table.GET_SUMMARIES
root@accumulo-testing> config -t accumulo.root
2022-10-07T19:35:28,604 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
root@accumulo-testing> config -t accumulo.metadata
2022-10-07T19:35:31,563 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
root@accumulo-testing> config -t ci
2022-10-07T19:35:37,635 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloException: org.apache.accumulo.core.client.AccumuloSecurityException: Error PERMISSION_DENIED for user root - User does not have permission to perform this action
```

But, I have no issue scanning the tables:
```
root@accumulo-testing> table ci
root@accumulo-testing ci> scan
root@accumulo-testing ci> table accumulo.metadata
root@accumulo-testing accumulo.metadata> scan
+rep< srv:dir []	default_tablet
+rep< srv:time []	L0
+rep< ~tab:~pr []	\x00
...
```

**Comment by dlmarion** [comment]
Looking at [this](https://github.com/apache/accumulo/blob/main/shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java#L155) ConfigCommand in the Shell retrieves the Site, System, Namespace, and Table configurations to print out the table configuration. Also, looking at the list of permissions ALTER_NAMESPACE was missing for the root user on the default namespace and the accumulo namespace. We didn't add the ALTER_NAMESPACE permission in the tests for the default namespace in #2994, but I think I assume that the ALTER_NAMESPACE permission would be their for the accumulo namespace. 

I added those permissions and things worked:
```
root@accumulo-testing> grant Namespace.ALTER_NAMESPACE -ns "" -u root
root@accumulo-testing> grant Namespace.ALTER_NAMESPACE -ns accumulo -u root
root@accumulo-testing> config -t ci
-----------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SCOPE      | NAME                                        | VALUE
-----------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default    | table.balancer ............................ | org.apache.accumulo.core.spi.balancer.SimpleLoadBalancer
```

I feel like two things should happen from this:

1. The root user should get the ALTER_NAMESPACE permission (and maybe others) on the `accumulo` namespace.
2. The logic for getting the different configuration information in ConfigCommand should be moved server-side. If we leave it in the Shell, then we need to back out the changes in #2994. However, if we leave it in the shell, then we are exposing information about the site and system configuration to *all* users.

**Comment by cshannon** [comment]
If we grant the root user the ALTER_NAMESPACE permission then wouldn't that fix things and allow us to keep the logic in the shell? It worked once you granted the proper permissions as the root user would have access. I only briefly looked at this but trying to figure out why the changes would need to get moved to the server if the user running the shell had the proper permissions granted.

**Comment by cshannon** [comment]
I spent some time prototyping a server side change and the change would be a decent sized change as we'd need to update the API with a new RPC call (probably multiple for both namespace and tables) and handle all the logic the shell is doing to figure out where the properties came from and then return that information (likely associating an enum value for where the config is applied). I think a change that extensive would be better for 3.0 and not 2.1 if we wanted to go that path and would probably generate some discussion on the API and shouldn't be rushed.

After talking to @dlmarion a bit I think another approach for now (which would avoid having to revert the permissions checks) would be to simply not show the level where the properties came from if the user doesn't have permission when they provide a table or namespace. The call for getTableConfiguration() already gets all the properties merged together and that is really what the user cares about if they want to view a table config. The user also has permission to view defaults. So if a user doesn't have permission to view site or system or namespace configuration when we display the table we could just show any property that was not set specifically on the table as "default" and not the exact level it came from.

For admin users (or other users with permissions) that can view the Site/System config, etc we can still display the existing information. This check could be done as simply as try/catch on those calls to detect if they can view it.

I will work on a PR tomorrow that will modify the command to just skip over the get site, system, namespace, etc calls if there is no permission to view them and show default instead. My thinking is if any of those calls failed we'd just switch "modes" and just show "default" if not set on the table or namespace they wanted to see. 

The other option is to just revert #2994 but I do think it would be a good idea to not allow all users without to look up the full configs for system and site.

**Comment by cshannon** [comment]
I fixed the first permission issue for the root user in this PR https://github.com/apache/accumulo/pull/3011
There was a bug for the accumulo namespace and default namespace was not set at all

**Comment by cshannon** [comment]
@dlmarion pointed out that root user shouldn't have access to the default namespace by default so I'm updating my PR to remove that.

**Comment by cshannon** [comment]
Ok, I'm out of time for today but submitted 2 PRs to address this as linked, #3011 and #3012. When testing #3012 it's best to also merge in #3011.
