### ISSUE TITLE
Does Accumulo support Erasure Coding for its files?

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3040]
Installed Hadoop 3.3.4 with minimal configuration changes. The NameNode shows that the enabled erasure coding policy is RS-6-3-1024k. After init'ing Accumulo, the RFiles show as replicated.
```
hadoop fs -ls -e /accumulo/tables/\!0/table_info
Found 1 items
-rw-r--r--   3 hadoop supergroup Replicated        265 2022-10-25 11:56 /accumulo/tables/!0/table_info/0_1.rf
```
I'm curious if the way the files are created enforce a block replication approach vs a block striping approach.

**Comment by ctubbsii** [comment]
I believe Accumulo has a per-table configuration to specify the number of replicas. I do not know much about the API/configuration options for HDFS's erasure coding, but I imagine that you can set the number of replicas to 1 in the Accumulo configuration, and enable erasure coding for HDFS through it's own configuration. Getting this working as an example, may be a useful exercise for a blog post for our website.

**Comment by dlmarion** [comment]
It appears that the `RS-6-3-1024k` policy is available for use, but not set on any directory.

```
hdfs ec -getPolicy -path /accumulo
The erasure coding policy of /accumulo is unspecified
hdfs ec -getPolicy -path /
The erasure coding policy of / is unspecified
```

We'll need to investigate further.

**Comment by dlmarion** [comment]
Reference: https://hadoop.apache.org/docs/r3.3.4/hadoop-project-dist/hadoop-hdfs/HDFSErasureCoding.html

**Comment by dlmarion** [comment]
I think the answer is [here](https://accumulo.apache.org/docs/2.x/administration/erasure-coding). I didn't see this until after the 2.1.0 release documentation was merged and put up onto the staging site.
