### ISSUE TITLE
Time stamps are not correctly formatted in the Accumulo Monitor 

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3055]
In the Monitor the date format is not properly being rendered. The JavaScript function that is supposed to format the date calls format but then doesn't return the formatted value and instead returns the original date and a very verbose format.

An example of the format that displays is: `Fri Oct 28 2022 11:15:10 GMT-0400 (Eastern Daylight Time)` which is the default toString() method being called. The bug is here with the return on this line https://github.com/apache/accumulo/blob/6099e81c891195caa7f54a4f4e96cf9fd10afef0/server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/functions.js#L138

**Comment by EdColeman** [comment]
Same as https://github.com/apache/accumulo/issues/3048 ?

**Comment by cshannon** [comment]
> Same as #3048 ?

Yes I did not know that other issue existed, I'll close this as a duplicate.
