### ISSUE TITLE
3 Properties with version X.X.X in 2.1

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3085]
There are 3 properties in Property.java that have "X.X.X" as their version. I think they were added in 2.1.0 as they are marked experimental and related to the crypto services. @milleruntime - do you know?

**Comment by ctubbsii** [comment]
Yes, those all should be 2.1.0.

**Comment by ctubbsii** [comment]
We can manually update the docs on the website for those so they are correct before the 2.1.1 release.

**Comment by cshannon** [comment]
@ddanielr - This might be a good one for you to work on as well.
