### ISSUE TITLE
Add GitHub build action that fails the build if Thrift generated code is different

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3095]
Add a build step that uses Thrift to generate the java code and compare it to the code in core/src/main/thrift-gen-java/. If different, fail the build so that the PR owner can regenerate the Thrift java files and push them to their branch. This will require installing Thrift as part of the GitHub action. We should look to see if there is an ASF repository where we could host a Thrift binary tarball and then download it as part of the action.

**Comment by ctubbsii** [comment]
It doesn't even need to be a binary tarball... just the single executable for `bin/thrift`. Actually, we can probably put it in svn. We have a dev space there we can use. We can also try to cache it in GitHub Actions so it doesn't need to be re-downloaded every time. The main concern is builds triggering IP bans on ASF infrastructure, so we need to be responsible in ensuring the downloads are aren't too frequent.

I can spend a little time looking into this.

**Comment by dlmarion** [comment]
@ctubbsii - This is great, thanks for doing this!
