### ISSUE TITLE
PreferredVolumeChooser properties / configuration is not well documented

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3110]
This volume chooser (and likely others in its package) are rewrites of older, deprecated classes. The property configuration for the PreferredVolumeChooser is not well document (others in this package may be the same). Would be good to provide examples of the configuration in the class javadoc.

**Comment by ddanielr** [comment]
I can work on this.

**Comment by rukundob451** [comment]
Hello there, @ddanielr were you able to work on this?
