### ISSUE TITLE
Replication StatusCombiner remains on metadata table after upgrade to 3.0

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3147]
CNFE raised in TabletServer for StatusCombiner class, which was removed in #3080 . Looking at the `accumulo.metadata` table, the following is in the configuration:

```
table      | table.iterator.majc.replcombiner .............. | 9,org.apache.accumulo.server.replication.StatusCombiner
table      | table.iterator.majc.replcombiner.opt.columns .. | stat
table      | table.iterator.minc.replcombiner .............. | 9,org.apache.accumulo.server.replication.StatusCombiner
table      | table.iterator.minc.replcombiner.opt.columns .. | stat
table      | table.iterator.scan.replcombiner .............. | 9,org.apache.accumulo.server.replication.StatusCombiner
table      | table.iterator.scan.replcombiner.opt.columns .. | stat
```

**Comment by dlmarion** [comment]
I was able to remove this in the shell using `deleteiter -all -n replcombiner -t accumulo.metadata`

**Comment by dlmarion** [comment]
Looks like it was set on the metadata table in InitialConfiguration [here](https://github.com/apache/accumulo/commit/9bbde86a68c87f8ac75eac843c2aa1f82712420b#diff-933f56855b27c2216e3120db4446ac23ff62d005f413bf95de686c428e65638aL122)

**Comment by EdColeman** [comment]
This is a duplicate of https://github.com/apache/accumulo/issues/3097 and is being handled with https://github.com/apache/accumulo/pull/3137

**Comment by dlmarion** [comment]
Thanks @EdColeman , I didn't see that.
