### ISSUE TITLE
seek() efficiency in 2.x

### ISSUE THREAD

**Issue by FineAndDandy** [apache/accumulo#3162]
When calling seek() my understanding is that we check the block index, move to the block that contains the target Key (if any) and then next() until the target Key is found. I am wondering if the target Key is in the existing block that the iterator is processing if this all still happens, or if next() is called until reaching the target Key, making seek() or next() in a loop near equivalent when the Key is in the currently processed block? If this isn't the case, it seems like a short-circuit case which could be a nice optimization.

**Comment by dlmarion** [comment]
@keith-turner - can you take a look at this question when you have a minute?

**Comment by keith-turner** [comment]
@FineAndDandy  when an iterator seeks forward in the same block there is an optimization for that [here in RFile](https://github.com/apache/accumulo/blob/5c870af5015b3dfd8d3db3d5fc56d58d7c2584c0/core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java#L975).   So for the following situation 

 * KeyA, KeyB,KeyC,KeyD exist in the same RFile block 
 * KeyA<KeyB<KeyC<KeyD 
 * We are currently positioned at KeyB

if we seek to KeyD then it should skip from KeyB until it gets to KeyD w/o having to start at the beginning of the RFile block.

There is also another optimization for when an RFile block is in cache and is being repeatedly seeked to different locations, the code will start to build a little index for the data block.  The more its seeked the more entries are added to the index related to the cached block.  The code is [here in RFile](https://github.com/apache/accumulo/blob/5c870af5015b3dfd8d3db3d5fc56d58d7c2584c0/core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java#L1051-L1072)

**Comment by FineAndDandy** [comment]
extremely helpful response @keith-turner Thank you!
