### ISSUE TITLE
ThriftScanner.serversWaitedForWrites - make configurable for user tables

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3182]
Clients pass `true` for the `waitForWrites` parameter to the `startScan` and `startMultiScan` Thrift service calls when the client is scanning a specific server for the first time. The comments in ThriftClientHandler indicate the reason for this, but it's arguable that for some applications a client may not need to wait for writes to complete against user tables.

**Comment by dlmarion** [comment]
I have asked @ddanielr to look at this.

**Comment by ddanielr** [comment]
@dlmarion I read through your documentation and I'm working on this.
Can you assign this issue to me?

**Comment by ddanielr** [comment]
WIP up with current changes.
https://github.com/apache/accumulo/pull/3187

I based these changes off 1.10. Did you want that branch targeted? or is this a 2.1 change?

**Comment by ddanielr** [comment]
This issue is on hold, pending a response to https://github.com/apache/accumulo/pull/3187#issuecomment-1422338787

**Comment by dlmarion** [comment]
Closing this as won't fix for 1.10 and 2.1.1. If we find this is an issue in the future, then we can re-open.
