### ISSUE TITLE
Refactor HostRegexTableLoadBalancer to support user-defined pool names.

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#3190]
**Is your feature request related to a problem? Please describe.**
Right now the balancer creates resource pools on a per table-property level and uses the table name as the pool name. 
https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/spi/balancer/HostRegexTableLoadBalancer.java#L274-L285

Per-table pool naming makes sense if you have a small amount of tables that are semi-persistent. However, anyone using a large number of tables that are short-lived would end up creating a large number of pools that have a high likelihood of overlapping similarity.

In addition to the high volume of pools existing, this isn't very user friendly as a host regex needs to be set for each table. 

Since any mistype or issue with the regex may result in undesired balancing state, setting this regex property per-table increases the amount of human value comparisons needed when troubleshooting a balancing issue. 

Also, if a user is looking at pool properties, it is harder to deconstruct a regex to identify what servers are being matched vs reading a descriptive pool name. 

**Describe the solution you'd like**
Move the pool regex properties to a defined system property instead of a per-table property.
Example property layout. 
```
resource.pool.name
resource.pool.name.regex
resource.pool.name.using.ips
resource.pool.name.max.migrations
etc...
```
Add a "resource-group" per-table property that corresponds to a defined resource pool name. 

The users would define resource pool names that are descriptive (`high-performance`, `medium-performance`, `low-performance`, `rack-adjacent`, `top-of-rack`, etc) and set these regex values ONCE on pool initialization. 

On table creation, the users only need to set a descriptive resource pool name from a list of currently defined pools. 
This per-table property can be validated against the defined pool list and rejected if it doesn't match. 
This reduces the chance of a single table being improperly balanced. 

The balancer functionality would mostly remain the same with a slight change for pool initialization, retrieving pool names, and matching table prop to pool name.  

There should also be a way of validating the regex against currently known servers from the CLI. 

**Describe alternatives you've considered**
I concede that you could solve this by setting the host patterns at the namespace level, however this means a user is restricted to a single balancing strategy per-namespace. 

**Additional context**
This is related to the server group conversation in #3178. However, that conversation seems to be scoped for 3.0.0 and beyond whereas this change isn't that drastic and could be applied to 2.x versions.

**Comment by ctubbsii** [comment]
The balancer is pluggable, making it already possible for a user to do something like this if it is appropriate for their situation in 2.1. I don't think it's worth us baking this new feature in for a bugfix release, since new features should really be much more rare for bugfix releases, and especially not since it will likely be immediately superseded in 3.0 by the changes proposed in #3178. For 2.1, I think this is better left as an exercise for the user, if they need that for 2.1, rather than us baking it in as a new feature in 2.1.x.

**Comment by ctubbsii** [comment]
Also, this doesn't seem like it would be done as an enhancement to HostRegexTableLoadBalancer, but maybe a new ResourcePoolTableLoadBalancer.

**Comment by ddanielr** [comment]
> The balancer is pluggable, making it already possible for a user to do something like this if it is appropriate for their situation in 2.1. I don't think it's worth us baking this new feature in for a bugfix release, since new features should really be much more rare for bugfix releases, and especially not since it will likely be immediately superseded in 3.0 by the changes proposed in #3178. For 2.1, I think this is better left as an exercise for the user, if they need that for 2.1, rather than us baking it in as a new feature in 2.1.x.

I agree that 2.1.x would be a bugfix release so this change wouldn't be within scope for a 2.1.x release.
I thought this change would be appropriate for a 2.2.x release, if that were to ever happen. 

Given that the balancer is pluggable, I'll close this issue for now.
