### ISSUE TITLE
Multiple Managers: Add basic conditional mutation support to Ample

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3209]
Accumulo will start to heavily use conditional mutations for metadata updates in one proposed design for achieving elasticity.  To support this use Ample should be updated to support at least the following things.

 * Easily writing conditions in java code.
 * Submitting batches of updates for efficiency. It can be better to submit many conditional mutations rather one at time.  This could be achieved in impl with a shared conditional writer that can be used in a process via a queue.
 * Be able to know if a conditional metadata update was actually made.

This functionality could be implemented at first in Ample w/o actually using it Accumulo as a draft PR.  For an initial pass would be good to support the following conditions.

 * No location (future or current)
 * A specific location
 * A specified set of files must exists 

The above conditions must be able to specified in java code and mixed together, like only preform a metadata update if the tablet has location X and has the file in set Y.

**Comment by keith-turner** [comment]
I have started experimenting with this here https://github.com/keith-turner/accumulo/tree/meta-conditions ... will eventually post a draft PR once I have some basic functionality working.

**Comment by keith-turner** [comment]
Completed in #3251
