### ISSUE TITLE
OnDemand Tables: Create new table state called ONDEMAND

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3210]
Currently tables are either online or offline. Create a new table state called on-demand where tables are treated as offline unless they are specifically brought online by request. The thought here is that a client that wants to perform a scan or live ingest into a range of KeyExtents will look up the location for these tablets in the TabletLocator. When they are not found, the client contacts the Manager and requests that they be hosted. The client would then wait until the TabletLocator resolves the location for these tablets, then continue.

**Comment by ctubbsii** [comment]
I kind of like the idea of having all tables on-demand. Is there a specific advantage of having a new table state that is treated differently than "online"? I am admittedly behind in following all the proposed changes, and ideas recently. I am still trying to work on getting 3.0 out the door, and this seems to be moving too fast for me to keep up with when it's progressing concurrently. But that's my problem, I guess.

**Comment by dlmarion** [comment]
I made a similar comment to @keith-turner last week. If all tables were on-demand, then startup would be really fast as you would not have to wait for assignment and balancing. I'm all for getting 3.0, 2.1.1, and 1.10.3 released ASAP so that we can get everyone working on this. Please let me know what issues I can work on to help with this.

**Comment by dlmarion** [comment]
I don't think that we would want to remove the online table state though. There is a latency cost to hosting an ondemand tablet and a user may not want to avoid that latency for some (or all) of their tables.

**Comment by ctubbsii** [comment]
Elsewhere I saw a proposal to have tablets/tables pinned. Since the online state can be represented as a particular pinning, I think it makes sense to rely on that, so the online and ondemand features cohere into a single concept, rather than exist as two distinct concepts.

**Comment by keith-turner** [comment]
One minor difference between online and ondemand on the client side is the behavior when a tablet does not have a location.  For on demand tables the client would need to request the tablet be loaded.  For online tables the client would not need to make this request, it knows that the goal is to get tablets loaded as soon as possible.  If a client were aware of what ranges of an ondemand table were pinned, then it could avoid making the request.  However, if the client does make an unneeded request to load a tablet it should be fine but could place unnecessary load on manager for an online table that happens to have some tablets that temporarily do not have a location.
