### ISSUE TITLE
OnDemand Tables: Determine how OnDemand tablets are brought online

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3211]
When a client requests that an on-demand tablet be brought online, the Manager will create a future location in the TabletMetadata causing the tablet to be assigned and balanced. The assignment / balancer will need to take into account the tserver group when deciding which tserver to use.

**Comment by dlmarion** [comment]
Draft PR up at https://github.com/dlmarion/accumulo/pull/37

**Comment by dlmarion** [comment]
> Is there a mechanism to alert on approaching resource limits or evaluate the cluster's current size/use before marking a tablet as onDemand?

Given that we don't know which schedulers might be in use on a cluster, I think we just need to emit metrics that can be used for a scheduling system to make a determination that more tablet servers are needed. Accumulo doesn't do any alerting, that's typically set up by the users of the system - trigger an alert when some criteria is met.

> Given the possibility of a limited resource footprint, what mechanism is going to be used for scheduling the tablet hosting?

I don't think we should build or use a specific scheduler. [KEDA](https://keda.sh/) and [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) exist already and I'm sure the different commercial cloud vendors may supply their own solutions as well (Azure has [VPA](https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler) for example).

> What determines hosting priority of onDemand tables? should this exist? should it be a per-client setting or perhaps per table?

I don't think we have had any discussion of priority. Can you give an example of how priority would work?

> Are "resources unavailable for hosting" an error condition that can be handled for onDemand tables?

I'm not sure that we can do this reliably. If we were able to determine a cost (in terms of memory required to host a tablet), a TabletServer may or may not have enough memory to host another tablet. It may appear that the TabletServer doesn't have the memory, but after a GC it very well could. I'm not sure there is a good answer here.

> Is there a possibility of scheduling deadlock situations?

I don't think so, this is using the existing mechanism of assigning online unassigned tablets to tablet servers. When the client requests that an ondemand tablet is assigned, it just puts a marker entry in the tablet metadata for that tablet. The TabletGroupWatcher process in the Manager will notice this change and on it's next pass assign it to a TabletServer.

**Comment by ddanielr** [comment]
> > Is there a mechanism to alert on approaching resource limits or evaluate the cluster's current size/use before marking a tablet as onDemand?
> 
> Given that we don't know which schedulers might be in use on a cluster, I think we just need to emit metrics that can be used for a scheduling system to make a determination that more tablet servers are needed. Accumulo doesn't do any alerting, that's typically set up by the users of the system - trigger an alert when some criteria is met.

:+1:  Using an external metric collection system makes sense.

> > Given the possibility of a limited resource footprint, what mechanism is going to be used for scheduling the tablet hosting?

> I don't think we should build or use a specific scheduler. [KEDA](https://keda.sh/) and [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) exist already and I'm sure the different commercial cloud vendors may supply their own solutions as well (Azure has [VPA](https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler) for example).

Scheduling was probably the wrong word to use. But I agree on using a pre-defined scheduler for k8s resources. 
I think this question is wrapped into the priority discussion.

>> What determines hosting priority of onDemand tables? should this exist? should it be a per-client setting or perhaps per table?

> I don't think we have had any discussion of priority. Can you give an example of how priority would work?

Please correct any inaccuracy here. 

Lets say we have an accumulo cluster that does not have tserver groups implemented and services two clients. 
Both clients have tables that, individually, fit within the cluster's resource footprint but when hosted at the same time exceed the current resources. 

If my understanding is correct, both clients can attempt writes on "onDemand" tables that are currently unloaded. Or, both clients could request that tables be moved from offline to "onDemand". 
Each of these actions would result in the tablets being marked for assignment and attempt to be loaded onto tservers via the TabletGroupWatcher. 

Since these are not enough resources for both tables to be fully hosted, will the TabletGroupWatcher discern which "ondemand" tablets should be hosted first? Or does it just see a pool of tablets that need to be assigned and will do so indiscriminately?

If it's the latter, since the clients are attempting actions at a table level vs a tablet level. Does that mean all tablets for a given table need to be assigned and loaded before the action can be completed? 

If so, then as part of bringing tablets online, a priority level (1-x) or an "onDemand" request timestamp could be included in the metadata. Then the TabletGroupWatcher could ensure all tablets of a specific "onDemand" request would be fully hosted prior to assigning a second "OnDemand" requests tablets.

Otherwise, wouldn't there be a resource blocking issue where tablets of both tables are being assigned, but each table cannot fully be hosted due to resource constraints?

**Comment by dlmarion** [comment]
> > > Is there a mechanism to alert on approaching resource limits or evaluate the cluster's current size/use before marking a tablet as onDemand?
> > 
> > 
> > Given that we don't know which schedulers might be in use on a cluster, I think we just need to emit metrics that can be used for a scheduling system to make a determination that more tablet servers are needed. Accumulo doesn't do any alerting, that's typically set up by the users of the system - trigger an alert when some criteria is met.
> 
> 👍 Using an external metric collection system makes sense.
> 
> > > Given the possibility of a limited resource footprint, what mechanism is going to be used for scheduling the tablet hosting?
> 
> > I don't think we should build or use a specific scheduler. [KEDA](https://keda.sh/) and [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) exist already and I'm sure the different commercial cloud vendors may supply their own solutions as well (Azure has [VPA](https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler) for example).
> 
> Scheduling was probably the wrong word to use. But I agree on using a pre-defined scheduler for k8s resources. I think this question is wrapped into the priority discussion.
> 
> > > What determines hosting priority of onDemand tables? should this exist? should it be a per-client setting or perhaps per table?
> 
> > I don't think we have had any discussion of priority. Can you give an example of how priority would work?
> 
> Please correct any inaccuracy here.
> 
> Lets say we have an accumulo cluster that does not have tserver groups implemented and services two clients. Both clients have tables that, individually, fit within the cluster's resource footprint but when hosted at the same time exceed the current resources.
>

What does it mean to exceed? I believe that the limitation to a TabletServer hosting a Tablet is the amount of memory given to the TabletServer. If a TabletServer can host N Tablets, it will still be limited as to how many tablets can read/write concurrently based on other properties. If a TabletServer can't host N tablets, then it it needs more memory, or more TabletServers need to be stood up so that the load can be distributed. I would say that determining how many Tablets a TabletServer can host would be difficult as the TabletMetadata is not the same size for each Tablet. It might be possible to use some rough upper bound on the amount of memory required to host each Tablet to determine how many TabletServers are needed.
 
> If my understanding is correct, both clients can attempt writes on "onDemand" tables that are currently unloaded. Or, both clients could request that tables be moved from offline to "onDemand". Each of these actions would result in the tablets being marked for assignment and attempt to be loaded onto tservers via the TabletGroupWatcher.
> 

Moving the table state from `offline` to `ondemand` would not result in tablets being loaded. The tablets for an ondemand table are only loaded when the client needs them for live ingest or scans.

> Since these are not enough resources for both tables to be fully hosted, will the TabletGroupWatcher discern which "ondemand" tablets should be hosted first? Or does it just see a pool of tablets that need to be assigned and will do so indiscriminately?
> 
The latter

> If it's the latter, since the clients are attempting actions at a table level vs a tablet level. Does that mean all tablets for a given table need to be assigned and loaded before the action can be completed?
> 

The way that I currently have this wired up, the tablets are loaded when they are required by the client. The client tries to determine the location (which TabletServer) a tablet is hosted on, so that it can send read or write requests. If the tablet is not hosted, and the table is ondemand, it sends a request for the tablet to be hosted which incurs some latency cost. So, the number of tablets that need to be hosted for an ondemand table are the sum of the tablets involved in read and write requests from all of the clients. If you do an unbounded scan, then it's going to eventually host the entire table, but that's what the user requested of the client.

> If so, then as part of bringing tablets online, a priority level (1-x) or an "onDemand" request timestamp could be included in the metadata. Then the TabletGroupWatcher could ensure all tablets of a specific "onDemand" request would be fully hosted prior to assigning a second "OnDemand" requests tablets.
> 
> Otherwise, wouldn't there be a resource blocking issue where tablets of both tables are being assigned, but each table cannot fully be hosted due to resource constraints?

If we end up with a mechanism for determining reliably how many tablets a TabletServer can host, then I agree we could introduce some priority scheme. Without that, and in its current form, the code just does what is asked. In #3212 we will create some mechanism for unloading ondemand tablets, not sure what that will look like yet. I think there are several possibilities, for example: a TabletServer could host N (configurable) ondemand tablets and unload them in an LRU fashion.

**Comment by ddanielr** [comment]
> What does it mean to exceed? I believe that the limitation to a TabletServer hosting a Tablet is the amount of memory given to the TabletServer. If a TabletServer can host N Tablets, it will still be limited as to how many tablets can read/write concurrently based on other properties. If a TabletServer can't host N tablets, then it it needs more memory, or more TabletServers need to be stood up so that the load can be distributed. I would say that determining how many Tablets a TabletServer can host would be difficult as the TabletMetadata is not the same size for each Tablet. It might be possible to use some rough upper bound on the amount of memory required to host each Tablet to determine how many TabletServers are needed.

"Exceed "is exactly what you stated, no TabletServers with available memory exist to host the assigned tablet. 
I'm curious what the default balancer does for tablet assignment. If it's just based off # of tablets per tserver that doesn't seem optimal, but out of scope of this current conversation. 

> The way that I currently have this wired up, the tablets are loaded when they are required by the client. The client tries to determine the location (which TabletServer) a tablet is hosted on, so that it can send read or write requests. If the tablet is not hosted, and the table is ondemand, it sends a request for the tablet to be hosted which incurs some latency cost. So, the number of tablets that need to be hosted for an ondemand table are the sum of the tablets involved in read and write requests from all of the clients. If you do an unbounded scan, then it's going to eventually host the entire table, but that's what the user requested of the client.

Thanks for the explanation, I think what wasn't clicking in my head was how the client interaction worked for a given write. This makes more sense. 

> If we end up with a mechanism for determining reliably how many tablets a TabletServer can host, then I agree we could introduce some priority scheme. Without that, and in its current form, the code just does what is asked. In https://github.com/apache/accumulo/issues/3212 we will create some mechanism for unloading ondemand tablets, not sure what that will look like yet. I think there are several possibilities, for example: a TabletServer could host N (configurable) ondemand tablets and unload them in an LRU fashion.

Yeah, I could see priority being used for both hosting and unloading. But I agree that a mechanism for # of possible hosted tablets is required for that to work.

**Comment by dlmarion** [comment]
Since tablet sizes are going to vary widely, even within the same table or database, it might just make sense to have a property somewhere that limits the number of ondemand tablets that can be hosted per tablet server. This could feed into the implementation of #3212 . Users could use something like OpenJDKs Java Object Layout tool, specifically the [footprint](https://github.com/openjdk/jol#footprint) command to find the average size of their tablets to help inform them on how to modify this property. Or maybe the property is used to emit a metric when more tablet servers are need to be spun up based on the number of tablet servers, the number of ondemand tablets hosted, TabletServer heap size, block cache sizes, etc. However, that assumes equal distribution of tablets. It might be easier to write an SPI where the user can plug in their own logic, since this seems like a pretty intractable problem.
