### ISSUE TITLE
OnDemand Tables: Allow users to pin ranges of a table as online

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3213]
For an on demand table users could  be provided with the ability to pin ranges of a table as online.  When this is done the manager would keep the tablets that fall in the range hosted.  Users would need the ability to do the following

 - list what ranges in a table are pinned
 - add new ranges as pinned
 - remove a pinned range

**Comment by EdColeman** [comment]
This is a nit, but maybe a there is better word than pinned?  To me, pinned could refer to a sticky server affinity - such as pinning metadata tables to run on hostA...hostN.  If we go the pinned route for state, then I think we are setting us up for overloading / confusing naming when we would need to clarify what flavor of pinned is referenced.

**Comment by dlmarion** [comment]
Given how tablets are unloaded in [38](https://github.com/dlmarion/accumulo/pull/38), I'm not sure that tablets need to be pinned. The TabletServer keeps track of the KeyExtent and last access time for each online onDemand tablet and passes that information to an implementation of an OnDemandTabletUnloader (unloader). The unloader then determines which tablets should be unloaded. If the unloader never returns a KeyExtent to be unloaded, then it's effectively pinned once loaded. Different OnDemandTabletUnloader implementations could be created for different types of tables. For example, for tables where a date is stored in the row, which is available in the KeyExtent, an implementation could be created that never returned any KeyExtent that falls within some time frame.

**Comment by dlmarion** [comment]
> My mental model for tracking loading / unloading is that this is implementing a cache. This description
> 
> > The TabletServer keeps track of the KeyExtent and last access time for each online onDemand tablet
> > seems to be describing LRU behavior.
> 
> Tracking the last access time can be expensive. How often does the access time get updated? If it is updated only on loading, then this seems that it would act more like "expireAfter", where it would be eligible for removal an a fixed time period.

In my current PR for unloading, the last access time is set when the tablet is loaded, updated when TabletServer.getOnlineExtent() is called, and removed when the tablet is unloaded.

>  In that case, what would prevent a tablet from being unloaded while a scan is in progress? Updating on every "next()" seems like it could be prohibitively expensive. The sweet spot would seem to be something that is tracking tablet usage so that tablet being used in active scans would not be unnecessarily unloaded. Maybe the last access is updated on init and on tear-down?

I think I found a solution using the existing metrics that are tracked. I added it in https://github.com/dlmarion/accumulo/pull/38/commits/33fa498fe5272400a3da88645be01d56f097f845

> 
> The TableServers are going to need to gather sufficient metrics that unloader implementations can make determinations - while things like row / key knowledge will be custom, usage and access times will need to be provided.
> 
> As a "base" implementation, we could provide a time-based cleaner thread and as a extension, something triggered on low memory conditions?

**Comment by dlmarion** [comment]
#3294 included a capability that allows a user to specify a range of tablets that should always be hosted.
