### ISSUE TITLE
Tablet.needsSplit() shouldn't calculate new split point

### ISSUE THREAD

**Issue by FineAndDandy** [apache/accumulo#3217]
**Describe the bug**
Tablet.needsSplit() calls Tablet.findSplitRow(...) which may call FileUtil.findMidPoint(). This call is potentially very expensive, and due to Tablet.needsSplit() being synchronized may block what should be short operations. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.x, 2.x

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Suspend idle compactions
2. Set the compaction threshold very high
3. Create a very large tablet
4. Drop the split threshold below the tablet size
7. Attempt to bulk load a file into the tablet
8. Observe the bulk load to timeout as a split point is computed

**Expected behavior**
Because the tablet is over the estimated size, the bulkLoad should return quickly and trigger TabletServer.executeSplit(...) which should do the actual computation of the split point and all validation rather than the needsSplit().

**Additional context**
There is some state that is computed/held in the tablet when the splitPoint is calculated that either has to be moved or added another way.

**Comment by FineAndDandy** [comment]
I'm working on a PR for this issue

**Comment by EdColeman** [comment]
Are you going to target 1.10 and then merge forward?

**Comment by FineAndDandy** [comment]
This code looks pretty stable across all versions. I'll target 2.1.

**Comment by EdColeman** [comment]
Maybe I should have been more explicit - it seems (to me) that it would be a bug-fix that starts at 1.10.

**Comment by FineAndDandy** [comment]
Okay, no problem.
