### ISSUE TITLE
Race condition in set property.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3248]
There appears to be a race condition in setting / reading properties that is exposed by occasional failures in the ShellServerIT. exporttableImporttable() test.

The test sets a property and then exports the table - the import tests the property is set.  On a failure, the table_config.txt file that was written is missing the set property.  The test was set to validate that the property was set in ZooKeeper after the set.

**Comment by ctubbsii** [comment]
There is always a race condition due to propagation delay with ZooKeeper. Are you sure this isn't just that, but something else?

**Comment by EdColeman** [comment]
Pretty sure.  My first thought was that reading the updated value from ZooKeeper during the test would be enough to ensure that the change had committed and would have been propagated.  However, the test would still fail occasionally with the changed value not showing up in the exported table config file.  

Looking at that code - it was reading values from the secondary cache in ServerConfigurationFactory.  Originally, that secondary cache was only being cleared on delete events - mainly to limit memory usage.  Change events were delegated to the prop store.   By clearing the secondary cache on any ZooKeeper change event for a cache Id, it forces the values to be re-read on access. 

This should not impact performance because properties are relatively stable.

With the changes in #3245 I have not been able to get ShellServerIT to fail.

**Comment by EdColeman** [comment]
@ctubbsii  asked 

```Is this issue completely fixed by https://github.com/apache/accumulo/pull/3245? If so, why was this issue created after the PR already existed?```

This issue was created after PR #3245 because the initial fix / testing in that PR pointed to a potential problem that should not be solved by adding delays in the test.  Something else needed to be done, but what was unknown. The issue was created to expand scope of the issue beyond a PR that was just trying to fix the ShellServerIT test.  

Follow-on work under PR #3245 then addressed the underlying issue and will be a fix for this issue.
