### ISSUE TITLE
Comparisons between TserverInstance and TabletMetadata.Location are error prone

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3254]
While working on #3251 an equals method was added to [TabletMetadata.Location](https://github.com/apache/accumulo/blob/540179d1f52dcc478eee3a3ee3c5fac106736c8b/core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java#L135-L146) which caused [this test](https://github.com/apache/accumulo/blob/540179d1f52dcc478eee3a3ee3c5fac106736c8b/core/src/test/java/org/apache/accumulo/core/metadata/schema/TabletMetadataTest.java#L199) to break.

The cause of the breakage in the test was [this code](https://github.com/apache/accumulo/blob/540179d1f52dcc478eee3a3ee3c5fac106736c8b/core/src/main/java/org/apache/accumulo/core/metadata/schema/TabletMetadata.java#L293-L294) that ends up looking up a TabletMetadata.Location object in a set of TServerInstance objects.  This works because TabletMetadata.Location extends TServerInstance and does not override equals or hashcode.  Overriding the equals method caused the test to break.

It would be much cleaner and less error prone if TabletMetadata.Location encapsulated TServerInstance instead of extending it.  If something wanted to compare to the TServerInstance then it could call getTServerInstance() on location and compare to that.  Encapsulation instead of extension would allow TabletMetadata.Location to have its own sensible equals and hashcode methods also.

**Comment by ctubbsii** [comment]
This is a similar problem to the TabletFile/StoredTabletFile issue that @EdColeman and I were previously looking into (the "as stored" format being analogous to "location" here as the type to be encapsulated). However, I think this one might be a bit easier to fix.

**Comment by cshannon** [comment]
I also was thinking the same thing that this looked similar to https://github.com/apache/accumulo/issues/2830

I can can ahead and fix it.

**Comment by cshannon** [comment]
I think I might try and keep the scope of this smaller for now as doing a bunch of refactoring has a lot of changes and would be nice to fix the issue with a smaller change and refactor later if we wanted.
