### ISSUE TITLE
Teardown documentation inaccurate

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3287]
The Teardown section of the User Manual states that "Being torn-down is equivalent to a new instance of the Iterator being creating and deepCopy being called on the new instance with the old instance provided as the argument to deepCopy."  This is entirely inaccurate.  deepCopy is not used at all when recreating the iterator stack for a scan.  The iterator stack is created as brand new instances, init is called with the original options, and then it is seeked from where it left off.  Implying that deepCopy is used suggests that way more state can be preserved in an iterator which is not true.

Affects at the 1.x versions of the user manual and the 2.x versions of the development manual (e.g. https://accumulo.apache.org/1.10/accumulo_user_manual.html#_teardown and https://accumulo.apache.org/docs/2.x/development/iterators#teardown).

**Comment by DomGarguilo** [comment]
Here is that section in the 2.1 user manual: https://accumulo.apache.org/docs/2.x/development/iterators#teardown

**Comment by ctubbsii** [comment]
We're currently voting on 1.10.3, and it looks like the release candidate is likely to pass. The docs are embedded into the build, so if that passes, it's too late to fix it for 1.10, but the 2.x documentation is directly on the website and can be fixed with a PR at any time.

**Comment by ctubbsii** [comment]
Fixed for 2.x docs on the website in https://github.com/apache/accumulo-website/pull/383
