### ISSUE TITLE
Change Accumulo version to 4.0.0 in elasticity branch

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3298]
The inclusion of the OnDemand Tablet feature is a large enough behavior change to warrant a bump in the major version. Additionally, the other planned changes to this branch will also likely mean significant changes in how Accumulo is deployed and monitored.

**Comment by ctubbsii** [comment]
I think this is premature. We use semver for versioning. A major version bump communicates a breaking change. While there may a compelling reason to go straight to 4.0 without semver breaking changes, we should decide that on the mailing list. This does not need to be decided now, though. It can wait until closer to a release. I just think that doing it in the branch before that decision is premature.

**Comment by dlmarion** [comment]
The version is easy to change should we decide to make it something else. Semver tells us when we must change certain parts of the version number, it doesn't say that we can't change the version number for other reasons.

**Comment by keith-turner** [comment]
I agree the since version should be reevaluated before the elasticity branch is merged to main.  I doubt we will forget, but it may be good to create a follow on issue with so many things to remember. I will add something to the project.

**Comment by keith-turner** [comment]
Created this project item so we do not forget.

https://github.com/orgs/apache/projects/164/views/1?pane=issue&itemId=26194355
