### ISSUE TITLE
OnDemand Follow-on: Modify user Tablet hosting goal to use FaTE

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3303]
Currently the client calls TabletClientHandler.setTabletHostingGoal, which modifies the metadata for the extents passed to the method. Instead, the list of extents should be calculated on the server-side based on the range supplied by the user, and the mechanism should be performed as a FaTE operation so that the user's intention is honored in case of failure.

Reference comment made at: https://github.com/apache/accumulo/pull/3294#discussion_r1165704928

**Comment by EdColeman** [comment]
@dlmarion - can this be closed?
