### ISSUE TITLE
OnDemand Follow-on: Resolve how Tablet.java will stay in sync with metadata changes

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3310]
Specifically, resolve todo at line 236 in Tablet.java. The hostingGoal could be updated by a user (ALWAYS <-> ONDEMAND) while the Tablet is hosted and in-memory. I don't think we need to worry about the NEVER case, as that would cause the Tablet to become unhosted.

Generally, tablet management functions that are moved to the Manager (e.g. Bulk Import, Compaction, etc) will likely modify the TabletMetadata. For any hosted Tablet, how will the Tablet object stay in sync?

**Comment by keith-turner** [comment]
May be easier to work on this after functionality is removed from the tablet server.  Then we will only need to update the code that is left behind in the tablet server.

**Comment by dlmarion** [comment]
#3350 added `TabletServerClientService.refreshTablets`. I assume we just need to add a call to this in the correct places to resolve this issue?

**Comment by keith-turner** [comment]
> #3350 added TabletServerClientService.refreshTablets. I assume we just need to add a call to this in the correct places to resolve this issue?

When refresh was first added it had race conditions on the tserver side. Those were cleaned up and fixed in #3625 and #3634.  There is still work that could be done to clean up the overall locking in the tserver, which is outlined in #3670.  Cleaning up locking the in the tablet would be good since compactions and bulk import were removed and the tablet code is simpler.

**Comment by keith-turner** [comment]
Also compaction commit has a customized refresh processes that could be simplified by using FATE as outlined in #3559

**Comment by keith-turner** [comment]
Closing this issue, the work is done and follow on issue are open for potential improvements.
