### ISSUE TITLE
OnDemand Follow-on: Check that TabletHostingGoal set when Tablet splits

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3340]
I as seeing in a recent test that the TabletHostingGoal was not being set when a Tablet split. Need to confirm this.

**Comment by keith-turner** [comment]
I noticed BulkSplitOptimizationIT was failing when I was running the bulk ITs for #3350.  I wonder if this is why.  Fixing this could wait unti lthe split code is moved out of the tserver.  I am planning to start working on moving the split code soon, I have already experimented with this a few weeks ago.

**Comment by keith-turner** [comment]
I think the changes related to #3382 have fixed this, however we probably want explicit tests that verify the hosting goal after a split is correct in the new child tablets.

**Comment by jmark99** [comment]
PR #3532 adds the additional test alluded to in this ticket.
