### ISSUE TITLE
Handle setting time in bulk import FATE operation

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3354]
After the changes in #3350 the bulk import code no longer sets the tablet time for bulk imported files.  This can be done using conditional mutations when the tablet is offline (piggy backing on existing conditional mutations) OR by a new RPC when the tablet is hosted to request allocation of a timestamp.

**Comment by keith-turner** [comment]
In BulkNewIT there is a disabled test.  When this is fixed that test can be enabled.

**Comment by dlmarion** [comment]
The test in BulkNewIT mentioned above is no longer Disabled, however setting time for hosted tablets still does not work. Likely need to add a test in BulkNewIT for this condition.

**Comment by keith-turner** [comment]
In #4045 setting time was implemented for bulk imports against hosted tablets.  However this is not complete, still need to persist this time in a follow in PR.
