### ISSUE TITLE
tservers falling over because a scan failed

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3371]
Scans were being performed on a table and the vfs class loader was having some threading issue that was causing the scan to fail.  The threading issues I am handling with VFS-836 (in jira).  The problem with accumulo is that these failures (NoClassDefFoundError) are causing the tserver to be halted.  A user's scan should not cause the tserver to be halted.  It is perfectly conceivable that the iterator stack could be using classes that are not accessible by the tserver it is being run on if, for example, the table.context is specified incorrectly.  This happens periodically on our systems when we have various deployment issues.

Accumulo 2.1.1-SNAPSHOT
CentOS 7.3

**Comment by EdColeman** [comment]
I'll work to create a test iterator that throws Error (instead of an exception) to see if I can reproduce in a local / test environment.

**Comment by ivakegg** [comment]
So the error being thrown in our case is
```
java.lang.NoClassDefFoundError: Could not initialize class datawave......
     at datawave......
     ...
     at org.apache.accumulo.core.iteratorsImpl.system.SourceSwitchingiterator.readnext(SourceSwitchingIterator.java:165)
     ...
     at org.apache.accumulo.tserver.scan.LookupTask.run(LookupTask.java:129)
     at org.apache.accumulo.tserver.session.ScanSession$ScanMeasurer.run(ScanSession.java:62)
     at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
     at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: ZipFile closed
    ...

Error thrown in thread: Thread[scan-default-Worker-14,5,main], halting VM.
```

**Comment by EdColeman** [comment]
Fixed by PR #3375  (PR is a possible approach)

**Comment by ctubbsii** [comment]
While this may be a bug caused by commons-vfs, this does not appear to be a bug in Accumulo. I think Accumulo is behaving correctly in the face of Errors thrown by the optional third-party component. See my comment at https://github.com/apache/accumulo/pull/3375#pullrequestreview-1414393608

**Comment by ivakegg** [comment]
From an operational standpoint.  I cannot have a scan thread that exposes a problem taking down tservers, especially when it is likely that that scan is being spread across a good portion of the system.

**Comment by ctubbsii** [comment]
> From an operational standpoint. I cannot have a scan thread that exposes a problem taking down tservers, especially when it is likely that that scan is being spread across a good portion of the system.

Understood. However, from another operational standpoint, we can't have a bad scan thread corrupt a tservers' internal state and leave it running to cause more harm, like corrupting user data or returning bad results, either. I've seen that too.

These are competing principles, but both have merits. The greater risk of the two really depends on the specific application and user risk tolerances. Best we can do is to try to make it possible for users to make their own choices, by making things more pluggable, which is what we've been doing over the last several years, to make Accumulo's components more modular, with SPI endpoints, and less tightly coupled default internal components.

**Comment by ivakegg** [comment]
Now that I have a way of overriding the context class loader factory and pass through the configuration, I can override the vfs class loader with one that will capture NoClassDefError and throw an exception instead which will avoid the tserver from falling over.

**Comment by ivakegg** [comment]
Actually, looking at what the error was more closely, it was actually not in the path of the VFS Class loader.  I am reopening this until I can dig further.

**Comment by dlmarion** [comment]
@ivakegg - were you able to confirm that the issue is related to your scan trying to load a class that did not exist on the classpath (using table.classpath.context) and that the issue was due to something external to the Accumulo codebase?

**Comment by ivakegg** [comment]
I think I have now done enough to be able to mitigate this problem in our systems.  Closing this issue.
