### ISSUE TITLE
Consolidate or rename two different SplitRecoveryIT classes

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3376]
We seem to have two different ITs with the same name. These are either redundant and test the same code, or they test different aspects of it, or test entirely different things. These should either be consolidated into a single IT with that name, or one of them should be renamed, because this is confusing.

* test/src/main/java/org/apache/accumulo/test/functional/SplitRecoveryIT.java
* test/src/main/java/org/apache/accumulo/test/SplitRecoveryIT.java

Saw this on de73759c24c2d298bf569cd5b84783f2d3eb6d07 in the main branch for 3.0.0-SNAPSHOT. I'm sure it exists for earlier branches, but it's not worth fixing there. It can just be fixed in the main branch for whatever version we're working on at the time it is fixed.

**Comment by jmark99** [comment]
I ran across this ticket today. It looks like it has been addressed. The current main branch has a modified version of  `accumulo/test/functional/SplitRecoveryIT.java` and the the `accumulo/test/SplitRecovertyIT.java` class no longer exists.

I'm going to close the ticket. It can be re-opened if someone thinks more work should be done.
