### ISSUE TITLE
Accumulo tablets are getting out of sync with metadata

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3386]
We are finding a good number of tablets in separate tservers that are getting stuck in the state where the files differ.  The commonality between these are that the accumulo metadata references an F file (minor compaction file) that is not in the "in-memory" list of files.  Once the tablet gets into this state it appears to be stuck in that state.  The F files are always relatively small (400-500 bytes).

Accumulo 2.1.1-SNAPSHOT
CentOS 7.3

**Comment by ivakegg** [comment]
For the 12 tablets that got out of sync, they all were for the same table (lets call it table X) and the metadata for all of them were from the same accumulo metadata tablet.  Also they all started complaining about the error at about the same time.  So this suggests that this bad state has to do more with the accumulo metdata tablet that was handling all of the table X tablets at the time.  No errors were found in the previous 30 minutes on either the tserver handling the metadata tablet, or in the tservers handling the tablets for table X.

**Comment by dlmarion** [comment]
@ivakegg  - Are you able to give us an example of the wording of the log message? There are a couple of different places where these checks occur, with slightly different wording.

**Comment by EdColeman** [comment]
I think it was in the same check-loop that was changed to prevent the check from killing the tserver

**Comment by dlmarion** [comment]
> I think it was in the same check-loop that was changed to prevent the check from killing the tserver

This doesn't mean anything to me.

**Comment by EdColeman** [comment]
The code that was modified in https://github.com/apache/accumulo/pull/3366.  Now instead of killing the tserver it is logging that the contents of the tserver memory and the metadata table do not match.

**Comment by dlmarion** [comment]
That loop seems like it could over-warn considering that it grabs all of the tablet metadata first, then checks each tablet. By the time it gets to a Tablet, its metadata could have changed.  The fact that the tablets seems stuck in this state is concerning. @ivakegg - could you confirm via scanning the metadata table in the shell that the minor compaction file is listed in the tablet metadata for one of the 12 tablets? Then, on the tserver for this tablet, what is in the log for the F file? Did it get compacted away?

**Comment by EdColeman** [comment]
If I recall from what he showed me - the file does not get compacted away.  It seems that 
1. The tablet had ingest and a flush is triggered
2. The metadata is updated with the flush F file
3. The tserver in-memory cache is not updated
Then after some period, the check gets scheduled an runs - sees that the metadata and the in-memory cache do not match, it now prints the issue and then keeps repeating for every check.  

@ivakegg - please correct this if I have the details misrepresented.

**Comment by keith-ratcliffe** [comment]
> @ivakegg - do you know if the tablet in question split around the same time?
> 
FWIW, I did `grep -m 1 'differ from in-memory' ` across all tserver logs and noted the earliest occurrence that I could find. Then I grepped across all tserver logs again to find all 'Starting split' log messages associated with that tablet, but found none at all for that one

**Comment by ivakegg** [comment]
I can confirm what Ed stated.

**Comment by keith-turner** [comment]
I opened #3392 while looking into this. I noticed a race condition in the code and #3392 fixes that.  I don't think #3392 fixes what we are seeing here.  If a false positive did trigger because of the race condition fixed in #3392 I think it would be transient, so would not see the same file reported on the next check.  The fix in #3392 moves the increment of the start counter to before the metadata table update, it was before the walog update but not the metadata table update (the increment just needed to move up a bit further).

**Comment by dlmarion** [comment]
Related comment thread [here](https://github.com/apache/accumulo/pull/3392#discussion_r1191504746)

**Comment by cawaring** [comment]
It appears in all cases it was either a MinC file (F*****.rf) or a bulk load file (I******.rf) that is present in the metadata table, but not in the tserver memory.  There are three F files from one table that were all generated at the same time on the same day and one I file from a different table.   So this is happening across multiple tables and multiple tservers. It seems to always be the same tables and the same files referenced in the logs.  

I do not see any messages regarding splits on the metadata table or the individual tsevers hosting the tablets referencing a discrepancy.  I also do not see any time outs for connections or scans around the time these warnings are generate.

**Comment by keith-turner** [comment]
Another potential cause that would be good to rule is something odd happening with the serialization/deserialization/hashCode/equals.  Roughly the following is happening

 1. A StoredTabletFile object is created and saved to the metadata table and stored in memory
 2. Later the code reads a string from the metadata table, use that string to create a new StoredTabletFile object.  Then it compares the new object created from the metadata table with created earlier and stored in a set or map.

If we can rule out that something is going wrong with the desieralization and/op comparison of these objects that would be useful.  One possible was to do this is to look for the same file that is translated to a slightly different string in the logs at diff times, for the files involved in the messages that is.

**Comment by dlmarion** [comment]
@keith-turner - regarding StoredTabletFile - https://github.com/apache/accumulo/issues/2830

@cawaring - You didn't see any messages like [this](https://github.com/apache/accumulo/blob/2.1/core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java#L67) ?

**Comment by keith-turner** [comment]
> @cawaring - You didn't see any messages like [this](https://github.com/apache/accumulo/blob/2.1/core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java#L67) ?

Looking at the referenced code, we do not do the recursive check for an error when the top level exception is not an error.  So if an exception wraps an error it will not halt.

**Comment by dlmarion** [comment]
> > @cawaring - You didn't see any messages like [this](https://github.com/apache/accumulo/blob/2.1/core/src/main/java/org/apache/accumulo/core/util/threads/AccumuloUncaughtExceptionHandler.java#L67) ?
> 
> Looking at the referenced code, we do not do the recursive check for an error when the top level exception is not an error. So if an exception wraps an error it will not halt.

Correct. However, if an exception was raised in the minc thread and was uncaught, as you suggested earlier, then there should be an ERROR message in the log with the stack trace.

**Comment by keith-turner** [comment]
> Correct. However, if an exception was raised in the minc thread and was uncaught, as you suggested earlier, then there should be an ERROR message in the log with the stack trace.

Yeah, hopefully there are two.  One from the uncaught handler and one from the minc code.  I am going to make a quick draft PR to change the uncaught handler.

**Comment by ivakegg** [comment]
BTW, we have seen this same situation occur for bulk import files where the metadata contains the "I" files but the tserver's memory does not.

**Comment by dlmarion** [comment]
> > As an aside, this Error seems like it shouldn't be there:
> 
> Yeah that catching of error is suspect.

I found others, I created #3395

**Comment by keith-turner** [comment]
Created #3396 to modify the behavior of the uncaught exception handler

**Comment by cawaring** [comment]
I do not see those messages in the logs

**Comment by ctubbsii** [comment]
I'm trying to sum up the status of this issue. It looks like #3392 and #3396 probably fixed it, but we are waiting on confirmation from the reporter that this is no longer happening after the patches are applied. Based on that, I'm closing this for now, but feel free to reopen it if I've misunderstood the status, or if the issue continues occurring with these patches. If you do re-open, please provide the git commit of the SNAPSHOT you're using (a good idea whenever you open a ticket specifying a SNAPSHOT version is being used).
