### ISSUE TITLE
Access to AccumuloConfiguration when overridding classloader

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#3399]
In order to resolve our issue described in #3371, it was denoted that we override the class loader and hence the context class loader factory to be able to catch the errors being thrown that would halt the tservers.  So I created such a mechanism and hit the problem where the ClassLoaderUtil does not pass the accumulo configuration to the factory if overridden.  This is needed to be able to access the context classpaths currently configured.  We have a good amount of infrastructure surrounding setting up this configuration as we add new contexts.  Can we perhaps add a method to the ContextClassLoaderFactory to pass the accumulo configuration in, or at least the subset related to context configuration (general*.context.*).

Accumulo 2.1.1-SNAPSHOT
CentOS 7.3

**Comment by ivakegg** [comment]
Perhaps add a method on the ContextClassLoaderFactory to pass the accumulo configuration in, or perhaps a ServiceEnvironment implementation.  I guess a ClassLoaderEnvironment mechanism would be the cleanest way to handle this.

**Comment by ctubbsii** [comment]
If you're using classpaths as the context, then the factory will already receive that context when it is asked for the context's corresponding context. However, I don't see a problem injecting a service environment.
