### ISSUE TITLE
Revisit unassignment request mechanism introduced in #3382

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3406]
In #3382 a quick hack was added to for requesting the manager to unassign a tablet that needed to be split.  This code needs to be revisited.  Either need to develop a new approach or improved the approach that was taken in #3382 to make it more robust.  There are multiple TODOs in the code related to this.

**Comment by keith-turner** [comment]
The following are TODOs in the code related to this issue.

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/split/SplitScanner.java#L35

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/base/src/main/java/org/apache/accumulo/server/manager/state/CurrentState.java#L45

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/base/src/main/java/org/apache/accumulo/server/manager/state/MetaDataTableScanner.java#L105

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/Manager.java#L573

**Comment by dlmarion** [comment]
@keith-turner and I discussed a possible solution for this would to create a new method on the Manager Thrift API so that another process could request a Tablet to be unloaded for maintenance (split/merge). The new method would write an entry into the tablet metadata so that when the TabletMetadataIterator read the TabletMetadata for the Tablet it would return a unhosting state to the TabletGroupWatcher.

**Comment by keith-turner** [comment]
The new metadata key could contain the fate transaction id.  That allows concurrent FATE ops to remove their unassignment request independently. The hacky in memory map that does this currently tracks each FATE that wants a tablet unassigned independently.

**Comment by keith-turner** [comment]
> @keith-turner and I discussed a possible solution for this would to create a new method on the Manager Thrift API so that another process could request a Tablet to be unloaded for maintenance (split/merge). The new method would write an entry into the tablet metadata so that when the TabletMetadataIterator read the TabletMetadata for the Tablet it would return a unhosting state to the TabletGroupWatcher.

We also discussed that this change is a prerequisite for #3822 as it removes the reliance on FATE execution and the TGW being in the same process.

**Comment by dlmarion** [comment]
@keith-turner  - I think #3835 resolved this. That PR replaced the hack, and the TODOs referenced above are gone.
