### ISSUE TITLE
Add more split integration tests

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3407]
The following TODOs about adding more test were added by #3382

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/split/SplitUtils.java#L191

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java#L68

**Comment by DomGarguilo** [comment]
I've started working on adding tests for these cases in #3415 

@keith-turner can you please take a look to see if I am on the right track to address the second case mentioned above?

**Comment by DomGarguilo** [comment]
This ticket has been partially addressed by #3415. The TODO in `SplitUtils` is still unaddressed:

> https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/split/SplitUtils.java#L191
