### ISSUE TITLE
Determing if split FATE op should get table lock

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3412]
In #3382 a new fate operation was introduced for splitting a tablet.  This new FATE operation does not get a tablet lock.  Later when all tablet operations have been moved from the tserver to the manager, need to determine if the tablet lock is needed. The following is a todo in the code related to this.

https://github.com/apache/accumulo/blob/808c0bb5cc28511da6b50676a34f1abf36b7d20c/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/PreSplit.java#L63

**Comment by keith-turner** [comment]
One problem with not getting a tablet lock is that splits could run on an offline table.  See [this comment](https://github.com/apache/accumulo/issues/3823#issuecomment-1781457175)

**Comment by keith-turner** [comment]
Looked into that and opened #4334 and #4335.  Prior to elasticity a compaction or split operation could never run unless a tablet was hosted.  Now these operations can run on unhosted tablets.  Taking a table offline assumed that once all the tablets were no longer hosted that splits or compactions would no longer happen.  

 * The offline API has a wait operation, we could change the wait operation to wait for no compactions to be runnning, no splits to be running, and no tablets to be hosted.  Currently it only waits for all tablets to be unhosted.
 * We could make sure that new split and compaction operations do not start on offline tables. 

For making operations not start, these checks can be done early to avoid work which is where #4335 comes in.  Then the checks can be done as late as possible which is where #4334 comes in, it adds a check immediately before setting the compaction id in the tablet.  Could also add a check in the split code as late as possible, that work could be done under this issue.

**Comment by cshannon** [comment]
I started this aternoon working on an attempt at a PR for the first checklist item:

> Add code to offline wait operation that scans tables metadata and waits for no location, no external compaction id, and no operation ids. 

After talking to @keith-turner about this, there might be some race condition issues still to solve and more work to do here but the first attempt will at least update TableOperationsImpl to check no external compaction is or op id. I'm working on some tests now and should have a PR up tomorrow.
