### ISSUE TITLE
Improve unit test cover for FencedReader 

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3448]
This issue is a follow on to improve tests after merging #3418

There are a few new methods in the newly added iterator [FencedReader](https://github.com/apache/accumulo/blob/8d39c8e34b86a95e108681e33e1c7c19e2ebbc4a/core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java#L1707) that do not have test coverage and need unit tests written. 

See the comments below:

https://github.com/apache/accumulo/pull/3418#discussion_r1214827264
https://github.com/apache/accumulo/pull/3418#discussion_r1214828434
https://github.com/apache/accumulo/pull/3418#discussion_r1214828907
https://github.com/apache/accumulo/pull/3418#discussion_r1214840221

**Comment by cshannon** [comment]
@ddanielr - I think this is something you can start working on if that sounds good.

**Comment by ddanielr** [comment]
Yep that works!

**Comment by cshannon** [comment]
I'm closing this as this extra test coverage is now covered as an item in the list for #3766
