### ISSUE TITLE
Add unit test for bounded compaction job priority queue

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3466]
In #3460 a new bounded priority queue was created to hold compaction jobs in the manager.  This new class needs unit test.

**Comment by dlmarion** [comment]
@keith-turner  - Curious if you evaluated Guava 33.0's MinMaxPriorityQueue when you created CompactionJobPriorityQueue.

**Comment by dlmarion** [comment]
HBase also has https://github.com/apache/hbase/blob/master/hbase-server/src/main/java/org/apache/hadoop/hbase/util/BoundedPriorityBlockingQueue.java

**Comment by keith-turner** [comment]
> Curious if you evaluated Guava 33.0's MinMaxPriorityQueue when you created CompactionJobPriorityQueue.

Yeah I did.  One reason I did not use was the following comment on the javadoc.  So when trying to use it as a bounded size prio Q it seems like it would be slow. 

> If you only access one end of the queue, and don't use a maximum size, this class is functionally equivalent to [PriorityQueue](https://docs.oracle.com/javase/9/docs/api/java/util/PriorityQueue.html?is-external=true), but significantly slower.

A second reason I did not use was to because when a new jobs are added for tablet, need to efficiently remove any previous jobs related to the tablet that happen to be in the queue.

**Comment by keith-turner** [comment]
Wrong comment from the javadoc, the following was the comment I was looking at

> If you only access one end of the queue, and do use a maximum size, this class will perform significantly worse than a PriorityQueue with manual eviction above the maximum size. In many cases [Ordering.leastOf(java.lang.Iterable<E>, int)](https://javadoc.scijava.org/Guava/com/google/common/collect/Ordering.html#leastOf(java.lang.Iterable,int)) may work for your use case with significantly improved (and asymptotically superior) performance.
