### ISSUE TITLE
Improve conditional mutation check for adding an external compaction

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3467]
In #3460 a basic conditional mutation check was added to ensure a tablet has no compactions running.  This check was used when adding a compaction to a tablet.  The check is too restrictive and will only allow a single concurrent compaction per tablet. What is needed is a conditional check that examines any existing running compactions and ensures their files are disjoint with the new compaction being added.  The check in #3460 ensures files are disjoint by only allowing one at a time.

**Comment by keith-turner** [comment]
This was addressed in #3513, should be able to have multiple concurrent compactions running on a tablet after #3513.  The new requireSame call added to ample made this complex check easy to implement.

**Comment by ctubbsii** [comment]
> This was addressed in #3513

That PR is still open. Linking the issue with the PR and re-opening this.

**Comment by keith-turner** [comment]
Closing as #3513 was merged.
