### ISSUE TITLE
Remove compaction hierarchy from cluster.yaml

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3470]
Now that the CompactionCoordinator was moved into the Manager, there is no need for the extra heirarchy in the cluster.yaml file. 

This:
```
compaction:
  compactor:
```

Can now simply become:
```
compactor:
```

**Comment by ctubbsii** [comment]
Is this causing harm? It seems like unnecessary churn. What's the risk of leaving it the way it is?

**Comment by AlbertWhitlock** [comment]
I have worked with the cluster.yaml file before. I can do this ticket (if it is deemed necessary). Could someone assign to me?
If this change is completed it looks like a test, the ClusterConfigParserTest, will need to be updated as well.

**Comment by keith-turner** [comment]
> Is this causing harm? It seems like unnecessary churn. What's the risk of leaving it the way it is?

We could easily support both, as long as only one is specified.

**Comment by ctubbsii** [comment]
> > Is this causing harm? It seems like unnecessary churn. What's the risk of leaving it the way it is?
> 
> We could easily support both, as long as only one is specified.

Only if it's not much code to support both. accumulo-cluster is supposed to be a very lightweight tool that serves as a reference for how one might manage a cluster. It really shouldn't be getting too complex. It'd be easy for this tool to start accruing technical debt through these kinds of choices. It might be simpler to just leave the existing hierarchy... it's  just one extra element, and it might not be causing any harm.

**Comment by dlmarion** [comment]
This was completed as part of #3591
