### ISSUE TITLE
Update JLine past 3.21.0 (non-trivial)

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3485]
Updating to 3.22.0 caused problems (#3446). That needs to be investigated further. Depending on the outcome of that investigation, we could choose one of:

1. figure out how to achieve the desired behavior in the newer versions
2. get a patch pushed upstream to JLine, and update to that newer version
3. accept the change in behavior and update to the newer versions anyway (let users know of any workarounds that exist)

**Comment by ctubbsii** [comment]
The underlying issue should be fixed in 3.23.1, but JLine hasn't released that version yet.

**Comment by EdColeman** [comment]
JLine 3.24.0 was released - working on testing it now.
