### ISSUE TITLE
TServer Sort by Scans

### ISSUE THREAD

**Issue by apmoriarty** [apache/accumulo#3488]
**Describe the bug**
Put a system running accumulo 2 under load and view the tservers page for a particular table and then sort by scans. The sort order is lexicographical when it should be numerical. 

The result of the current sort order is that a lightly-loaded tablet server with 9 scans sorts before a heavily loaded tablet server with 50-odd scans with other scans queued. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.1
 - OS: Centos
 - Others:

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Put a system under load
2. Navigate to the tables page
3. Select a table with running scans
4. Sort by "scans"

**Expected behavior**
When I sort tservers by running scans, I expect the sort to be numerical. As it was in accumulo 1.

**Screenshots**
N/A

**Additional context**

**Comment by ctubbsii** [comment]
This seems like it affects the `/manager` and `/tservers` pages in addition to `/tables/<tid>`. It would also apply to compactions. Scans, Minor Compactions, and Major Compactions on each of these pages use a custom `running(queued)` format that does not lend itself to numerical sorting by datatables natively. We'll need to create and use something custom to try to sort these by running first, then by queued second.

**Comment by AlbertWhitlock** [comment]
I have done a good amount of work in the monitor code in the past. I will tackle this. Could someone assign it to me please? Thanks.
