### ISSUE TITLE
Table Page Should Display Table Name

### ISSUE THREAD

**Issue by apmoriarty** [apache/accumulo#3489]
**Is your feature request related to a problem? Please describe.**
When navigating from the "Tables" page to a specific "Table page, the human-readable name is not displayed anywhere. When multiple tabs are open for multiple tables it's easy to lose track of which table id maps to which table name. 

**Describe the solution you'd like**
The "Table" page should display the table name. I would not be upset if the table id was also displayed in parenthesis. For example "TableName (table_id)"

**Describe alternatives you've considered**
I briefly considered memorizing the mapping of table name to table id but ultimately decided against it. 

**Additional context**
N/A

**Comment by ctubbsii** [comment]
> I briefly considered memorizing the mapping of table name to table id but ultimately decided against it.

:rofl:
