### ISSUE TITLE
Trying to split Tablet with large row leaves Tablet in bad state

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3491]
**Describe the bug**
Tablet.split calls [initiateClose](https://github.com/apache/accumulo/blob/7c5bbc6e90af44b959e8c6f0a2807a7dda4b61ce/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1522) on the Tablet. However, if a split row cannot be calculated, then the split process is [aborted](https://github.com/apache/accumulo/blob/7c5bbc6e90af44b959e8c6f0a2807a7dda4b61ce/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1553) leaving the Tablet in a bad state. The Tablet is open, but the Compactable is closed, and compactions on that Tablet will not occur.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.0, 2.1.1-RC1

**Comment by ctubbsii** [comment]
For now, I'll mark this for 2.1.2, but if the vote for 2.1.1-RC1 fails because a fix for this is ready, then I'll change it back to 2.1.1 and include it in RC2.
