### ISSUE TITLE
Add data file path validation to MetadataConstraints

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3504]
This is a follow on to #3502 . Now that `StoredTabletFile` was changed to lazy load `ReferencedTabletFile` to improve GC performance, validation is not done all the time unless the `ReferencedTabletFile` is loaded. This could be an issue if someone enters in a bad path in data file mutation that is stored in the metadata tablet since we don't validate always.

To fix this we can add a constraint [check](https://github.com/apache/accumulo/blob/85e1e25c89e3333563db471b50193d2bdad6988b/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java#L132) to `MetadataConstraints` to verify that mutations that write to the different file columns (DataFile, BulkFile, ScanFile, etc) have the paths validated before insert/update.

Tests should also be added to `MetadataConstraintTest` to verify the validation works.

**Comment by keith-turner** [comment]
@cshannon  I was just updating the metadata constraint in the elasticity branch to add validation for a new selected file column for compactions.  I opened #3505 after doing that work and seeing this issue.

**Comment by cshannon** [comment]
@keith-turner - Do you think we should just do everything in one PR or just do #3505 as a follow on to this issue? I guess it makes sense to keep them separate as there are different things.

**Comment by cshannon** [comment]
@keith-turner - Nevermind, I started working on a PR for this and I'm almost done so #3505 can be a follow on.

**Comment by keith-turner** [comment]
@cshannon I see this issue as a specific validation that is needed.  For #3505, its a more general improvement about making the code more efficient and easier to analyze.  After making it easier to analyze we can look for other missing validations like this one that should be added.
