### ISSUE TITLE
Reorganize MetadataConstraints for efficiency and easier code analysis

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3505]
**Is your feature request related to a problem? Please describe.**

The code in [MetadataConstraints](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java) is very disorganized and is possibly inefficient.  The disorganization makes it difficult to anylyze the code to ensure the validation is as strict as possible for each column.  The inefficiency comes from the chained if else statements that may compare the same family multiple times.

**Describe the solution you'd like**

It would be nice to use a swtich statement on the column family for efficiency and have a function per colum family to better organize the code.  With this structure it will be easier to analyze to ensure every column has coverage.  The following is a skeleton of what this might look like.

```java
  @Override
  public List<Short> check(Environment env, Mutation mutation) {
    final ServerContext context = ((SystemEnvironment) env).getServerContext();

   byte[] row = mutation.getRow();

    if (row.length > 0 && row[0] == '~') {
      return validateNonTabletUpdate(mutaion);
    }
  
    ArrayList<Short> violations = null;

    violations = validateTabletRow(violations, row);

    for (ColumnUpdate columnUpdate : colUpdates) {
      var familyStr = new String(columnUpdate.getColumnFamily(), UTF_8);
      switch (familyStr) {
        case  TabletColumnFamily.STR_NAME:
          violations = validateTabletFamily(violations, columnUpdate);
          break;
        case ServerColumnFamily.STR_NAME:
          violations = validateServerFamily(violations, columnUpdate);
          break;
          // TODO add case stmt for each family
        default:
          violations = addViolation(violations, 2);
      }
    }
    
    return violations;
}

  private ArrayList<Short> validateServerFamily(ArrayList<Short> violations, ColumnUpdate columnUpdate) {
    var qualStr = new String(columnUpdate.getColumnQualifier(), UTF_8);
    
    switch (qualStr) {
      case ServerColumnFamily.OPID_QUAL:
        // TODO validate this
        break;
      case ServerColumnFamily.DIRECTORY_QUAL:
        // TODO validate this
        break;
     //TODO validate other qualifiers
      default:
        violations = addViolation(violations, 2);
    }
    
    return violations;
  }
```

**Comment by keith-turner** [comment]
Realized [MetadataConstraints](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java) does no validation for non tablet updates.   As part of this reorganization effort, could open up follow on issues for areas lacking validation after reorganizing the existing code.

**Comment by cshannon** [comment]
As part of the reorganization we should also address https://github.com/apache/accumulo/pull/3506#discussion_r1248270420

**Comment by kevinrr888** [comment]
Closing as completed from https://github.com/apache/accumulo/pull/4852

> Realized [MetadataConstraints](https://github.com/apache/accumulo/blob/main/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java) does no validation for non tablet updates. As part of this reorganization effort, could open up follow on issues for areas lacking validation after reorganizing the existing code.

@keith-turner this may be still be something left to do, I'm not sure. I'm not sure which areas are lacking validation or just don't need it, so this may be better for someone else to open the issues if there are any more (since you have already opened a few follow ons noted in https://github.com/apache/accumulo/pull/4852).
