### ISSUE TITLE
Create a cluster configuration object to use when starting MAC

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3515]
In prior versions scan servers and compactors were optional components. This is no longer the case, so MAC should be updated to start the required components. Additionally, the compactor, sserver, and tserver components will support groups. I think we should create a java object, much like cluster.yaml, that defines the grouping and number of components that MAC should start and remove methods like `startCompactor`. A default configuration should exist with options for users to supply their own configuration in the ITs.

**Comment by keith-turner** [comment]
For compactions it would be good to consider root and metadata table for this change.  I opened #3518 as a general issue around getting the root and metadata table to support external compactions.  We will need those compacting and running in mini also.

**Comment by dlmarion** [comment]
Closed by #3533
