### ISSUE TITLE
Add unit test for SetEqualityIterator

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3521]
In #3513 a new iterator was added called SetEqualityIterator.  This new iterator is used by conditional mutations to check if a set stored in the column qualifier is the same as expected before making an update.  For example it supports use cases like the following.

 1. Read tablet metadata and see that it has files F1,F2,F3
 2. Create a mutation that deletes files F2, F3 and adds F4
 3. Add a condition to the mutation that the tablets current set of files must be F1,F2,F3 inorder to make the update.  This condition will use the SetEqualityIterator

**Comment by keith-turner** [comment]
May be best to do this after #3522

**Comment by rsingh433** [comment]
I will look at this issue.

**Comment by dlmarion** [comment]
Closed by #4486
