### ISSUE TITLE
Explore comparing file values in requireSame

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3522]
In #3513 a new requireSame conditional mutation check was added to Ample.  This check allows easily comparing if something read from a tablet is the same before making an update.  For the tablets files it only compares the file path and not the value.  Currently when we read a tablet files we get a `Map<StoredTabletFile, DataFileValue>`.  When requireSame is called and told to check that the tablets files are the same it only checks the keys in the map are the same (it checks if the set of StoredTabletFile is the same).  Ideally it would check the entire map is the same in order to be more rigorous.

**Comment by rsingh433** [comment]
I will look at this issue.

**Comment by dlmarion** [comment]
Closed by #4486
