### ISSUE TITLE
Prevent user compaction starvation

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3524]
In #3513 coordination of user compaction was moved to the metadata table and manager.  User compactions select a set of files that are compacted by one or more compaction jobs.  Inorder to select file for a tablet it must not have any current compactions running.  The fate operation will wait for this.  If new files are always coming in and system compactions are continually running, then the fate operation may never select files.  This could be prevented by adding a new column to the tablet metadata that indicates a fate operation is waiting to select files.  When this column is present it would prevent new system compactions from starting until the new fate op selects files and deletes this new column.

**Comment by cshannon** [comment]
I will take a look at this
