### ISSUE TITLE
Consolidate CompactionIT and ExternalCompactionIT*

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3525]
Some of the test in ExternalCompactionIT exercise the same functionality as test in CompactionIT except they do it for external compactions.  As accumulo moves to only having external compactions these test should be consolidated if possible.

**Comment by keith-turner** [comment]
Some of the test in ExternalCompactionIT explicitly start compactor processes in mini, that will probably not be needed anymore. That could be cleaned up as part of this issue or as part of #3515

**Comment by DomGarguilo** [comment]
Do you think this consolidation could happen now or once accumulo moves to only having external compactions?

**Comment by keith-turner** [comment]
> Do you think this consolidation could happen now or once accumulo moves to only having external compactions?

I think that work could start after I make one more big PR for compactions that I am hoping to make this weekend.
