### ISSUE TITLE
Decide default compactor group names and make supporting changes

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3546]
In the 4.0 elasticity changes all compactions will be external and internal compactions that ran in tserver will be removed.  In 2.1 the internal compactions that ran in the tserver supported different compaction executors for the metadata table with the default config.  This meant in 2.1 that metadata table compactions would never have to wait on user tablet compctions because they had dedicated thread pools.

In 4.0 a similar thing could be achieved by assigning metadata table compactions to dedicated compactors groups.  However there is a wrinkle with this, it means that users would need to start these compactors. In #3460 and #3539 the following default compaction groups were defined in the Accumulo config.

Group Name | Purpose
------------------| ------------
accumulo_meta | A group of compactors and associated priority queue that is dedicated to processing accumulo metadata compactions.  We could define an additional default group for the root tablet, this compactor would be idle most of the time but it would ensure root table compactions never have to wait on metadata table compactions.
user-small | A group of compactors and associated priority queue  that is dedicated to processing compactions on user tables where the sum of the input files is less than 128M.  Having these dedicated resources ensures that small quick compactions do no linger waiting on larger compactions.
user-large | A group of compactors and associated priority queue  that is dedicated to processing compactions on user tables where the sum of the input files is greater than 128M

Need to decided if these are the defaults we want and update scripts and documentation to make it easy for a user to start with these defaults.

**Comment by keith-turner** [comment]
Need to consider the default compaction service config that defines default groups with the default compactor group name.

**Comment by ctubbsii** [comment]
I'm not caught up on all the details, but definitely shouldn't mix underscore\_based naming conventions with dash-based naming conventions, as shown above.

**Comment by dlmarion** [comment]
IMO we should keep the default compactor group configuration simple. `system` for compactions for the root and metadata tables, and `default` for everything else. `default` is already used in the default configuration for scan servers and tablet servers in #3496 and it's follow-on PR, so it's consistent.

**Comment by dlmarion** [comment]
I talked with @ddanielr about this issue and #4273 as they seem to overlap a little. I'm going to change the existing configuration down to one group in a PR. He said that @keith-turner made a change recently that would give root and meta priority over user tables within one group. I want to see how much faster the ITs run when we are only starting one compactor for MAC vs four.
