### ISSUE TITLE
User initiated compactions that throw an exception may hang

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3553]
**Describe the bug**

A user initiated compactions that throw an exception may hang.

**To Reproduce**

Would like to try to recreated this with an integration test.  Maybe something like the following.

 1.  Create a an iterator that throws an IOException if file X exists in DFS
 2. Create file X
 3.  Initiate a user compaction with the above iterator configured.
 4. Sleep a bit (or devise a way to know if the iterator has run once and failed, it could create file Y when it fails and instead of sleeping wait for file Y to exist)
 5. Delete file X
 6. Wait for compaction to complete

**Expected behavior**

Compactions that throw an exception retry.

**Comment by ctubbsii** [comment]
@keith-turner In which version was this seen?

**Comment by keith-turner** [comment]
2.1.1 I think

**Comment by dlmarion** [comment]
I wrote a [test](https://github.com/dlmarion/accumulo/commit/c4110282a293387469a51ed98716af39d90fa161) that hangs.  On the Manager side, CompactionDriver.[isReady](https://github.com/apache/accumulo/blob/2.1/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java#L110) will continue to return a non-zero wait time as long as there are tablets which have a compactID that is less than the compactID for `this` compaction. For those tablets, the CompactionDriver continues to call TabletClientHandler.compact(), which goes through the motion each time of initiating a compaction on that tablet. 

In InternalCompactionExecutor.InternalJob.[run](https://github.com/apache/accumulo/blob/2.1/server/tserver/src/main/java/org/apache/accumulo/tserver/compactions/InternalCompactionExecutor.java#L91) I cannot find anything that checks the FAILED status (or the COMPLETED status for that matter). A `completionCallback` is invoked (line 97) on success, but nothing happens on the failure path.
