### ISSUE TITLE
Wait.waitFor(Condition) return value not checked

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3564]
**Describe the bug**
A lot of test code calls `Wait.waitFor(Condition)` and does not check its return value.  I had assumed this method would wait forever, but it does not it only waits for 30 seconds and then returns false.

**Expected behavior**

Either test code checks the return value OR remove the return value and make the method wait forever.  I am in favor of waiting forever and letting junit timeout the test as it makes test code easier to write.

**Comment by ctubbsii** [comment]
@keith-turner Planning to fix this in 2.1 branch, or just main branch? I think probably main is the only place we need this... existing tests are pretty stable in 2.1, as far as I can tell.

**Comment by EdColeman** [comment]
Would it be an option to check the return state in Wait.waitFor and if false, throw an exception (IllegalState?)  That way instead of waiting "forever" and needing the test to time out we could signal the failed condition sooner and the callers would bit need to check the return status?

I'm think of something like a ZooKeeper update - it should happen within seconds, certainly less than a minute - why wait longer for the entire test timeout period.

If an exception is okay, I can take this and target 2.1

**Comment by keith-turner** [comment]
> Would it be an option to check the return state in Wait.waitFor and if false, throw an exception (IllegalState?) That way instead of waiting "forever" and needing the test to time out we could signal the failed condition sooner and the callers would bit need to check the return status?

There are Wait.waitFor methods that take a timeout period as a parameter.  If someone wants to wait less than the test timeout then they can call those methods and maybe those methods could throw an exception instead of return a boolean.  The methods that take a parameter could directly call a junit method to the fail the test.   The method that does not take a parameter could wait forever and let the per test timeout config determine what happens.  These two changes could make using the methods easier and make the test more correct, there is never a boolean to remember to check.

**Comment by EdColeman** [comment]
I'll have a PR up shortly (as long as sunny tests pass)

There was push-back from trying to include junit dependencies in this class in the recent past - so I opted to just thow IllegalStateException - but we can change that if we don't like the way it looks.
