### ISSUE TITLE
Evaluate use of TabletManagement iterator outside of TabletGroupWatcher

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3576]
The TabletManagementIterator is used a good bit by code other than the TabletGroupWatcher.  In the elasticity branch a lot of functionality was added to the TabletManagementIterator that is used exclusively by the TabletGroupWatcher.  For the other code that uses TabletManagementIterator need to evaluate if its still suitable or would using an Ample tablet metadata scanner better.

Was attempting to refactor the TabletManagementIterator a bit as part of #3517 and doing so became unwieldy because of how widely it was used outside of TGW.  The predecessor of TabletManagementIterator predates Ample, so it may now make more sense to use Ample outside of the TGW now.  Using the TabletManagementIterator outside of the TGW could lead to suprises as it is a complex iterator and all of its complexity exists because of TGW use cases.

**Comment by dlmarion** [comment]
@keith-turner - I'm not sure that this is still an issue.

**Comment by keith-turner** [comment]
In #3904 code outside of TGW was moved away from using the TabletMgmtIter.  Also #3933 was opened to do server side filtering in a more straightforward way.
