### ISSUE TITLE
Acquire per tablet operation id as part of deleting a table

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3580]
Many different processes can now update tablets using conditional mutations.  To prevent spurious writes to the metadata table the delete table fate op should set the operation id on each tablet before deleting the tablets.  This prevents split and or merge operations from spuriously writing  writting data to the metadata table.  This should probably be done as a new Repo in the Fate operation that runs before the current cleanup operation and sets an operation id on each tablet.

If this is done, then the split fate op probably does not need to get a tablet lock re #3412.

**Comment by dlmarion** [comment]
@keith-turner  - Is this closed by #3929 ?
