### ISSUE TITLE
Resolve resource group usage in TableLoadBalancer

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3590]
This is a follow-on issue to #3496. TableLoadBalancer.getAssignments and TableLoadBalancer.balance create a subset of TabletServers for the table based on the new custom property. This behaves like the HostRegexTableLoadBalancer except that it uses the new resource group properties instead of host regular expressions (Note: HostRegexTableLoadBalancer could likely be removed at this point).

This issue is to resolve the disconnect between table load balancing and tablet balancing. #3496 included a new method, `getResourceGroup` on TabletBalancer, but the new feature really only works at the table level. In order for resource group assignment to work at the tablet level, all of the other tablet balancers would need to change to be aware of the resource group assignment for the tablet.

**Comment by ctubbsii** [comment]
It looks like this was fixed by #3603
