### ISSUE TITLE
Deprecate InstanceOperations.getActiveComactions(String tserver)

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3593]
While working on #3592 noticed [this method](https://github.com/apache/accumulo/blob/d4846d407e5b28482394e2c0baa16932ae35e086/core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java#L212) that list the active compactions on a tsever.  Given this will always be the empty set now, should probably deprecate this method in 3.x so it can be remove in 4.0.

**Comment by dlmarion** [comment]
So, we could just change the parameter from `tserver` to `server` and update the javadoc. If we remove this method, then there is no way to get the compactions running on a Compactor. Do we need to deprecate this and create a new method for this type of change? I'm thinking not.

**Comment by dlmarion** [comment]
#3613 just fixes the existing method in the elasticity branch to use the compactor instead of the tserver. Do we want to cause users of this to break intentionally so that they have to evaluate their code and use a different API method?

**Comment by keith-turner** [comment]
> Do we want to cause users of this to break intentionally so that they have to evaluate their code and use a different API method?

One reason to break it is that code like the following would keep compiling, but would no longer do anything.  Not all usages of  getActiveCompactions(String) have to be tightly coupled to InstanceOperations.getTabletServers() but its likely some are.

```java
void someUserMethod(AccumuloClient client, Consumer<ActiveCompaction> acc){
   var io = client.instanceOperations();
   for(String tserver : io.getTabletServers()){
      if(match(tserver)) {
         acc.accept(io.getActiveCompactions(tserver));
      }
   }
```

**Comment by keith-turner** [comment]
If we had used more specific types in the API than string  in the past then this would be easier to handle. For example if the API had looked like.

```java
interface InstanceOperations {
     Collection<TabletServerAddress> getTabletServers();
     Collection<ActiveCompactions> getActiveCompactions(TabletServerAddress tsa).
}
```

**Comment by keith-turner** [comment]
The premise of this issue is wrong, see #3797 and #3827

**Comment by keith-turner** [comment]
> @keith-turner - what are you saying, that we should close this issue and close the associated PR?

The initial premise of this issue was that `InstanceOperations.getActiveComactions(String tserver)` would no longer return anything because tablet server no longer did major compactions.  However I did not realize that the method also returned minor compactions running on a tserver until attempting to run a test that checked for that.  So I was commenting on the reason for opening the issue being wrong.

Even though the initial premise was wrong I think exploring this area did reveal the following problems.

  * No way to list compactors
  * InstanceOperations.getActiveComactions(String tserver) does not currently accept a compactor address (and if it did there is no way for users to get them).  It could be modified to accept a compactor address.

The PR addressed some of these more general problems in addition to addressing the specific problem.  I think there is still value in what the PR was doing.  Also, I can't remember if it was this PR or discussion elsewhere but I seem to remember discussion about being able to retrieve resource groups associated with servers.

May need a new issue that describes these problems.

**Comment by dlmarion** [comment]
> Even though the initial premise was wrong I think exploring this area did reveal the following problems.
> * No way to list compactors
> * InstanceOperations.getActiveComactions(String tserver) does not currently accept a compactor address (and if it did there is no way for users to get them). It could be modified to accept a compactor address.

Created #4845 to address these issues.

**Comment by dlmarion** [comment]
#4845 has been merged. I think that addresses the issues in this PR (deprecation and the original issue are OBE due to later comments).
