### ISSUE TITLE
Look into what to do with rate limiting for compactions

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3597]
While working on #3592 noticed that tserver compaction services supported rate limiting.  Need to determine what if anything should be carried forward.  Depending on the decision, need to make changes to code and properties.

**Comment by dlmarion** [comment]
If rate-limiting was added as a way of reducing the load on the TabletServer, then I think we could remove it. Now that all major compactions are running externally, they are going to be rate limited by other factors already (CPU load on the host where the Compactor is running and the read and write rate from/to the underlying filesystem).
