### ISSUE TITLE
Handle manual metadata updates of selected files value in metadata

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3602]
Need to address the issue in the following comment

https://github.com/apache/accumulo/pull/3575#discussion_r1258203537

One way to do this is to add an iterator to the condition that compares selected files.   This iterator would take the value in the metadata table and decode and re-encode to and emit that as the value.  A test could be added to AmpleConditionalWriterIT to simulate a metadata value with out or order files.  The following code is where this iterator would need to be added to the condition.

https://github.com/apache/accumulo/blob/cfd7c8044a1c927a243914d04223ff14aa65c60f/server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java#L185-L192

**Comment by DomGarguilo** [comment]
Closing as completed via #3642
