### ISSUE TITLE
Properly handle tablet metadata refresh

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3625]
Tablets have a [RPC method for handling refresh](https://github.com/apache/accumulo/blob/037dba45cb606496fb19a10448ea08ddb7717a54/server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java#L1410-L1451) that is currently hack and has race conditions.  Need to remove the race conditions w/ all other tablet code.

**Comment by ctubbsii** [comment]
This looks closed by #3634
