### ISSUE TITLE
Improve nav bar in monitor by rolling up server statuses with distinct icons

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3688]
Currently, the servers menu shows status indicator dots when the different server types are in "normal", "warning", or "error" situations. The status rolls up into the main nav bar, showing the worst of the ones in the list. However, this is inconvenient because while it may be somewhat usual to see a yellow "warning" indicator because a few tservers are offline, it is less common for the manager to show a yellow indicator, such as when it is running in safe mode. To see the status of the server types, you have to click on the menu in order to unroll it and see which servers are causing the yellow indicator.

The proposed solution on #3548 and #3561 was to use a different icon for the different server types, or the different warning situations, instead of just using a simple dot in all situations. That way, the rolled up indicator, which will show the specific icon that got rolled up, will more quickly communicate abnormal operating conditions to a user, without having to first unroll the menu.

**Comment by ivakegg** [comment]
I like the icon being added in #3719, however I emphasize that I would like some text in the navbar to denote what the current state of the system is when not normal.  Manager green, tservers yellow, and gc gree is a normal state for us as there are almost always tservers that are down for maintainance etc.  However when the manager is down, or GC is not running I would love a banner on the navbar.  When the system is being shutdown I would love a banner on the navbar.  The whole point is that people are used to watching the monitor and it should always be readily apparent in those conditions.

**Comment by ctubbsii** [comment]
> I like the icon being added in #3719, however I emphasize that I would like some text in the navbar to denote what the current state of the system is when not normal. Manager green, tservers yellow, and gc gree is a normal state for us as there are almost always tservers that are down for maintainance etc. However when the manager is down, or GC is not running I would love a banner on the navbar. When the system is being shutdown I would love a banner on the navbar. The whole point is that people are used to watching the monitor and it should always be readily apparent in those conditions.

There's no room for text in the nav bar. The icon solution was an attempt to achieve the same visual distinction, but without cluttering the nav bar. I don't know how we can accommodate the request to add text there, without mangling the layout. The icon solution was the best idea I could think of.

If we want to add text instead, we could add a section in the main page layout for system messages, and those system messages could come from anywhere, even when not on the manager page. If that solution is reasonable to you, then I think we should abandon the distinct icons idea, since that was merely an attempt to achieve a compromise for the text you had wanted. Shutting down, or safe mode are reasonable system messages. Are there any others?

**Comment by ctubbsii** [comment]
We could also just have a single alert icon (like an exclamation point in a triangle) in the nav bar, and that could be clickable and open a modal window with the detailed system message.
