### ISSUE TITLE
Delete referenced candidates in AccumuloGC

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#3693]
**Is your feature request related to a problem? Please describe.**
Currently the AccumuloGC only removes AccumuloGC deletion candidates from the metadata table on a successful file deletion in HDFS. 

However, this can cause the AccumuloGC to continuously check the metadata table for file references that previously exist. 
For example, if a candidate exists for a year, the AccumuloGC will continually include that deletion candidate in each of its runs. 
This can negatively impact the AccumuloGC as the GC breaks up the deletion candidates into batches to process. By including false deletion candidates this increases the number of passes the GC has to make per cycle. 

**Feature Request**
Add a process step to check deletion candidates for file references and remove the deletion candidates if a file reference is found. 

To avoid race conditions with new deletion candidates being added, the timestamp field should be utilized so only a specific deletion candidate is removed.

**Comment by ddanielr** [comment]
The data object that's stored in zookeeper had to change. 
https://github.com/apache/accumulo/blob/f02d2ac5000d7d3ed664ba51e7e9d586fbba4a65/server/base/src/main/java/org/apache/accumulo/server/metadata/RootGcCandidates.java#L43-L59

**Comment by ctubbsii** [comment]
This was mostly done in #3738, but I think we should consider removing the experimental property prior to release and closing this. I'll mark this as a blocker to force us to review this prior to release. If we do end up keeping the property, I think it's probably worth changing the default to so the feature is enabled by default.

**Comment by ddanielr** [comment]
Linking #3805 to handle the scan ref case for inuse candidate deletions.

**Comment by ddanielr** [comment]
The majority of this work has been completed and merged.
#3918 has been created to enable the in-use deletion behavior in the 3.1 to ensure that GC behavior is consistent for users upgrading between the 2.1.x versions.

**Comment by ddanielr** [comment]
#4113 contains the last change for this GC feature based on user feedback so I'm linking this issue to be closed by that PR.

@ctubbsii, I would still prefer to keep the experimental property set to disabled in 2.1.3 due to the limited amount of user feedback on the feature.

There have been a decent amount of changes in 2.1.3, so if this feature is really desired in 2.1.x I would like to push the enabling of this property to 2.1.4 if possible. 

If we enable this property in 2.1.4, then I think removing the property in either a 2.2.x or 3.1.x release is perfectly fine.

Currently, the property is enabled by default in the `main` branch.
