### ISSUE TITLE
Add metadata table validation to AccumuloGC

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#3696]
**Is your feature request related to a problem? Please describe.**
When the AccumuloGC reads incomplete information from the metadata table, deletions can occur for files that are still being referenced.

**Describe the solution you'd like**
The AccumuloGC should validate the contents of a metadata table read to ensure that both a `srv:dir` and `~tab:~pr` entries exist in order to proceed with deletion actions.

**Comment by keith-turner** [comment]
This is the [code](https://github.com/apache/accumulo/blob/57903f4636197202489f057fdbd0e2bb8f99a2f1/server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java#L167) that currently ignores tablets w/ null dir entries.

**Comment by keith-turner** [comment]
The 1.10 code is different, it checks the dir [here](https://github.com/apache/accumulo/blob/3cc35be0379068e51a0ba3ac709b726f43ab392f/server/gc/src/main/java/org/apache/accumulo/gc/GarbageCollectionAlgorithm.java#L203).  It seems like the 1.10 code would also not complain if the dir column was absent.
