### ISSUE TITLE
ACCUMULO_JAVA_PREFIX in accumulo shell script not expanding correctly

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3697]
The `*` subscript in `ACCUMULO_JAVA_PREFIX` at https://github.com/apache/accumulo/blob/38c261d1236f118ffc2c6eebc505f5daf12bf0e2/assemble/bin/accumulo#L86 is expanding the array to a single word separated by `IFS`. In testing, I believe `@` should be used here instead.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.10

**To Reproduce**
I wrote a script to test this out. The following fails:
```
ACCUMULO_JAVA_PREFIX=(
        '/usr/bin/numactl'
        '--all'
)

CMD=("${ACCUMULO_JAVA_PREFIX[*]}" "/usr/bin/java")

echo "${CMD[@]}"
exec "${CMD[@]}" "--version"
```

Changing `*` to `@` on the line starting with `CMD=` allows the script to succeed.

**Comment by ctubbsii** [comment]
I will continue to look into this to see if there's something we should do to change this, so you can use an array. But there are trade-offs here that make no option perfect. If we use an array, you can't export it, and if you unintentionally set a scalar when we expect an array, we might not parse it correctly. If we expect a scalar and split it on IFS, then that could be a huge problem for quoting, requiring a bunch of convoluted quoting escapes, and assumptions about how the args are flattened when our script uses the environment variable. There's a good chance that the best option is to leave it as-is, and interpret it as a single scalar, requiring users to put multiple arguments into a script as suggested above.

**Comment by ctubbsii** [comment]
As it turns out, you can jump through hoops to effectively export an array variable, but it's not pretty:

```bash
BASH_ENV=<(echo "declare -a ACCUMULO_JAVA_PREFIX='(numactl --all)'") bin/accumulo
```

If you set the variable as an array in the environment, but then try to set it as a scalar in the script, then the scalar will only override the first item in the array. This can result in some confusing behavior. I added a sensible check with `declare -p` in my PR #3701 to fix this.
