### ISSUE TITLE
Remove single mutation thrift RPC

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3734]
**Describe the bug**
The changes in #3733 left a thrift RPC that is no longer used by client code.  The RPC was left in 2.1.x for compatibility purposes.  In 3.1.x the RPC can be removed.  The RPC is [here](https://github.com/apache/accumulo/blob/59897142d4ba39e563f1a9ad14ef512efb842abe/core/src/main/thrift/tabletingest.thrift#L70)

**Comment by ctubbsii** [comment]
@keith-turner seems to have merged this in e129b80ddf621cb52485e0fa455a3de9c82d326b ; so, I'll unassign myself and close this as fixed.

**Comment by ctubbsii** [comment]
> I wanted to merge main into the elasticity branch and wanted to include this change with that merge. I had forgotten about this issue.

No worries!
