### ISSUE TITLE
Avoid serving tablets with an operation id in the scan server

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3741]
Tablets that are splitting ( and in the future merging or deleting) will have an operation id set.  When this is set it means a destructive operations is active on the tablet.  If a scan server reads a tablets metadata and the operation id is set, then it should probably not serve queries from the files in that tablet.  This is because those files may be in flux and not represent all of the tablets data while the operation is in progress which may modify the tablet and its files over multiple mutations.  Its ok for scan servers to respond with old data, but they should not knowingly respond with data that may be incomplete.

**Comment by dlmarion** [comment]
I assume this means that scans in the ScanServer that were started *before* the destructive operation started are safe to continue?

**Comment by keith-turner** [comment]
> I assume this means that scans in the ScanServer that were started before the destructive operation started are safe to continue?

The scan got a snapshot of the tablets when it was in a good state and reserved those files, so it seems like it should be ok.
