### ISSUE TITLE
Review conditional writers handling of writes after close

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3742]
In #3733 issues with writes after close that caused metadata inconsistencies were addressed in the batch writer.  In the elasticity branch the conditional writer is now used for metadata updates where it was not before.  The conditional writer may already have handling for writes after close.  Would be good to review this handling and review what test there are for this in the conditional writer.

**Comment by dlmarion** [comment]
When ConditionalWriterImpl.close is called it calls shutdownNow on the `threadPool` ThreadPool. This ThreadPool is used to send mutations to tablet servers. ConditionalWriterImpl.write checks that `threadPool` is still alive every time the method is invoked.
