### ISSUE TITLE
GCRun logger name improperly created

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#3744]
**Describe the bug**
The GCRun class creates a logger based off the class and the current datalevel. 
https://github.com/apache/accumulo/blob/b1b2557f949e9212a1b1ca9b65f2d66c01a69edb/server/gc/src/main/java/org/apache/accumulo/gc/GCRun.java#L100

As a result, the logger name is not properly formatted.

given a datalevel = "ROOT"
expected logger name = `ROOTorg.apache.accumulo.gc.GCRun` 
actual logger name = `ROOTclass org.apache.accumulo.gc.GCRun` 

This was not noticed in the log output as the layout pattern uses a [precision specifier](https://logging.apache.org/log4j/2.x/manual/layouts.html#patterns) of `[%c{2}]` to only show the last two items in the logger name. 
https://github.com/apache/accumulo/blob/b1b2557f949e9212a1b1ca9b65f2d66c01a69edb/test/src/main/resources/log4j2-test.properties#L28

**Current Workaround**
The current logger can be targeted in a log4j2.properties file with proper character escaping. 
```
logger.gc.name = ROOTclass\ org.apache.accumulo.gc.GCRun
logger.gc.level = debug
logger.gc.additivity = false
```

**Expected behavior**
At minimum, the `class` string and spacing should be removed from the logger name. 
That can be accomplished by calling `getName()` on the `GCRun.class` 
```
LoggerFactory.getLogger(level.name() + GCRun.class.getName()); 
```

**Additional Improvements**
Given the precision specifier that's used, I'm wondering if the datalevel should be switched to a suffix.
This would allow it to be displayed in the log format `[gc.GCRunROOT]` as opposed to being hidden `[gc.GCRun]`.

**Comment by ddanielr** [comment]
> I think changing it to `LoggerFactory.getLogger(GCRun.class.getName() + "." + level.name());` would be fine.

That is the current solution being added in #3745

**Comment by EdColeman** [comment]
Closed with https://github.com/apache/accumulo/pull/3745
