### ISSUE TITLE
Broken tests: BalanceInPresenceOfOfflineTableIT,MetadataMaxFilesIT,SplitIT

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3757]
**Test name(s)**
 - org.apache.accumulo.test.functional.BalanceInPresenceOfOfflineTableIT.test
 - org.apache.accumulo.test.functional.MetadataMaxFilesIT.test
 - org.apache.accumulo.test.functional.SplitIT.tabletShouldSplit
 - org.apache.accumulo.test.functional.SplitIT.interleaveSplit

**Describe the failure observed**
All of these tests seemed to hang and time out.

**Testing Environment:**
 - Version of this project: 2.1.3-SNAPSHOT and 3.1.0-SNAPSHOT
 - First commit known to fail (or current commit): de0cf9f739978a04099d43cb0b9f729d0b4a1bab, but maybe also 98fc87d427b4fd42b389aa5af92f5467d5733767 (last good commit was 11824cf7a56b0d3772863f8225c8ce057d541d0b)
 - OS: Fedora 38 (6.4.15-200.fc38.x86_64)
 - Java: 11.0.20, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.20.0.8-1.fc38.x86_64
 - Maven: 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
 - Other environment details: This was run in Jenkins 2.423

**What have you tried already?**
I tried running a local build with `-Dtimeout.factor=2` to see if the tests just needed extra time to finish. They still hung.

**Additional context**

The tests previously passed as of commit 11824cf7a56b0d3772863f8225c8ce057d541d0b. They started failing as of the build that included the commits from #3750, #3747, and #3748, which were all merged in quick succession. The same tests failed in both the 2.1 branch and the main branch, so the fix should be applicable to both branches as well.

**Comment by ctubbsii** [comment]
Assigning this to @keith-turner , since all the PRs that broke this were authored by him, and he's the most likely person to know how to fix this quickly. But, anybody is free to take this on, if they can identify the solution and fix it.

**Comment by keith-turner** [comment]
With the changes in #3760 I am seeing all the integration test mentioned in this issue pass.
