### ISSUE TITLE
No-chop merge file metadata upgrade code

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#3768]
The changes in #3761 change the format of the file metadata stored from being just a path to a json object with a path and a range. We need to make sure we can handle the legacy format by upgrading existing entries when Accumulo is upgraded. The other option is to be backwards compatible and handle both but it would be cleaner if we could just upgrade existing entries to the new format. There's also a few other things that need upgrading as well. Below is a list that will get updated as new things are discovered.

Upgrade Tasks:

- [ ] Update format of metadata in root and metadata tablets for `DataFileColumnFamily` from a path to the new json format that contains a path and a range serialized as Base 64. The code for handling the new format of the file metadata is part of the `StoredTabletFile` class. When converting the existing file metadata (which is just a path) we should convert that to the new format which will just contain a Range that is infinite.
- [ ] Remove old [ChoppedColumnFamily](https://github.com/cshannon/accumulo/blob/ff916e6759fbfd88d09b2ff0b3681d082c1e342e/core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java#L328-L332) markers in metadata if any exist. I'm planning to move this constant over to the Upgrade section as part of https://github.com/apache/accumulo/issues/3769 .
- [ ] As noted [here](https://github.com/apache/accumulo/pull/3761#discussion_r1334818629), we also need to delete any external compaction entries which is the `ExternalCompactionColumnFamily`

**Comment by cshannon** [comment]
Something else is we also need to clean up the old [ChoppedColumnFamily](https://github.com/cshannon/accumulo/blob/ff916e6759fbfd88d09b2ff0b3681d082c1e342e/core/src/main/java/org/apache/accumulo/core/metadata/schema/MetadataSchema.java#L328-L332) markers in metadata if any exist. I'm planning to move this constant over to the Upgrade section as part of #3769 .

**Comment by EdColeman** [comment]
Looking at this, I am assuming at this point we would want to support a direct upgrade from 2.1.x to 3.1 without needing to first upgrade to a 3.0 version as an intermediate step.

3.0 introduced data level 11, but the changes appear to be mostly deletions to support deprecation remove.  A 2.1 -> 3.1 upgrade should be able to support those same changes.

**Comment by keith-turner** [comment]
> Looking at this, I am assuming at this point we would want to support a direct upgrade from 2.1.x to 3.1 without needing to first upgrade to a 3.0 version as an intermediate step.

We could do this.  The code can support running a list of Upgraders.  So could run the 10->11 upgrader followed by the 11->12 upgrader.

**Comment by EdColeman** [comment]
`The code can support running a list of Upgraders` 

That was my intention - mainly I wanted to point out the need for a 2-hop and get agreement that we would not require an intermediate 3.0 - more of a policy / philosophy statement than a technical limitation.

**Comment by keith-turner** [comment]
> That was my intention - mainly I wanted to point out the need for a 2-hop and get agreement that we would not require an intermediate 3.0 - more of a policy / philosophy statement than a technical limitation.

For that, one consideration is that more upgrade paths means more testing.  If 3.1 supports 3.0->3.1 and 2.1->3.1, then both paths would need to be well tested.

**Comment by ctubbsii** [comment]
> > That was my intention - mainly I wanted to point out the need for a 2-hop and get agreement that we would not require an intermediate 3.0 - more of a policy / philosophy statement than a technical limitation.
> 
> For that, one consideration is that more upgrade paths means more testing. If 3.1 supports 3.0->3.1 and 2.1->3.1, then both paths would need to be well tested.

The [LTM versioning strategy](https://accumulo.apache.org/contributor/versioning#LTM) documents the intent that LTM releases can be upgraded from either the immediately preceding release, or the immediately preceding LTM release series. (That's not counting patch releases, which are drop-in substitutions, not actually "upgrades" in the same sense. Upgrades should always be using the latest patch for a given release line.) It's implied, but not explicitly stated, that non-LTM releases will support these same two paths, because: 1) they are incremental releases towards the next LTM release, and 2) any non-LTM release under development could be declared LTM at the time of its release. So we should expect the same upgrade paths would exist in a non-LTM release as for an LTM release, and we should expect to test both paths.

**Comment by EdColeman** [comment]
Thanks for the clarification - I was unaware of the LTM -> LTM provision, but that's what I intended on doing and just wanted to make sure that was known.
