### ISSUE TITLE
Use TLSv1.3 by default

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#3786]
By default, when Accumulo is configured to use SSL/TLS, it uses TLSv1.2. However, TLSv1.3 is available, and should be the default.

I'm not sure exactly what, if anything, needs to change to support TLSv1.3, but it might just be a matter of changing the defaults in Property.java.

**Comment by cshannon** [comment]
For changing this we should also make sure the monitor supports TLSv1.3. There are 2 things here that I would recommend doing the first would be to set the default for the client to be TLSv1.3 but it's probably a good idea to still accept TLSv1.2 as well for now.
