### ISSUE TITLE
Broken or Flaky test: AmpleConditionalWriterIT

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3831]
**Test name(s)**
 - AmpleConditionalWriterIT.testFiles()
 - AmpleConditionalWriterIT.testSelectedFiles()
 - AmpleConditionalWriterIT.testSelectedFilesReordering()

**Describe the failure observed**
All of the tests in AmpleConditionalWriterIT (and maybe more, I haven't looked yet) that create a `StoredTabletFile` are failing. I think this is due to the change to the `StoredTabletFile` constructor in 1ab0cc7808fb68568b5312235bdea15ea396b04a. Last known working commit is 83d2dc24e87641171b2aef3fa3e4e35dc94cf279.

The constructor while the test was working was:
https://github.com/apache/accumulo/blob/83d2dc24e87641171b2aef3fa3e4e35dc94cf279/core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java#L47-L51
and is currently this:
https://github.com/apache/accumulo/blob/31323e5e5ecd870aff94fa6aa3579730031a651b/core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java#L62-L64

It looks like the new constructor expects the given string to be a json that it can deserialize and the old code expects the string to be a file path.

**Testing Environment:**
 - Version of this project: elasticity

**Comment by EdColeman** [comment]
I am currently working on issue #3768 and when that is finished I may be able to tackle this - the upgrade code has similar issues with the encoding change so changes / code should end up being similar.

**Comment by cshannon** [comment]
I can fix this real quick as I had to fix a lot of the tests in main.
