### ISSUE TITLE
Create set of working integration test in elasticity.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3834]
Instead of the changes made in #3816, it may be better to create a set of integration test that are known to work in the elasticity branch. If its easy to run this set of tests, then we can detect changes that break test that were working like #3831.  This could also make it easier to find and fix test that are not working, if there is an easy way to list test not in the set.

If this change is made, then the changes in #3816 can be reverted and #3825 could be closed.

**Comment by keith-turner** [comment]
Discussed this issue with @cshannon and @DomGarguilo  and we were not sure if would be best to take an exclusive or inclusive approach when creating the set of working test.  Should we list the test that work or exclude the test that do not work?

**Comment by keith-turner** [comment]
Once all the test in elasticity are working we can remove whatever was added to create this set.  So the set would be be a temporary build addition.  If we create an initial PR to bootstrap this, then we can also create an issue about removing whatever was added.

**Comment by dlmarion** [comment]
I wonder if the following should be done instead:

1. Merge #3832 into `main` and up into `elasticity`
2. Revert #3816
3. Add `@Ignore` to IT classes that are known to be failing.

This would:

1. Enable people to run the Sunny profile if they want
2. Allow us to re-enable the IT build for the elasticity branch (not just the Sunny profile)
3. Enable us to find and fix broken ITs. When working, we just remove the `@Ignore` annotation.

**Comment by cshannon** [comment]
Adding the `@Ignore` tag I think would work too. It seems like the exclusive approach to mark tests as broken/ignored would be better than listing tests that work so I am in favor of whatever makes the most sense to make it easy to exclude broken tests and then quickly bring them back once they are fixed.

**Comment by keith-turner** [comment]
@dlmarion that approach sounds good.  Could add a 4th step of opening an issue to ensure all the @ignore tags are removed in elasticity.

**Comment by dlmarion** [comment]
I modified the Jenkins elasticity build to remove the sunny profile so that we can determine which ITs are failing. When that is done I will add the `@Ignore` annotation on the failing tests and create the issue to remove them.

**Comment by dlmarion** [comment]
> @dlmarion that approach sounds good. Could add a 4th step of opening an issue to ensure all the `@Ignore` tags are removed in elasticity.

I'm not sure that an issue to remove all of the Ignore annotations is necessary. I added "//ELASTICITY_TODO" to all of the Ignore annotations that I added in #3884. I am 100% positive that we are going to be  looking for all of the TODOs and resolving them, and looking at the failing tests in Jenkins.

**Comment by dlmarion** [comment]
Kicked off another Full IT build after merging #3884 to see if I got all of the tests.
