### ISSUE TITLE
Add support for checking WALs did not change in conditional updates

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3847]
When making conditional updates to a tablet will need to be able to ensure that wals are the same.  This can be done by adding a case to [this code](https://github.com/apache/accumulo/blob/c3358c0d8398319f29ff2cbd7b643e324f26e1b7/server/base/src/main/java/org/apache/accumulo/server/metadata/ConditionalTabletMutatorImpl.java#L168).  Hopefully the case stmt can use the same iterator that used to check if files are the same.

This is a prerequisite to #3844

**Comment by DomGarguilo** [comment]
I have been looking into this and have a few point/questions.

> When making conditional updates to a tablet will need to be able to ensure that wals are the same.

When comparing two `LogEntry` objects to one another, objects constructed with the same initial values will not be equal (using `.equals()`). Looking at the [`LogEntryTest`](https://github.com/apache/accumulo/blob/85b7d3be9f7c8942fe2ecd2c4a97e335cb150c8b/core/src/test/java/org/apache/accumulo/core/tabletserver/log/LogEntryTest.java#L34) this seems to be expected. Given this info, what should be checked within the condition? Should we check each member variable between two `LogEntry` objects for equality?

**Comment by keith-turner** [comment]
> Given this info, what should be checked within the condition? Given this info, what should be checked within the condition?

@DomGarguilo I have been looking into this, the LogEntry class is in need of some cleanup and I am going to open an issue about that.  It seems the column qualifer for a walog is a prefix of `-/` followed by a fully qualified URI of a walog.  For this issue we want to ensure the set of column qualifiers for the `log` column family are the same.  This is similar to what we do for the `file` column family.  

The LogEntry class does not override equals so can not compare them.  Taking a quick look though the code I did not see LogEntry used as a key in a Set or Map, but could have missed something.  Seems to always be used in List where equals does not matter.

**Comment by keith-turner** [comment]
@DomGarguilo  I opened #3878.  LogEntry has so much technical debt that it makes doing anything with it really confusing.  What it is doing is really simple, but the tech debt makes it hard to know what that is.  I spent a while looking around just to see what actually is in the column qualifier.  I even modified some code to print it and ran the Wal sunny test and looked at the print out.
