### ISSUE TITLE
Allow import table to set hosting goal.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#3857]
As a follow on the #3851.  The export / import was modified to preserve the hosting goal of the export source.  It may be desirable to allow the import to explicitly set a hosting goal independent and overriding the source.  

One use case would be to export an active / online table to a system with fewer resources and then the destination desired host goal would possibly be on-demand or offline.  If the import only supported the original state, there could be a need for more resources for the import until the table hosting goal could be changed to something less intensive.

**Comment by DomGarguilo** [comment]
There has been some discussion about alternatives to this approach. One of which is to make a new version of the export table file that is human readable. This would allow for changes to be made before the file is used for import. If this is possible, we could change the hosting goal in that file instead of creating the changes outlined in this ticket, allowing an imported table to have a different hosting goal than the exported table.

**Comment by EdColeman** [comment]
One way that may not require changes to the exported data if the use could provide parameters at import time that would supplement or override parameters that are set when exported.

**Comment by ctubbsii** [comment]
> One way that may not require changes to the exported data if the use could provide parameters at import time that would supplement or override parameters that are set when exported.

The impression I got was that was the original proposal. The human-readable(editable) export file format is one that avoids adding any of that complexity into the import code/feature set. If import parameters are added instead, I think it would add more complexity baked in to Accumulo that users can already do with external text editing tools, so I'd prefer the change in the file format. But, if we do end up going the route of adding the ability to add import parameter overrides, it should be done in the most generic way possible (for example, adding a single option with an override map of parameter names and values is simpler and more extensible than adding separate options to override each import parameter separately).
