### ISSUE TITLE
Clean up LogEntry class

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3878]
The LogEntry class has some technical debt  that would be good to cleanup.  The following improvements could be made.

 * There is a field named filename that actually seems to store a fully qualified path.  Could rename this field  Could also add validation to this field to ensure its of the expected format.  The filename in path current has a tserver host plush uuid, could validate this.
 * There is a field named extent that is only used by unit test, could probably remove this.
 * There is no equals or hashCode method, these could be added.
 * There is upgrade code in the class that deals with some old format of the data.   Can not see any test for this.   Could remove this if adding validation that would fail on seeing this. Could possibly look for this in upgrade and covert,if we can figure out what the old format was.  However the old format may be really old and seeing it may be unexpected or not realistically possible.
 * The value in the metadata table seems to store the exact same data as the column qualifier.  This code could be cleaned up to not store redundant info, may require change in upgrade.

**Comment by DomGarguilo** [comment]
I'll start looking into this

**Comment by DomGarguilo** [comment]
Fixed via #3886

**Comment by DomGarguilo** [comment]
Oops I just realized this ticket was marked for 3.1.0 however the PR, 3886 was merged into elasticity.
