### ISSUE TITLE
Handle tablets that have a hosting goal of never and WALs

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3880]
If tablets have a hosting goal of never and also have write ahead logs, it could cause problems as outlined in the following comment.

https://github.com/apache/accumulo/issues/3844#issuecomment-1775767859

**Comment by dlmarion** [comment]
Is this somewhat of a duplicate of #3663  ?

**Comment by keith-turner** [comment]
Closed this because it was a duplicate of #3663
