### ISSUE TITLE
Investigate removing `getValue()` from LogEntry class

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#3943]
The LogEntry class has method `getValue` which is used to put a value for mutations. This data is redundant as the column qualifier stores the same thing (the filePath). Explore removing this method and using just the column qualifier where this data is needed.

**Comment by rsingh433** [comment]
I will look at this.

**Comment by ctubbsii** [comment]
The column qualifier used to not be redundant. The value used to be **very** different, and the column qualifier used to contain `server + / + filename`, and server and filename used to be able to be separated by doing:

```java
    String[] parts = key.getColumnQualifier().toString().split("/", 2);
    result.server = parts[0];
    result.filename = parts[1];
```

That implies that the `server` portion did not contain any slashes itself. So, now that the server is just replaced with `-` in the column qualifier, I think we can safely continue to parse the filename from it by ignoring everything up to, and including, the first slash. That should work, even if there happens to be an older entry that still had a server in there for some reason. Then, we can just start using an empty value for new entries, and parsing from the column qualifier instead.
