### ISSUE TITLE
Set default value of table.majc.compaction.strategy property to empty string

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#3966]
**Describe the bug**

In 2.1 the default value of the property `table.majc.compaction.strategy` is set to the DefaultCompactionStrategy class. However if the user does not set this property, then its default value is ignored.  If its possible to do w/o breaking anything, the default value should be empty string to better reflect this behavior.

This property was deprecated in 2.x and dropped in 3.0.  so the change only needs to be made in 2.x.

**Comment by EdColeman** [comment]
When a user does not set the property, what happens?

**Comment by keith-turner** [comment]
> When a user does not set the property, what happens?

It will use the plugin to make compaction decisions.

**Comment by keith-turner** [comment]
>>   When a user does not set the property, what happens?
>
> It will use the plugin to make compaction decisions.

I just noticed I misread your question, I missed the `not` in the original question so the answer above is wrong.  When a user does not set this property it will use the newer plugins like its does currently.  Prior to this change Accumulo has the odd behavior of ignoring the default value for this property in the case where the user does not set the property.  So making the default empty string makes it more apparent that the default value is ignored.
