### ISSUE TITLE
Mark property TSERV_LAST_LOCATION_MODE as deprecated

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3971]
#3926 removed this property. Need to mark it deprecated in a 3.x release.

**Comment by ctubbsii** [comment]
Can you refresh my memory, is there a replacement behavior for this, or is it just no longer useful in elasticity?

**Comment by dlmarion** [comment]
MAJC occur outside of TServer in elasticity, so the mode is no longer needed. When a tablet is hosted (optional behavior in elasticity), then the last location is set. Balancers can choose whether to use the last location or not.

**Comment by ctubbsii** [comment]
> MAJC occur outside of TServer in elasticity, so the mode is no longer needed. When a tablet is hosted (optional behavior in elasticity), then the last location is set. Balancers can choose whether to use the last location or not.

Ah, okay. So, it's just not needed, because only one of the options makes sense in elasticity, so there's no point in choosing. In addition deprecating the old one, should we change the default behavior to use the `assignment` mode, to match the behavior that would be seen in the elasticity branch?

**Comment by dlmarion** [comment]
> should we change the default behavior to use the `assignment` mode, to match the behavior that would be seen in the elasticity branch?

I don't know that we should change the behavior. If we did that, then I think we would need to add code to the 3.1 upgrade to warn users that don't have the property specified (default `compaction`) that there is a behavior change and if they see "issues" after upgrading then they may want to configure the property with the value 'compaction'. I think I'd rather leave it as is and just remove it.
