### ISSUE TITLE
Modify upgrader to error if 'tserver.last.location.mode' is set

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#3972]
#3926 removed this property. Modify the upgrader to fail if the property is set. We may want to consider just generically failing the upgrade if any property is set that no longer exists?

**Comment by ctubbsii** [comment]
Is it really worth failing? Maybe this should just be a warning that an unrecognized property exists, and that perhaps it was one that was removed?

**Comment by dlmarion** [comment]
> Is it really worth failing? Maybe this should just be a warning that an unrecognized property exists, and that perhaps it was one that was removed?

Do you think this should be a warning for all unknown properties?

**Comment by ctubbsii** [comment]
> > Is it really worth failing? Maybe this should just be a warning that an unrecognized property exists, and that perhaps it was one that was removed?
> 
> Do you think this should be a warning for all unknown properties?

I'm not sure. I thought we already had something like that.

**Comment by keith-turner** [comment]
Found the following in the code 
> I'm not sure. I thought we already had something like that. 

https://github.com/apache/accumulo/blob/df362efeee3113d3e3c23ff6f6778f394a588363/core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java#L204

https://github.com/apache/accumulo/blob/df362efeee3113d3e3c23ff6f6778f394a588363/server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java#L118

So maybe warns are logged when tables or site configs have props that do not validate.  Not related to this PR, but wondering if the system config in ZK should also be validated.

**Comment by keith-turner** [comment]
> Not related to this PR, but wondering if the system config in ZK should also be validated.

opened #3978 to address this
