### ISSUE TITLE
Incorrect comment in LogEntry

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4012]
I think the comment at https://github.com/apache/accumulo/blob/main/core/src/main/java/org/apache/accumulo/core/tabletserver/log/LogEntry.java#L45, added as part of #3939,  is incorrect. I believe the path for the log file needs to be fully qualified. See comments in #4004 .

**Comment by ctubbsii** [comment]
OBE by recent changes. There is no comment at the linked line. The file is a fully qualified absolute path, if that helps.
