### ISSUE TITLE
SummaryIT.basicSummaryTest failing

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4021]
Test is failing [this](https://github.com/apache/accumulo/blob/elasticity/test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java#L156) assertion.  Looking at the code, I think the code is assuming that the table has no files at this point. Modifying the test like below shows that the table does have a file after the call to `writeData`:
```
+      assertEquals(0, FileMetadataUtil.countFiles(getCluster().getServerContext(), table));
       BatchWriter bw = writeData(table, c);
+      assertEquals(0, FileMetadataUtil.countFiles(getCluster().getServerContext(), table));
```

I think this indicates that a minor compaction is happening now, where it was not happening in an earlier version of the code.

**Comment by dlmarion** [comment]
Tested my hypothesis by applying the changes above to SummaryIT in main, and it passes.

**Comment by keith-turner** [comment]
@dlmarion I experimented with the test in main and a minor compaction also happens in there, it just seems to happen consistently later.  In main I made the following change and that will cause the test to fail there also.

```diff
diff --git a/test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java b/test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
index ca9fa216c0..921e8fe09f 100644
--- a/test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
+++ b/test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
@@ -149,6 +149,8 @@ public class SummaryIT extends SharedMiniClusterBase {
 
       BatchWriter bw = writeData(table, c);
 
+      Thread.sleep(1000);
+
       Collection<Summary> summaries = c.tableOperations().summaries(table).flush(false).retrieve();
       assertEquals(0, summaries.size());

```

So it seems the minc is happening in both places, its just consistently happening sooner in elasticity.

I also looked at config and both branches end up with a config of 40M for the in memory map which seem to come from mini accumulo.  Also seeing very similar log messages from LargestFirstMemoryManager in both branches.  Not sure why elasticity is consistently donig the minc a bit sooner.
