### ISSUE TITLE
Remove MemoryStarvedMajCIT?

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4037]
This test is current disabled in elasticity because it's using the MemoryConsumingIterator to consume memory in the TabletServer to pause the major compactions. Since MAJC no longer happens in the TabletServer, this mechanism of consuming memory won't work in the Compactor. I'm not sure of a way to make this happen in the Compactor, but since the Compactor is single threaded, we may not need this feature at all for MAJC.

**Comment by ctubbsii** [comment]
Do you know what the pause was intended to do? Was it intended to prevent the tserver from falling over due to OOM?

**Comment by ctubbsii** [comment]
If the IT is removed, it should be removed because the corresponding low-memory pausing feature is also removed (or if it was never implemented there).
