### ISSUE TITLE
Update configuration javadoc to indicate if a composite view is being returned or not.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4038]
**Describe the bug**
On the interfaces InstanceOperations, NamespaceOperations, and TableOperations there are multiple methods for obtaining configuration/properties.  Some of these methods return a composite view and some do not.  The javadoc for each method should clearly indicate whether its returning a composite view or not.

A composite view means it combines multiple layers of configuration.  For example obtaining a composite view of the table properties would return table+namespace+system+site+default properties.

**Expected behavior**
The javadoc clearly explains what is returned.

**Comment by kevinrr888** [comment]
I'll work on this issue

**Comment by kevinrr888** [comment]
I believe this issue can be closed
