### ISSUE TITLE
VolumeUtil.switchVolumes() may be unneeded

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#4058]
The VolumeUtil class has a switchVolumes method that handles mapping LogEntry objects from the metadata table into new LogEntry objects with a replaced volume (see [volume replacements property](https://accumulo.apache.org/docs/2.x/configuration/server-properties3#instance_volumes_replacements)). However, it doesn't look like we actually store a path from a volume in these log entries anymore. So, there shouldn't be anything to replace. This code seems unnecessary now. (From what I can tell, we only store a server and a UUID in the log entry, not any full path with a volume.)

**Comment by dlmarion** [comment]
FYI that I recently merged #4007 into the 2.1 branch. You are saying it is unnecessary in 3.1?

**Comment by ctubbsii** [comment]
> FYI that I recently merged #4007 into the 2.1 branch. You are saying it is unnecessary in 3.1?

Possibly. It's not clear to me that we're actually storing the full absolute path to the WALs there. The code that parses it seems to expect `tserver/UUID` as the documented format, not `tserver/hdfs://path/to/UUID`. However, I haven't dug enough to find where it maps the UUID to the location on one of the actual volumes, so I can't be sure. I also haven't been able to verify the entry on a live system, to see an example. However, I could be misunderstanding the parsing. It may be trying to store things in `hdfs://path/to/<tserver>/<uuid>`, and it's just dropping off everything except `<tserver>/<uuid>`, so the switch volumes may still be needed. If so, we may need to revert some of #3997

**Comment by ctubbsii** [comment]
Based on #4065, it appears this is still needed. #3997 was implemented incorrectly. Will work on reverting/fixing this. I led @rsingh433 astray by misunderstanding the implementation and communicating the wrong design, based on incomplete internal comments about the implementation.
