### ISSUE TITLE
Validate lock type in distributed lock recovery code

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4066]
**Describe the bug**

For FATE table and namespace locks, [Utils.getLock()](https://github.com/apache/accumulo/blob/5b46bd8f97e95234992c6ceb6347cbe5ba72b6d3/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/Utils.java#L169) is called which calls [DistributedReadWriteLock.recoverLock](https://github.com/apache/accumulo/blob/5b46bd8f97e95234992c6ceb6347cbe5ba72b6d3/core/src/main/java/org/apache/accumulo/core/fate/zookeeper/DistributedReadWriteLock.java#L247).  In Utils.getLock() it knows if wants a read or write lock, however when it calls DistributedReadWriteLock.recoverLock() it may return a different lock type.  Validation should be added that the recovered lock is of the expected type and throw an exception if it is not.

**Expected behavior**
When the recovered lock does not match the desired type an exception is thrown with information about the lock types and lock ids.

**Comment by rsingh433** [comment]
I will look at this.
