### ISSUE TITLE
Update MetaDataTableScanner to use Ample.

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#4073]
Reviewing other PRs, the code in MetaDataTableScanner stuck out as not using Ample.  It seems like the code could be upgraded to use Ample unless there is a specific reason not to.  

If the code cannot use Ample, then at least add some documentation in the class saying why.

**Comment by ctubbsii** [comment]
I definitely saw some custom code in here that wasn't using the more up-to-date logic that other classes were using to interact with the metadata table. It looks like this class is removed in the elasticity branch, though, so it may not be worth touching if it's going away. I'm curious what happened to it in the elasticity branch that made it possible to remove, though. Maybe that's possible in the main branch as well.

**Comment by keith-turner** [comment]
@EdColeman  MetaDataTableScanner has an associated complex iterator that does server side filtering.  That is why it does not use Ample.  It is tightly coupled with the TabletGroupWatcher class in the manager, however prior to elasticity other classes used it.  In the elasticity branch the server side iterator was changed significantly and all other usages of the iterator outside of TabletGroupWatcher were removed.
