### ISSUE TITLE
Remove uses of deprecated ClientConfiguration

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#408]
`ClientConfiguration` was deprecated in favor of `Connector.builder()`.  There are about 353 usages of ClientConfiguration.  As many usages should be removed if possible.

**Comment by ctubbsii** [comment]
This replaces https://issues.apache.org/jira/browse/ACCUMULO-4819

**Comment by mikewalch** [comment]
This work was completed with several pull requests that mentioned this issue.
