### ISSUE TITLE
Determine whether RecoveryPath should be removed

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#4087]
A class named RecoveryPath, containing a single static method exists, apparently for the sole purpose of parsing multiple outdated versions of log paths to affect WAL recovery. We probably don't need this, as we may not even support those outdated versions of logs anymore. Somebody could investigate this and determine what can be done to simplify or remove this class.

**Comment by ArbaazKhan1** [comment]
I can take a look at this.
