### ISSUE TITLE
Log a warning when no system compactions are planned but a tablets files exceeds the max for scans.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4089]
**Is your feature request related to a problem? Please describe.**

Its possible to configure a compaction planner such that it schedules zero compactions jobs even in the case where the tablet currently has more files than is allowed for scans.  If this is happening it could indicate a misconfiguration of the compaction planner that may lead to problems.

**Describe the solution you'd like**
If this is happening, a periodic warning should be logged indicate that a compaction service has observed tablets that have more files than allowed for scan for which no compaction jobs are being generated.

This message should not be logged too frequently and it should not happen for the case of tablets that have compactions running as a planner may not issue new jobs when compaction jobs are currently running.

**Describe alternatives you've considered**

It would also be useful to emit metrics for this case in addition to logging, will open another issue for that.

**Comment by keith-turner** [comment]
Discussed this with @ctubbsii and we think the following is a good way forward.

 1. Drop the property in 3.x
 2. Update the documentation in 2.x to explain that the property is only used by deprecated code. Could also deprecate the property in 2.x.  The property should have been deprecated for 2.1.0 since its only used by deprecated code, it was just missed. Document that the property was very inefficient and that compaction ratio is the best way to handle the number of files on a per table basis and mention it was used by merging minor compactions.
 3. Modify the DefaultCompactionStrategy to log a warning when it performs a sub optimal compaction based on table.files.max
 4. Make the new compaction planning code log a warning when no compactions are scheduled for a tablet that has more than tserver.scan.files.open.max files.

**Comment by keith-turner** [comment]
Opened #4098 for updating the table.file.max docs in 2.1

**Comment by keith-turner** [comment]
Opened #4099 to address logging when compactions are not being planned and a tablet has more files than is allowed for scan.

**Comment by kevinrr888** [comment]
I believe this issue can be closed from https://github.com/apache/accumulo/pull/4143

**Comment by keith-turner** [comment]
Looking at the comment on this issue, #4127 was work done as a result of the discussion on this issue.
