### ISSUE TITLE
Test that WAL header length constants should be moved from DfsLogger to a unit test

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#4100]
DfsLogger [has an assertion in code](https://github.com/apache/accumulo/blob/f9897862dd4e6ff4892239ff5ebeb8ed6e34bc68/server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java#L333-L339) that the version 3 and version 4 WAL header constants are the same length. This should be moved to a unit test rather than left as a runtime assertion.

**Comment by EdColeman** [comment]
I'm working the empty wal utility and its in the same area, I'll to this, it may help with the utility testing.
