### ISSUE TITLE
TabletManagementParameters uses convoluted serialization

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#4107]
For #4103 , I replaced `List<Pair<Path,Path>>` with the much friendlier and more intuitive `Map<Path,Path>`.

However, when merging this into the elasticity branch, the TabletManagementIteratorIT failed. Looking at the server logs, I saw that it was failing on Gson serialization of TabletManagementParameters. In order to get it to pass, I had to preserve the `List<Pair<Path,Path>>` in the JsonData inner class, and convert it back and forth from the `Map<Path,Path>`. This is not ideal.

The TabletManagementParameters serialization should be fixed so it can use the simpler, `Map<Path,Path>` directly. I'm not sure what this involves yet, because I'm not sure why it's working with the list of pairs and not working with a map. Other maps, even of user classes, seem to deserialize just fine. And Path itself serializes fine either way. If anything, there should be fewer classes to serialize, because the removal of the Pair, so I don't understand it just yet.

See:

https://github.com/apache/accumulo/blob/48d39719148454f002ab346610ad39b911662acc/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java#L128-L129

and

https://github.com/apache/accumulo/blob/48d39719148454f002ab346610ad39b911662acc/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementParameters.java#L248-L249

**Comment by keith-turner** [comment]
Using `List<Pair<>>` allows duplicate keys.  However looking at the code its given a Map, so there would not be duplicate keys in the source data that is used to create the ` List<Pair<>>`.  Seems like converting it to a map would be fine.

**Comment by ctubbsii** [comment]
@keith-turner All of the replacements code used to be a List of pairs, which did allow duplicates, but duplicates don't make sense here. You can't have a volume replaced by two separate volumes. That would be chaos. So, I changed it all to a map in #4103 , but I had to keep this a list of pairs, because GSon threw an error in the test when deserializing the map. This code doesn't exist in the main branch, so it's new in elasticity. I'm not sure what is causing the GSon error during deserialization, and I'm not sure why serialization is needed in the elasticity branch when it's not needed in the main branch. We can't make this less convoluted until the deserialization error is fixed.

**Comment by dlmarion** [comment]
Closed by #4184
