### ISSUE TITLE
Update FATE AccumuloStore to use conditional mutations

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4114]
This is a follow on to #4049 where an `AccumuloStore` for storing FATE was added. We should switch to using conditional mutations for the different operations to make sure things are consistent and what we expect on an update. For example, when creating a new transaction we should verify that it doesn't already exist or that when we push a new repo onto the stack the repo existing count of repos is what we expect etc.

**Comment by cshannon** [comment]
This could be broken down into multiple PRs potentially as well if it is simpler to convert one operation at a time to be conditional.

**Comment by DomGarguilo** [comment]
Would be cool to have a running list of checks we could add for each operation that way its easier to break things up into multiple PRs and track what has been done and what is still left to do. I'll keep a checklist here for us to add to. I think anyone (that has access) can edit this comment so feel free to add and update this comment.

- [ ] when creating a new transaction we should verify that it doesn't already exist. could do this with TabletExistsIterator potentially.
- [ ] when we push a new repo onto the stack the repo existing count of repos is what we expect. Could add checks to ensure the spot we are pushing to is empty and the previous spot has an entry.
