### ISSUE TITLE
Investigate making tableOperations.online() more strict with table state checks

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#4132]
There was some discussion (below) about investigating if there should be more strict checks in regards to table state when using `tableOperations().online()`. Not sure the extent of the current checks, but it at least allows a table to be onlined when it is in a `NEW` table state which is questionable.

> Does the following sound correct?  Want to make sure I understand these changes.
> 
>  * Without these changes the table would be in the new state, so `client.tableOperations().isOnline(destTable)` would have returned false.  
>  * The call to `client.tableOperations().online(destTable, true)` just kinda fix things for the rest of the test.
> 
> If that is true, it makes me wonder if the call `client.tableOperations().online(destTable, true)` should be a bit more strict about what table states it will transition.

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/4115#discussion_r1441173711_

**Comment by kevinrr888** [comment]
I would like to work on this

**Comment by kevinrr888** [comment]
I believe this issue can be closed now
