### ISSUE TITLE
When a bulkImport fails to update the MetadataTable, which bulk import failed is hard to determine

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#415]
While trying to track back issues that were seen with ConstraintViolationExeptions thrown in MetadataTableUtil#update, I noticed that tracking back exactly which bulk import threw the exception was not simple. It would be great if the error message could include more information so that we could more easily track back to which import failed

**Comment by jmark99** [comment]
This issue appears to be addressed with a change in #2086 (Add optional extent to metadata update failure logs). Any objections to it being closed?

**Comment by jmark99** [comment]
Closing as no objections were raised and it is addressed with #2086.
