### ISSUE TITLE
Update upgrade code to handle the addition of the new FATE table

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4167]
#4049 added a new FATE table to the Accumulo namespace. This table is created and initialized for new Accumulo instances but we will need to make sure to handle the table being created for an upgrade as well as the init code won't handle that case.

**Comment by EdColeman** [comment]
One restriction is that upgrades will not continue if there are any FATEs present - this includes FATEs that are in progress, but also FATEs that have failed or completed but not cleaned up.

The upgrade code, if it sees any FATEs halts, and prints out instructions that they need to be removed.  This can be done by reverting and allowing any in-progress to complete - of if you really don't care, delete them from ZooKeeper manually.

As long as that check is in place, the only thing the upgrade code needs to do is create and initialize the new table, there is no expectation that any conversion of FATEs needs to occur between versions.

Likewise, for future upgrades, the new table will need to be examined / clear before an upgrade should continue.
