### ISSUE TITLE
Update Fate admin command to support the addition of the Accumulo instance type

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4168]
With the addition of support for multiple Fate instances and an AccumuloStore in #4133 and #4049 the fate [command](https://github.com/apache/accumulo/blob/da7866ee3606fd43202f536fd50a6e2d890a1dee/server/base/src/main/java/org/apache/accumulo/server/util/Admin.java#L212) in the Admin utility needs to be updated.

The changes in #4133 only partially updated things to fix the problems with unit tests but more work is needed. 

More investigation needs to be done for all the changes but a few things are:

1. We need to make the command compatible with the Accumulo instance as well and not just Zookeeper for operations such as cancelling a fate operation. This will mean updating the command to provide an instance type.
2. We should provide an option to filter transactions based on instance type.
3. Updating the formatting of the summary output to show the instance type

We may want to wait to update the command until the changes are finished in #3964 as that might require more changes

**Comment by kevinrr888** [comment]
I would like to work on this

**Comment by kevinrr888** [comment]
This issue can be closed. Completed by https://github.com/apache/accumulo/pull/4350
