### ISSUE TITLE
Move tracking of unsplittable tablets from manager memory to metadata table

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4177]
When a tablet is larger than the split threshold but a split point can not be found (this could happen if the tablet has a very large row with many columns) Accumulo tracks this.  It is tracked to avoid repeatedly wasting resources on trying to find a split point for a tablet that can not split.  In the elasticity branch, tracking of which tablets can not split is done in manager memory [here](https://github.com/apache/accumulo/blob/f6c096bef1c7809b698a9ed9b39d1f625c1e0ee3/server/manager/src/main/java/org/apache/accumulo/manager/split/Splitter.java#L53),

This tracking could be moved to the metadata table by adding a new column to tablet metadata for tablets that are unsplittable.  Tracking this information in the metadata table would reduce memory pressure on the manager and would make running splits in distributed fate possible. Its also nice because the information will survive manager restarts and not possibly cause a flurry of unneeded computation when the manager restarts.

This tracking could be moved to the metadata table by adding a new column to tablet metadata for tablets that are unsplittable.    This column could record the following information.

 * The relevant configuration at the time the tablet was determined to be unsplittable.  For example, the tables split threshold config at the the time could be recorded.  May not need to record the actual config key/values, could possibly record a hash of them.
 * Information about the tablets files at the time the tablet was determined to be unsplittable.  This does not need to be the full set of file URLs.  Could be just the filenames or a hash of the file URIs.  The current code that tracks things in memory tracks a hash of the file URIs to detect a change in the set of files.

The tablet management iterator is used to find tablet that need to split.  This iterator could be modified to use this new column when determining if tablet needs to split.  If the column exists it could check if the table config or tablet files has changed since the column was set.

**Comment by cshannon** [comment]
I have started looking into this issue and working on a PR. #4178 added a spot to store the new column and informationafter the refactor [here](https://github.com/apache/accumulo/blob/d7348ae5219e40f7e960eb585b14960a1a242bcd/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/split/FindSplits.java#L78) inside of the FindSplits repo

**Comment by cshannon** [comment]
I have a prototype working for this issue but it still needs some polishing and some more testing, but I should be able to submit a PR soon. I'm also waiting to submit a PR because I based the branch for this PR off of #4254 to avoid merge conflicts since both PRs modify the Metadata schema and add new columns so once that PR is merged I can rebase off elasticity and then create a PR for this
