### ISSUE TITLE
Add createIfNotExists method to table/namespace operations

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#418]
Currently, if you want to create a namespace or table in Accumulo that may already exists, you need to try to create it and ignore the exception.

```java 
  try {
      connector.namespaceOperations().create("mynamespace");
    } catch (NamespaceExistsException e) {
      // ignore
    }

    try {
      connector.tableOperations().create("mynamespace.mytable");
    } catch (TableExistsException e) {
      // ignore
    }
```

It would be nice if a `createIfNotExists` method was added to the API that ignored this exception. This would simplify the above code to the following:

```java
connector.namespaceOperations().createIfNotExists("mynamespace");
connector.tableOperations().createIfNotExists("mynamespace.mytable");
```

**Comment by keith-turner** [comment]
Could add a method to NewTableConfiguration instead of adding a method to tableOperations

**Comment by jkosh44** [comment]
Anyone working on this and is it still needed? I'd like to take a shot at this.

**Comment by jkosh44** [comment]
If so I have a couple questions/comments.

1. Could it get confusing or inconsistent if we put one createIfNotExists in NamespaceOperationsImpl and one in NewTableConfiguration instead of putting them both in XOperationsImpl (X being Namespace or Table).
2. I think it may be helpful for the method to return a boolean to indicate whether or not a new table/namespace was created or if it already existed.

Any thoughts?

**Comment by ctubbsii** [comment]
@jkosh44 Although it might generally be better to prefer new config over new methods, I think you've raised two good points that indicate it's better to create the new methods in `<Table|Namespace>Operations` instead of using `NewTableConfiguration` here.

**Comment by hkeebler** [comment]
This looks like it was done but maybe a pull request was never submitted?  @jkosh44 are you still working on this?

**Comment by milleruntime** [comment]
> This looks like it was done but maybe a pull request was never submitted? @jkosh44 are you still working on this?

There was a PR that I recently closed.

**Comment by keith-turner** [comment]
@hkeebler I think a good way to handle this issue would be to add javadoc to the create table method suggesting the following as a concurrent safe way to ignore tables that exists.

```java
try {
      connector.tableOperations().create("mynamespace.mytable");
    } catch (TableExistsException e) {
      // ignore
    }
```

**Comment by hkeebler** [comment]
Thanks @keith-turner , will do that.
