### ISSUE TITLE
Organize Fate Operations 

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#421]
The RepOs of every fate operation are ALL in the org.apache.accumulo.master.tableOps package.  It is annoying to track down which RepO goes with which operation.  Creating a package in o.a.a.master.tableOps for each operation would organize them nicely.  This would have to be done in 2.0 since it will break serialization.

**Comment by cjmctague** [comment]
@milleruntime Am I right by saying you want these sorted by the operations like 
`CREATE, DELETE, RENAME, SET_PROPERTY, REMOVE_PROPERTY, ETC.`

Or do you want them grouped like `CloneInfo, CloneMetadata, ClonePermissions, CloneTable, CloneZookeeper, FinishCloneTable` all put into a subpackage say `clone` and so on for the rest of them for their respective operation.

**Comment by milleruntime** [comment]
Check out [bulkver1](https://github.com/apache/accumulo/tree/master/server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1) and [bulkver2](https://github.com/apache/accumulo/tree/master/server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2)

It would be like those packages but one for each operation in [FateOperation](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/master/thrift/FateOperation.java)

**Comment by milleruntime** [comment]
So TABLE_BULK_IMPORT and TABLE_BULK_IMPORT2 are already done, that is what [bulkver1](https://github.com/apache/accumulo/tree/master/server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer1) and [bulkver2](https://github.com/apache/accumulo/tree/master/server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2) cover.

**Comment by milleruntime** [comment]
It would probably be easiest to start with one FateOperation and open a pull request first to make sure we are on the same page.  Then you could do a second PR for the rest.
