### ISSUE TITLE
Improve verification in TabletManagementIteratorIT

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4231]
This is an existing problem with this test.  The test could do more than just verify a count, it could verify the ManagementActions and extents returned are what is expected.  I can open an issue about this.

_Originally posted by @keith-turner in https://github.com/apache/accumulo/pull/4229#discussion_r1478954146_

**Comment by ArbaazKhan1** [comment]
I think this is being addressed in [issue4344](https://github.com/apache/accumulo/issues/4344)

**Comment by dlmarion** [comment]
Thanks @ArbaazKhan1 , this does look like a dupe of #4344. Closing this as the other issue has more detail.
