### ISSUE TITLE
Remove TSERV_WORKQ_THREADS before 3.1 release?

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4249]
When I merged #4238 from 2.1 to main in 171fdcd7f539da7b4ee0c011b5d546d3af6bde96, I left the Property TSERV_WORKQ_THREADS and modified the description to note that the property is unused. I left it because I was not sure if a user upgrading from 2.1 or 3.0 to 3.1 would have an issue if the property was in there configuration. Need to evaluate and remove the property for the 3.1 release if removing it won't cause any upgrade issues.

**Comment by rsingh433** [comment]
I will look at this issue.

**Comment by ctubbsii** [comment]
Done in #4747
