### ISSUE TITLE
Rename FATE AccumuloStore to something else more descriptive

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4253]
#4049 introduce a new FATE store type to store fate transactions in an Accumulo table. Right now it is called AccumuloStore but we should rename it to be more descriptive and less confusing as to what it is. Ideally it would be good to leave "Accumulo" out of the name since the entire project is called Accumulo. One possible option could be `TableFateStore` and then rename ZooStore to `ZookeperFateStore` (or `ZooFateStore`).

I also noticed that [FateStoreIT](https://github.com/apache/accumulo/blob/3f3da5a5da9cf500777d4c4b0d5a1c6556557dd8/test/src/main/java/org/apache/accumulo/test/fate/accumulo/FateStoreIT.java) is in the wrong package as it should be one level up since it is abstract and applies to Zookeeper as well so that can moved as part of this.

**Comment by dlmarion** [comment]
Is the Zoo store is for system initiated FATE transactions, and the Table store is for user initiated FATE transactions, or is it the case that the Zoo store is for FATE transactions on the System tables, and the Table store is for FATE transactions on user tables?

**Comment by cshannon** [comment]
It's the latter: The Zoo store is only going to be used to store FATE transactions for system tables (root, metadata, etc). Everything else (for now at least, more below) goes into the Table store for other tables so that performance is better now that Accumulo will generate a lot more FATE operations for all the system initiated transactions. 

There was discussion with @keith-turner about splitting up the Table store into 2 stores (or 2 sections of the table) to separate out user vs system initiated operations but for now we decided to just put everything into one Table store and see how it goes. So we could end up with a 3rd store at some point if we need it (system tables in Zoo store, Table store for Users ops and Table store for system ops for all other tables)

**Comment by dlmarion** [comment]
So, maybe instead of `ZooStore` and `AccumuloStore`, name them `SystemTableFateStore` and `UserTableFateStore`.

**Comment by cshannon** [comment]
> So, maybe instead of `ZooStore` and `AccumuloStore`, name them `SystemTableFateStore` and `UserTableFateStore`.

Sounds fine to me unless anyone else has any suggestions. I think the plan is to wait until all the outstanding FATE stuff to be merged and then we can do the rename to not break any open PRs

**Comment by cshannon** [comment]
I talked to @keith-turner and I am going to go with `MetaFateStore` and `UserFateStore` since it aligns with the `FateInstanceType` enum.
