### ISSUE TITLE
Re-evaluate need to always return tablet in tablet mgmt iterator

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4256]
The TabletManagementIterator will always return tablet when certain conditions are met in [this code](https://github.com/apache/accumulo/blob/9d80b65f0eec60ad6d137cc8400798380cc55fe7/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java#L204-L208).  The code changes in #4255, but still has similar behavior.

This behavior is a carry over from the original code in main.  However, the code in elasticity has dramatically changed since main.  Wondering if it is still needed and if it is,  is this the best location for this code.  Ideally TabletGroupWatcher and TabletManagementIterator use the same code to come to decisions about tablets, both using code like TabletGoalState.compute and TabletState.compute.  This code may be specific to TabletManagementIterator.

**Comment by keith-turner** [comment]
Some of the conditions handled in the code linked in the description are also handled in more detail in lower level parts of the code.  For those cases it may be better to always rely on the lower level conditions.

https://github.com/apache/accumulo/blob/0739f7ee6d4db2931d855abefea00e70a32ada86/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java#L176

https://github.com/apache/accumulo/blob/0739f7ee6d4db2931d855abefea00e70a32ada86/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletGoalState.java#L97-L99

**Comment by keith-turner** [comment]
Would be useful to try removing the specialized code and only calling ` computeTabletManagementActions(tm, actions);` AND running all ITs to see if anything breaks.  However need to get all of the ITs reliably working in elasticity before doing this experiment.

**Comment by dlmarion** [comment]
I removed the special logic in #4363 and kicked off a full IT build. I'm not sure that it's necessary any more.

**Comment by dlmarion** [comment]
Full IT build succeeded. Closing this by merging #4363
