### ISSUE TITLE
MeterRegistryFactory lacks mechanism for configuration.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4262]
The MeterRegistryFactory does not have any mechanism for passing configuration. Since its likely metrics will need configuration (like a server to send metrics to) this leads to placing the configuration for the MeterRegistryFactory class and any options needed by the class in different places.  For example the MeterRegistryFactory class would be configured in accumulo.properties files and if it needs the hostname of a server this might be set as java system prop in accumulo-env.sh.

This plugin could be modified to follow the pattern of many other SPI plugins for passing configuration to a plugin. Since a new type is being introduced in #4244, that presents a good opportunity to make this change.

**Comment by keith-turner** [comment]
Marked this for version 2.1.3 on the assumption that #4244 will be in 2.1.3.  If that turns out to not be the case then the version on this could change.

**Comment by EdColeman** [comment]
I am currently working this as part of #4244

**Comment by dlmarion** [comment]
@EdColeman  - was this implemented in #4459 as part of the new MeterRegistryFactory SPI class? If so, can this be closed?

**Comment by EdColeman** [comment]
Completed with #4459
