### ISSUE TITLE
Add test to FateIT that tests errors

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4266]
FateIT needs to test that errors are handled as expected and undo is called.  This could be done with a test like the following

 1.  Fate is seeded with Repo1
 2. Repo1 is called and returns Repo2
 3. Repo2 is called and return Repo3
 4. Repo3 is called and throws an exception (need to test throwing an exception in isReady() and call(), may need to run test twice with that minor diff)

After the above happens fate should call undo() on Repo3, then Repo2, then Repo1.  The test needs to verify that undo is called in the expected order.

It may be worthwhile to add this test to 2.1 and merge it forward.

**Comment by kevinrr888** [comment]
Created PR https://github.com/apache/accumulo/pull/4282
