### ISSUE TITLE
Remove FateTxId in Elasticity

### ISSUE THREAD

**Issue by kevinrr888** [apache/accumulo#4275]
**Is your feature request related to a problem? Please describe.**
The class FateTxId was used to format fate transaction ids in a consistent way. From [issue#4044](https://github.com/apache/accumulo/issues/4044) and the related PRs https://github.com/apache/accumulo/pull/4191, https://github.com/apache/accumulo/pull/4228, https://github.com/apache/accumulo/pull/4247, and https://github.com/apache/accumulo/pull/4258, this class is no longer used/has been replaced with FateId.

**Describe the solution you'd like**
After [issue#4274](https://github.com/apache/accumulo/issues/4274) is completed, FateTxId should be removed.

**Comment by kevinrr888** [comment]
This issue can be closed now

**Comment by DomGarguilo** [comment]
Closed via #4370
