### ISSUE TITLE
Replace boolean with enum for table locks

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4276]
Fate operations can obtain distributed read/write table locks by calling [this code](https://github.com/apache/accumulo/blob/da7b3b005e13276c202b4f337496f9ecf2c039e5/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java#L77). A boolean is used to specify the lock type.  Replacing the boolean with an enum would have the following advantages.

 1. Makes the code more readable
 2. Makes it easy to find all code using a write lock or find all code using a read lock.  Can not search on `true` or `false` in the code to find uses read/write locks.

**Comment by cshannon** [comment]
I will take a look at this issue, I don't think it would take too long to update and would be a nice change.
