### ISSUE TITLE
Shell performance issue with large number of tservers

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#4303]
**Describe the bug**
When monitoring zookeeper connections on a large cluster the shell makes 2 * ( number of tservers) + 1 connections to zookeeper on connect when trying to determine tablet server to connect to.

It looks like it is retrieving from ZK:

1. The node that contains all tservers ( in our case `/accumulo/<instance id>/tservers`)
2. The list of locks under `/accumulo/<instance id>/tservers/<server id>`
3. The lock at `/accumulo/<instance id>/tservers/<server id>/<lock id>`

It would make sense to cut this off once it has a valid tserver, until such time as talking to other tservers is necessary.

**Versions (OS, Maven, Java, and others, as appropriate):**
Affected Version -  2.1.2

**To Reproduce**
1. Enable ZK logging at DEBUG
2. Connect to shell, monitoring ClientCnxn messages from zk
3. Observe requests to ZK for each tserver

**Expected behavior**
Accumulo should only make as many connections as necessary to function. Making extra calls wastes time and resources.

**Additional context**
This problem would probably not have a noticable affect on small systems.

**Comment by dlmarion** [comment]
Looks like this is the code in question: https://github.com/apache/accumulo/blob/2.1/core/src/main/java/org/apache/accumulo/core/rpc/clients/TServerClient.java#L64-L77
