### ISSUE TITLE
Add support for runing multiple compactors per host to accumulo-cluster script

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4312]
**Is your feature request related to a problem? Please describe.**

External compactor processes handle a single compaction at a time.  Internal compaction thread pools running in a tablet servers can handle many compactions on single host.   To provide a number of external compaction threads on an accumulo cluster that scales with the number of cores on the cluster one would need to run multiple compactor processes per host.  The accumulo-cluster script currently only supports running a single compactor process per host.

**Describe the solution you'd like**
The accumulo-cluster script supports running multiple scan servers and tablet servers per host.  It would be useful to also support running multipe compactors per host also.  The yaml config for accumulo cluster supports [these settings](https://github.com/apache/accumulo/blob/aed3919e4649a3bcd82c35e5d0c65b8192a086d2/assemble/bin/accumulo-cluster#L507-L508).  It could additionally support the following setting to allow starting more than one compactor per host.

```yaml
compactors_per_host: 1
```

**Comment by dlmarion** [comment]
Closed by #4329
