### ISSUE TITLE
WAL Recovery directories not being removed

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#432]
While running test for 1.9.0, I noticed some files in /accumulo/recovery that were a few days old.  I investigated this and could not find any code in the garbage collector that actually deletes WALs in the recovery directory.  There is code in 1.7 to delete recovered WALs, so I suspect this problem was introduced in 1.8.0 with the change in how WALs are tracked.

I also found the property `master.recovery.max.age` has not been used by Accumulo internals since 1.4

**Comment by keith-turner** [comment]
@ctubbsii  ACCUMULO-4851 is a different issue.

**Comment by ctubbsii** [comment]
Okay. My mistake.
