### ISSUE TITLE
Refactor AccumuloStoreIT to create fate table with system config

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4321]
AccumuloStoreIT should use the fate table config from InitialConfiguration when it creates accumulo tables used for testing Fate.

**Comment by keith-turner** [comment]
Prior to #4320 fate as not behaving correctly because the versioning iterator was not present.  Test created tables in a different way so did not have this issue. Making the test fate tables use the same config as the real fate table may have uncovered this earlier.

**Comment by keith-turner** [comment]
Also need to update AccumuloStoreFateIT.

**Comment by cshannon** [comment]
> Also need to update AccumuloStoreFateIT.

I opened up #4322 to add a test to make sure the real system table is correctly configured with the iterator going forward. I can work on that issue and also I will take this issue and update AccumuloStoreIT and AccumuloStoreFateIT
