### ISSUE TITLE
Periodically clean up compacted and loaded markers in tablets

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4324]
Transient per tablet markers are written to the metadata table by compaction and bulk load fate operations.  At the conclusion of these fate operations these markers are cleaned up.  The cleanup only happens within the range of the fate operation.  Concurrent split operations could copy these markers outside of the range of the fate operation causing cleanup to miss them.  There are at least two possible ways to fix this. One is to make the clean up operation scan the whole table, this is expensive for an edge case that will rarely happen.  The other option is to periodically remove markers that have no live fate operation.  The bulk code used to clean up the entire table but was modified to only consider the range that data was imported.

The periodic clean up could be done by the Accumuo GC process by running a loop like the following.

```java
        for(Ample.DataLevel level : Ample.DataLevel.values()){
            // TODO create a cache that loads live ids from the fate store
            LoadingCache<FateId, FateId> liveFateIds = ..;
            // TODO create a new filter that only returns tablets that have loaded or compacted markers
            for(TabletMetadata tm : ample.readTablets().forLevel(level).filter(new LoadedCompactedFilter())).build()){
    
                //important that live ids are only loaded for the first time after being seen in the metadata table 
                var loadedToDelete = tm.getLoaded().entrySet().stream().filter(e->liveFateIds.get(e.getKey())!=null).collect(Collectors.toList());
                var compactedToDelete = tm.getCompacted().stream().filter(fateId -> liveFateIds.get(fateId) != null).collect(Collectors.toList());
                
                if(!loadedToDelete.isEmpty() || !compactedToDelete.isEmpty()) {
                    // TODO update table to delete markers
                }
                
            }
        }
    }
```

For testing this could manually insert data into fate and the metadata table in test code and call the above code to see if it deletes or does not delete markers.

**Comment by keith-turner** [comment]
In 2.1 and 3.1 there is a metadata table compaction time iterator that does something similar for bulk load markers.  This iterator was removed in the elasticity branch because it was not needed.  However changes to how bulk import does clean up and the introduction of the compaction markers mean something like this probably still needed. IMO the compaction time iterator in 2.1 and 31. is not a very clean way to do this because it reads from ZK. In elasticity doing this w/ a compaction time iterator would not be possible because fate ids will need to be read from ZK or the new fate table.  Would not want a metadata compaction iterator attempting to read from the new fate table.

This new check should run periodically in the manager or GC. IMO the GC process seems like the best place.  Whichever process it runs in the code should be self contained and easily moved to another process.

Realized this was an issue while working on #4323

**Comment by ArbaazKhan1** [comment]
I can take a look at this

**Comment by keith-turner** [comment]
@ctubbsii suggested expanding the compaction range to match table split points to avoid having to do the periodic cleanup of compaction tablet metadata mentioned in this issue.  I think this will work and will be much simpler.  I think all that needs to be done is [at this point in the code](https://github.com/apache/accumulo/blob/1688cecd5a8889bcb41cec2bdb45d2f063d1d9a9/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactRange.java#L86) do the following.

 * if startRow is not null then find the tablet containing startRow and pass its prev row to the ComactionDriver constructor
 * if endRow is not null then find the tablet containing endRow and pass its end row to the CompactionDriver constructor.

Going to look at the bulk import code next.

**Comment by keith-turner** [comment]
I looked at the bulk import code and it is already using table split points for it cleanup of its temporary tablet metadata, so it should not need any additional cleanup.  Closing this issue in favor of #4341
