### ISSUE TITLE
Dead compaction detection only looks at user tables

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4340]
The dead compaction detection code is only [examining user tablet metadata](https://github.com/apache/accumulo/blob/1688cecd5a8889bcb41cec2bdb45d2f063d1d9a9/server/manager/src/main/java/org/apache/accumulo/manager/compaction/coordinator/DeadCompactionDetector.java#L82). It needs to also look at the root and metadata table metadata.

**Comment by keith-turner** [comment]
Noticed this while working on #4339.

**Comment by cshannon** [comment]
I will take a look at this
