### ISSUE TITLE
Compaction fate operation may not clean up all of its temporary metadata changes

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4341]
When a compaction on a table is initiated via the public API a range can be specified. All tablets that overlap the range are compacted.  This is driven by a fate operations that writes temporary tablet metdata.  At conclusion the fate operation cleans up this compaction metadata.  Concurrent splits could cause tablet metadata related to the compaction fate operation to be copied outside of the range specified in the API.  If this happens then the fate operation would not clean up the metadata.

This comment offers a solution to [this problem](https://github.com/apache/accumulo/issues/4324#issuecomment-1981441097)

**Comment by ArbaazKhan1** [comment]
I can take a look at this
