### ISSUE TITLE
Elasticity Broken or Flaky test: ZooStoreFateIT

### ISSUE THREAD

**Issue by kevinrr888** [apache/accumulo#4378]
**Test name(s)**
 ZooStoreFateIT

**Describe the failure observed**
Running the IT as a whole leads to some test failures. Running the tests individually works fine.

**Testing Environment:**
Elasticity branch

**What have you tried already?**
The issue is that some tests don't delete all the transactions from the store at the end of the test leading to subsequent tests seeing these transactions. The fix is to just add this cleanup to all tests.

**Comment by kevinrr888** [comment]
I will create a PR for this

**Comment by cshannon** [comment]
FYI, ZooStoreFateIT has been renamed in #4393
