### ISSUE TITLE
Remove tx_ prefix from Accumulo fate store rows.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4389]
With the changes in #4388 the rows in Accumulo fate store will look like `tx_<uuid>`.  The `tx_` prefix could be dropped.  If we ever need to store other data in the fate table, then it could follow the pattern of the accumulo metadata table where things other than table ids are prefixed which a byte that can not exists in a table id.

**Comment by kevinrr888** [comment]
I can work on this
