### ISSUE TITLE
Should a Deriver cache a null value? 

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4423]
**What is your question?**
Accumulo has the concept of a Deriver which is used to reload a class object that's defined by an accumulo property.
Due to some recent testing, it appears that the Deriver is adding references for null values.
https://github.com/apache/accumulo/blob/946485208f5eccd1801d9e4358f1acf0acefb4eb/core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java#L516

Should the Deriver cache references to null class objects?

**Comment by dlmarion** [comment]
Looking at the code, it appears that the places where this could occur are only in the TableConfiguration constructor when calling `createScanDispatcher` and `createCompactionDispatcher`. In both cases they are calling `Property.createTableInstanceFromPropertyName` and passing in `null` for the default instance. However, for both properties being referenced default property class names are documented, just not being used.
