### ISSUE TITLE
Add a version number to cluster.yaml 

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4426]
**Is your feature request related to a problem? Please describe.**
Add a version number to cluster.yaml so that different schemas can be validated.

This blocks #4424

**Comment by dlmarion** [comment]
I'm not sure what this accomplishes. If a user already has a cluster.yaml file generated and stored in their CM system that they lay down on the system, they will never see that a new version number is expected. There is some validation that happens in [ClusterConfigParser](https://github.com/apache/accumulo/blob/2.1/core/src/main/java/org/apache/accumulo/core/conf/cluster/ClusterConfigParser.java). We could make that more robust or we could start using yaml/json schema and performing validation as the first step in ClusterConfigParser.

**Comment by keith-turner** [comment]
> f a user already has a cluster.yaml file generated and stored in their CM system that they lay down on the system, they will never see that a new version number is expected.

One possible way to deal with this is that absence of a version number implies version 1 and its associated schema.  To use newer schema than version 1, must specify a version number.

**Comment by dlmarion** [comment]
> One possible way to deal with this is that absence of a version number implies version 1 and its associated schema. To use newer schema than version 1, must specify a version number.

Sure, but I was trying to say that just because there is a version number in the yaml, it doesn't necessarily make it valid. We could add a version number to the yaml and immediately fail in ClusterConfigParser if it doesn't match what is expected. I don't think we should support different schemas though. A version of Accumulo should support one version of cluster.yaml. If it's not correct, then the software should fail and the user should have to fix it.

**Comment by keith-turner** [comment]
> A version of Accumulo should support one version of cluster.yaml. If it's not correct, then the software should fail and the user should have to fix it.

That makes sense.  If a minor version of accumulo l(ike 2.1.X) only supports a single schema then a version number is not very useful.

**Comment by ddanielr** [comment]
Adding a version number to the cluster would imply that we have various schema support across major accumulo versions. 
Given the upgrade paths, I don't think that is a pattern of support we want to adopt.
