### ISSUE TITLE
Setting empty property value via the shell deletes the property

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4456]
**Describe the bug**
Setting a table property to an empty string deletes the property from ZK vs overriding the value to an empty string.

This was verified by using the accumulo admin dumpConfig  -a tool to pull down the table configs and verify that the property no longer existed as a per-table override 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x
 - OS: [e.g. CentOS 7.5] centos 7
 - Others:

**Expected behavior**
The property value is overridden to an empty string and is only deleted if the `-d` flag is used. 

**Additional context**
@ctubbsii  had some ideas on why this was happening

**Comment by ddanielr** [comment]
@sparkyy34 discovered this bug if there are any more questions.

**Comment by ctubbsii** [comment]
@jmark99 are you working on this?

**Comment by jmark99** [comment]
@ctubbsii yes. Started looking this week. Should have a PR early next week as I'm away the rest of this week.
