### ISSUE TITLE
Seeing execution hints in logs for system compaction

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4460]
**Describe the bug**
After running a user compaction with hints, the hints will show up in the logs for system compactions.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 7c6572caf336cd76bb794befe7a31dce3503cd4b

**To Reproduce**
A compaction like the following was run with execution hints set.

```
compact -t testtab -w --exec-hints compaction_type=test
```

The user compaction completed and more files were inserted causing a system compaction.  The logging for system compaction showed the hints from the previous user compaction.  Hints should only be associated with an active user compaction.

```
2024-04-12T20:54:46,255 [tablet.files] DEBUG: Compacting 2<< on i.default.small for SYSTEM from [F000000f.rf, F000000e.rf, F000000d.rf, A000000c.rf] size 864 bytes config [hints={compaction_type=test}]
```

**Expected behavior**
Should not see hints related to system compactions.

**Comment by kevinrr888** [comment]
I will look into this
