### ISSUE TITLE
Admin Fate list command should ignore "no node" exceptions

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4462]
**Describe the bug**
The admin list command first gets a list of all fate tx ids, then starts to query for specific information. 
When a large number of fate transactions are present, the fate command will error on "no node exceptions" because that fate transaction ID has since completed. 

This blocks the entire fate list from being printed

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x
 - OS: [e.g. CentOS 7.5] Centos 7
 - Others:

**Expected behavior**
The list command should not fail on fate transactions that are no longer present in ZK.

**Comment by ddanielr** [comment]
This section of the code could be moved under a try/catch loop for zk lookup failures.
https://github.com/apache/accumulo/blob/7c6572caf336cd76bb794befe7a31dce3503cd4b/core/src/main/java/org/apache/accumulo/core/fate/AdminUtil.java#L343-L376

**Comment by ddanielr** [comment]
See if the `-s` path in the code bypasses this error.

**Comment by kevinrr888** [comment]
I can work on this

**Comment by kevinrr888** [comment]
No, the -s path would not bypass the error as the filtering is done after the transaction info is obtained (or attempted to be obtained).

**Comment by dlmarion** [comment]
Closed by the merge of #4556
