### ISSUE TITLE
Create a SteadyTime type in the manager

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4482]
[Manager.getSteadyTime()](https://github.com/apache/accumulo/blob/cb25f26ab3be77dbfce54e9d1e7234e5974510ec/server/manager/src/main/java/org/apache/accumulo/manager/Manager.java#L1633) returns a long.  Replacing the long with a specialized SteadyTime type would make any use of the type in the code more apparent and correct. May also be nice to have methods for serializing and deserializing this type in a consistent way on the method as this type is intended to be serialized.

**Comment by keith-turner** [comment]
This issue supports the possible use of steady time more in the manager as outlined in #4481 and [this comment](https://github.com/apache/accumulo/issues/4454#issuecomment-2067765994)

**Comment by cshannon** [comment]
I'm starting work on this now
