### ISSUE TITLE
Scan server file references stored in the metadata table can cause hotspots and empty metadata tablets

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4493]
**Is your feature request related to a problem? Please describe.**

Scan server references stored in the metadata table use a fully qualified file path in the row.  This can lead to the same problems as described in #1043 that gc candidates stored in the metadata table used to have. The code that write scan server refs can be found [here](https://github.com/apache/accumulo/blob/6d0b4768522187d8c43b9bf0850034d80a684235/server/base/src/main/java/org/apache/accumulo/server/metadata/ServerAmpleImpl.java#L346-L358)

**Describe the solution you'd like**

The solution to #1043 was to store a hash of the file path in front of the file path in the metadata table.  Something similar could be done for these refs, or the uuid for the scan server that is currently stored in the qualifier could be moved in front of the file.

**Comment by ddanielr** [comment]
The work for 2.1 was completed for this issue. Moved this to 3.1 milestone.
