### ISSUE TITLE
Create an `accumulo status` command

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4495]
**Is your feature request related to a problem? Please describe.**
The Monitor has poor visibility of compactors and scan servers, it's hard to determine how many are running.

**Describe the solution you'd like**
A tool that can be invoked via the command line that prints out the process counts based on the information in ZooKeeper. The tool should have an option to print using json for parsing.

Example:
```
> accumulo status
-----------------------------------------
Manager: 1
Monitor: 1
Garbage Collector: 1
Coordinator: 1
Tablet Servers: 32
Scan Servers: 44
Compactors: 99
-----------------------------------------
```

For Compactors in 2.1, count could be aggregated by compaction queue. For elasticity, the tablet / scan / compactor counts could be grouped by resource group. There could be another option that lists the servers below the count. An example of this for elasticity would be:
```
> accumulo status --list-servers
-----------------------------------------
Manager: 1
  localhost:1234
Monitor: 1
  localhost:1235
GarbageCollector: 1
  localhost:1236
TabletServers: 3
  Default:1
    localhost:1237
  GroupA:2
    localhost:1238
  GroupB:2
    localhost:1239
ScanServers:4
  Default:2
    localhost:1240
    localhost:1241
  Metadata:2
    localhost:1242
    localhost:1243
Compactors: 4
  Default: 2
    localhost:1244
    localhost:1245
  LongRunning:2
    localhost:1246
    localhost:1247
-----------------------------------------
```

**Comment by EdColeman** [comment]
Can be closed with https://github.com/apache/accumulo/pull/4567
