### ISSUE TITLE
Out of date comment in TabletServerMetricsUtil

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#4501]
**Describe the bug**
TabletServerMetricsUtil javadoc mentions Hadoop metrics2 which we no longer use. This comment should be updated.
https://github.com/apache/accumulo/blob/e682a2f2296cf95a32d58250aeef612b61147936/server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java#L25-L29

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 2.1.2 and up

**Comment by DomGarguilo** [comment]
Did a quick search and found these mentions of hadoop metrics2 as well:
https://github.com/apache/accumulo/blob/6d0b4768522187d8c43b9bf0850034d80a684235/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L386-L387

https://github.com/apache/accumulo/blob/6d0b4768522187d8c43b9bf0850034d80a684235/core/src/main/java/org/apache/accumulo/core/conf/Property.java#L928-L929

These could probably all be fixed in one PR

**Comment by EdColeman** [comment]
MANAGER_FATE_METRICS_ENABLED and MANAGER_FATE_METRICS_ENABLED Look like they are unused and have been marked deprecated. If so, maybe they can be removed?

**Comment by EdColeman** [comment]
Fixed by #4503
