### ISSUE TITLE
Add scan server metrics to track reservation write times and collisions

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4509]
**Is your feature request related to a problem? Please describe.**

Reserving files is an extra step that scan servers take that can add time to scans.  In order to understand the cost of this metrics are useful.  The current metrics are not adequate to fully understand the problem.

**Describe the solution you'd like**
The changes in #4461 add metrics to track the total time reserving a tablets files takes.  In addition to these metrics it would be useful to also track the time it takes to write out reservations and count when collisions happen.  The changes in #4461 should indirectly track the time it takes to read metadata via the cache metrics it added, so there may not be a need to explicitly track read time.

**Comment by DomGarguilo** [comment]
I can take a look at this

**Comment by dlmarion** [comment]
@DomGarguilo - can this be closed now that #4577 is merged?

**Comment by DomGarguilo** [comment]
Closing as completed via #4577
