### ISSUE TITLE
Add Busy/Idle metric for compactors

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4569]
**Is your feature request related to a problem? Please describe.**
When performing a scale-in operation, only compactors that are not performing compactions should be candidates for removal. 
Currently, a combination of using `jstack` and looking for a MajC thread can help determine if a compactor is performing work. 

**Describe the solution you'd like**
The compactor should emit a metric value to determine if it's currently working or idle.
This metric can then be used to drive scaling decisions and/or rolling compactor updates.

**Comment by DomGarguilo** [comment]
I can take a look at this
