### ISSUE TITLE
Moving the coordinator resets compaction duration

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4570]
**Describe the bug**
When the coordinator is restarted, the duration reported on the external compactions page in the monitor changes and reports a new time that is never greater than the coordinators uptime. 

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0] 2.1.x
 - OS: [e.g. CentOS 7.5] centos

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Run a compaction that should take a time longer than your test (30min)
2. Wait until the monitor shows the compaction duration being greater than 5min.
3. Stop the coordinator and start it again (alternatively, start it on a completely different node).
4. Check the monitor, the duration time should now roughly match the time since the coordinator's start time 

**Expected behavior**
The coordinator should report back the compaction duration based on state and this value should be consistent throughout coordinator process restarts.

**Comment by DomGarguilo** [comment]
I can start looking into this
