### ISSUE TITLE
Estimation of rfile entries is not implemented for fenced files.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4611]
**Describe the bug**

When merging #4452 from 2.1 to main in 72110813107f14949bc082a109b4e35b06ea39ad estimating entries for a fenced rfile was not implemented.   Wanted to avoid making this change in a merge commit.  

**Expected behavior**

[Rfile.FencedReader.estimateOverlappingEntries](https://github.com/apache/accumulo/blob/72110813107f14949bc082a109b4e35b06ea39ad/core/src/main/java/org/apache/accumulo/core/file/rfile/RFile.java#L1811-L1813) uses its fence range on the passed in extent.

**Comment by cshannon** [comment]
I will fix this and will add some tests to the [RFileTest](https://github.com/apache/accumulo/blob/76459c17b1c5713219dffe751c0f9c47b0d5412b/core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java) and [FencedRFileTest](https://github.com/apache/accumulo/blob/76459c17b1c5713219dffe751c0f9c47b0d5412b/core/src/test/java/org/apache/accumulo/core/file/rfile/FencedRFileTest.java)
