### ISSUE TITLE
Service status command is not functional in elasticity after merge

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4612]
**Describe the bug**

In commit c54d544758ed964c29f7df69b2e7acb91e679b80 the changes from #4567 were merged into elasticity.  The changes did not compile because the compaction coordinator no longer exists as separate process in elasticity. Rather than attempt to fix this in a merge commit, changes were made to get the code compiling that likely left the command non functional.  Probably need to remove a lot of code and test to properly fix this.

The following are the two changes that made things compile, but left things in a broken state. 

https://github.com/apache/accumulo/blob/c54d544758ed964c29f7df69b2e7acb91e679b80/server/base/src/main/java/org/apache/accumulo/server/util/ServiceStatusCmd.java#L180-L182

https://github.com/apache/accumulo/blob/c54d544758ed964c29f7df69b2e7acb91e679b80/server/base/src/test/java/org/apache/accumulo/server/util/ServiceStatusCmdTest.java#L277-L278

**Expected behavior**
The service status command works in elasticity.

**Comment by EdColeman** [comment]
On it.

**Comment by EdColeman** [comment]
This requires 814ac68a67 to be merged first which should be most of the changes becuase of ServiceLock usage changes.  After that is merged, the removal of the coordinator should just be some deletes - the methods that collects the info `getCoordinatorStatus`, places where it is called and removal of the test case.
