### ISSUE TITLE
Investigate if both METRICS_COMPACTOR_BUSY and METRICS_SERVER_IDLE are needed in elasticity branch

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#4641]
As of 528711eb17d89e7d41b88658c22065f870b3c6ad, there are two metrics that are very similar:
1. `METRICS_SERVER_IDLE` which is a counter that is incremented when a server is idle
2. `METRICS_COMPACTOR_BUSY` which is a gauge whose value is 0 when the compactor is idle and 1 when the compactor is busy

This ticket exists to track the investigation of whether both of these metrics should continue to exist in the elasticity branch.

**Comment by dlmarion** [comment]
I think `METRICS_COMPACTOR_BUSY` could be removed in `elasticity`. The `METRICS_SERVER_IDLE` metric is used by the Compactor, Scan Server, and Compactor and the changes in #4078 include a time based property to avoid flapping of busy/idle states.

**Comment by dlmarion** [comment]
I talked with @keith-turner this afternoon and I think we talked about backporting #4078 to 2.1, modifying `METRICS_SERVER_IDLE` to be a gauge vs a counter, and removing `METRICS_COMPACTOR_BUSY`.

**Comment by dlmarion** [comment]
@DomGarguilo - can this be closed?

**Comment by DomGarguilo** [comment]
Closing as completed via #4716
