### ISSUE TITLE
Handle the addition of the new Scan Ref table during upgrade

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4652]
#4650 added a new [SCAN_REF](https://github.com/apache/accumulo/blob/f1a200aaaa32e8644cd574d8b5dc12df0bea41dd/core/src/main/java/org/apache/accumulo/core/metadata/AccumuloTable.java#L36) table to the Accumulo namespace in elasticity. This table is created and initialized for new Accumulo instances but we will need to make sure to handle the table being created for an upgrade as well as the init code won't handle that case. We also need to make sure old scan refs will be cleaned up from metadata now that this new table is used.

**Edit:** #4690 backports this to 3.1 so the upgrade code needs to go there now

**Comment by cshannon** [comment]
#4690 backports this to 3.1 so the upgrade code will need to be done there too

**Comment by keith-turner** [comment]
#4692 is related.  Both of these will need to create new tables in upgrade, ideally they can share code as much as possible when doing this.
