### ISSUE TITLE
Investigate idle compactor load on zookeeper

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4666]
When running some external compactor tests, it was noticed that zk resource usage seemed to increase in relation to the number of idle compactors. This did not seem to occur if the compactors were busy.

This should be investigated to ensure we aren't creating additional ZK load as part of the job polling operations. 

General Investigation Steps:
1. Start a running accumulo instance
1. Check ZK usage (watchers, etc) https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands
1. Create a external compaction service 
1. Trigger a user compaction for a compaction queue that would queue up work
1. Spin up external compactors and ensure they are busy (compactor's busy metric). 
1. Monitor ZK usage
1. Either cancel the external compactions or spin down existing compactors and create new ones with no work. 
1. Monitor ZK usage

**Comment by keith-turner** [comment]
Its possible that #4681 was a cause of this, but not sure.

**Comment by ctubbsii** [comment]
@ddanielr Does this still occur after #4681 ?

**Comment by ddanielr** [comment]
Unable to replicate this problem after #4681 was merged.
Closing issue
