### ISSUE TITLE
Remove AvailabilityForTablet from public API

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4706]
AvailabilityForTablet is a type in the public API that is currently only used by test code.   At one point other parts of the API referenced this, but no longer do.   The type should be removed from the public API.  The type could possibly be replaced with Pair or Map.Entry.

**Comment by ctubbsii** [comment]
I don't think Pair is public API either.

**Comment by meatballspaghetti** [comment]
I can look into this.

**Comment by keith-turner** [comment]
> I don't think Pair is public API either.

Correct, Pair is not public API.  Currently this class is only used by test code.  The class could be moved out of public API into a test package.  Or the class could be deleted and replaced with something more generic because it only has two fields.

**Comment by ctubbsii** [comment]
Thanks @keith-turner . I think I misunderstood the ticket to mean that the public API needed to use Pair or Map.Entry. I now understand you meant that the test code that's using it could do that instead of this class.

**Comment by keith-turner** [comment]
> I now understand you meant that the test code that's using it could do that instead of this class.

Yeah and I am uncertain about what is best for the test code because I only took a quick glance at it.  Not sure of the details of how the test code is using the class. So the suggestion to use Pair or Entry may not be a good one.

**Comment by keith-turner** [comment]
Completed by #4728
