### ISSUE TITLE
Conditional writer creation does not always use client properties.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4708]
**Describe the bug**

When creating a conditional writer with this [method](https://github.com/apache/accumulo/blob/fdd8ce31ab3ef7089c67bd730866304291414a90/core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java#L788) accumulo client properties will not be used to create the config object.  When creating a conditional writer with this [method](https://github.com/apache/accumulo/blob/fdd8ce31ab3ef7089c67bd730866304291414a90/core/src/main/java/org/apache/accumulo/core/clientImpl/ClientContext.java#L777) client properties are used by `config.merge(getConditionalWriterConfig())`.

**Expected behavior**
Both methods for creating a conditional writer use an client properties set.  

Could create an IT that does the following to test the fix for this.

 * Create AccumuloClient w/ all condition writer props set
 * Create conditional writers using the AccumuloClient.  Test both methods that create a conditional writer.
 * cast the ConditionalWriter to ConditionalWriterImpl and get its config object and verify it has the expected things set from Accumulo props.

**Comment by keith-turner** [comment]
Noticed this bug by running ComprehensiveIT and looking at ClientContext coverage data using #4704.

**Comment by keith-turner** [comment]
This fix could be done 2.1.3, but it does not need to hold up 2.1.3 which is why I placed it in 2.1.4

**Comment by kevinrr888** [comment]
I can work on this
