### ISSUE TITLE
Increase coverage of conditional mutation rejection handling code.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4710]
Ample has code related to [handling special cases](https://github.com/apache/accumulo/blob/6e73d0dc3e1fb7d80492d219546490c5afe08e29/core/src/main/java/org/apache/accumulo/core/metadata/schema/Ample.java#L604) related to conditional mutations that is usually not exercised under normal circumstances.   One way this code is exercised in test is by use of TestAmple like what [ComprehensiveFlakyAmplIT](https://github.com/apache/accumulo/blob/elasticity/test/src/main/java/org/apache/accumulo/test/ComprehensiveFlakyAmpleIT.java) does.   Need to increase the coverage of the Ample RejectionHandler lambdas by having more test code use FlakyAmpleManager and FlakyAmpleTserver.

Can use #4704 to determine what is covered and not covered.

**Comment by keith-turner** [comment]
Ran ComprehensiveFlakyAmpleIT w/ coverage and look at areas that were not covered.  Found the following high level areas so far

 * volume replacement
 * concurrent user compactions on same tablet -- USER_COMPACTION_REQUESTED
 * unload ondemand tablet in tablet server 
 * walog recovery

**Comment by keith-turner** [comment]
While researching this noticed the volume replace condition update is checking the files it added are present on failure.  Because of race conditions they may have been added but not be present.  It should probably check the files it removed are not there to see if the update went through.  I plan to make this change when adding test for volume replacement, this is comment is a reminder to do that.

https://github.com/apache/accumulo/blob/3ad9198a86ae9f8b2b24831f6593d33362f8088a/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L1051-L1053

**Comment by keith-turner** [comment]
I wanted to reuse some code in the CompactionIT with FlakyAmple. I was looking into taking a different strategy for this rather than extending classes.  Looked in to using junit Tags and TestInfo, was hoping I could annotate a test method with `@Tag(FLAKY_AMPLE)`, but I have not completely figured out how to do this in a way that is not disruptive.

**Comment by keith-turner** [comment]
Ran the following with code coverage.

```
mvn clean -PskipQA -DskipTests=false -DskipITs=false -Dit.test="*FlakyAmple*IT,ManagerRepoIT" -Dtest=nothing -DfailIfNoTests=false verify
```

and found the following.

 * Need to increase the coverage of unsplittable case by modifying ManagerRepoIT
 * Need to get coverage on CompactionCoordinator.compactionFailedForLevel
 * The following has no test at all CompactionDriver.cleanupTabletMetadata, will open an issue.

**Comment by cshannon** [comment]
I can work on creating a test for `CompactionCoordinator.compactionFailedForLevel` so that we can close out this issue as `CompactionDriver.cleanupTabletMetadata` will be opened as a separate issue. I'll probably try and do something with TestAmple first as that has the interceptor to support the unknown status but FlakyAmpleManager is also an option depending on what is easiest when I take a look.

**Comment by keith-turner** [comment]
> The following has no test at all CompactionDriver.cleanupTabletMetadata, will open an issue.

Opened #4795

**Comment by cshannon** [comment]
> I can work on creating a test for `CompactionCoordinator.compactionFailedForLevel` so that we can close out this issue as `CompactionDriver.cleanupTabletMetadata` will be opened as a separate issue. I'll probably try and do something with TestAmple first as that has the interceptor to support the unknown status but FlakyAmpleManager is also an option depending on what is easiest when I take a look.

I opened up #4797 and I went with using FlakyAmpleManager after all as that was by far the simplest way to test after having tried to use TestAmple. There were already good tests for cancellation that would exercise the failed compaction code so using Flaky ample exercises the rejection handler inside `CompactionCoordinator.compactionFailedForLevel`
