### ISSUE TITLE
Look at collapsing MutableByteSequence into ArrayByteSequence

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4738]
MutableByteSequence extends ArrayByteSequence with two method to modify the object, but ArrayByteSequence isn't immutable. MutableByteSequence is only used in 2 classes. Evaluate whether or not MutableByteSequence can be removed in favor of ArrayByteSequence with necessary modifications.

**Comment by keith-turner** [comment]
MutableByteSequence is not in a public API package so it would be easy to delete

**Comment by meatballspaghetti** [comment]
I can look into this.

**Comment by dlmarion** [comment]
@meatballspaghetti - Is there a pull request for your commit to merge it into the main repo?

**Comment by meatballspaghetti** [comment]
> @meatballspaghetti - Is there a pull request for your commit to merge it into the main repo?

Yes, there is now #4745 .
