### ISSUE TITLE
Ensure all files are present in bulk import load mapping.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#474]
This is follow up work to #436.    It would be nice to add a sanity check to the new bulk import code that ensures every file in the dir is represented in the load mapping file.

**Comment by keith-turner** [comment]
There are checks and test for the checks to ensure that the set of files in a load plan equals the set of files in the dir.

**Comment by ctubbsii** [comment]
@keith-turner Does your previous comment mean no work is done, or is necessary? If so, we should remove the 2.0 label.
