### ISSUE TITLE
Add methods to Key that populate existing ArrayByteSequence

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#4749]
In #4735 a method was added that populated an ArrayByteSequence with the data for the column visibility. A suggestion was made that like methods could be added for populating ArrayByteSequence with data for the row, family, and qualifier as well.

**Comment by ctubbsii** [comment]
@meatballspaghetti You might be interested in doing this one, since you're working on a related issue, #4745

**Comment by meatballspaghetti** [comment]
I can look into this.
