### ISSUE TITLE
Monitor 2.0 Bulk Import State is funky

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#475]
Follow on for #436 and for new Monitor.  The Monitor had previously displayed (or attempted to) the state of Bulk import processes.  Hopefully, for Bulk Import 2.0, this won't be needed.  If so, then the bulk import page could be removed in Monitor 2.0.  Otherwise we need to determine how/what to monitor for the new bulk import.

**Comment by keith-turner** [comment]
We could put a message on the page saying it only tracks bulk imports made via the deprecated method.

**Comment by milleruntime** [comment]
> We could put a message on the page saying it only tracks bulk imports made via the deprecated method.

That was my thinking as well but I am not sure the old bulk import state tracking works with the new Monitor.

**Comment by milleruntime** [comment]
I am re-opening this issue since there is a bug with the table displaying status of the legacy bulk imports.

**Comment by milleruntime** [comment]
![image](https://user-images.githubusercontent.com/11872539/60111205-89117c80-973b-11e9-9523-ec860a0123a7.png)
