### ISSUE TITLE
Negative numbers are allowed in Configuration for memory and duration types.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4758]
**Describe the bug**

Accumulo configuration supports specialized types for properties like memory and time.  The parsing of these types allows negative numbers. For example the following code 

```java
System.out.println(ConfigurationTypeHelper.getFixedMemoryAsBytes("-6G"));
System.out.println(ConfigurationTypeHelper.getTimeInMillis("-50s"));
```

prints 

```
-6442450944
-50000
```

**Expected behavior**
For all numeric configuration types (not sure if there are others besides memory and duration) where a negative number is not valid throw an exception when a negative number is seen.  For the example above `getFixedMemoryAsBytes()` and `getTimeInMillis` should throw IllegalArgumentException

**Comment by ctubbsii** [comment]
@keith-turner I believe I've already implemented this in [PropertyType](https://github.com/apache/accumulo/blob/bb9a967f5608986ef92d1299426c437750dfb7aa/core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java) with the validation of various types using numeric bounds. All the relevant types are covered, as far as I can tell. `ConfigurationTypeHelper` just helps parse them, but doesn't actually enforce the type constraints. That's done by `PropertyType`. If there's something that we've overlooked, we can reopen this, but I don't think there's anything to do here.
