### ISSUE TITLE
Variable redirection logic could be simplified

### ISSUE THREAD

**Issue by ddanielr** [apache/accumulo#4770]
**Is your feature request related to a problem? Please describe.**
The accumulo-cluster script contains a good deal of loops for incrementing over the number of servers.
This code could be simplified into some base functions that make the script a bit more readable and easier to maintain. 

**Describe the solution you'd like**
Simplify the looping logic in the accumulo-cluster script to remove repeated lines of code. 

**Additional context**
See the code changes in #4763 for improvement areas
https://github.com/apache/accumulo/pull/4763/files/64c38e5ce381a54e5d8b80a1cedf31c81e2105aa#diff-25441da11c70026e7132765c9c1cba145b80ba9c9d211a7ef46bef8ebf0ab18aR297-R298

**Comment by dlmarion** [comment]
@ddanielr - Did #4763 fix this? Can this be closed?

**Comment by ddanielr** [comment]
> @ddanielr - Did #4763 fix this? Can this be closed?

no, #4763 added the loop logic. This is a follow up task to that PR for cleaning up this loop logic.

**Comment by ddanielr** [comment]
Fixed by #5037
