### ISSUE TITLE
CompactionDriver.cleanupTabletMetadata is untested

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4795]
**Is your feature request related to a problem? Please describe.**

This [code](https://github.com/apache/accumulo/blob/0d72500bf2fa35916818e9d50b9956ab0950c686/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/compact/CompactionDriver.java#L357) in compaction driver is not covered by any test.  

**Describe the solution you'd like**

Test should be added that exercise this code and ensure it correctly cleans up a failed compaction fate operation.

**Comment by cshannon** [comment]
I can work on this, the best way to test is probably to add a test or 2 using `TestAmple`. There is an existing `ManagerRepoIT` that would be a good candidate to add tests for this. We can add some test metadata with TestAmple and then test that it is cleaned up.
