### ISSUE TITLE
Refactor Compression.java

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#483]
Follow on to #438.  We forked Compression.java from Hadoop at one point and then continued adding new compression Codecs to this enum.  The only codecs Hadoop has in this class are just GZ and LZO: https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/file/tfile/Compression.java
So there is no need for us to have this class the way it is and we can condense the enum, reducing duplicate code.

**Comment by lbschanno** [comment]
I am working on this.

**Comment by lbschanno** [comment]
Just submitted a PR for this. I focused primarily on removing duplicate code, but I also cleaned up some of the comments and restructured the code to make it more readable overall. If any of my changes went too far, let me know.

**Comment by jzgithub1** [comment]
Really great pull request @lbschanno .  Nice re-factoring.

**Comment by lbschanno** [comment]
@jzgithub1 thanks!
