### ISSUE TITLE
Add resource group to CompactionHost

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4849]
**Is your feature request related to a problem? Please describe.**

Every compactor process has an associated resource group. This information could be exposed int he API.

**Describe the solution you'd like**

This information could be added the the [CompactionHost](https://github.com/apache/accumulo/blob/df8a3670a4100bee083a02d6ac6f45ff36ffe8f6/core/src/main/java/org/apache/accumulo/core/client/admin/ActiveCompaction.java#L138) type as a new `String getResourceGroup()` method.  If added there then it could potentially be added to the listcompactions shell command output.

**Describe alternatives you've considered**

It may be good to consider how to get resource group information for scan servers and tablet servers also in the API.  I thought there was a draft PR related to this, but could not find it.  It could be usefui if listscans showed the resource group for tablet and scan servers.

**Comment by keith-turner** [comment]
#3626 was the PR I was trying to find.  It may  be better to take a more general approach like that in 4.0.  Made a comment on that PR about this.

**Comment by dlmarion** [comment]
#4782 could make use of this feature.

> It may be good to consider how to get resource group information for scan servers and tablet servers also in the API.

I think we should do it for Compactor, ScanServers, and TabletServers.

**Comment by dlmarion** [comment]
If #4851 is merged, then we can deprecate and remove CompactionHost.
