### ISSUE TITLE
1.8 Master marks bulk import as failed when it could still be successful

### ISSUE THREAD

**Issue by hlgp** [apache/accumulo#486]
Using default configurations for bulk.timeout, bulk.retry.max, the master will sometimes mark a bulk import as failed even though it was successful.  Sample timings:

11:18:08 master asks tserver1 to import
11:18:08 tserver1 gets request
11:23:08 master marks attempt 1 failed (SocketTimeoutException)
11:23:08 master asks tserver2 to import
11:23:08 tserver2 gets request
11:25:27 tserver1 finishes calculating overlapping tablets
11:25:27 tserver1 completes import
11:28:08 master marks attempt 2 failed (SocketTimeoutException)
11:28:22 tserver2 finishes calculating overlapping tablets
11:28:22 tserver2 successfully completes import
etc until marked completely failed.

Include examination of map files in tserver timeout?  Check isActive between master reattempts? Other?

**Comment by ctubbsii** [comment]
@keith-turner Any update on this? Or should this be bumped from the 1.9.3 release?

**Comment by keith-turner** [comment]
I think the changes in #837 fix this.  Those changes should prevent any files from loading while the metadata table is being scenned to see what failed.
