### ISSUE TITLE
Cache result of parsing TIMEDURATION property type in AccumuloConfiguration

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4860]
Each time getTimeInMillis is called on AccumuloConfiguration it will parse the time duration string and convert it to millis.  The result of parsing this could be remembered in the AccumuloConfiguration obj until the config changes.  Making this change could avoid continually re-parsing a string that never changes.  The changes could also allow removing any code outside of AccumuloConfiguration that attempts to cache the result of parsing a duration on its own.

Opened this issue based on discussion on #4855

**Comment by cshannon** [comment]
Looking at this, this seems like a problem for all properties. It looks alike all getters will always re-parse the string property value and do a conversion, such as getPort or getBoolean etc. Maybe we need a generic way to cache the computed value for all types and invalidate on update.

**Comment by keith-turner** [comment]
> Maybe we need a generic way to cache the computed value for all types and invalidate on update.

The configuration does have the Deriver that can do something like this, but not sure if its the best option for this. The deriver builds on a long that is increased whenever a changed is detected.  So a solution would probably either directly use this long or use the deriver.

**Comment by keith-turner** [comment]
If this change is made, then the map added in #4855 can be removed.
