### ISSUE TITLE
Possible bug with scan server timeout in TabletServerBatchIterator

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#4865]
While working on PR #4864 for Issue #4804 I noticed there might be a possible bug with the timeout that was added in #4671 and #4638.

Inside of `TabletServerBatchIterator` in the binRangesForScanServer() method the timeoutLeft is computed [here](https://github.com/apache/accumulo/blob/3a7982349219b36392d761bad4abd4f01630bb30/core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java#L681-L682) but this appears to be in the wrong spot as it will never be updated.

It seems like that code should be moved to be inside of waitUntil() method and possibly go right above [this](https://github.com/apache/accumulo/blob/3a7982349219b36392d761bad4abd4f01630bb30/core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java#L703) line

**Comment by cshannon** [comment]
When I merged #3864 forward I noticed that the code is the same in 2.1 and 3.1 but in main it's a bit different and `binRangesForScanServer` is [called](https://github.com/apache/accumulo/blob/3a7982349219b36392d761bad4abd4f01630bb30/core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchReaderIterator.java#L277) in a different spot in a while loop so I'm not sure if this issue also is a problem in 4.0 or not so that needs to be looked at as well.

**Comment by DomGarguilo** [comment]
I can take a look into this.

**Comment by DomGarguilo** [comment]
Closing as completed via #4893
