### ISSUE TITLE
Batch scans do not set scan session id in listscans

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4868]
**Describe the bug**
Batch scans always show a scan session id of zero in the listscans output.  This [code](https://github.com/apache/accumulo/blob/38952c922648014e74e4e7a5704bfa256f390faa/server/tserver/src/main/java/org/apache/accumulo/tserver/session/SessionManager.java#L497) sets the scan id for a normal scan.  However in the same class a bit later when it creates an ActiveScan object for a batch scan it does not set the session id.

**Expected behavior**

The session id is also set on batch scans. In addition to this it would be good to test this.  Maybe ScanIdIT should be improved to also test creating a batch scanner in the background in addition to the background scanners it creates.  If that test also ran batch scans it may have detected this problem.

**Comment by kevinrr888** [comment]
Completed by https://github.com/apache/accumulo/pull/4871
