### ISSUE TITLE
Consolidate code to clean up empty server lock nodes

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4883]
**Is your feature request related to a problem? Please describe.**

There are completely different implementations of the same functionality to clean up empty lock nodes for scan servers, compactors, and tablet servers.

**Describe the solution you'd like**

Create a single implementation of this functionality and use it to clean up all server types.  This  should build on #4861.

**Additional context**

#4882 is related.  Opened it as a separate issue because the testing could be added to older versions.  The code consolidation proposed in this issue only makes sense in the latest branch if it will build on #4861.

**Comment by dlmarion** [comment]
I pushed a branch up to my local repo that contains changes for this that use #4861 as a base. Can compare branches at https://github.com/dlmarion/accumulo/compare/group-in-zk-paths...dlmarion:accumulo:4883-group-in-zk-followon?expand=1.
