### ISSUE TITLE
Improve TabletInformation.getLocation

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#4937]
**Is your feature request related to a problem? Please describe.**

[TabletInformation.getLocation()](https://github.com/apache/accumulo/blob/e9a531e84046ae698768d29bb2c4331d80df047f/core/src/main/java/org/apache/accumulo/core/client/admin/TabletInformation.java#L61-L64) returns an `Optional<String>`.  However the javadoc does not explain what is in the string.  Looking at the implementation the string seems to be of the form `<location type>:<host>:<port>`.

**Describe the solution you'd like**
At the very least the javadoc should describe the contents of the string.  However a specialized type would be better.  Sigh, if only we could use records for this, this would be a great place to use a record to define a tuple the code is returning.

**Comment by dlmarion** [comment]
If / when #4851 is merged, you could use the `ServerId` class.

**Comment by dlmarion** [comment]
#4851 has been merged, ServerId class is available now.

**Comment by dlmarion** [comment]
I updated the javadoc in #4967. I didn't create a new concrete type for it. The return value is only used in the ListTabletsCommand where the String is printed. If we created a concrete type for this that separated the parts, then we would have to concatenate them back together just to print them.
