### ISSUE TITLE
Empty issue

### ISSUE THREAD

**Issue by Drxtofayel** [apache/accumulo#4981]
**Describe the bug**

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: [e.g. 1.10.0]
 - OS: [e.g. CentOS 7.5]
 - Others:

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dlmarion** [comment]
Issue opened with no content. Open a new issue with appropriate content if needed.
