### ISSUE TITLE
A '-' in the resource group name in cluster.yaml causes failure

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#5033]
**Describe the bug**
When configuring groups of servers in cluster.yaml, using a `-` in the group name causes an error to occur. The cluster.yaml file is parsed by java code, which creates a file containing environment variables. That file is then sourced by `accumulo-cluster` and the `-` in the environment variable name causes a failure.

**Versions (OS, Maven, Java, and others, as appropriate):**
Versions starting with 2.1.0 forward are probably affected.

**To Reproduce**
Create a cluster.yaml file using the command `accumulo-cluster create-config`. In the cluster.yaml file, create a group name that contains a `-`. Then try to start the cluster using `accumulo-cluster start`.

**Expected behavior**
The cluster should start

**Additional context**
The workaround here is to not use a group name containing a `-`. Instead of allowing they hyphen to work, we might want to change the ClusterConfigParser to enforce a set of valid conventions when parsing cluster.yaml and returning an error with an appropriate message when the user supplies a group name that violates the conventions.

**Comment by keith-turner** [comment]
We could have static method in the code somewhere named `isValidResourceGroupName()`.  This could be called by the yaml parsing code and the code that starts a server using a RG name option.

**Comment by dlmarion** [comment]
Yeah, I found some information on the web that suggests that [a-zA-Z0-9_] are valid, portable characters for shell environment variable names.

**Comment by dlmarion** [comment]
> This could be called by the yaml parsing code and the code that starts a server using a RG name option.

I don't know that we need to validate from the server as the issue is solely with the bash environment variables, which are created by parsing the cluster.yaml file and used in `accumulo-cluster`.
