### ISSUE TITLE
Utility to check configuration cannot be run prior to init 

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo#5034]
**Describe the bug**
The CheckServerConfig class that checks the Accumulo configuration, run via the `check-server-config` command, cannot be run before an instance is initialized.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 4.0.0-SNAPSHOT, but may go back to 2.1.0

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
Run `accumulo check-server-config` without an instance initialized

**Expected behavior**
Expected to validate the configuration regardless of cluster state

**Comment by kevinrr888** [comment]
I'll take a look at this, if you aren't already.
A ticket I'm currently working on (#4892) would involve moving this check, so would be nice to fix this before I make those changes.

**Comment by dlmarion** [comment]
@kevinrr888 - I'm not currently looking at this.

**Comment by kevinrr888** [comment]
Completed from #5073
