### ISSUE TITLE
The handling of children for non-existent nodes in ZooCache may not be correct.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#5047]
**Describe the bug**

ZooCache attempts to cache nonexistence.  This may not be done correctly for the case of getChildren.

The ZooCache code expects that ZooKeeper.getChildren() may return null [here](https://github.com/apache/accumulo/blob/cfae5e9abc7447aacc7136777f853fc0842c49de/core/src/main/java/org/apache/accumulo/core/fate/zookeeper/ZooCache.java#L316-L318).  However it will probably never return null.  When a node in zookeeper exists and has no children an empty list is returned.  When a node does not exist a NONODE KeeperException is thrown.  The code zoocache code is handling this, however it does not cache this.   The code behaves correctly, this is only a possible performance bug.

**Expected behavior**

 * Remove handling for null in code as its not expected to ever happen.
 * Determine if its safe to cache non-existence for getChildren, which depends on ZK watcher behavior.  If it is safe then look into changing the code to cache this.  If not then only the null handling needs to be removed for this issue.

**Comment by keith-turner** [comment]
Examining jstacks of a running manager I was seeing lots of threads stuck in ZooCache waiting to resolve if a tablet server currently had its lock.  Things were getting stuck in zoocache because it was continually having to go to zookeeper.  There were only a few tablet servers, so it was not clear why they were getting stuck. After apply the change in #5133 was able to see why zoocache was continually missing and it was because of this issue plus there being multiple tserver resource groups.  This problem results in every scan or write to accumulo hitting zookeeper.  The following is what happened.


 1. A scan or write does a check using zoocache to see if the tablet server is currently holding its lock in zookeeper.
 2. When there are multiple resource groups the check will look for the tserver in each resource group calling `zooCache.getChildren("<zkroot>/tservers/<resource group>/<tserver>`. 
 3. The tservers only exists in one RG and for the ones it does not getChildren does not cache non-existence so it will fall back to zookeeper.
 4. While the getChildren call is made to zookeeper all other threads block for the same path.

If there was a single resource group for tablet servers then this problem would not be seen.

**Comment by dlmarion** [comment]
> 1. A scan or write does a check using zoocache to see if the tablet server is currently holding its lock in zookeeper.
> 2. When there are multiple resource groups the check will look for the tserver in each resource group calling `zooCache.getChildren("<zkroot>/tservers/<resource group>/<tserver>`.
> 3. The tservers only exists in one RG and for the ones it does not getChildren does not cache non-existence so it will fall back to zookeeper.
> 4. While the getChildren call is made to zookeeper all other threads block for the same path.
> 
> If there was a single resource group for tablet servers then this problem would not be seen.

Is this check originating in the TabletServer to check it's own lock? If so, each process knows which resource group it is in, there is no need to check them all.

**Comment by keith-turner** [comment]
> Is this check originating in the TabletServer to check it's own lock? If so, each process knows which resource group it is in, there is no need to check them all.

Not in this case.  I observed the problem happening in the tablet location cache which checks the lock in zoo cache prio to returning a location.  This was causing every scan/write in accumulo to make a read to zookeeper.  Not sure if this is workable or worthwhile but wondering about adding the RG to the tsever location stored in the metadata table.  Then the tablet location cache would know of it.  Also scans of the metadata table would know of it and it could be exposed via TabletInformation.  The RG is invariant for the lifetime of the tserver process so storing it there seems like it would be safe.  The downside is its just reduntant data.  If we did this the location entry in the metadata table might look like `<RG>:<host>:<port>[<session>]`

If there are places in the code that are doing a lock check and the RG is known then it would be nice to pass it along.  Need to survey the code and see if there are any places like this.

**Comment by dlmarion** [comment]
> I observed the problem happening in the tablet location cache which checks the lock in zoo cache prio to returning a location. The tablet location cache gets the tserver location from the metadata table where the RG is unknown.

There could be an alternate way to determine the resource group of a tserver that is hosting the tablet - the value of `table.custom.assignment.group` in the tables' configuration. I'm not sure if you have access to this in the TabletLocationCache code or not, but in theory this should help.

**Comment by keith-turner** [comment]
> There could be an alternate way to determine the resource group of a tserver that is hosting the tablet - the value of table.custom.assignment.group in the tables' configuration. I'm not sure if you have access to this in the TabletLocationCache code or not, but in theory this should help.

That may not always be a reliable way to determine the RG.  Interpreting that property depends on the configured balancer, so that could lead to differences in the property and what is actually happening.  Also if the config changes then there is a time where the current tserver RG and the desired tserver RG could differ.
