### ISSUE TITLE
Add server and resource group pattern options to listscans and listcompactions

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#5069]
**Is your feature request related to a problem? Please describe.**

The listscans and listcompactions command contact every server to gather information unless the tserver option is given in which case a single tablet server, scan server, or compactor is contacted.  This option name no longer makes sense. Also it would be really useful to be able to quickly list compactions of scans for a subset of servers instead of a single server or all servers.

**Describe the solution you'd like**

Remove/deprecate the tablet server option and replace it with the following options that take a reg ex.

  * `-rg/--regource-group <regex>`
  * `-s/--server <regex>`

The implementation of these options could call this [function](https://github.com/apache/accumulo/blob/78fd622c022b7186761aabfcb687609d900569db/core/src/main/java/org/apache/accumulo/core/client/admin/InstanceOperations.java#L251) passing predicates that execute the regex.  This approach will offer the following benefits for filtering servers.

 * Getting the list of servers requires a lot of back and forth RPCs to zookeeper.  Passing in regex predicates to the InstanceOperations.getServers function will reduce the amount of zookeeper RPCs and the overall latency of the command.
 * Once a list of servers has been efficiently obtained an RPC to each one must be made to obtain the scan or compaction information.  Operating on a subset of servers for these RPCs will reduce the overall latency of the command.

With these options it would be possible to efficiently only list scans on a resource group, subset of servers in a resource group, severs on a rack (if the server naming scheme supports this), etc.

**Comment by cshannon** [comment]
I can take a look at this issue
