### ISSUE TITLE
Mini Accumulo Cluster class loaders behaviour

### ISSUE THREAD

**Issue by pomadchin** [apache/accumulo#507]
Hey all! 

I'm trying to use (the first attempt to move from accumulo mock client) Mini Accumulo Cluster in [SBT](https://github.com/sbt/sbt) tests and experience an issue with this line: https://github.com/apache/accumulo/blob/rel/1.9.1/minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java#L272

The thing is that it loads the following class loaders: 

```
URLClassLoader with NativeCopyLoader with RawResources(
  urls = List(...),
  parent = DualLoader(a = java.net.URLClassLoader@1c345372, b = java.net.URLClassLoader@69ea3742),
  resourceMap = Set(app.class.path, boot.class.path),
  nativeTemp = ...
)
DualLoader(a = java.net.URLClassLoader@1c345372, b = java.net.URLClassLoader@69ea3742)
NullLoader // <!- here is the issue
sun.misc.Launcher$AppClassLoader@75b84c92
sun.misc.Launcher$ExtClassLoader@483f6d77
```

The error I'm getting is: `Unknown classloader type : sbt.internal.inc.classpath.NullLoader`
Where the `NullLoader` itself is: 

```scala
package sbt.internal.inc.classpath
final class NullLoader() extends java.lang.ClassLoader { ... }
```

Mb it makes sense to skip unknown class loaders rather than to throw exceptions and to throw an exception only if there are no class loaders at all? Also any workarounds are welcome and let me know if it makes sense to create issue on the `SBT` side rather than here.

Would be glad to fix and to test this issue in case it's indeed required.

Update:

Also I discovered a workaround on the `SBT` side (accidentally right after posting this issue), to fork JVM in tests (SBT setting: `fork in Test := true`).

**Comment by keith-turner** [comment]
MiniAccumulo reads the classpath from classloaders because it launches subprocesses which need a classpath.  The non public API for MiniAccumulo allows explicitly setting this classpath as config, would it be helpful to make this public?

**Comment by pomadchin** [comment]
Sounds like a good solution in this buggy case! Thanks for a quick reply.

**Comment by keith-turner** [comment]
> Sounds like a good solution in this buggy case!

So for your testing case, you could easily know what classpath to use?

**Comment by pomadchin** [comment]
Yes. Or I can reproduce the logic from the `private String getClasspath()` but with an extra skip of `bad` loader(s).

**Comment by keith-turner** [comment]
Ok.  At [MiniAccumuloClusterImpl.java#L252](https://github.com/apache/accumulo/blob/rel/1.9.1/minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java#L252) you can see where it checks this internal config.   This can be set using [MiniAccumuloConfigImp.setClasspathItems()](https://github.com/apache/accumulo/blob/rel/1.9.1/minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloConfigImpl.java#L597).  You could experiment with using that internal API, however since its not Public API there is no guarantee of stability.

**Comment by pomadchin** [comment]
Looks like everything works, thanks for your support, if smth would happen again we can always create a new issue / reopen this one. Thanks a lot!
