### ISSUE TITLE
Remove graphs, problem reports and logs from the monitor

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo#5091]
In an effort to trim down the accumulo monitor, the following can be removed first from 3.1:

- [x] graphs on the homepage (completed via #5108)
- [x] problem reports
- [x] logs (completed via #5110)

Each of these things can happen in a separate PR.

**Comment by ctubbsii** [comment]
#5019 removed the problem reports in the main branch. It needs to be backported to 3.1 for this. I was going to do it, but am also okay with you taking it over, since I haven't gotten to it yet.

**Comment by ctubbsii** [comment]
> > #5019 removed the problem reports in the main branch. It needs to be backported to 3.1 for this. I was going to do it, but am also okay with you taking it over, since I haven't gotten to it yet.
> 
> I can do it if you haven't started.

I haven't started it, but looking at the PR, it does not look like it will be a difficult backport.
