### ISSUE TITLE
Cleanup InstanceOperations API for retrieving active scans and compactions

### ISSUE THREAD

**Issue by cshannon** [apache/accumulo#5096]
This issue is to implement the suggestions mentioned in https://github.com/apache/accumulo/pull/5072#discussion_r1847008790

There's more details in that comment but the main goals are:

1. Simplify the API for getting active scans and compactions by removing overlap of methods related to filtering servers and instead just creating methods that take a collection of servers to get scans/compactions from.
2. Make getting  getActiveScans multi-threaded like getActiveCompactions is.

**Comment by cshannon** [comment]
@keith-turner - In regards to adding multi-threading for scans, I'm planning to add a new API call to InstanceOperations that is similar to getActiveCompactions(List<ServerId> servers) and I'm wondering what we want to do with the custom java [iterator](https://github.com/apache/accumulo/blob/bbfd250d8694c210faf31116d199b56570c46f38/shell/src/main/java/org/apache/accumulo/shell/commands/ActiveScanIterator.java#L33) used by the shell for the listscans command. 

We could update that to just use the new API call and get back all the scans at one time for all the servers and print them out which simplifies things compared to now (currently it just makes calls as it loops through the list of servers instead of all at once). But we could get a lot of scans back depending on how many servers are queried at once. We could just and limit the number of servers we query at one time (maybe break the server list into chunks) but I'm also thinking we may just not need to worry about it because if too many scans are returned a better regex could be used to limit the results more.

**Comment by keith-turner** [comment]
> @keith-turner - In regards to adding multi-threading for scans, I'm planning to add a new API call to InstanceOperations that is similar to getActiveCompactions(List servers) and I'm wondering what we want to do with the custom java [iterator](https://github.com/apache/accumulo/blob/bbfd250d8694c210faf31116d199b56570c46f38/shell/src/main/java/org/apache/accumulo/shell/commands/ActiveScanIterator.java#L33) used by the shell for the listscans command.

That iterator seems like its concatenating iterators and transforming.  Seems like that cusomt iter could be dropped and replaced w/ streams that concat and transform and then turn the stream into an iterator.

> We could update that to just use the new API call and get back all the scans at one time for all the servers and print them out which simplifies things compared to now (currently it just makes calls as it loops through the list of servers instead of all at once). But we could get a lot of scans back depending on how many servers are queried at once. 

Pull too much into memory seems like a valid concern.  Could possibly use guavas Lists.partition for this.  

```
List<List<ServerId>> partServerIds = Lists.partition(serverIds, 100);
Stream<String> servers = partServerIds.stream().flatMap(ids->client.instanceOps.getActiveScans(ids).stream()).map(//do the string mapping that ActiveScanIter does);
```

Maybe this will fetch 100 severs at a time in parallel, not sure.  Depends on flatMap behavior.
