### ISSUE TITLE
Investigate if preference is given to splits over compactions

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#5101]
**Is your feature request related to a problem? Please describe.**

In Accumulo 2.1 and earlier when a tablet needs to split no compactions will be initiated.  This is because if a tablet is really large then its best to compact after split.  

**Describe the solution you'd like**

Determine if the Accumulo 4.0 code will start a compaction when a tablet needs to split and if so possibly avoid doing this.

**Comment by cshannon** [comment]
I chatted with @keith-turner a bit about this. It looks like 4.0 doesn't have this check, the spot where it would likely be done is [here](https://github.com/apache/accumulo/blob/d139704010987b0dc6474d74db0fbabe52795b82/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L609-L619).

Some more investigation is still needed, something else to consider is what to do if a tablet is marked as unsplittable. We'd probably still want to compact in that case

**Comment by cshannon** [comment]
It looks like the unsplittable tablet case should already be handled as TabletManagementIterator won't return that the tablet needs splitting if it is unsplittable. The check is made by a call to [shouldReturnDueToSplit](https://github.com/apache/accumulo/blob/d139704010987b0dc6474d74db0fbabe52795b82/server/base/src/main/java/org/apache/accumulo/server/manager/state/TabletManagementIterator.java#L303) and inside that method the check is done

**Comment by cshannon** [comment]
I think fixing this is as simple as changing [this](https://github.com/apache/accumulo/blob/d139704010987b0dc6474d74db0fbabe52795b82/server/manager/src/main/java/org/apache/accumulo/manager/TabletGroupWatcher.java#L609-L619) block of code from two if statements to an if/else if statement so that compaction only gets processed if the tablet doesn't need to split. Ie

```java
if (actions.contains(ManagementAction.NEEDS_SPLITTING)) {
  // split
} else if (actions.contains(ManagementAction.NEEDS_COMPACTING) && compactionGenerator != null) {
  // use else if so we only compact if we don't need to split
}
```
