### ISSUE TITLE
Add User initiated Compaction Information to IteratorEnvironment

### ISSUE THREAD

**Issue by bbux-atg** [apache/accumulo#512]
Add User initiated Compaction Information to IteratorEnvironment

The IteratorEnvironment only indicates that a major compaction is a full compaction if it is in the final round of the full compaction. 

For example, let's say there are 19 files in the tablet and the maximum number of files per major compaction is 10. Accumulo will compact those 19 files in two rounds. The first round will merge 10 files into 1, leaving the other 9 untouched.  Once that round is complete , there will be 10 remaining files.  This is considered a major compaction, but not a full major compaction, according to the IteratorEnvironment.

The second and final round will compact all the remaining files into 1 file.  This final round is considered a full and major compaction.

There are some filter use cases that don't need to the complete compacted information before they operate and thus could optimize operations during round 1 of the compaction.  There are also use cases that may only run during a user initiated compaction.  By exposing this information filters could be constructed that can use both rounds of compaction optimally and save tablet server resources.

**Comment by ctubbsii** [comment]
PR in #513
