### ISSUE TITLE
Tablet server client pool metric name is inconsistent with other names.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#5136]
**Describe the bug**

The executor name `accumulo.pooltabletserver.client` for the following metric should have a `.` after pool to be consistent with other metric names.

```
2024-12-04T19:06:13,492 40 [accumulo.METRICS] INFO : executor.completed{host=localhost,instance.name=miniInstance,name=accumulo.pooltabletserver.client,port=34055,process.name=tserver,resource.group=default} throughput=44.2 tasks/s
```

**Comment by keith-turner** [comment]
I tried to find where this is defined in the code with a few different greps and was unable to find anything.  So this is probably being composed from constants or something like that.

**Comment by dlmarion** [comment]
I think it's here:

https://github.com/apache/accumulo/blob/cd07dc60360b3c14009380b0b0d96f2197757b26/server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java#L309
