### ISSUE TITLE
Tiered Storage Volume Chooser

### ISSUE THREAD

**Issue by alerman** [apache/accumulo#517]
For systems with a mixture of high density, slower disks and low density faster disks provide a volume chooser that can be configured to put data accesses more often onto the faster disks. This will require having the fast/slow disks partitioned into seperate volumes, and will also require that the _majorCompact code be modified to use the volume chooser to determiner where to put new files, instead of relying on srv:dir. This choice will be made based on the tablet that is being compacted using a user defined strategy for how to decide which volume to use.

Needed:

1. New TieredStorageVolumeChooser
2. New configuration options for the volume chooser
3. Updates to major compaction code that determines the output file location (Specifcally around line 1945 of Tablet.java)
4. A VolumeChooserStrategy that can be user defined to allow users to define how to pick the new volumes

**Comment by alerman** [comment]
I am already working toward this, but wanted to give others a chance to weigh in earlier rather than later

**Comment by alerman** [comment]
@ctubbsii I have code working for 1,2,4. I think for now I am leaving 3 alone. This will force the new choice on removal of srv:dir but not before.

**Comment by ctubbsii** [comment]
I think much of this is OBE by removal of srv:dir property. If there's still more related to this, please re-open or create a new tracking issue.

**Comment by alerman** [comment]
I concur. Thanks @ctubbsii
