### ISSUE TITLE
Drop very old deprecated Instance.getConnector methods

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#530]
We have several very old, outdated Instance.getConnector methods representing previous attempts to improve our API entry point. These haven't been recommended in a very long time, and were never very good. They should be removed in 2.0 to highlight the newer, better APIs which we support.

**Comment by keith-turner** [comment]
I took a quick survey of a few projects : Fluo, Gora, Rya, Geowave, and Datawave and found 3 of 5 are currently using some of these methods.  This change will impact those projects.  What benefit does removing these methods have that justifies the inconvenience for downstream projects? 

>   They should be removed in 2.0 to highlight the newer, better APIs which we support.

Another way to highlight the new APIs is to document them, blog about them, tweet about them, etc...

**Comment by ctubbsii** [comment]
Major versions are our best opportunities to remove old cruft, and encourage users to migrate to currently supported, APIs that we can continually improve. We have already communicated that these are to be avoided... years ago. If it causes any problems for other projects, I think it will be fine to just provide any support we can to help them migrate their code.
