### ISSUE TITLE
Add multiple compaction thread pools and allow multiple compactions per tablet

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#564]
Currently there is a single thread pool/executor for compactions and only a single compaction can run per tablet.  This can cause problems when a user initiates a single long running filter or transform compaction because new files build up and are not compacted.  Ideally a long running compaction for a tablet could run in executor1 while new tablets files are compacted in executor2.

The current user pluggable CompactionStrategy class is not well suited for handling this case of multiple executors and  compactions per tablet.  The following design is better suited for mananging this concurrency in a way that is easy to understand.  In this design the CompactionManger and CompactionPrioritizer are user pluggable.  Currently, prioritization of queued compaction are not configurable. 

| Functional components | Description |
|-----------------------|-------------|
| CompactionJob         | Immutable class that describes work to be done.  Contains list of files to compact, info about iterators for user compactions, info about output file (like compression type). |
| CompactionManager  | Per table class that decides what compactions to do for a tablet. Can create and cancel compactions jobs.  Can see list of existing jobs.  Can submit multiple jobs for a table as long as files are disjoint. This class decides which executor should process a job.   |
| CompactionPrioritizer | Per executor class that decides which compaction job to execute next. |
| CompactionExecutor    | Each tablet server has one or more executors that process compaction jobs.  These are configured system wide. Number of threads, rate limits, max file per compaction are some things that can be configured.  If a job exceeds the max files, then the executor will process it in multiple passes.|

One major goal with this design is to make it easy for the user to write code that avoids concurrency mayhem.  The idea underlying this that a compaction manager will be called in the following way.

 * System gathers a snapshot of tablet files and current compaction jobs.
 * System calls compaction manger with gathered snapshots.
 * The compaction manager returns jobs to cancel and new jobs to run.
 * If the set of files and/or jobs has changed the decisions are ignored and the manager is called again.

With this model the prioritizer is dealing with immutable jobs that will not magically change when its time to run the job (how current compaction strategy works).  Immutability makes reasoning about creating, canceling, and prioritizing jobs sane.

The following is an example of how this might work.  In this example assume executor E1 is intended for small compactions and executor E2 is for large compactions. Small vs large could be a function of the input file sizes.

 * Tablet T1 has three files F1,F2,F3
 * Compaction manger decides to compact F2 and F3 on executor E1 as job J1
 * A new file F4 is added to T1
 * J1 is still queued on E1
 * Compaction manger decides to cancel J1 and compact F1,F2,F3,andF4 on executor E2 as J2.
 * Nothing changed, so J1 is canceled and J2 is submitted. 

For user initiated compactions, compaction strategies would still be used for compatibility.  The behavior should be the following :
  * Cancel existing queued jobs (that are system initiated) and prevent more jobs from qeueing
  * Wait for any running jobs to complete
  * Apply the users strategy and create a job.
  * Ask the compaction manager which executor the job should be queued on.

**Comment by keith-turner** [comment]
This design shares some similarities with scan executors.

https://accumulo.apache.org/docs/2.0/administration/scan-executors

**Comment by keith-turner** [comment]
This design should address the concerns raised in

https://issues.apache.org/jira/browse/ACCUMULO-4573

**Comment by keith-turner** [comment]
I have been doing some simulation and experimentation related to this issue.

https://gist.github.com/keith-turner/16125790c6ff0d86c67795a08d2c057f

**Comment by phrocker** [comment]
Could we break these runners out into sep processes to facilitate containerized compactions ?

**Comment by keith-turner** [comment]
> Could we break these runners out into sep processes to facilitate containerized compactions ?

I have been thinking about that, wondering should I do that or this or both.  I have concluded that I think doing both makes sense.  The reason I am thinking that way currently is it seems like the external compactions would be good for one off really large filtering and/or transformation operations.  The internal compactions seem better suited to maintaining order with a constant stream of incoming small files.  I opened #1451.

I have tried to think through the case of tservers using an external global work queue of compactions to deal with  incoming small files.  Thinking through it, it starts to become really complex because how tserver want to prioritize and select files for compaction may change as soon as a few new small files arrive. Within a tserver it can easy cancel previously queued work, queue new work, and re-prioritize work.  With a distributed work queue, this seems more daunting.  This what I was thinking of when I mentioned early vs late binding in #1451.

**Comment by ivakegg** [comment]
+1

**Comment by ivakegg** [comment]
I presume that the CompactionPrioritizer and Compactionmanager would be pluggable.

**Comment by drewfarris** [comment]
I think this is looking good as well, just a couple questions:

Have you thought much about how the `CompactionManager` decides to perform work or decides to cancel scheduled work? Is this implemented via some sort of pluggable strategy and does this mean that there's a new interface we need to design to support this?

I could be misunderstanding the role of the `CompactionPrioritizer` - it seems that this class establishes priorities for jobs that have already been formulated, but perhaps this class actually creates the jobs to run by looking at a set of files to potentially compact?

I like the idea of moving large or compute-intensive jobs out of the tserver process. Interested to see how managing external compactions works out.

In the documentation for `CompactionExecutor` you mention that if a job is too big it will be processed in multiple passes. I wonder how much complexity this will add to the code - perhaps it will be more straightforward if the executor can split jobs - with the notion that an entire job either succeeds or fails, but there's no partial success state?

**Comment by keith-turner** [comment]
> Have you thought much about how the CompactionManager decides to perform work or decides to cancel scheduled work?

The work I was doing with [compaculation](https://github.com/keith-turner/compaculation) was all centered around creating a new default algorithm for Accumulo that can leverage multiple executors in an efficient manner that keeps the avg files per tablet low.  I [wrote up](https://gist.github.com/keith-turner/16125790c6ff0d86c67795a08d2c057f) some of my results so far, but I am still working towards finding a new default algorithm I like.

> CompactionPrioritizer - it seems that this class establishes priorities for jobs that have already been formulated

That is what I was thinking.  Specifically each executor would have priority queue of immutable compaction jobs and users can specify a comparator for this queue if they like.

> In the documentation for CompactionExecutor you mention that if a job is too big it will be processed in multiple passes. I wonder how much complexity this will add to the code -

That is probably a bad idea and would make things really hard to reason about. If needed a compaction job could possibly support having a list of list of files, with each list being done in a single pass.  With this there is the possibility of multiple passes, but the compaction manager has complete control over it.
