### ISSUE TITLE
Tables with write ahead logs disabled still attempt recovery and fail

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#577]
If a table has write ahead logs disabled it may still attempt to recover logs and fail because a tablet id of -1 was written to the WALs.

**Comment by ctubbsii** [comment]
What does `because a tablet id of -1 was written` mean? What is a `-1` supposed to indicate?

**Comment by keith-turner** [comment]
It seems the code is using -1 to indicate an invalid id for all tablets with walog disabled.   When the walog is disabled, tablets get a walog id of -1. As long as the walog is disabled, define tablet events should not be written to the walog.  However I think the define tablet events are being written in some situations.

**Comment by keith-turner** [comment]
This may have been fixed by b8f574fc282cdc7fc4f92b7bf0d5db49bc7ee4ce

**Comment by ctubbsii** [comment]
@keith-turner Should we close this, then, and reopen if it's still broken?

**Comment by keith-turner** [comment]
I did a few experiments with 1.9.3-SNAPSHOT and did not see any issues.  I tried different combinations of disabling walogs, enabling walogs, writing data, and killing tservers.  The tablets always recovered without issue.
