### ISSUE TITLE
Monitor 2.0 Main page is pessimistic 

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#593]
The monitor for 2.0 will flash "Master is down" when refreshing.  I believe it is pessimistic by default and then onload will display the live information.  It should be an easy fix to display the whole table by default but just update the numbers when data is loaded.

**Comment by jzgithub1** [comment]
I will look at this now.

**Comment by milleruntime** [comment]
@jzgithub1 Any progress on this?

**Comment by jzgithub1** [comment]
No progress.  I jump off of this to concentrate on #1052.

**Comment by milleruntime** [comment]
No worries!  I was just looking through tickets and thought I would ping you.  Hit me up on Slack if you have any questions.

**Comment by jzgithub1** [comment]
I will get on it later today or on Tuesday.

**Comment by jzgithub1** [comment]
I am working on this now but is there any other issue that is a priority?

**Comment by ctubbsii** [comment]
> I am working on this now but is there any other issue that is a priority over this one?

As 2.0 development winds down and we enter the final stretches towards a 2.0 release, there's probably going to be fewer and fewer high priority items... just lots of little stuff like this to polish up.
