### ISSUE TITLE
Tservers not removed from serversToShutdown

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#603]
The master has a set called serversToShutdown.  Tablets servers are added to this set by stop here script. Sometimes the tablets server are not removed from this and that prevents balancing.

**Comment by ctubbsii** [comment]
Is this still an issue? What versions does it affect?

**Comment by dlmarion** [comment]
@ctubbsii It looks like this may have been addressed in https://github.com/apache/accumulo/pull/781
