### ISSUE TITLE
Include version in Jar filenames of Accumulo depedencies

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#622]
At some point, Accumulo moved away from including version numbers in file names for dependencies found in the `lib/` directory of the Accumulo binary release tarball. While I am sure there was a good reason for this at the time, it would be nice to move back to putting the version in the filename of these jars.

**Comment by ctubbsii** [comment]
I seem to remember there being some debate about it at the time, but I thought I had made a convincing case for it. I believe it had something to do with making it easier to manage the class path, either by unpacking a newer tarball on top of another (probably a bad idea anyway), or something to do with our scripts being broken every time we bumped the dependency version.

I think going back to the explicit version numbers are fine, but I'd like to first review the history to see if there's any still valid reason why we shouldn't do that.
