### ISSUE TITLE
Performance with midsize table size

### ISSUE THREAD

**Issue by snoami** [apache/accumulo#624]
I have a table with about 4M rows in Accumulo, which is grouped to about 90K entities with different rowIds, and it takes about 10 sec to scan all the table from the Java API when I scan with large rowId range or ranges. I have also tried BatchScan ranges where each rowId is its own range. Scan -np on the Accumulo shell gives similar result.
I have tried it with different configurations on very strong machines @AWS and the performance does not get better than about 10s. Is that reasonable? It seems very slow but maybe that is what Accumulo can do. Does anyone have experience with such queries? Using: Accumulo 1.7.4 Hadoop 2.8.1 4vCPU, 16GB RAM (AWS m5d.xlarge), 5 servers running Accumulo tservers and Hadoop data nodes, one name node running Accumulo master.

**Comment by medined** [comment]
how many threads are running at the same time?

**Comment by snoami** [comment]
In the BatchScan? I have tired 10,100,500 and 1000...  this didn't provide much improvement

**Comment by mikewalch** [comment]
Have you enabled [caching](https://accumulo.apache.org/docs/2.0/administration/caching) for the table? Below is the command to do this in the shell...

```
config -t mytable -s table.cache.block.enable=true
```

There are other [tips for improving performance](https://accumulo.apache.org/docs/2.0/troubleshooting/performance) in the 2.0 documentation that should probably apply to 1.7.4.

**Comment by milleruntime** [comment]
It sounds like you are doing a full table scan with your queries, which is always going to be slower and you should avoid.  Providing a Range on BatchScanner should greatly narrow the focus of queries to a smaller subset of data.  Have you set any split points on your data?   This step on the tour is a good introduction: https://accumulo.apache.org/tour/ranges-splits/

**Comment by mjwall** [comment]
There was discussion on the user list that may be of interest as well.  https://s.apache.org/rXId and https://s.apache.org/8QS3

**Comment by snoami** [comment]
thanks for all the answers. I have set splits on the tables, which helps very little, since its  not a resource issue.(CPU/ Mem/ IO are all under utilized)
Table scan was just a test and the real problem is slow queries. I do use ranges (large ones as needed) and it takes several seconds. I was trying to understand if its reasonable time?,Rational DB of this size (a few million rows) will do it in a split of a second.
