### ISSUE TITLE
question: how can I get the size of the table in accumulo?

### ISSUE THREAD

**Issue by misslzyan** [apache/accumulo#647]
how can I get this size of the table in accumulo ?
I want to know  the storage information about the table  in  MB .

**Comment by keith-turner** [comment]
The accumulo shell has a `du` command that takes one or more table names as an argument.   If given multiple tables, it will compute the amount of overlapping space which is useful for cloned tables.

**Comment by misslzyan** [comment]
thank you ! I will try it.
