### ISSUE TITLE
Analyze creation of Volume Managers

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#666]
In the course of reviewing #645 I was curious when VolumeChoosers are created.   Seems they are created by the VolumeManager.  Most code uses a single VolumeManager created as part of ServerContext.  However some code seems to create its own VolumeManager directly from config.  Where possible it's better to use the VolumeManager from server context.

Making this has a direct impact on #645 because it creates a VolumeChooser with a cache.

**Comment by ctubbsii** [comment]
Any progress on this?
