### ISSUE TITLE
Add metrics to summarization

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#695]
Table summaries were added in ACCUMULO-4500. Need to add metrics to the summary retrieval rpc and file operations.

Also referenced: 

  Accumulo-4500 (closed) Implement visibility histograms as a table feature
  Accumulo-4607: Add tracing support for summarization

(moved from JIRA: ACCUMULO-4608)

**Comment by DomGarguilo** [comment]
This may be able to me included as part of #2017

**Comment by cshannon** [comment]
This issue is over 4 years old so closing out. If there is still a desire to do it then it can be re-opened.
