### ISSUE TITLE
Add tracing support for summarization

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo#696]
Table summaries were added in ACCUMULO-4500. Need to add tracing to the summary retrieval rpc operations.  (and see  https://github.com/apache/accumulo/issues/695)

(Moved from ACCUMULO-4607)

**Comment by cshannon** [comment]
This issue is over 4 years old so closing out. If there is still a desire to do it then it can be re-opened. Also tracing was replaced recently so this may or may not be relevant.
