### ISSUE TITLE
NullPointerException when doing MapReduce job

### ISSUE THREAD

**Issue by deniskuzZ** [apache/accumulo#705]
Caused by: java.lang.NullPointerException
        at org.apache.accumulo.core.client.mapred.AbstractInputFormat$AbstractRecordReader.initialize(AbstractInputFormat.java:608) 
        at org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat$1.initialize(AccumuloRowInputFormat.java:60)

**Comment by deniskuzZ** [comment]
Null check should be added for tableConfig

**Comment by keith-turner** [comment]
In what version of Accumulo did you see this?

**Comment by deniskuzZ** [comment]
Hi Keith,

Issue is reproducible in v1.8.1, v1.9.2 and works fine with v1.7.3.

Use-case that I was testing:
1) Created from Hive CLI Accumulo backed table

CREATE TABLE accumulo_pushdown(key string, value string)
STORED BY 'org.apache.hadoop.hive.accumulo.AccumuloStorageHandler'
WITH SERDEPROPERTIES ("accumulo.columns.mapping" = ":rowid,cf:string");

2) Executed below statement (triggered MapReduce job)

select * from accumulo_pushdown where key>'90' and value like '%9%';

Caused by: java.lang.NullPointerException

at
org.apache.accumulo.core.client.mapred.AbstractInputFormat$AbstractRecordReader.initialize(AbstractInputFormat.java:637)

at
org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat$1.initialize(AccumuloRowInputFormat.java:67)

at
org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat.getRecordReader(AccumuloRowInputFormat.java:92)

at
org.apache.hadoop.hive.accumulo.mr.HiveAccumuloTableInputFormat.getRecordReader(HiveAccumuloTableInputFormat.java:224)

at
org.apache.hadoop.hive.ql.io.HiveInputFormat.getRecordReader(HiveInputFormat.java:295)


Please let me know if you need some additional information.


Regards,

Denys

ср, 17 окт. 2018 г. в 16:55, Keith Turner <notifications@github.com>:

**Comment by deniskuzZ** [comment]
Btw. I have submitted upstream patch for that:
https://issues.apache.org/jira/browse/ACCUMULO-4857

Would be great if you could take a look.

**Comment by milleruntime** [comment]
Hey @deniskuzZ thanks for the information.  No need to also create a JIRA issue.  The github issue you created here is all we need to look into the error you are seeing.  Please close ACCUMULO-4857 as a duplicate, thanks!

**Comment by deniskuzZ** [comment]
HI @milleruntime, closed. 
Here is a pull request: https://github.com/apache/accumulo/pull/706
