### ISSUE TITLE
Simplify API definition by moving impl packages from under API packages

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#708]
Currently the API definition is as follows and has the exclusions for  : `impl`, `thrift`, or `crypto`.

```
Accumulo’s public API is composed of all public types in the following packages and 
their sub-packages excluding those named impl, thrift, or crypto.

 * org.apache.accumulo.core.client
 * org.apache.accumulo.core.data
 * org.apache.accumulo.core.security
 * org.apache.accumulo.minicluster
```

These exclusion packages could be moved elsewhere to simplify the API definition.  For example everything in `org.apache.accumulo.core.client.impl` could be moved to `org.apache.accumulo.core.impl.client`.

**Comment by jmark99** [comment]
I'm planning to refactor the packages as listed below. Let me know if you have suggested changes prior to the update, especially as it pertains to the security/crypto packages.

- org.apache.accumulo.core.client.impl ==> org.apache.accumulo.core.impl.client
- org.apache.accumulo.core.client.impl ==> org.apache.accumulo.core.impl.client
- org.apache.accumulo.core.client.impl.thrift ==> org.apache.accumulo.core.impl.client.thrift
- org.apache.accumulo.core.client.lexicoder.impl ==> org.apache.accumulo.core.impl.client.lexicoder
- org.apache.accumulo.core.client.mapred.impl ==> org.apache.accumulo.core.impl.client.mapred
- org.apache.accumulo.core.client.mapreduce.impl ==> org.apache.accumulo.core.impl.client.mapreduce
- org.apache.accumulo.core.client.mapreduce.lib.impl ==> org.apache.accumulo.core.impl.client.mapreduce.lib
- org.apache.accumulo.core.data.impl ==> org.apache.accumulo.core.impl.data
- org.apache.accumulo.core.data.thrift ==> org.apache.accumulo.core.impl.data.thrift
- org.apache.accumulo.core.security.thrift ==> org.apache.accumulo.core.impl.security.thrift
- org.apache.accumulo.core.security.crypto ==> org.apache.accumulo.core.crypto.security
- org.apache.accumulo.core.security.crypto.impl ==> org.apache.accumulo.core.crypto.security.impl
- org.apache.accumulo.core.security.crypto.streams ==> org.apache.accumulo.core.crypto.security.streams
- org.apache.accumulo.minicluster.impl ==> org.apache.accumulo.impl.minicluster

**Comment by milleruntime** [comment]
@jmark99 We might be able to simplify the crypto packages further but we can do that as a follow on task.  Looks good!

**Comment by mikewalch** [comment]
@ctubbsii, Better sorting is a nice idea but using `xImpl` breaks the [lowercase naming convention for packages](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

**Comment by ctubbsii** [comment]
@mikewalch That link is to a tutorial, which explains a simplified convention. A better link on package naming conventions is probably http://java.sun.com/docs/codeconv/html/CodeConventions.doc8.html , which explains that the package name *prefix* should be all lower-case, based on organizations DNS, but also spells out that "Subsequent components of the package name vary according to an organization's own internal naming conventions."

I think `camelCase` is fine as a convention for these "subsequent components" impl packages (as long as it starts with a lowercase, to not look like conflict with class names). And, this naming convention is permitted by the JLS. `x_impl` is also an option, but I just don't like it as much, and it's not very Java-like.

**Comment by mikewalch** [comment]
@ctubbsii, you are right. `camelCase` is fine. I like `impl.x` better but that's personal preference. `xImpl` works too.

**Comment by ctubbsii** [comment]
Could also go with `ximpl`, but that hurts readability. `x.impl → impl.x` is problematic because:

1. it creates potential for collision across jars (see the minicluster example above, which would create the "top-level" `org.apache.accumulo.impl` package in the more narrowly scoped minicluster jar), and
2. we lose the whole attempt to scope the implementation "near" the API to which it corresponds.

**Comment by jmark99** [comment]
I will go with the xImpl. Like @ctubbsii indicated, security.crypto and security.crypto.streams are the most problematic. We need to repackage to remove them from the public api sub-packages but a new package name is not as clear for them as the others.
