### ISSUE TITLE
Monitor 2.0 overview plots overlap when resizing browser window

### ISSUE THREAD

**Issue by cleroux** [apache/accumulo#713]
Monitor 2.0 overview plots do not resize gracefully when resizing the browser window.
This is resolved by adding a script tag for jquery.flot.resize.js in default.ftl
I will submit a pull request.

**Comment by ctubbsii** [comment]
Hi @cleroux ; Thanks for the patch. For what it's worth, there's no need to open an issue if you're going to immediately submit a pull request. The pull request itself serves as its own issue. :smiley_cat:
