### ISSUE TITLE
Use of Object.finalize() is deprecated in Java 9, and generally bad practice

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#723]
It would be great to find and triage uses of finalize() throughout our code, and see if we can improve the code to avoid the reliance on finalize().

Some cases might be easy. Some cases might be more difficult. Triage is needed. Multiple PRs may be needed to complete this.

**Comment by cjmctague** [comment]
Currently these are the only 8 implementations of `Object.finalize()` through the code base.

[AbstractMetricsImpl.java](https://github.com/apache/accumulo/blob/11e26d481b7885e46ce439e1345f0bf9bdd5dfb2/server/base/src/main/java/org/apache/accumulo/server/metrics/AbstractMetricsImpl.java#L269-L277)
[BatchWriterIterator.java](https://github.com/apache/accumulo/blob/d55ce357b9f7555cef6c91cbe93b94de26b58d88/test/src/main/java/org/apache/accumulo/test/BatchWriterIterator.java#L231-L238)
[MetadataConstraints.java](https://github.com/apache/accumulo/blob/11e26d481b7885e46ce439e1345f0bf9bdd5dfb2/server/base/src/main/java/org/apache/accumulo/server/constraints/MetadataConstraints.java#L328-L332)
[MetaDataTableScanner.java](https://github.com/apache/accumulo/blob/08644e6858f2aa9b2f4ebf6e3d9cfdd70eb9e77d/server/base/src/main/java/org/apache/accumulo/server/master/state/MetaDataTableScanner.java#L116-L119)
[MultiTableBatchWriterImpl.java](https://github.com/apache/accumulo/blob/4bd3afa2c997fdcb35d54b8be32b703385f3b5c1/core/src/main/java/org/apache/accumulo/core/client/impl/MultiTableBatchWriterImpl.java#L100-L115)
[NMIterator.java](https://github.com/apache/accumulo/blob/11e26d481b7885e46ce439e1345f0bf9bdd5dfb2/server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java#L485-L492) (inner class of `NativeMap`)
[NativeMap.java](https://github.com/apache/accumulo/blob/11e26d481b7885e46ce439e1345f0bf9bdd5dfb2/server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java#L504-L511)
[TabletServerBatchReader.java](https://github.com/apache/accumulo/blob/4bd3afa2c997fdcb35d54b8be32b703385f3b5c1/core/src/main/java/org/apache/accumulo/core/client/impl/TabletServerBatchReader.java#L84-L93)

**Comment by prakapenka** [comment]
...if object already has Closable or analog of close implementation like MetaDataTableScanner it is looks simple to rely just on close call. 

Compare to MetadataConstraints that tries to clear zoo cache on finalize call and seems does not have other pre-destroy possibilities.

**Comment by ctubbsii** [comment]
> ...if object already has Closable or analog of close implementation like MetaDataTableScanner it is looks simple to rely just on close call.

Yes, but we'd need to ensure callers are calling the `close()` method in a try-with-resources block or in a finally block.

Other options might be to use Java's new Cleaner utility (with PhantomReferences?), whose API I'm not yet familiar with using.
