### ISSUE TITLE
Investigate making MiniAccumuloCluster AutoCloseable

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#724]
Mini has a .start() and .stop() pattern, but it might be more user friendly to have it work seamlessly in a try-with-resources block as an AutoCloseable.

**Comment by prakapenka** [comment]
what about this - https://github.com/apache/accumulo/pull/733 ?

**Comment by DomGarguilo** [comment]
Does this still seem like something that would be good to add?
