### ISSUE TITLE
Metrics not instance specific for multiple tablet-servers in 1.9

### ISSUE THREAD

**Issue by forzamehlano** [apache/accumulo#729]
When multiple tablet servers are in use, the MetricsSystemHelper https://github.com/apache/accumulo/blob/5de8d0f1e1aa674bfada825ddd9014367b3e2e27/server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsSystemHelper.java#L34
 appends a serviceInstance to the process name. This service instance is derived from the system property 'accumulo.metrics.service.instance'. 

I believe the accumulo script https://github.com/apache/accumulo/blob/5de8d0f1e1aa674bfada825ddd9014367b3e2e27/assemble/bin/accumulo#L170 is setting up the incorrect property (accumulo.service.instance) which leads to the metrics system ignoring the service instances and incorrectly reporting metrics.

**Comment by ctubbsii** [comment]
I'm not sure this is a bug. The `accumulo.service.instance` being set in the script is associated with the default configuration for file-based logging. It's not for the metrics. The system property for metrics appears to be a similar property, but we do not try to set it for the user. The user can set this system property in their `accumulo-env.sh` script on startup, though, when they set up metrics for their system.

We could converge on the same property... but there's already a lot of assumptions being made when setting these for our scripts, that I'd be concerned that this would break somebody who managed to rely on those assumptions. In 2.0, it is my intent to argue in favor of moving more of these things under the user's control, and to have fewer assumptions in our own scripts and/or configuration about the user's intended setup. The scripts in 2.0 have already been rewritten with this principle in mind, so I'm not sure there's a lot of value in messing with the 1.9 scripts.

I'm closing this and #730 for now, but if setting this property for metrics in one's `accumulo-env.sh` script is insufficient, we can revisit this.
