### ISSUE TITLE
a question about accumulo shell commnad table row 'scan'

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#738]
Hi all

I'd like to know that Accumulo has a  pattern search function such a  'wild character' or 'like operator' for scanning Accumulo table rows in shell command line?
I know that 'scan command' has make range function from begin to end rows. But it's not perfect it is taken by Accumulo load order. i just wanna scan out the same pattern row keys at one time.
i tried to search the documents and  use some character like '*' or '%' etc. it's all fail. so i'd ask what wild character is or any other way for searching row function in Accumulo? 

Please Let me know it.

Thank you for your reading and good day :)

plus, How to give -b and -e at 'Range rm=Range.exact(new Text(bkey));' in Accumulo java api for scanning?

**Comment by keith-turner** [comment]
> i tried to search the documents and use some character like '*' or '%' etc. it's all fail. so i'd ask what wild character is or any other way for searching row function in Accumulo?

It sounds like you want a prefix range, can do this in java code but not in shell. We could add a shell option for prefix ranges.

```java
// Range for all rows starting with 'abc'
Range pr = Range.prefix("abc");
```

> plus, How to give -b and -e at 'Range rm=Range.exact(new Text(bkey));' in Accumulo java api for scanning?

You can use the range constructor for this like the following.

```java
String startRow ="abc";
String endRow = "def";

Range rm = new Range(startRow, true, endRow, true);
```

**Comment by ctubbsii** [comment]
Closing issue, since the question was answered. Please continue to discuss, if necessary.

**Comment by byungwok** [comment]
Thx very ill try!!!
