### ISSUE TITLE
Make use of JAVA_TOOL_OPTIONS in accumulo-env.sh

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#746]
In accumulo-env.sh for 2.0+, we have a custom JAVA_OPTS that we expect to be set by the end of the script. However, this is non-standard. We should instead use [JAVA_TOOL_OPTIONS][1].

[1]: https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html

**Comment by mikewalch** [comment]
In `accumulo-env.sh`, we build `JAVA_OPTS` but allow users pass in extra options using `ACCUMULO_JAVA_OPTS`:
```bash
## JVM options set for all processes. Extra options can be passed in by setting ACCUMULO_JAVA_OPTS to an array of options.
JAVA_OPTS=("${ACCUMULO_JAVA_OPTS[@]}"
  '-XX:+UseConcMarkSweepGC'
  '-XX:CMSInitiatingOccupancyFraction=75'
  '-XX:+CMSClassUnloadingEnabled'
  '-XX:OnOutOfMemoryError=kill -9 %p'
  '-XX:-OmitStackTraceInFastThrow'
  '-Djava.net.preferIPv4Stack=true'
  "-Daccumulo.native.lib.path=${lib}/native")
```

In `bin/accumulo`, we exec java with `JAVA_OPTS`:
```bash
exec "${JAVA[@]}" "${JAVA_OPTS[@]}" org.apache.accumulo.start.Main "$@"
```

If we switch to `JAVA_TOOL_OPTIONS`, it sounds like we shouldn't exec java with `JAVA_TOOL_OPTIONS` as the JVM will include this environmental variable on its command line. However, are we sure this env variable is used by every JDK?

**Comment by mikewalch** [comment]
> Yeah, we should stop using ACCUMULO_JAVA_OPTS here. We don't need it. We should just append to whatever pre-existing value of JAVA_TOOL_OPTIONS

We could append to existing value JAVA_TOOL_OPTIONS but also let users set ACCUMULO_JAVA_OPTS in case users want to set configuration in their shell that only Accumulo gets.

**Comment by ctubbsii** [comment]
> We could append to existing value JAVA_TOOL_OPTIONS but also let users set ACCUMULO_JAVA_OPTS in case users want to set configuration in their shell that only Accumulo gets.

This is a user file. They can construct `JAVA_TOOL_OPTIONS` from any environment they wish, but there's no reason for us to do this for them. It just introduces unnecessary complexity, which makes it harder for users to tweak to conform to their needs. Having `ACCUMULO_JAVA_OPTS` built-in in the default script just elevates it to "a thing", when really it's not... it's meaningless unless the user gives it meaning. It's best to just remove it to simplify things, and let the user add their own variables in if they want to.

**Comment by mikewalch** [comment]
Setting `JAVA_TOOL_OPTIONS` causes a debug message that looks like it cannot be suppressed.
```bash
$ accumulo version
Picked up JAVA_TOOL_OPTIONS:  -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+CMSClassUnloadingEnabled
2.0.0-SNAPSHOT
```
Another way to show this:
```bash
$ JAVA_TOOL_OPTIONS="-XX:+UseConcMarkSweepGC" java -version
Picked up JAVA_TOOL_OPTIONS: -XX:+UseConcMarkSweepGC
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

https://stackoverflow.com/questions/11683715/suppressing-the-picked-up-java-options-message

**Comment by ctubbsii** [comment]
Yeah, that's definitely a downside for client-facing processes, like the classpath, or version commands. But, it's actually a nice benefit for server processes like master, tserver, gc, and monitor. I'm actually even okay with it on the shell, because it's informative at shell startup, though I see how it has potential for annoyance.

Users can always unset the environment variable inside the env script when it isn't desirable for a process (and we can do so in the default env script for some things that we think it's not needed). Users can also redirect and/or filter stderr (where the message is printed) if they want to set the environment but don't want to see their JVM print the message, at command-execution time, although I typically wouldn't expect them to do so.

So, there's definitely tradeoffs. I'll put some more thought into the pros and cons.

**Comment by ctubbsii** [comment]
Updated links:

For Java 11:
https://docs.oracle.com/en/java/javase/11/troubleshoot/environment-variables-and-system-properties.html

Java 9 and later also have a new `JDK_JAVA_OPTIONS`:
https://docs.oracle.com/en/java/javase/11/tools/java.html

Example:
```bash
$ JDK_JAVA_OPTIONS="-Xmx1g" JAVA_TOOL_OPTIONS="-Xms500m" java -version 1>/dev/null
NOTE: Picked up JDK_JAVA_OPTIONS: -Xmx1g
Picked up JAVA_TOOL_OPTIONS: -Xms500m
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment 18.9 (build 11.0.3+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7, mixed mode, sharing)
```
