### ISSUE TITLE
Add Multi table functionality to new MapReduce API

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#749]
Follow on work for #743 to maintain functionality that AccumuloMultiTableInputFormat provided in the old mapreduce API.

**Comment by milleruntime** [comment]
I am wondering what the best way to do this would be... have an intermediate method such as "add()" to signal more tables are going to be added?
```java
AccumuloInputFormat.configure().clientInfo(info).table(name).auths(auths).add()
    .table(name2).auths(auths2).ranges(myRanges).add()
    .table(name3).auths(auths3).fetchColumns(cols).samplerConfiguration(conf).store(job);
```
This would allow for looping, if tables have the same configuration:
```java
TableParams opts = AccumuloInputFormat.configure().clientInfo(info);
for (int x = 0; x < 10; x++) {
    opts = opts.table("table" + x).auths(myAuths).ranges(myRanges).add()
}
opts.store(job);
```

Or maybe call the method "next()"?

**Comment by keith-turner** [comment]
Seems like the following could work without `add()`.  Each time `table()` is called it implies you are starting a new table.

```java
AccumuloInputFormat.configure().clientInfo(info)
    .table(name).auths(auths)
    .table(name2).auths(auths2).ranges(myRanges)
    .table(name3).auths(auths3).fetchColumns(cols).samplerConfiguration(conf)
    .store(job);
```

**Comment by keith-turner** [comment]
Another possibility is that the entire fluent chain is called for each table.

```java
AccumuloInputFormat.configure().clientInfo(info).table(name).auths(auths).store(job);
AccumuloInputFormat.configure().clientInfo(info).table(name2).auths(auths2).ranges(myRanges).store(job);
AccumuloInputFormat.configure().clientInfo(info).table(name3).auths(auths3).fetchColumns(cols).samplerConfiguration(conf).store(job);
```

**Comment by milleruntime** [comment]
> Seems like the following could work without add(). Each time table() is called it implies you are starting a new table.

OK I like this one.
