### ISSUE TITLE
Remove "fast failure" authentication check in new AccumuloClientImpl

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo#754]
The old ConnectorImpl would reach out to a random tserver when the Connector was constructed in order to verify the credentials it was constructed with. This was a poor attempt to validate arguments and caused problems with performance with the system user. An exception was hard-coded in to avoid this fast-failure with the system user, but in general, it was bad behavior. However, since users may have been relying on this early check, it could have caused problems to change the behavior in the old API.

That code was moved into AccumuloClientImpl for the new AccumuloClient API, along with that bad behavior. However, this fast failure check should be removed. It is an unnecessary client performance hit when constructing a client, and could cause failures in legitimate circumstances, and doesn't exempt a user from catching authentication related exceptions later. However, this is shared code... so it might be nice to continue the existing behavior if a user uses the old API.

**Comment by milleruntime** [comment]
Fixed in #792
