### ISSUE TITLE
A problem can not read 'exportMetadata.zip', when importing accumulo table.

### ISSUE THREAD

**Issue by byungwok** [apache/accumulo#755]
Hi
I tested to import accumulo table at the same Environment of hdfs using all way which let me know before. In result, i got a new error message when importing Accumulo table at last phase.

It can't read 'exportMetadata.zip' already 'distcp'ed in hdfs. i'd attached shot the error came out. I'd checked that hdfs url was working and that zip file existed in hdfs. but nothing special. it was all ok.

As far as I know Accumulo looks for file using hdfs url.  right? then i have no idea why accumulo said he couldn't read that 'Metadata.zip' and replied 'null'. Did you know what is problem to come out this error message? And for fixing up, Did i need to change the files in 'exportMetadata.zip' to the dest. hdfs info like InstanceID, zookeeper ip  etc?

Please let me know how to fix up?

![img_2584](https://user-images.githubusercontent.com/39606428/48183106-fc16e000-e370-11e8-8954-69ab372e0276.JPG)

![img_2585](https://user-images.githubusercontent.com/39606428/48183107-fcaf7680-e370-11e8-93c6-e73cfc9461f4.JPG)

**Comment by EdColeman** [comment]
what do you get if you do 

> hadoop -fs -ls hdfs://ofbdas-nd1.ofbdas.go.kr:8020/tmp/distch


do you have more that one namenode? I believe the files to be in hdsf, not the local file system, and they need to be in the same namespace as accumulo. 
Does the accumulo user that the shell is running have the necessary permissions? (you may try to use the rfile-info utility (https://accumulo.apache.org/1.9/accumulo_user_manual.html#_tools) to try to read one of the rfiles - maybe that will provide more information)

the command 

> importtable importtest /tmp/distcdh

seems to be the correct format - maybe try giving the fully qualified path to the directory - i.e. hdfs://ofbdas-nd1.ofbdas.go.kr:8020/tmp/distch  (or whatever it really is)

**Comment by keith-turner** [comment]
Can you do the following in the accumulo shell?  This may give more info.

```
debug on
importtable <table> <dir>
```

Also can you do the following to see if the zip file is ok?

```
hdfs dfs -copyToLocal hdfs://ofbdas-nd1.ofbdas.go.kr:8020/tmp/distcdh/exportMetadata.zip /tmp/exportMetadata.zip
unzip -l /tmp/exportMetadata.zip
```

**Comment by keith-turner** [comment]
Can you look in the Accumulo master logs around the time you did the import to see if there are ERROR or WARN messages?

**Comment by byungwok** [comment]
Thank you for ur answer but sorry i have master log and i have to fix up accumulo-zookeeper error first.

**Comment by ctubbsii** [comment]
Closing inactive question thread.
