### ISSUE TITLE
Accumulo and zookeeper

### ISSUE THREAD

**Issue by SebeiHiba** [apache/accumulo#762]
Hi!
1. why accumulo requires zookeeper ?
2. in a case of three node cluster
master : namenode, resourcemanager, accumulo monitor, accumulo master, tracer
slave1: datanode, tablet server, nodemanager
slave2: datanode, tablet server, nodemanager
the zookeeper server should it be installed just on the master node or on each machine of the cluster?

Regards,

**Comment by ctubbsii** [comment]
1. Accumulo uses ZooKeeper for service advertisement for the clients and cluster-wide shared state.
2. For a three node cluster, I would probably just put a single ZooKeeper instance on the master node.
