### ISSUE TITLE
Accumulo 1.9 and Yarn

### ISSUE THREAD

**Issue by SebeiHiba** [apache/accumulo#771]
Hi!
 can I deploy Accumulo 1.9 above the Hadoop Yarn?

Regards,
Hiba Sebei

**Comment by ctubbsii** [comment]
Accumulo doesn't use Yarn. It may be possible to deploy Accumulo in yarn, but I haven't tried, personally. I recommend discussing on our user mailing list, where you may be able to learn from others who have tried it.
