### ISSUE TITLE
Move partitioners in new map reduce module to public API

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#776]
In the new map reduce API the partitioners were placed in impl package.  These are intended for user writing bulk import code and need to be in a public package.

**Comment by cjmctague** [comment]
@keith-turner 
I was gonna do this but I saw these classes where duplicated. 
Once is Public API `o.a.a.c.client.mapreduce.lib.partition` and the other `o.a.a.hadoopImpl.mapreduce.lib.partition`

Did you just want `o.a.a.hadoopImpl.mapreduce.lib.partition` moved under `o.a.a.hadoop.mapreduce`?

**Comment by ctubbsii** [comment]
@cjmctague wrote:
> @keith-turner
> I was gonna do this but I saw these classes where duplicated.
> Once is Public API `o.a.a.c.client.mapreduce.lib.partition` and the other `o.a.a.hadoopImpl.mapreduce.lib.partition`

I'm working on deprecating the `o.a.a.c` ones, so nothing should be done with that one.

> 
> Did you just want `o.a.a.hadoopImpl.mapreduce.lib.partition` moved under `o.a.a.hadoop.mapreduce`?

I think that's the idea. @milleruntime might already be working on this. He's been spending a lot of time on this new module.

**Comment by milleruntime** [comment]
I have not done anything to these classes.  The work I am doing next is #749

**Comment by ctubbsii** [comment]
I don't think moving them would conflict with that work, so it's all yours, @cjmctague , if you want to do it.
