### ISSUE TITLE
AccumuloClient.changeUser needs better documentation

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#787]
The method `AccumuloClient.changeUser(String user, AuthenticationToken token)` creates a new AccumuloClient object that must be closed.  This should be documented in the Javadoc.  It might also make sense to change the method name to `newClientForUser(user, token)` to make it clear to users that a new AccumuloClient object is being created.

**Comment by ctubbsii** [comment]
The benefits of this method are unclear to me, given the considerations users must make. How about we just remove the method?

**Comment by mikewalch** [comment]
I am cool with removing the method. Users can still create a new client for a new user from an existing client using the following code:

```
AccumuloClient client = Accumulo.newClient().from(oldClient.info()).as(principal, token).build();

```

The above code is more clear than the following that we are creating a new client:

```java
AccumuloClient client = oldClient.changeUser(principal, token);

**Comment by mikewalch** [comment]
Completed in #792
