### ISSUE TITLE
Remove ClientInfo from API

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#788]
`ClientInfo` isn't really necessary in the API as `Properties` can be used instead in most cases. I would like to remove it from the API and make the following changes:

* Remove `changeUser()` and `info()` from AccumuloClient
* Use `Properties` where `ClientInfo` is used
* Keep `ClientInfo` as internal class
* Add `properties()` and `token()` to AccumuoClient. `token()` is needed for code that creates `ClientContext` from `AccumuloClient`.
* Stop creating `ClientInfo` from `Accumulo.newClient()` builder and create a `Accumulo.newProperties()` builder.

| Current | New |
|---------|-----|
| ClientInfo info = client.info() | Properties props = client.properties(); Authentication token = client.token() |
| client.changerUser(user, token) | Accumulo.newClient().from(oldClient.properties()).as(user, token).build() |
| ClientInfo info = Accumulo.newClient().to(instance, zoo).from(user, token).info() | Properties props = Accumulo.newProperties().to(instance, zoo).from(user, token).build() |

**Comment by ctubbsii** [comment]
Can `token()` be added to `AccumuloClientImpl` rather than `AccumuloClient` to satisfy the requirements for `ClientContext`? I'm not sure it should be on the public API... and if we really need it, we could always add it later.

I think the method should be `Accumulo.newClientProperties()` instead... just to be more explicit about the scope of the properties.

:+1: to everything else in the proposal.

**Comment by mikewalch** [comment]
Updated with feedback from @ctubbsii:

* Remove `changeUser()` and `info()` from AccumuloClient
* Use `Properties` where `ClientInfo` is used
* Keep `ClientInfo` as internal class
* Add `properties()` to AccumuoClient
* Stop creating `ClientInfo` from `Accumulo.newClient()` builder and create a `Accumulo.newClientProperties()` builder.

| Current | New |
|---------|-----|
| ClientInfo info = client.info() | Properties props = client.properties() |
| client.changerUser(user, token) | Accumulo.newClient().from(oldClient.properties()).as(user, token).build() |
| ClientInfo info = Accumulo.newClient().to(instance, zoo).from(user, token).info() | Properties props = Accumulo.newClientProperties().to(instance, zoo).from(user, token).build() |
