### ISSUE TITLE
Periodic test failure in ConcurrentKeyExtentCacheTest

### ISSUE THREAD

**Issue by ivakegg** [apache/accumulo#791]
I have found that my build with tests wil periodically fall in the ConcurrentKeyExtentCacheTest in the master branch.  If I simply restart the build from that module then it will always succeed and continue on:

[ERROR] Failures: 
[ERROR]   ConcurrentKeyExtentCacheTest.testExactEndRows:115 expected:<256> but was:<255>

**Comment by milleruntime** [comment]
This could be due to the test now using SecureRandom.

**Comment by milleruntime** [comment]
Nevermind.  I don't think SecureRandom is affecting the random number count.
