### ISSUE TITLE
Compaction and flush operations do not properly handle the root table

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#798]
While working on #797 I noticed that the compaction and flush client operations do not properly handle the root table.  The problem is the code in CompactionDriver and MasterClientServiceHandler.  Both of these scan the metadata table to see what tablets need to be flushed or compacted.  For the root table both of them them scan the metadata table.

This problem exists in 1.9.  The code kinda works in that it will cause a flush of the root table, however it will never wait for that flush to complete.  The compaction code does not work at all for the root table.  However, compaction is proceeded by a flush by default which will trigger a compaction with the default config of a compaction ratio of 1 for the root table.  So in 1.9 if someone changed the root table config or disabled flush before compact, then the compact would be a noop.

**Comment by keith-turner** [comment]
I am thinking of only fixing this in 2.0.  Was thinking of fixing by making the new tablet metadata abstraction layer handle the root tablet.

**Comment by ctubbsii** [comment]
Fixing in 2.0 only seems reasonable to me. It doesn't seem to have been much of a nuisance up to this point.

**Comment by keith-turner** [comment]
https://issues.apache.org/jira/browse/ACCUMULO-2007

**Comment by ctubbsii** [comment]
Bumping this off of 2.1, but I'm wondering if this is still a problem at all.

**Comment by cshannon** [comment]
This issue is pretty old so closing this out for now, if it is still a problem it can be re-opened.
