### ISSUE TITLE
Refactor KeyExtent.toMetadataRange() to use TabletSection.getRow(id,prev)

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#807]
The function [KeyExtent.toMetadataRange()](https://github.com/apache/accumulo/blob/787ae13841d6b3540cded5fb6464632d2a8ce732/core/src/main/java/org/apache/accumulo/core/dataImpl/KeyExtent.java#L498) manually constructs `metadataPrevRow`.  It would be better if `TabletsSection.getRow(id, prevRow)` was used to construct  `metadataPrevRow`.  To do this the case of a null prev row would need to be properly handled.

**Comment by jzgithub1** [comment]
I will look at this now.
