### ISSUE TITLE
Missing tests in hadoop-mapreduce

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#811]
Tests should be added for the following options (which probably aren't even tested in core.mapred*):
- InputFormatBuilder -> classLoaderContext
- InputFormatBuilder -> executionHints
- OutputFormatBuilder -> simulationMode

**Comment by milleruntime** [comment]
More information because this may be a good task for newer developers. 

The Map Reduce code in org.apache.accumulo.core.client.mapred and org.apache.accumulo.core.client.mapreduce was deprecated in 2.0 in favor of more maintainable code now in the hadoop-mapreduce package.  A fluent builder was added to the new code to make it easier to set all the properties on a map reduce job. So now a job can be configured in one line like this:
<pre>
AccumuloOutputFormat.configure().clientProperties(props).batchWriterOptions(bwConfig)
      .defaultTable(name).createTables(true) // disabled by default
      .simulationMode(true) // disabled by default
      .store(job);
</pre>

The tests from the old code were copied over to the new package in hadoop-mapreduce.  But there are tests missing for some of the options.  We want to have tests for all of the new builder methods for 2.0.  Tests can be added to existing ones in hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop or it may be better to have new unit tests that just test the fluent API directly.  

Here are some more methods that are missing tests:
- OutputFormatBuilder -> createTables
- OutputFormatBuilder -> clientPropertiesPath

**Comment by jzgithub1** [comment]
The Jeffs are looking at this now.

**Comment by Manno15** [comment]
I have some questions about the tests that need to be implemented.  For the createTables test, is the goal to enable the flag and then to have the test create a table and verify that works properly or just verify that the flag can be set through the fluent builder API. Similar question for the simulation mode test. Thanks.

**Comment by milleruntime** [comment]
> have the test create a table and verify that works properly 

This would be a better test then just checking that the flag gets set in the config object.

**Comment by Manno15** [comment]
Okay, thanks. That is what I figured.

**Comment by Manno15** [comment]
@milleruntime Just some clarification before I get too far ahead of myself. For tests like createTable and the like, am I needed to configure a mini accumulo cluster to test or am I misinterpreting what you are asking the test to do. Thanks. Sorry for the delay on this.

**Comment by Manno15** [comment]
I currently have the test setup and working on my local accumulo instance but that will obviously not work for the actual test.

**Comment by milleruntime** [comment]
@Manno15 I am not sure what you are asking... I pinged you on Slack.

**Comment by milleruntime** [comment]
@Manno15 @elinaawise are you done working on this ticket?

**Comment by elinaawise** [comment]
@milleruntime yes, we are.
