### ISSUE TITLE
Make sure AccumuloClient is closed

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#820]
The following warnings were output while running random walk tests.

```
2018-12-11 12:21:01,973 [core.singletons.SingletonReservation] WARN : An Accumulo Client was garbage collected without being closed.
```

It looks like there a several places in the code where AccumuloClient objects are being created without being closed.  While it would be nice to fix any occurrence of this in the ITs, it's more important to find and fix all occurrences in the non-test code.

**Comment by keith-turner** [comment]
Accumulo clients created from the ClientContext do not need to be closed.

**Comment by ctubbsii** [comment]
> Accumulo clients created from the ClientContext do not need to be closed.

It shouldn't be possible to create an AccumuloClientImpl from a context. The context should contain everything we need. It should go from API to context, but not back to API again. A lot of that is from the migration away from ConnectorImpl internally... and will take time to migrate.

**Comment by mikewalch** [comment]
I think this can now be closed.  Several PRs were completed to fix this.
