### ISSUE TITLE
Refactor how constraint violations are handled

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#824]
[Tablet server code](https://github.com/apache/accumulo/blob/c8d19d45f361f49a4d42b07310393b7bdf68b3b4/server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java#L1059) that handles contraint violation uses an exception to return information about constraint violations.  I am not sure about this, but I think it may clean up the code if an exception was not used to return information in this way.  The code could instead always return an object contains info about 0 or more constraint violations.  I think this could cut down on duplicate code, how that may not be the case.

**Comment by lbschanno** [comment]
I will work on this.

**Comment by lbschanno** [comment]
Pull request available for review.

**Comment by keith-turner** [comment]
b9505a6a36a97dc9c029f6621648e83e8f867507
