### ISSUE TITLE
Look into correct API to use for Hadoop distirbuted cache

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#896]
The `setClientProperties` method in `ConfiguratorBase` uses `DistributedCacheHelper.addCacheFile` to cache the client properties file.  This code works but is deprecated.  Other API like the following code might be better use:

```java
String files = conf.get("mapreduce.job.cache.files");
conf.set("mapreduce.job.cache.files", files == null ? uri.toString() : files + "," + uri.toString());
```

**Comment by milleruntime** [comment]
I was thinking we could use `job.addCacheFile(uri);`
I found this [here](https://stackoverflow.com/questions/21239722/hadoop-distributedcache-is-deprecated-what-is-the-preferred-api).

**Comment by milleruntime** [comment]
I just saw your comment on #894 .  Yeah I can't seem to find any recommendations for JobConf so we might have to do something like that... ugh :man_facepalming:
