### ISSUE TITLE
Visibility Issues in Accumulo when scaning a table. Getting following error :- error bad authorizations for user on table T1 (id:1y) - the user visuser does not have the specified authorizations assigned

### ISSUE THREAD

**Issue by BharatAnalyst** [apache/accumulo#900]
Visibility Issues in Accumulo when scaning a table. Getting following error :-

```
error bad authorizations for user on table T1 (id:1y) - the user visuser does not have the specified authorizations assigned
```

Background :- 
I am setting user authorizations in accumulo  from Presto Java client by calling method
```java
 void changeUserAuthorizations(String var1, Authorizations var2)
```
 from class `SecurityOperations.java` (`accumuo-core.jar`)

This in turn calls the `setauths -u <username> -s <authorizations>` command in accumulo. 
This sets authorizations in accumulo and I can see these authorizations using  method call
```java
Authorizations getUserAuthorizations(String var1) 
```
from Java client or even login in to accumulo shell using get auths command

```shell
root@accumulo>getauths -u visuser
b0,b1,b2,b3,b4,b5,b6
```

But when i run a scan table command it throws the above mentioned error. 

```shell
visuser@accumulo>scan -t T1 -s b0
error bad authorizations for user on table T1 (id:1y) - the user visuser does not have the specified authorizations assigned
```

But now if i set the `setauths` using root user and shell command line as below the scan table command works fine and gives the desired output. 
```shell
root@accumulo>setauths -u visuser -s b0,b1,b2,b3,b4,b5,b6
root@accumulo>getauths -u visuser
b0,b1,b2,b3,b4,b5,b6
```

Now the scan table command runs fine here as desired. And i dont understand why it should do that. So i tried to think of what the differences could be and i even tried with trimming the code sorting and sending the authorizations.
I also made sure that Before calling `changeUserAuthorizations()` the Character encoding has been set to UTF-8 using 

```java
System.setProperty("file.encoding", "UTF-8");
```

Accumulo version I am using is `accumulo-2.0.0-SNAPSHOT` (`accumulo-rel-2.0.0-alpha-1`)

**Comment by ctubbsii** [comment]
The authorizations are stored in ZooKeeper, which can take some time to propagate changes if you're cluster size is greater than 1. It's possible that the internal ZK cache is not being expired and retried when it fails the first time in this case. Does it work if you wait a minute or two after changing the authorizations? Or when you have a single-node cluster?

Also, it would be helpful if we could see a visibility expression on a successful scan.

If you can provide a small example project which reproduces the error, that could help troubleshoot it, also.

**Comment by mikewalch** [comment]
I think the Java API is being used incorrectly. I think authorizations are being set as below:

```java
client.securityOperations().changeUserAuthorizations("user", new Authorizations("b0,b1,b2,b3,b4,b5,b6,b7");
```
This creates a single `b0,b1,b2,b3,b4,b5,b6,b7` authorization instead of several authorizations (i.e `b0`, `b1`, `b2`, etc).  If you are setting multiple auths, your code should be as follows:

```java
client.securityOperations().changeUserAuthorizations("user", new Authorizations("b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7");
```
Accumulo should have probably never allowed commas `,` in authorizations to prevent this problem but this probably can't be changed now.  At a minimum, we could print auths better in the shell so you know if you are looking at one or multiple auths.  

Let me know if this was your issue

**Comment by ctubbsii** [comment]
Allowing commas is okay... but the shell should definitely escape them when it prints them, to make it easier to debug.

**Comment by BharatAnalyst** [comment]
Thanks @ctubbsii and @mikewalch for your responses. Will test and update here.

**Comment by BharatAnalyst** [comment]
Yes this indeed fixed the issue. I had even thought of this issue to be authorization being set as a full string but because setauths -u viz2 -s "b0","b1","b2" threw syntax error i did not go that route to pass the values in double quotes in java. But i should have thought that there could be difference in how api would work and try out anyways as i tried few other things. Anyways thanks again for helping me find a resolution for my issue. 

Also i agree as you both suggested there should be better way of showing the authorizations for debugging.

**Comment by ctubbsii** [comment]
Glad you got it resolved. Thanks for asking the question! If anybody's is interested in improving the display output for this in the shell, please feel free to submit a pull request with a proposed solution, or open a new issue to discuss potential solutions.
