### ISSUE TITLE
Clear table problems link on monitor page do nothing.

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo#918]
While running continuous ingest against 2.0.0-alpha-2 I saw the following.   Clicking on the links to clear the problems did nothing.

![screenshot at 2019-01-24 17 32 28](https://user-images.githubusercontent.com/1268739/51712870-25551d00-1ffe-11e9-99bf-1eb5f3e90320.png)

**Comment by jzgithub1** [comment]
I will work on this now.  Any idea on steps I can make to duplicate this?

**Comment by ctubbsii** [comment]
> I will work on this now. Any idea on steps I can make to duplicate this?

Could delete a Table's file from HDFS and then try to scan the table in the shell. I think that will trigger something to show here.

**Comment by jzgithub1** [comment]
Works for all the links on the page. Now.
