### ISSUE TITLE
Upgrade thrift to 0.12

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo#922]
The latest stable release of Thrift is 0.12.0 (released on 2019-JAN-04).
https://thrift.apache.org/download

I don't know what all has changed since I can't find release notes but upgrading should be looked into for 2.0 and 1.9.  This [JIRA filter](https://issues.apache.org/jira/browse/THRIFT-3983?jql=project%20%3D%20THRIFT%20AND%20fixVersion%20%3D%200.12.0%20AND%20resolution%20%3D%20Fixed%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC) is the best I can come up with for issues.

**Comment by mjwall** [comment]
Thanks Mike.  I found [this](https://lists.apache.org/thread.html/c02fea099e0e4315770593895e2998df88b40e656f4d143833411259@%3Cuser.thrift.apache.org%3E) release announcement.

**Comment by ctubbsii** [comment]
We can't really change 1.9, but we could look into this for 2.0.

**Comment by ctubbsii** [comment]
Fixed in #1004
