### ISSUE TITLE
reading array types via hive

### ISSUE THREAD

**Issue by sidnakoppa** [apache/accumulo#923]
Team,

When I read the contents of table via hive.I am unable to fetch complete details.
But via accumulo shell ,i can see that data has been inserted .
Could you please help .I have to read the the data in spark(java)
Facing same issues for other array types too.

Table `DDL`

> CREATE TABLE acc_arr_dec(rowid INT,unique_id array<decimal>)
> STORED BY 'org.apache.hadoop.hive.accumulo.AccumuloStorageHandler' WITH SERDEPROPERTIES('accumulo.columns.mapping' = ':rowid,account:at_unique_id')
> 

Hive out-put

> hive> select * from acc_arr_dec;
> OK
> 121	         [null]
> 1221	[null]

Accumulo shell output

> root@hdp-accumulo-instance> scan -t acc_arr_dec
> 121 account:at_unique_id []    1\x03\x00\x00\x00\x00
> 1221 account:at_unique_id []    212\x03789

Actual data

> 
> 121 [1,null]
> 1221 [212,789]

**Comment by milleruntime** [comment]
Have you asked anyone for help in the Apache Hive community?  They are the ones supporting the class you are using to interact with Accumulo.

**Comment by ctubbsii** [comment]
This appears to be a question about [Apache Hive](https://hive.apache.org) and should be asked in their community. You may also be able to find help by asking on a user forum, such as [StackOverflow](https://stackoverflow.com/search?q=hive+accumulo).
