### ISSUE TITLE
RuntimeException while stopping Accumulo

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#933]
```
$ ./bin/accumulo-cluster stop
Stopping Accumulo cluster...
2019-02-01 13:50:15,801 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /path/to/accumulo-2.0.0-SNAPSHOT/conf/accumulo.properties
Exception in thread "Thread-2" java.lang.RuntimeException: No files-cache implementation set.
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getCache(AbstractFileSystem.java:209)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.getFileFromCache(AbstractFileSystem.java:222)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:332)
	at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFile(AbstractFileObject.java:2007)
	at org.apache.commons.vfs2.provider.AbstractFileObject.resolveFiles(AbstractFileObject.java:2052)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:1222)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.checkForNewChildren(DefaultFileMonitor.java:553)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.check(DefaultFileMonitor.java:667)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor$FileMonitorAgent.access$200(DefaultFileMonitor.java:423)
	at org.apache.commons.vfs2.impl.DefaultFileMonitor.run(DefaultFileMonitor.java:376)
	at java.lang.Thread.run(Thread.java:748)
Accumulo shut down cleanly
```

**Comment by keith-turner** [comment]
I saw something similar #928

**Comment by jzgithub1** [comment]
I think we need to look at the version of vfs2 we are running.  I don't  have a run function on line 376 in my decompiled DefaultFileMonitor class that the AccumuloReloadingVFSClassLoader uses to manage the file caching.  The IDE is telling me that DefaultFileMonitor.class if bytecode version 50.0 (Java 6) .  Maybe my environment is going to the wrong .class file?

A newer Vfs2 library may have some improvements we want.

I will keep trying to get to the bottom of this issue.

**Comment by jzgithub1** [comment]
Seems like this is the most up-to-date:

https://mvnrepository.com/artifact/org.apache.commons/commons-vfs2/2.3


<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-vfs2</artifactId>
    <version>2.3</version>
</dependency>

**Comment by jzgithub1** [comment]
`
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-vfs2</artifactId>
    <version>2.3</version>
</dependency>`

**Comment by jzgithub1** [comment]
AccumuloVFSClassLoader.generateVfs adds providers for many file types but not one for "files-cache" which the file monitor thread seems to be looking for given the stack trace above.  We have a LruBlockCache implementation thread running but that is separate.  

Inside of the AccumuloVFSClassLoader.generateVfs function a line like:
vfs.addProvider("files-cache", /* our files-cache implementation */ );
needs to be added.  
I can't find a provider for "files-cache" inside of the 'org.apache.commons.vfs2.provider' package.

Should I implement this provider?  Or if we set the property general.vfs.classpaths to a place where it is will the error not occur.  On my "UNO" instance the property general.vfs.classpaths is not set.  It is null.

**Comment by ctubbsii** [comment]
Can you use `org.apache.commons.vfs2.provider.local.DefaultLocalFileProvider` for `files-cache`?

**Comment by ctubbsii** [comment]
Actually, it looks like we should probably pick from one of the built-ins here: http://static.javadoc.io/org.apache.commons/commons-vfs2/2.3/org/apache/commons/vfs2/cache/package-summary.html

I think we probably just have to register the provider. I don't know enough about VFS2, but it seems like if we have to do all this manual registration of providers to initialize VFS, we're probably doing something wrong... like how we used to manually initialize Log4J in code rather than rely on the built-in initialization using Log4J config files and system properties.

For now, though, the best fix is probably to find a reasonable provider, and register it explicitly, like we do for the other types.

**Comment by jzgithub1** [comment]
There is no "files-cache" implementation in this list of support Vfs2 file systems:

https://commons.apache.org/proper/commons-vfs/filesystems.html

I know my code change does not fail during runtime when I shut down or anything else but I can't really say what the effect of the change will really be.

**Comment by ctubbsii** [comment]
Does the upgrade to 2.3 alone fix the issue? Or does the addition of registering the "files-cache" provider fix it? If the upgrade alone fixes the issue, then we should probably omit the registration of a "files-cache" provider until we understand the effect of that change better. If both are needed, then we should do both, but I'm a bit uncomfortable registering that specific provider without understanding the implications.

**Comment by jzgithub1** [comment]
My latest revision of the code catches a runtime exception if vfs cannot find an implementation while adding or removing files from the monitor and logs exception's message as at error level.  At least we won't crash and throw stack traces but we will have to look into the logs to find the error.   I am scratching my head trying to figure out what part of our code is putting "files-cache" in its URI string.

**Comment by jzgithub1** [comment]
I can't positively assert whether the upgrade to 2.3 fixed anything.  I never saw this runtime error on my test system and don't really have a technique to reproduce it.  I just think upgrading the version to 2.3 has to have some advantages.
