### ISSUE TITLE
Network issue during WAL creation results in a 'missing' WAL during recovery

### ISSUE THREAD

**Issue by andrewglowacki** [apache/accumulo#949]
As far as I can tell this is what's happening...

When a new WAL is being created, after the header and OPEN mark are written, the new WAL marker is written to Zookeeper for the master. If due to a network interruption, the marker is written, but the tserver is unaware of this, the tserver will delete the WAL from HDFS, leaving an orphaned entry in the metadata table. This then prevents Accumulo from proceeding with ingest for the associated tablets without manual intervention, because it thinks it's missing a WAL.

This was observed twice in the last three weeks on a moderately sized cluster. Why is the WAL deleted by the tserver, shouldn't the GC do this? Maybe it should only delete the WAL if it doesn't fail on the Zookeeper step?

Note: this only seems to happen in rare circumstances when the cluster is under heavy load.

Version 1.9.2

**Comment by andrewglowacki** [comment]
After further investigation, it looks like the Zookeeper exception was NoExists (after several connection losses with retries). I can contribute fix I made locally if necessary, however testing it seems like it would be difficult.

**Comment by keith-turner** [comment]
@andrewglowacki  I would be interested in seeing the changes.

**Comment by jzgithub1** [comment]
You might want to check that Network Time Protocol is installed across the cluster properly.
I am trying to replicated this issue on my cluster as well.

**Comment by jzgithub1** [comment]
Should I work on this issue in Accumulo 1.9.2 or Accumulo 2.0 alpha 2?

**Comment by keith-turner** [comment]
@jzgithub1  I think #1005 is for this issue.

**Comment by ctubbsii** [comment]
@keith-turner You self-assigned this. Any update on this? Or should this be bumped from the 1.9.3 release?
