### ISSUE TITLE
Support Java 11 in Accumulo 1.9

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo#958]
Support for Java 11 was added in #952 for Accumulo 2.0. 

I am not sure if this should be done for Accumulo 1.9.  See #952 for how this was done for 2.0.

**Comment by milleruntime** [comment]
Do you want to try and do this for 1.9.3?

**Comment by mikewalch** [comment]
> Do you want to try and do this for 1.9.3?

I think we should wait on this. If there is a demand from 1.9 users, they can comment on this ticket and we can do it in the future.

**Comment by ctubbsii** [comment]
This was been done in #1295 and #1236 , and will be supported in 1.10.0
