### ISSUE TITLE
Log waits beyond a threshold in FileManager.reserveReaders()

### ISSUE THREAD

**Issue by FineAndDandy** [apache/accumulo#978]
While calling FileManager.reserveReaders() filePermits.acquireUninterruptibly(files.size()) is called. This method will block until the filePermits are available. Using tryAcquire(int, long, TimeUnit) in a loop until successful would allow logging beyond a configurable threshold while waiting.

**Comment by keith-turner** [comment]
In addition to logging, could also have metrics ... see #946

**Comment by FineAndDandy** [comment]
closed via #981
